### PR TITLE
test(mysql): add test-support for MySQL 8

### PR DESCRIPTION
**Pull request by sdepold**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

This PR implementing the changes for #13601 and #13609 by introducing a separate build using MySQL 8.0. It also fixes all relevant details that have been introduced in v8 such as migrating from GeomFromText to ST_GeomFromText and rejection of descending indices in MyISAM databases.

### CODE REVIEW

**Comment by sdepold** [comment]
@Puvipavan I enabled a test workflow for MySQL 8 and there are a couple of failing tests. As you can see, I have copied your fix to this PR already. I'll have a look into the other issues in the next couple of days.

**Comment by Puvipavan** [comment]
Thank you @sdepold. Main reason for the most of the error is using deprecated function `GeomFromText` for MySQL 8.0(https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html). We have to use `ST_GeomFromText` instead of `GeomFromText`. Fortunately `ST_GeomFromText` is supported by 5.6/5.7 too(https://dev.mysql.com/doc/refman/5.6/en/populating-spatial-columns.html). So I had to replace `GeomFromText` with `ST_GeomFromText` on the file `lib/data-types.js`. Then I ran the integration test for MySQL 8.0 and errors were reduced from 19 to 3. I tested with 5.7 too and all the tests were passed. I will investigate the remaining errors when I get some time.

Updated my PR: https://github.com/sequelize/sequelize/pull/13609/

PS: I tested both versions by editing the docker image version on the docker compose file at `dev/mysql/5.7/docker-compose.yml`

**Comment by sdepold** [comment]
> Fortunately `ST_GeomFromText` is supported by 5.6/5.7

This is exactly what I just looked into and pushed :)

**Comment by sdepold** [comment]
Woop. Green. @Puvipavan I have copied all your lovely commits into this one now

**Comment by Puvipavan** [comment]
Wow. Thank you @sdepold

**Review by Keimeno — APPROVED** [review]

**Pull request merged**
