### PR TITLE
meta: extract `utils.inspect()` function into a separate utility

### PR DESCRIPTION
**Pull request by catamphetamine**
Throughout the code, Node.js's `util.inspect()` function is imported in various ways:
* `import { inspect } from 'util'`
* `import NodeUtil from 'util'`
* `import NodeUtil from 'node:util'`
* `const util = require('util')`
* etc

This PR unifies such imports by replacing them with:
* `import stringify from './util/stringify.js'`

### CODE REVIEW

**Comment by WikiRik** [comment]
Why did you choose to make a new function instead of unifying the imports to `import { inspect } from 'node:util'`? Is there going to be a follow-up PR that changes the `stringify` function to work without Node as well?

**Comment by WikiRik** [comment]
I think it's good to reduce the imports that we do from Node and centralize them. I agree that working on a non-Node implementation is not needed right now. So I would be in favour of this change but I'd like to hear the input from @ephys as well about this.

I think it might also be good to include this in the CONTRIBUTING file, under https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#coding-guidelines
Just a small sentence mentioning that instead of using `JSON.stringify()` or `util.inspect()` we use the `stringify` function from `utils/stringify`. That would be a nice first step towards further guidelines for contributors

**Comment by ephys** [comment]
I don't think doing this right now is going to be very useful. It's highly likely that we'll have to change everything again once we move to an alternative solution and I don't want to have a file that does nothing but re-export from another library. I think this change is premature

@WikiRik the library I was talking to you about on slack does include an isomorphic inspect

**Comment by WikiRik** [comment]
> @WikiRik the library I was talking to you about on slack does include an isomorphic inspect

Nice! If we can start using that in the next few months it might indeed be better to wait until then so we don't change twice

**Comment by WikiRik** [comment]
As @ephys mentioned above, we're going to move to an alternative solution in the hopefully not to distant future so I'll close this PR

**Pull request closed without merging**
