### PR TITLE
Add imprint to the docs

### PR DESCRIPTION
**Pull request by sdepold**
As the content is still originally from me and somehow related to my
anyways, I think we’ll have to add this lovely imprint :-| Hooray!

### CODE REVIEW

**Comment by sdepold** [comment]
This PR is based on top of #3143

**Comment by mickhansen** [comment]
Why do we need an imprint?

**Comment by mickhansen** [comment]
Seem to be a lot of unrelated changes, will have to rebase after we merge the other PR likely.

**Comment by sdepold** [comment]
yes rebase is missing. regarding the imprint: I'm not entirely sure about this tbh. there is this lovely document (which of course is only in german: http://www.bmjv.de/SharedDocs/Downloads/DE/pdfs/LeitfadenZurAnbieterkennzeichnung.pdf;jsessionid=E1E29E27582AF8BF9E8E7D2FE18A48B9.1_cid324?__blob=publicationFile). It states that an imprint has to be part of a website when it is steadily available. At this point it isn't really important if the goal of that website is to make money. Apparently it's just the fact that people can consume your website that enforces you to have an imprint (facepalm). As I'm only partially (if at all) am the owner of the website's content, I'm a bit confused about if this is really necessary. But as I don't really have an answer and I don't really want to get trouble, I'd rather vote for just adding that shit.

**Comment by sdepold** [comment]
rebase is done btw

**Comment by mickhansen** [comment]
Agreed, better safe than sorry.

**Comment by sdepold** [comment]
Thanks :)

**Comment by BridgeAR** [comment]
The imprint is only relevant for www.sequelizejs.com and you should insert your phone number to the imprint.

You'll find everything necessary about this subject here: http://www.internetfallen.de/Homepagebetreiber/Anbieterkennzeichnung/anbieterkennzeichnung.html

**Comment by sdepold** [comment]
Yeah I noticed that today as well... Will be super glad to do that ... not.

**Comment by sdepold** [comment]
@BridgeAR I think we decided to point sequelizejs.com to rtd. so the docs will run under sequelizejs.com

**Pull request merged**
