### PR TITLE
fix(types): missing upsert hooks

### PR DESCRIPTION
**Pull request by imsergiobernal**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

Upsert hooks are missing in types. I've made this PR directly from Github UI editor.

### CODE REVIEW

**Comment by imsergiobernal** [comment]
I want to apply this on V5 as well (our current version). How can we achieve it?

**Review by papb — CHANGES_REQUESTED** [review]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

Please add at least one test to make sure your implementation works as intended and to prevent regressions in the future. For good examples on how to test typescript typings, check the following PRs: [11368](https://github.com/sequelize/sequelize/pull/11368/files), [11379](https://github.com/sequelize/sequelize/pull/11379/files), [11520](https://github.com/sequelize/sequelize/pull/11520/files), [13042](https://github.com/sequelize/sequelize/pull/13042/files). You can also use [expect-type](https://www.npmjs.com/package/expect-type#documentation) if you need more complex assertions for your test.

**Comment by papb** [comment]
> I want to apply this on V5 as well (our current version). How can we achieve it?

After this PR is merged, you need to open a new PR pointing to our `v5` branch with the same changes (I recommend using `git cherry-pick` on the merged commit from this PR).

**Comment by papb** [comment]
Also, sorry to take so long to respond here.

**Comment by reediculous456** [comment]
+1, I ran into this today in my development

**Comment by Ygilany** [comment]
any update on this?

**Comment by reediculous456** [comment]
this was fixed in #13394 and should be closed

**Pull request closed without merging**
