### PR TITLE
build: add caching to CI workflow

### PR DESCRIPTION
**Pull request by WikiRik**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [X] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

This will hopefully speed up rerunning checks. Something that @ephys and I have been discussing is that it might be nice if we can store the installed and built artifacts in the first job of this workflow and that it can be reused for the other jobs but that's for a future PR.

### CODE REVIEW

**Comment by ephys** [comment]
I've compared a few different runs and I think on average the install time is shorter
It's also sometimes slower (by a few seconds) but it may still be positive on average.

**Comment by WikiRik** [comment]
Oh yeah, this will only have an impact when you re-run the checks I believe. It's not reusing artifacts within the various checks. That's something I want to take a look at over the next days to really speed up the CI

**Comment by ephys** [comment]
It should still overall have a positive impact across PRs as long as the lockfile is untouched
Do we want to merge this, or do we want to enable it in install-and-build in https://github.com/sequelize/sequelize/pull/14171? (it may be redundant)

**Comment by WikiRik** [comment]
I'll add it to #14171 to see if it helps, otherwise we'll not do it at all. I'll close this PR

**Pull request closed without merging**
