### PR TITLE
Lowercase onDelete option before cheking its value

### PR DESCRIPTION
**Pull request by Verdier**
This allow to define association using uppercase onDelete option: `{ onDelete: 'CASCADE', hooks: true }`. Default values for constraints are uppercase in the doc.

### CODE REVIEW

**Comment by Verdier** [comment]
I've just modified one test to use `CASCADE` because others use `cascade`.

**Comment by janmeier** [comment]
LGTM - could you rebase, then this should be ready to merge

**Comment by Verdier** [comment]
@janmeier done.

**Comment by janmeier** [comment]
Thanks - I manually rebased to remove the merge commit ;)

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/commit/d46a84fffba411983a34841ab43bb8887bd8d837

**Pull request closed without merging**
