### PR TITLE
fix(query-generator): fix add comment when addColumn on postgres(#4386)

### PR DESCRIPTION
**Pull request by theRichu**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change
[#4386](https://github.com/sequelize/sequelize/issues/4386) 
[Error comment on addColumn](https://github.com/sequelize/sequelize/issues/4386#issuecomment-433015711)

### CODE REVIEW

**Comment by sushantdhiman** [comment]
@theRichu This needs unit tests from remaining two dialects i.e mysql and mssql

**Comment by mirkojotic** [comment]
@theRichu let me know if you don't have time to fix this and I can take a look.

**Comment by theRichu** [comment]
@mirkojotic thanks!!

**Comment by mirkojotic** [comment]
@sushantdhiman if @theRichu doesn't mind we can close this PR in favour of
https://github.com/sequelize/sequelize/pull/10117

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/10117

**Pull request closed without merging**
