### PR TITLE
test(cls): fix flaky test and remove relevant tracing code

### LINKED ISSUE #7773: Fix flaky tests
On average, I have to restart 2 jobs on every build until all jobs are green. The errors take the form of `Expected 0 queries running, still 1 queries running`

### PR DESCRIPTION
**Pull request by SimonSchick**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes #7773

See failed build failure for trace https://travis-ci.org/github/sequelize/sequelize/jobs/678904686

### CODE REVIEW

**Comment by SimonSchick** [comment]
cc @jedwards1211

This only leaves one flaky test (that I know of) related to row locking, that one is much rarer tho.

**Comment by SimonSchick** [comment]
Lol node gyp failed.

**Comment by jedwards1211** [comment]
Ah where the DB detects a deadlock?  Do you know which test that is in particular or do a variety of tests random fail once in a blue moon?

**Comment by jedwards1211** [comment]
That's some classic irony about node-gyp

**Comment by SimonSchick** [comment]
@jedwards1211 https://travis-ci.org/github/sequelize/sequelize/jobs/678472682
We could slap a retry on this since it's isolated, feel free to poke at it.

**Comment by jedwards1211** [comment]
Okay, seems like just a race condition between these two promises:

But the MySql dialect stuff isn't supposed to delay `t2Jan.update` from returning until after `t1` is committed is it?
```js
                  return Promise.all([User.findOne({
                    where: {
                      username: 'jan'
                    },
                    transaction: t2
                  }).then(t2Jan => {
                    t2FindSpy();
                    return t2Jan.update({
                      awesome: false
                    }, {
                      transaction: t2
                    }).then(() => {
                      t2UpdateSpy();
                      return t2.commit().then(() => {
                        expect(t2FindSpy).to.have.been.calledBefore(t1Spy); // The find call should have returned
                        expect(t2UpdateSpy).to.have.been.calledAfter(t1Spy); // But the update call should not happen before the first transaction has committed
                      });
                    });
                  }), t1Jan.update({
                    awesome: true
                  }, {
                    transaction: t1
                  }).then(() => {
                    return delay(2000).then(() => {
                      t1Spy();
                      return t1.commit();
                    });
                  })]);
```

**Comment by SimonSchick** [comment]
No idea, I never really worked with explicit SQL locks 😅

**Comment by jedwards1211** [comment]
okay, I have in Postgres but seems like they're not very similar to MySql locks

**Comment by SimonSchick** [comment]
Amended change to make appveyor pass but now coverage failed 😂😂😂

**Pull request merged**
