### PR TITLE
feat: allow case insensitive model fetching

### PR DESCRIPTION
**Pull request by cbardasano**
## Pull Request Checklist

- [X] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

This PR adds the option to use case insensitive search in [`sequelize.model`](https://github.com/sequelize/sequelize/blob/f3253b9f3045b0225b5a321cecffbd754e81fa48/packages/core/src/sequelize.js#L527) function.

By extension, it also adds that option to [`sequelize.isDefined`](https://github.com/sequelize/sequelize/blob/f3253b9f3045b0225b5a321cecffbd754e81fa48/packages/core/src/sequelize.js#L542) and [`modelManager.getModel`](https://github.com/sequelize/sequelize/blob/f3253b9f3045b0225b5a321cecffbd754e81fa48/packages/core/src/model-manager.ts#L33)

By default, the search is case sensitive.

**NOTE: This is the same functionality of #16705 but updated for v7**

### CODE REVIEW

**Comment by ephys** [comment]
Boolean options need to be false by default, and the case sensitive behavior should be the default, so the option should be renamed to "caseInsensitive" and default to false

What is supposed to happen if more than one model match the name?

I don't currently believe the use case is common enough to add such a specific option to our API. You could simply use `findModel` instead

**Comment by cbardasano** [comment]
Well, I needed this kind of search for v6 (I'm using Oracle), which doesn't have `findModel` and there was where I added this functionality. But, you are right, in v7 `findModel` should do the work.

**Comment by ephys** [comment]
Ok, then I'm fine with adding this to v6 (or adding `findModel` in v6). In v7, we removed the options from `getModel` in favor of using `findModel`

**Comment by cbardasano** [comment]
Ok, I'll change the v6 PR to add `findModel`

Thank you!

**Pull request closed without merging**
