### PR TITLE
fix(query-generator): Options.group should be quoted

### PR DESCRIPTION
**Pull request by iyuq**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change
Use aggregate function I got the following sql:
```
'SELECT "userId", sum("cost") AS "sum" FROM "creative_projects" AS "creative_projects" WHERE "creative_projects"."userId" IN ('sub') AND ("creative_projects"."createdAt" >= '2017-03-31 16:00:00.000 +00:00' AND "creative_projects"."createdAt" < '2017-09-30 16:00:00.000 +00:00') GROUP BY userId;'
```
Obviously the quote is miss in `userId`.

### CODE REVIEW

**Comment by iyuq** [comment]
I don't have time to add test case, can somebody help me?

**Comment by iyuq** [comment]
I looked at the test case that failed,
```
{
          title: 'single string argument is not quoted',
          arguments: ['myTable', {group: 'name'}],
          expectation: 'SELECT * FROM `myTable` GROUP BY name;',
          context: QueryGenerator
 }
```
It seems it intends to let the single string argument not quoted. What is the purpose of this?

**Comment by mkaufmaner** [comment]
This is a vulnerability and the test case should be modified to check for quotes

**Comment by iyuq** [comment]
Ok, I will commit to fix the test.

**Pull request merged**
