### PR TITLE
feat(query-generator): add startsWith, endsWith and substring (#9935)

### LINKED ISSUE #9935: Feature Request: startsWith, endsWith, substring operators
## What are you doing?
I want to be able to perform `startsWith`, `endsWith`, and `substring` queries with operators so that I do not have to  manually wrap the where value with the `%` character as is done with the `like` operator. This would be something similar to the query operators offered by the [Django ORM](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#startswith). 

```js
mymodel.findAll({
  where: {
    myField: {
      [Op.startsWith]: 'abc'
    }
  }
})
```

## What do you expect to happen?
Output the equivalent SQL

```
... WHERE myField LIKE 'abc%' ...
```

### PR DESCRIPTION
**Pull request by ferfabricio**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Have you added new tests to prevent regressions?
- [X] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Implements startsWith, endsWith and substring query operatos like in django ORM like described in the issue.

Closes #9935

### CODE REVIEW

**Comment by ferfabricio** [comment]
I think this test is instable. I run many times on a docker and get different results on executions.

image

**Comment by sushantdhiman** [comment]
> I think this test is instable. I run many times on a docker and get different results on executions.

I'll look into this

**Comment by sushantdhiman** [comment]
Thanks @ferfabricio

**Comment by bodhisattva082915** [comment]
Legend. Thanks for the PR @ferfabricio

**Comment by gabegorelick** [comment]
It seems like `startsWith` and `endsWith` are reversed from what they should be, or am I missing something?

See https://github.com/sequelize/sequelize/issues/10743

**Comment by frlinw** [comment]
And based on javascript String, `includes` would have been more relevant than `substring`

**Pull request merged**
