### PR TITLE
Always quote identifiers after AS in join queries. Fixes #1589

### LINKED ISSUE #1589: Postgres Eager loading SQL syntax error.
When I execute `db.GoesVariable.findAll({include: [db.GoesMap]});`

This is what I get:

```
Executing (default): SELECT GoesVariables.*, GoesMaps.variableName AS GoesMaps.variableName, GoesMaps.imagePath AS GoesMaps.imagePath, GoesMaps.dataDate AS GoesMaps.dataDate, GoesMaps.createdAt AS GoesMaps.createdAt, GoesMaps.updatedAt AS GoesMaps.updatedAt FROM GoesVariables LEFT OUTER JOIN GoesMaps AS GoesMaps ON GoesVariables.variableName = GoesMaps.variableName;
{ [error: syntax error at or near "."]
  name: 'error',
  length: 83,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '58',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'scan.l',
  line: '1053',
  routine: 'scanner_yyerror',
```

Is there a way to fix this?

The following has my model definitions
Model: GoesVariable

``` js
'use strict';

module.exports = function(sequelize, DataTypes) {

  var GoesVariable = sequelize.define('GoesVariable', {
    variableName: {
      type: DataTypes.STRING,
      primaryKey: true
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true,
      validate: {
        notEmpty: true
      }
    }
  }, {
    classMethods: {
      associate: function(models) {
        GoesVariable.hasMany(models.GoesMap, {foreignKey: 'variableName'});
        GoesVariable.hasMany(models.GoesData, {foreignKey: 'variableName'});
      }
    }
  });

  return GoesVariable;
};
```

Model: GoesMap

``` js
'use strict';

module.exports = function(sequelize, DataTypes) {
  var GoesMap = sequelize.define('GoesMap', {
    variableName: {
      type: DataTypes.STRING,
      references: 'GoesVariables',
      referencesKey: 'variableName',
      primaryKey: true
    },
    imagePath: {
      type: DataTypes.STRING,
      primaryKey: true,
      validate: {
        notEmpty: true
      }
    },
    dataDate: {
      type: DataTypes.DATE,
      primaryKey: true
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
      primaryKey: true
    },
  }, {
    classMethods: {
      associate: function(models) {
        GoesMap.belongsTo(models.GoesVariable, {foreignKey: 'variableName'});
      },
      getLatest: function(variableName) {
        return GoesMap.find({
          where: {
            variableName: variableName
          },
          order: 'dataDate desc'
        });
      },
      getMapsBetween: function(variableName,startDate, endDate) {
        return GoesMap.findAll({
          where: {
            variableName: variableName,
            dataDate: {
              between: [startDate, endDate]
            }
          }
        });
      }
    }
  });

  return GoesMap;
};

```

### PR DESCRIPTION
**Pull request by idris**

### CODE REVIEW

**Comment by janmeier** [comment]
We need a test case before this can be merged, in order to prevent regressions. 

Perhaps models, associations and the call that failed for you, then we can build a test case from there

**Comment by mickhansen** [comment]
I assume this is only an issue with `quoteIdentifiers: false`?

**Comment by idris** [comment]
Yes, only a problem with `quoteIdentifiers: false`.  Could someone point me in the right direction in terms of testing?  I couldn't figure out how to check the SQL in a unit test.  Should I write an integration test that does the SELECT and asserts no error?

**Comment by janmeier** [comment]
There are no unit test for select query yet - we are still in the progress of rewriting "integration-ish" unit tests to proper unit tests.

You need to add a new file to test/unit/sql - look at the other files in  that folder for inspiration.

You could then add a beforeEach that sets sql.options.quoteIdentifiers to false

**Comment by idris** [comment]
@janmeier @mickhansen: Take a look.. Hopefully these unit tests make sense

**Comment by janmeier** [comment]
@idris Yep, the tests are looking good - Thanks :)!

**Pull request merged**
