### PR TITLE
postgre change

### PR DESCRIPTION
**Pull request by levansuper**
postgre change: in model : when different field name was used exapmle someField:{field:'some_field', type: JSON} update didnt work because the update query didn't generate correctly; in conut: when the search parameter was field with different column name example : someField:{field:'some_field'} the query didnt form correctly

### CODE REVIEW

**Comment by mickhansen** [comment]
Please squash commits and rebase on master (there's a conflict).

**Comment by mickhansen** [comment]
And please include a test :)

**Comment by mickhansen** [comment]
Also i believe this was already fixed when https://github.com/sequelize/sequelize/pull/2791 was merged and fixed.

**Comment by levansuper** [comment]
ok downloaded the new version and it seems to work

**Comment by mickhansen** [comment]
Great, closing then.

**Pull request closed without merging**
