### PR TITLE
fix(dependency): upgrade validator

### PR DESCRIPTION
**Pull request by LaureRC**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

The current validator dependency has 4 security vulnerabilities : 
- https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599
- https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600
- https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601
- https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602

### CODE REVIEW

**Review by Keimeno — APPROVED** [review]

**Comment by AshishDadhich4h2** [comment]
any update on above fix ?

**Review by papb — APPROVED** [review]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

**Comment by rulrok** [comment]
@LaureRC @Keimeno Could you port this to sequelize 5.22.x?

**Comment by manishgadhock-monotype** [comment]
> 5.22.x

+1

**Comment by ephys** [comment]
Sequelize 5 is EOL, upgrade to Sequelize 6, it has very few breaking changes https://sequelize.org/docs/v6/other-topics/upgrade/

**Pull request merged**
