### PR TITLE
fix(types): include 'as' in IncludeThroughOptions definition

### LINKED ISSUE #11185: IncludeThroughOptions missing definition for 'as'
## What are you doing?
IncludeThroughOptions typing does not contain the 'as' property

```typescript
through: {
        as: 'physicianSpecialty',
        attributes: ['isPrimary']
      } as IncludeThroughOptions // must cast here since 'as' is not defined in typings
```

## What do you expect to happen?
TS should compile without having to cast the through options

## Environment
If TypeScript related: TypeScript version: 3.5.3
Tested with latest release:
- [ ] No
- [X] Yes, specify that version:

### PR DESCRIPTION
**Pull request by mrcrow85**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This will add `as` property to the `IncludeThroughOptions` definition.
Closes #11185

### CODE REVIEW

**Comment by papb** [comment]
Since this is currently undocumented, I don't think this should be merged as-is... @mrcrow85 would you be willing to update the docs with this fact as well?

In fact, can you first create an sscce showing this thing working? The issue's OP does not have time, thanks!

**Comment by mrcrow85** [comment]
@papb Sure! I can do that

**Comment by papb** [comment]
Thanks for the work so far @mrcrow85, I have some requests before we can merge this. Since this feature seems a bit obscure to me, I think more has to be done:

* This has to be documented correctly, by adding a new line [here](https://github.com/sequelize/sequelize/blob/21d743a125716518fe85a080785b8a0d9f2f9ede/lib/model.js#L1657)
* I would like to see a test for this behavior, this feature seems untested currently, so please add a test for it [here](https://github.com/sequelize/sequelize/blob/master/test/integration/associations/belongs-to-many.test.js)

**Comment by mrcrow85** [comment]
@papb Don't we also need to update the docs [here](https://github.com/sequelize/sequelize/blob/21d743a125716518fe85a080785b8a0d9f2f9ede/docs/manual/associations.md#belongs-to-many-associations)(on the `findAll` example)?

**Comment by papb** [comment]
@mrcrow85 Not every feature is explained in the guides/tutorials, so I wouldn't say it is strictly necessary. Also, since I happen to be in the middle of rewriting the guides already, don't worry about it.

**Comment by mrcrow85** [comment]
@papb Does the codecov report is ok? Seeing 21% less coverage really worries me.

**Comment by mrcrow85** [comment]
> @papb Does the codecov report is ok? Seeing 21% less coverage really worries me.

Ok, nevermind. It fixed itself :thinking:

**Comment by papb** [comment]
Thanks @mrcrow85, great work!

**Pull request merged**
