### PR TITLE
feat(model): add `options.include[].right` option

### PR DESCRIPTION
**Pull request by ckeboss**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Add ability to specify a right join for associations

Addresses #4187, should we reopen it?

`test/integration/model/count.test.js` was changed due to the linter. I can revert it if you would like.

### CODE REVIEW

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

I have reopened the issue :+1:

I don't have time to look into your PR now though

**Comment by papb** [comment]
Do you consider this PR ready for merge or is it still a work in progress?

**Comment by ckeboss** [comment]
Yes, finished it up last night. Had to make some updates in regards to sqlite not supporting right joins.

**Comment by papb** [comment]
This looks good, but I am not sure about the current sqlite behavior. Currently, if I pass `right: true` to an SQLite call, it will silently ignore it and perform a left join... I'm not sure this is the best way... What do you think about this? Perhaps an error instead or at least a warning?

**Comment by ckeboss** [comment]
Is there any precedence for this? How does the library currently handle unsupported features in dialects? The only one I found was `UNION ALL` which just fallbacks to `UNION`.

I am open to other ways.

**Comment by papb** [comment]
I'm not sure really... Let's see what @sushantdhiman thinks about it.

**Comment by papb** [comment]
Thank you very much for the help @ckeboss!!

**Pull request merged**
