### PR TITLE
Corrected Typos

### PR DESCRIPTION
**Pull request by Codertaker**
Hi, I have corrected some minor typos in some of the pages such as : "Assocation" to "Association" and "Instace" to "Instance".

### CODE REVIEW

**Comment by janmeier** [comment]
The API docs are auto-generated - please update the code as well

**Comment by Codertaker** [comment]
@janmeier This is my first pull request and I am a student. Would you be able to clarify your last statement? Thanks!

**Comment by janmeier** [comment]
The docs are generated automatically from code comments - which means your changes will be overwritten next time we generate the docs, unless you change the comments as well

**Comment by Codertaker** [comment]
I have made the changes to the comments. Hope it helps.

**Comment by janmeier** [comment]
You forgot the comments for has one and the function parameters though ;-)

**Comment by Codertaker** [comment]
I'm not sure if i made the right changes but here they are! Thank you for your patience.

**Comment by janmeier** [comment]
Turns out the code was already updated - only the actual docs needed to be updated. Thanks for pointing it out :)

**Pull request closed without merging**
