### PR TITLE
fix(types): add Buffer to WhereValue type

### PR DESCRIPTION
**Pull request by fubar**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

`where` clauses that contain Buffer values (querying binary fields) fail Typescript validation due to a missing type declaration. Example:

```js
Foo.findOne({
  where: { bar: Buffer.alloc(0) },
});
```

This PR adds the missing Buffer type to the `WhereValue` type definition.

I ran `npm run test-typings`

### CODE REVIEW

**Comment by SimonSchick** [comment]
Can you please add a test for this as well?

**Comment by fubar** [comment]
@SimonSchick if you tell me how, more than happy to. `npm run test-typings` is producing no output, even when I explicitly throw an error in any of the files in `types/test`.

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

Testing the TypeScript typings consists simply on checking if some code can be compiled. In other words, a typings test is just some TS code that should compile. What it does when executed is irrelevant, the test is simply to compile it without errors, as can be seen in our CI configuration (using `npm run test-typings`) [here](https://github.com/sequelize/sequelize/blob/bd59b8729b8d898d2f3ce8deb764777bab7e57d5/.travis.yml#L49) and [here](https://github.com/sequelize/sequelize/blob/bd59b8729b8d898d2f3ce8deb764777bab7e57d5/package.json#L152). Since it's just a compilation, getting no output from it means that it passed. Getting a compilation error is a failure. Note that if you directly throw an error from your typings test code, the test will still pass because throwing an error is something that compiles just fine.

For good examples on how to write typescript typings, check the following PRs: #11368 #11378 #11520

Let me know if you need further help!

**Comment by fubar** [comment]
@papb right of course, makes sense. I've added a test for all WhereValue literals.

I've noticed some linting issues in those typescript files. What do you think of covering them under the existing eslint setup? Happy to put it a PR for it.

**Comment by SimonSchick** [comment]
I'd rather use TSLint for that until eslint is fully feature on-par with it, PR is welcome though :)

**Comment by fubar** [comment]
TSLint is reaching end of life on Jan 1st and will be officially replaced by ESLint (see https://github.com/palantir/tslint/issues/4534). We've been using the `typescript-eslint` parser and plugin in our repos, which works pretty well and allows the same set of rules to be applied to JS and TS.

**Comment by SimonSchick** [comment]
I haven't checked on their progress, but that sounds promising feel free to ahead with that.

**Comment by fubar** [comment]
@papb quick follow-up - all tests are passing now.

**Pull request merged**
