### PR TITLE
Added simple Postgres JSON support

### PR DESCRIPTION
**Pull request by jede**
This makes Sequelize support the new postgres JSON type! I added a test case based on the test case for HStore.

### CODE REVIEW

**Comment by timini** [comment]
:+1:  Json please!

**Comment by jonathanleang** [comment]
:+1:

**Comment by mickhansen** [comment]
@jonathanleang what part are you (y)'ing exactly? JSON support has landed, no JSONB yet though.

**Comment by Bondifrench** [comment]
@jonathanleang @timini 
JSON has been added, see here: https://github.com/sequelize/sequelize/pull/2314 and you can see an example here: https://github.com/sequelize/sequelize/blob/master/examples/postgres-json-datatype/app.js 
but @mickhansen the latest docs http://sequelize.readthedocs.org/en/latest/docs/models/#data-types don't mention JSON as a datatype

**Comment by mickhansen** [comment]
@Bondifrench that shall have to be added :)

**Comment by sunitJindal** [comment]
@Bondifrench links seems to be boken

**Comment by nparsons08** [comment]
Link is broken........

**Comment by janmeier** [comment]
The examples directory has been removed, since most were outdated. Have a look at the tests instead https://github.com/sequelize/sequelize/blob/master/test/integration/model/json.test.js plus the querying JSON section of the docs http://docs.sequelizejs.com/en/latest/docs/querying/#jsonb

**Pull request closed without merging**
