### PR TITLE
Moved predefined dialects to public object.

### PR DESCRIPTION
**Pull request by ziflex**
It will make 'sequelize' more modular and will allow us to provide custom implementations of different dialects.

### CODE REVIEW

**Comment by janmeier** [comment]
I think I like the general idea here, but you forgot mysql ;)

**Comment by ziflex** [comment]
Ooops :) Fixed!

**Comment by mickhansen** [comment]
I like the idea - However i'm not sure that we'll want this to be public API that we have to maintain, since we might want to move to some kind of store setup in the future.

@janmeier thoughts?

**Comment by janmeier** [comment]
@mickhansen true - we want pluggable stores / connectors to be public API, but this might not be the best solution

**Comment by ziflex** [comment]
I came up with this solution because I needed to provide custom implementation of sqlite provider. 
So, if there is another solution with similar feature I will be happy :D

**Comment by mickhansen** [comment]
@ziflex There isn't yet, but we're looking to design one. Hence why we can't introduce public API willy nilly.

**Comment by ziflex** [comment]
@mickhansen what if we introduce static method called 'registerDialect'? It will let us to incapsulate the internal logic. 
I really need this possibility, don't want to use fork in production.

**Comment by mickhansen** [comment]
@ziflex That will still be non-ideal public API we will need to maintain. I'd be very open to discussing a store API.

I'm thinking something like:

```js
new Sequelize({
  stores: [
    new (require('sequelize/stores/mysql2')({
      dialect: require('sequelize/dialects/msql') // possibly with a default dialect in the store
      write: true, // Make it possible to have multiple write stores for 2-part data migrations or set your app to read-only
      read: true
    });
  ]
});
```

**Comment by ziflex** [comment]
@mickhansen sorry for delay. Do you want to implement all these features at once? And do you still consider this way ?

**Comment by mickhansen** [comment]
@ziflex We likely won't accept this PR since it means less-than-ideal public API that has to be supported.

**Comment by ziflex** [comment]
@mickhansen with current PR everything is clear. But I'm asking about your proposal regarding store API.

**Comment by mickhansen** [comment]
@ziflex We're stilling considering it yes - And we won't get to it for a bit.

**Pull request closed without merging**
