### PR TITLE
Fixes transaction not getting cleaned up with sqlite Closes #4245

### LINKED ISSUE #4245: transaction does not clean up with sqlite
IDK if this affects other dialects but i am using sqlite3. 

Transactions are not getting removed from the connectionManager because the connection uuid is getting set to undefined before the connection is released. This might lead to long term resource  leaking.

The [old code found here](https://github.com/sequelize/sequelize/blob/f678009d7514b81a6f87e12b86360e9a597e3ca8/lib/transaction.js#L216-L225):

    Transaction.prototype.cleanup = function() {
      var cls = this.sequelize.constructor.cls;

      this.connection.uuid = undefined;

      if (cls) {
        if (cls.get('transaction') === this) {
         cls.set('transaction', null);
        }
      }

What i did to fix it (currently used as an override in my code, no PR, sorry):
    
    Transaction.prototype.cleanup = function() {
		var cls = this.sequelize.constructor.cls;
		if(cls && cls.get('transaction') === this) cls.set('transaction', null);
		
		return this.sequelize.connectionManager.releaseConnection(this.connection);
	};

### PR DESCRIPTION
**Pull request by codyrigney92**
This addresses https://github.com/sequelize/sequelize/issues/4245.

### CODE REVIEW

**Comment by codyrigney92** [comment]
I don't understand what would have caused the build to fail.  Can it be rerun?

**Comment by mickhansen** [comment]
Unrelated to this PR.
LGTM, although this does expose some inconsistencies in connection releasing.

/cc @janmeier

**Comment by janmeier** [comment]
LGTM too - thanks @codyrigney92 

I can't figure out a better way to fix the inconsistensies right now ...

**Comment by codyrigney92** [comment]
It looks like the 3.10.0 release came out right before this was merged, so the changelog item for this is in the wrong spot.  Should that be fixed?

**Pull request merged**
