### PR TITLE
docs(types): Add explanatory comments to operators

### PR DESCRIPTION
**Pull request by negezor**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Adds a description to the operators. Previously, you had to look only in the documentation.
Before:
image
After:
image

### CODE REVIEW

**Comment by negezor** [comment]
@papb I did not find their application in the [documentation](https://sequelize.org/master/manual/querying.html#operators).

**Comment by papb** [comment]
@negezor Makes sense. Thanks!

Would you be willing to dig in the source code to figure out what they do and improve both the typings and the docs? (this could be done as a separate PR, and is totally up to you, this PR is good as is)

**Comment by negezor** [comment]
I will supplement the documentation of this pull request.

**Comment by negezor** [comment]
I added explanatory comments to the remaining operators.

**Comment by papb** [comment]
@negezor Great!

Since you're into this already, can you please update [querying.md#operators](https://github.com/sequelize/sequelize/blob/master/docs/querying.md#operators) as well?

**Comment by negezor** [comment]
I added only the public API to the documentation. Because I am more than sure that `Op.values` and `Op.placheloder` are internal.

**Comment by papb** [comment]
LGTM

Let's wait for @sushantdhiman

**Pull request merged**
