### PR TITLE
[v3] fix(sqlite): properly catch errors

### PR DESCRIPTION
**Pull request by papb**
See #11862

See vulnerability report at https://www.npmjs.com/advisories/1142

PR to v4 here: #11877

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Need a test for this

**Comment by papb** [comment]
What is happening with v3 ci?

**Comment by sushantdhiman** [comment]
Build is broken for Travis

**Comment by papb** [comment]
@sushantdhiman What should I do?

**Comment by sushantdhiman** [comment]
@papb Need to fix whatever error causing build failure, I am thinking about deprecating v3/v4 so we can focus on recent releases

**Pull request closed without merging**
