### PR TITLE
feat: deprecate accessing DataTypes directly on Sequelize class

### PR DESCRIPTION
**Pull request by ephys**
### Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [x] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

This PR deprecates accessing DataTypes directly on the Sequelize constructor.
Instead, users should use the `DataTypes` object.

These DataTypes take up a lot of possible names and should be kept in their own namespace:

```typescript
// deprecated
Sequelize.STRING
Sequelize.INTEGER
// ...

// not deprecated
DataTypes.STRING
DataTypes.INTEGER
// ...

Sequelize.DataTypes.STRING
Sequelize.DataTypes.INTEGER
// ...
```

### CODE REVIEW

**Comment by WikiRik** [comment]
Maybe I missed it with my quick scroll through the changes, but do we test somewhere that `Sequelize.DataTypes.STRING` is valid?

**Comment by ephys** [comment]
Not directly but `require('@sequelize/core')` returns `Sequelize` so `const { DataTypes } = require('@sequelize/core');` is equal to `Sequelize.DataTypes`

**Comment by WikiRik** [comment]
Ah of course, that's true

**Review by WikiRik — APPROVED** [review]

**Comment by fzn0x** [comment]
Nice changes, remove confusion between using `Sequelize` class workaround or not for DataTypes.

**Review by sdepold — COMMENTED** [review]
Can we mark this as breaking change in the commit message somehow?

Good change overall

**Comment by sdepold** [comment]
Oh. Too slow :(

**Comment by sdepold** [comment]
Aha! There is a pr for this.

**Comment by WikiRik** [comment]
> Aha! There is a pr for this. 

To document this change? Yeah, this is indeed something that we needed to put in the upgrade guide

**Pull request merged**
