### PR TITLE
fix column comments

### PR DESCRIPTION
**Pull request by connyay**
Column comments seem to have been remove by 0c1ec1cc0f38edb1d57d0a37d26f3664440c6f49. Not sure why?

Column comments are still mentioned in [the docs](http://docs.sequelizejs.com/en/latest/docs/models/) but are currently unable to be created.

### CODE REVIEW

**Comment by connyay** [comment]
Ah. I see now https://github.com/sequelize/sequelize/issues/1521.. Looks like that fixed the references comments, and now I re-broke the references comments :frowning:

**Comment by mickhansen** [comment]
I removed them cause they were causing more trouble than they were worth it seemed :)

**Comment by BridgeAR** [comment]
@connyay do you still want to fix and implement the comments feature?

**Comment by connyay** [comment]
@BridgeAR because of the above comment, I would probably say no. I ended up just adding comments via migrations.

**Comment by justechn** [comment]
Can we get the docs updated then to reflect that comments are not working

**Comment by geoidesic** [comment]
How do we add table (not column) comments via migrations? I can't find documentation for this.

**Pull request closed without merging**
