### PR TITLE
fix(model): check attributes specified for included through model

### PR DESCRIPTION
**Pull request by aristov**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

```js
Project.belongsToMany(User, { through : 'UserProject' })
User.belongsToMany(Project, { through : 'UserProject' })

User.findAll({
  include : [
    {
      model : Project,
      through : {
        attributes : [] // the option is fixed by this change
      }
    }
  ]
})
```

### CODE REVIEW

**Comment by aristov** [comment]
Let me know If anybody cares. Then I complete the PR by tests.

**Comment by haseebsaeed** [comment]
> Let me know If anybody cares. Then I complete the PR by tests.

me and my production code are waiting for this.

**Comment by aristov** [comment]
I have no idea how to fix MariaDB tests. I need help to solve this problem.

**Comment by sushantdhiman** [comment]
This need a port to master branch first

**Comment by sushantdhiman** [comment]
MariaDB is currently broken on v5, ignore it for now

**Comment by aristov** [comment]
> This need a port to master branch first

Should I rebase this branch from master and change the PR's target branch to master, or create a new PR?

**Comment by sushantdhiman** [comment]
> Should I rebase this branch from master and change the PR's target branch to master, or create a new PR?

Depends if you are looking to have this released to v5. If you are just fixing the bug (thank you), just set target to `master`

**Comment by Bat-Orshikh** [comment]
> Let me know If anybody cares. Then I complete the PR by tests.

@aristov 

I need those changes on my production environment.
So I am waiting this PR gets merged.

@sushantdhiman 
Please merge it as soon as possible. 🙏 🙏 🙏

**Comment by aristov** [comment]
> This need a port to master branch first

Done: https://github.com/sequelize/sequelize/pull/12316

**Pull request merged**
