### PR TITLE
Implement SMALLINT and TINYINT datatypes.

### PR DESCRIPTION
**Pull request by dantman**
I'd like to see support for SMALLINT and TINYINT.

I 'wrote' the code for them. However I haven't tested them myself since my machine doesn't have the requirements to `npm install` Sequelize's `devDependencies`.

### CODE REVIEW

**Comment by OscarGodson** [comment]
Yes, I'd really love to see TINYINT. I have a permissions level that will never be two digits, but it'll be between 0-3. I can't use BOOLEAN which means I have to fall back on INTEGER

**Comment by dantman** [comment]
I've rebased and refactored the code.

However I can't test it and there is a new quirk in Sequelize.

PostgreSQL's driver now knows about the oids for the datatype. However I presume both SMALLINT and TINYINT are internally int2 since pg doesn't have a smaller int type. I don't know how this affects Sequelize.

**Comment by mickhansen** [comment]
Build is completely broken, issue with syntax.

**Comment by quiddle** [comment]
I'd love to see this as well!

**Comment by zaggino** [comment]
Hi, still no way to use `SMALLINT` in Sequelize?

**Pull request closed without merging**
