### PR TITLE
Closes #5985 -- Fixed an issue where custom-named model fields break when offsetting, ordering, and including hasMany simultaneously.

### LINKED ISSUE #5985: Custom-named model fields break when offsetting, ordering, and including hasMany simultaneously.
## What you are doing?
Sequelize doesn't seem to understand the naming of fields in the database outside of a subquery clause when ordering, offsetting and including members from a hasMany relationship. Here is an example:

```
        var Foo = current.define('foo', {
            fooId: {
              field: 'foo_id',
              type: DataTypes.UUID,
              primaryKey: true
            },
            baseNumber: {
              field: 'base_number',
              type: DataTypes.STRING(25)
            }
          }, {
          timestamps: false
        }),
          Bar = current.define('bar', {
            barId: {
              field: 'bar_id',
              type: DataTypes.UUID,
              primaryKey: true
            },
            fooId: {
              field: 'foo_id',
              type: DataTypes.UUID,
              allowNull: false
            }
          }, {
            timestamps: false
          });

        Foo.hasMany(Bar, {foreignKey: 'foo_id', as: 'bars'})

        return current.sync({force: true})
          .then(function () {
            var options = {
              include: [
                {
                  model: Bar, as: 'bars'
                }
              ],
              offset: 0,
              limit: 50,
              order: [['base_number', 'ASC']]
            };

           // This statement throws an exception.
            return Foo.findAll(options).then(function () {
              console.log('success!')
            })
          });
```

## What do you expect to happen?
I expect a proper data set in return.

## What is actually happening?
The output throws. This appears to be because the SQL that happens is the following:

> SELECT "foo".*, "bars"."bar_id" AS "bars.barId", "bars"."foo_id" AS "bars.fooId", "bars"."foo_id" AS "bars.foo_id" FROM (SELECT "foo"."foo_id" AS "fooId", "foo"."base_number" AS "baseNumber" FROM "foos" AS "foo" ORDER BY "foo"."base_number" ASC LIMIT 50 OFFSET 0) AS "foo" LEFT OUTER JOIN "bars" AS "bars" ON "foo"."fooId" = "bars"."foo_id" ORDER BY "foo"."base_number" ASC;

This causes postgres to return the following error:

>  column foo.base_number does not exist

The proper query should be:

> SELECT "foo".*, "bars"."bar_id" AS "bars.barId", "bars"."foo_id" AS "bars.fooId", "bars"."foo_id" AS "bars.foo_id" FROM (SELECT "foo"."foo_id" AS "fooId", "foo"."base_number" AS "baseNumber" FROM "foos" AS "foo" ORDER BY "foo"."base_number" ASC LIMIT 50 OFFSET 0) AS "foo" LEFT OUTER JOIN "bars" AS "bars" ON "foo"."fooId" = "bars"."foo_id" ORDER BY "foo"."baseNumber" ASC;

__Dialect:__ any
__Database version:__ 9.5.2.0
__Sequelize version:__ 4.0.0

### PR DESCRIPTION
**Pull request by DavidMorton**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Have you added an entry under `Future` in the changelog?

### Description of change

- [FIXED] Fixed an issue where custom-named model fields break when offsetting, ordering, and including hasMany simultaneously. [#5985] (https://github.com/sequelize/sequelize/issues/5985)

### CODE REVIEW

**Comment by DavidMorton** [comment]
This was breaking ordering on a grid of ours, but we don't want to change our model because it'll break the API, so hence, I humbly submit this fix.

**Comment by mickhansen** [comment]
As a note if you want this released soon you should target the v3 branch.

**Comment by janmeier** [comment]
We might not need this fix in 4.0 at all, once https://github.com/sequelize/sequelize/issues/5708 lands

**Comment by DavidMorton** [comment]
Alright. I've added #5996 to add this support in v3.

**Pull request closed without merging**
