### PR TITLE
PostgreSQL tsrange data type support.

### PR DESCRIPTION
**Pull request by ozum**
There are already other range data types for PostgreSQL, but tsrange is missing. See [Range Types on PostgreSQL doc](http://www.postgresql.org/docs/9.4/static/rangetypes.html).

This patch competes range types.

Regards,

### CODE REVIEW

**Comment by mickhansen** [comment]
Please add changelog notice to "Future" rather than add a new version yourself.
Needs a squash to a single commit, otherwise LGTM.

**Comment by ozum** [comment]
@mickhansen I've corrected version number on changelog and package.json.

Could you please check if it complies contribution rules now?

**Comment by mickhansen** [comment]
Looks good, needs a rebase (to resolve conflict) and a squash (to have a single descriptive commit) though.

**Comment by ozum** [comment]
@mickhansen. I messed my commits. I will recreate from scratch in another pull request. Could you please discard this pull request.

**Pull request closed without merging**
