### PR TITLE
feat(postgresql/validateSchemas)

### PR DESCRIPTION
**Pull request by hiradimir**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

I thought production deployment cycle.
But, I am worried migration script has mistake because it is generated by manually.
I am thinking schema-validation feature and then implementing.

I think I should write test too, but I cannot all test of model. 
For example migration-scripts are correct sql, but migrated db is may not same model-schema.
ex) model string field length is 255, but schema string field length 64.

### CODE REVIEW

**Comment by eseliger** [comment]
@hiradimir there are conflicts

**Comment by hiradimir** [comment]
@eseliger fix it!

This PR is still for postgresql only. 
PR is decreased coverage because CI seems to is not checking with postgresql dialect.

**Comment by eseliger** [comment]
somehow, the travis hook seems not to be triggered 🤔 try again in a few hours or so, maybe they are having difficulties right now

**Comment by sushantdhiman** [comment]
Validating schema before running a migration seems like a CLI domain problem. We should not add this to ORM code base. Its supposed to be used with migration, lets move this to CLI then.

If you want you can open a PR to CLI but then you will have to add support for other database as well.

**Comment by hiradimir** [comment]
@sushantdhiman 
I hope to add validate schema feature to ORM code base.
Because, I think this feature shoud be in options for sequelize#sync.
The idea is from hibernate 
ex: [hibernate.hbm2ddl.auto: validate](https://docs.jboss.org/hibernate/orm/5.0/manual/en-US/html/ch03.html)

But, I did not add sequelize#sync options, I thought it is risk.
Because, this code was imcplete, I shoud be want to add options after more brush up.

----

I want this feature running in another section on sequelize-cli.
If you not accept this PR, I will create another plugin ex) npm:seqelize-validate-schema.

**Comment by sushantdhiman** [comment]
A plugin seem like best approach for now @hiradimir , we can always include it in core if there is huge demand but doing opposite is complex.

**Comment by hiradimir** [comment]
@sushantdhiman Okey, Thanks for reply!

**Pull request closed without merging**
