### PR TITLE
fix(query): make stacktraces include original calling code

### LINKED ISSUE #6983: transaction stack traces unhelpful
I'm using bluebird with long stack trace option on.
However, when a transaction is rejected, I have no idea where the wrong query is run.

      error:  SequelizeForeignKeyConstraintError: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`enrev`.`Devices`, CONSTRAINT `distributorId_foreign_idx_device` FOREIGN KEY (`distributorId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)
          at Query.formatError (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/dialects/mysql/query.js:168:14)
          at Query._callback (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
          at Query.Sequence.end (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
          at Query.ErrorPacket (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
          at Protocol._parsePacket (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/Protocol.js:280:23)
          at Parser.write (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/Parser.js:74:12)
          at Protocol.write (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/Protocol.js:39:16)
          at Socket.<anonymous> (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/Connection.js:109:28)
          at emitOne (events.js:96:13)
          at Socket.emit (events.js:188:7)
          at readableAddChunk (_stream_readable.js:176:18)
          at Socket.Readable.push (_stream_readable.js:134:10)
          at TCP.onread (net.js:551:20)
      From previous event:
          at Query.run (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
          at /home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:849:20
          at /home/phil/Sorgenti/blackbox/node_modules/retry-as-promised/index.js:40:21
      From previous event:
          at retryAsPromised (/home/phil/Sorgenti/blackbox/node_modules/retry-as-promised/index.js:30:10)
          at /home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:848:12
      From previous event:
          at Promise.then (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/promise.js:21:17)
          at transactionResolver (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:1284:40)
      From previous event:
          at Sequelize.transaction (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:1313:12)
          at User.updateAsAdmin (/home/phil/Sorgenti/blackbox/release/js/api/controller/user.js:239:27)
          at User.update (/home/phil/Sorgenti/blackbox/release/js/api/controller/user.js:182:18)
          at Layer.handle [as handle_request] (/home/phil/Sorgenti/blackbox/node_modules/express/lib/router/layer.js:95:5)
          at next (/home/phil/Sorgenti/blackbox/node_modules/express/lib/router/route.js:131:13)
          at passport.authenticate (/home/phil/Sorgenti/blackbox/release/js/api/config/policies.js:58:24)
          at complete (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/middleware/authenticate.js:250:13)
          at /home/phil/Sorgenti/blackbox/node_modules/passport/lib/middleware/authenticate.js:257:15
          at pass (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:421:14)
          at Authenticator.transformAuthInfo (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:443:5)
          at /home/phil/Sorgenti/blackbox/node_modules/passport/lib/middleware/authenticate.js:254:22
          at /home/phil/Sorgenti/blackbox/node_modules/passport/lib/http/request.js:60:7
          at pass (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:267:43)
          at serialized (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:276:7)
          at /home/phil/Sorgenti/blackbox/release/js/api/config/passport.js:14:13
          at pass (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:284:9)
          at Authenticator.serializeUser (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:289:5)
          at IncomingMessage.req.login.req.logIn (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/http/request.js:50:29)
          at Strategy.strategy.success (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/middleware/authenticate.js:235:13)
          at verified (/home/phil/Sorgenti/blackbox/node_modules/passport-http-bearer/lib/strategy.js:126:10)
          at Model.db.models.Token.findOne.then (/home/phil/Sorgenti/blackbox/release/js/api/config/passport.js:73:21)
     
the relevant lines are

      at Sequelize.transaction (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:1313:12)
      at User.updateAsAdmin (/home/phil/Sorgenti/blackbox/release/js/api/controller/user.js:239:27)
      at User.update (/home/phil/Sorgenti/blackbox/release/js/api/controller/user.js:182:18)

user.js:239 is where the transaction begins, but there's no mention on where the actual query is located.

### LINKED ISSUE #8199: Support for enabling long stack traces
I think it would be nice to be able to activate long stack traces for debug purposes, similar to what Bluebird does: http://bluebirdjs.com/docs/api/promise.longstacktraces.html
Currently, in a complex application, getting an error like this is really not very helpful:
```
TypeError: Cannot read property 'field' of undefined
        at options.defaults.Object.keys.map.name (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/sequelize/lib/model.js:2078:117)
        at Array.map (native)
        at create.then.catch.err (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/sequelize/lib/model.js:2078:81)
        at tryCatcher (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/util.js:16:23)
        at /Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/catch_filter.js:17:41
        at tryCatcher (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/promise.js:689:18)
        at Async._drainQueue (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/async.js:133:16)
        at Async._drainQueues (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/async.js:143:10)
        at Immediate.Async.drainQueues (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)
```

### LINKED ISSUE #12044: Stack traces are awful
No one wants stack traces like this, and they don't have to be this bad in recent versions of node.

```
SequelizeValidationError: Validation error: Cannot read property 'length' of undefined
      at Promise.all.then (node_modules/sequelize/lib/instance-validator.js:74:15)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:673:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:145:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:673:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:145:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:673:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:145:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
      at process.topLevelDomainCallback (domain.js:120:23)
```

### PR DESCRIPTION
**Pull request by hsource**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

#### Problem

Most of the time, users want stacktraces that point to where in their code it broke, rather than where in Sequelize/MySQL libraries it broken.

Currently, stacktraces often look like this and have no mention of the actual user code:

```
SequelizeDatabaseError: Lock wait timeout exceeded; try restarting transaction
   at Query.formatError (/home/web/app/node_modules/sequelize/lib/dialects/mysql/query.js:235:16)
   at Execute.handler [as onResult] (/home/web/app/node_modules/sequelize/lib/dialects/mysql/query.js:46:23)
   at Execute.execute (/home/web/app/node_modules/mysql2/lib/commands/command.js:30:14)
   at Connection.handlePacket (/home/web/app/node_modules/mysql2/lib/connection.js:455:32)
   at PacketParser.onPacket (/home/web/app/node_modules/mysql2/lib/connection.js:73:18)
   at PacketParser.executeStart (/home/web/app/node_modules/mysql2/lib/packet_parser.js:75:16)
   at Socket.<anonymous> (/home/web/app/node_modules/mysql2/lib/connection.js:80:31)
   at Socket.emit (events.js:315:20)
   at Socket.EventEmitter.emit (domain.js:529:15)
   at addChunk (internal/streams/readable.js:309:12)
   at readableAddChunk (internal/streams/readable.js:284:9)
   at Socket.Readable.push (internal/streams/readable.js:223:10)
   at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
   at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```

#### Solution

Note that this fix relies on Node 12+'s async stacktrace support. Stacktraces before Node 12 will still be not that useful.

This fix creates a dummy error in a context before we send off the query. Then, if we catch any errors, it uses that dummy error's stacktrace to give users something they can then debug.

1. Add an additional parameter `errStack` to all `formatError` functions so they can override the stack
2. Set `errStack` to be the stack of a dummy error created in the original `query` function of different `query-interface` classes
3. Change most existing error types to support this `errStack`
4. Update the `query-interface` test to verify the stack includes the original calling function

Closes #8199. Closes #12044. Closes #6983; probably some more.

#### Testing

Tested by running tests on all platforms and verifying that they pass.

Tested the specific new tests by changing mocharc.jsonc to this:

```jsonc
{
  // You can temporarily modify this file during local development to add `spec` (and
  // even `grep`) in order to be able to call `DIALECT=some-dialect npx mocha` from a
  // terminal and execute only a one (or a few) tests (such as new tests you are
  // creating, for example).
  // Recall that if you want to `grep` over all tests, you need to specify `spec` as
  // `"test/**/*.test.js"`. Not specifying `spec` and calling `npx mocha` will not
  // execute any test.
  "spec": ["test/**/query.test.js"],
  // "grep": ["some test title here"],
  "exit": true,
  "check-leaks": true,
  "timeout": 30000,
  "reporter": "spec"
}
```

and then running `DIALECT=mssql npm run mocha`, replacing all 5 dialects.

#### Before and after

Output of adding `console.log(err.stack)` in the new tests

Before

```
SequelizeDatabaseError: Invalid column name 'unknown_column'.
    at Query.formatError (/Users/harry/code/sequelize/lib/dialects/mssql/query.js:314:12)
    at Query._run (/Users/harry/code/sequelize/lib/dialects/mssql/query.js:93:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

After

```
Error
    at Query.run (/Users/harry/code/sequelize/lib/dialects/mssql/query.js:119:25)
    at /Users/harry/code/sequelize/lib/sequelize.js:619:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (/Users/harry/code/sequelize/test/integration/sequelize/query.test.js:319:11)
```

### CODE REVIEW

**Comment by pjschmidt3** [comment]
Any chances of getting this merged? Not having useful stack traces for any sequelize queries pretty significantly impacts developer QOL, especially on larger projects where it isn't always immediately obvious which query is the source of the error.

**Comment by fncolon** [comment]
Hello @papb and other maintainers, can you review this pull requests to giving chances of this to being merged? look like the community will like it for Sequelize 2021.

**Review by fncolon — APPROVED** [review]

**Comment by WilliamNurmi** [comment]
Could this be reopened and merged, please? It was closed as stale although it would be a very good improvement.

**Comment by fncolon** [comment]
> Could this be reopened and merged, please? It was closed as stale although it would be a very good improvement.

Reopened! sorry for late response!

**Comment by fncolon** [comment]
Awesome work! thanks, look like you refactor some codes too!

**Comment by sinasalek** [comment]
Please merge this in. it's impossible to debug some of the errors sequelize throws due to lack of proper backtrace

**Comment by WikiRik** [comment]
This is merged, it will be part of the next release

**Comment by jedwards1211** [comment]
Woohoo!  Looking forward to this

**Comment by benasher44** [comment]
This is a great improvement, but I think there's still one missing piece here. I think because there is no await for the retry [here](https://github.com/sequelize/sequelize/blob/3059bce6003ca77b5e67cf7d6d673597b704db0e/lib/sequelize.js#L613), stack back to the calling code, outside of Sequelize, gets lost (see https://www.even.li/posts/2020-06-04-async-stack-traces/). At least in our code, we're still not able to see traces leave Sequelize.query, and I think this is a contributing factor.

**Comment by WikiRik** [comment]
@benasher44 could you make a PR with the proposed fix?

**Comment by benasher44** [comment]
I'm interested! I should have time in the next few weeks (maybe sooner). 

I should also add this may not be as trivial as I thought. I looked, and retry comes from the retry-as-promised library. Fixing this may require removing that dependency. This shouldn't be a problem now that Sequelize uses native promises, but it's worth calling out that testing may reveal that as a requirement, which would add effort (though not much I think).

**Comment by benasher44** [comment]
Circling back, it turns out we weren't getting good async stack traces because we hadn't touched our tsconfig target in 3-4 years. It was still set to es6, so the TS-generated code was still using `tslib.__awaiter`. We're on node 16, so I bumped it to es2021, which resulted in code that actually used `async`/`await`, and now our stack traces are complete.

I encourage anyone using sequelize with TypeScript to consult [node.green](https://node.green) and set their tsconfig.target to the higher version supported by their node version.

Getting back to the issue at hand, adding an await in front of [this retry](https://github.com/sequelize/sequelize/blob/3059bce6003ca77b5e67cf7d6d673597b704db0e/lib/sequelize.js#L613) does add one more frame to the stack trace. After digging into this problem (how do you always remember to `return await` to keep stack traces nice) some more, we stumbled upon the [return-await eslint rule](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/return-await.md). Since this is in `typescript-eslint`, I assume this only helps for TypeScript code bases? Good thing I see those migration-to-typescript PRs coming through :).

Anyway, I could open a PR to add the `return await`, but I don't think it'll meaningfully improve the trace here (just adds one, not-so-important frame). As sequelize moves to TypeScript though, that eslint rule would be a good one to add in to ensure stack traces stay complete (can always add eslint ignores in places you disagree with it).

**Comment by benasher44** [comment]
Sure! I want to carve out some time to do some Sequelize PRs. I'll keep this one on my list.

**Pull request merged**
