### PR TITLE
ES6 conversion of dialect tests

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?

### Description of change

`integration/dialect` these test are grouped properly but many tests are still scattered in some other big tests. I haven't touched them yet. This PR only convert these tests to ES6.

In next PRs I would move more dialect specific tests to these sections.

### CODE REVIEW

**Comment by mickhansen** [comment]
We really ought to consider implement bluebird-coroutines when we do to es6, otherwise i don't see a huge value in converting the tests - It does take up review time :)

**Comment by sushantdhiman** [comment]
Ok I'll start converting these to coroutines

**Comment by overlookmotel** [comment]
@sushantdhiman Hold off a sec! Please see my comment here https://github.com/sequelize/sequelize/issues/5898#issuecomment-221346901 about coroutines not working with CLS, which is a documented feature of Sequelize and I think needs to be retained.

I've raided an issue #6116 about preparing for coroutines. But in my opinion, we're not ready to go for it with coroutines until the problems have been ironed out. I feel that ensuring CLS support is 100% is really important because it's used for running queries in the right transactions - so a bug threatens to undermine consistency, which I think is a pretty big deal.

This is really annoying, as coroutines are going to be a massive boost - personally I can't wait until the Sequelize codebase uses them as it'll make the code much more readable - but I feel we should hold off for now.

I'm on the case to try to fix the CLS/bluebird problems and write a full set of tests for it (see [here](https://github.com/overlookmotel/cls-bluebird-test)). And I'll sort it as soon as I can.

Of course my word isn't final! I'm just a contributor like you. But I do feel this is really important.

Please give your opinion on #6116.

**Comment by sushantdhiman** [comment]
@overlookmotel It didn't make sense that test should not use coroutine because `lib` don't use them. This mean no one is able to use coroutine in production because of may be broken support of CLS. Because test are just calling the library API surface.

If there is any issue with transaction related support we can hold for that part.

Regardless I have deferred working on ES6 conversion for now as there are more pressing issues to solve.

**Pull request closed without merging**
