### PR TITLE
fix OptimistickLockError message

### PR DESCRIPTION
**Pull request by PavelPolyakov**
`BaseError` expects to receive `message`, but the `options` object is being passed. 

It leads to this:
```
SequelizeOptimisticLockError: [object Object]
```

With the fix the error looks like:
```
SequelizeOptimisticLockError: Attempting to update a stale model instance: Customers
```

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by sushantdhiman** [comment]
This PR needs some tests, you can add new describe section for `Optimistic locking` [here](https://github.com/sequelize/sequelize/blob/master/test/integration/error.test.js#L245) and get reference for sample tests from [here](https://github.com/sequelize/sequelize/blob/master/test/integration/model/optimistic_locking.test.js#L46), finally assert correct message is returned along with correct error type

**Comment by PavelPolyakov** [comment]
That's not what you expect when you use newly released inline edit button on `github` 😅 
But I'll have a look.

**Comment by PavelPolyakov** [comment]
@sushantdhiman with all respect, I don't think that integration test is necessary here. The change is very minor and it just does the thing which was originally meant by author.

So I've put additional unit test, just to be rock solid, that message it there and has correct format.

Regards,

**Comment by sushantdhiman** [comment]
@PavelPolyakov integration test is important here, I'll add that test myself soon

**Pull request merged**
