### PR TITLE
meta: Use crypto module instead of uuid

### PR DESCRIPTION
**Pull request by AlexHladin**
## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

This PR avoids using the uuid package and substitutes it with [crypto module](https://nodejs.org/docs/latest-v14.x/api/crypto.html) that is available in the Node.js package.
Suddenly the [dialect.ts](https://github.com/sequelize/sequelize/blob/main/src/utils/dialect.ts#L30) still uses uuid v1. This code blocks fully removing the uuid package from package.json.

### CODE REVIEW

**Comment by ephys** [comment]
I'm very pro using native solutions instead of libraries, unfortunately Sequelize 7 still needs to support Node 14 and `crypto.randomUUID` is only available starting with node 16.7.0.

We will be able to accept this PR in the major that is released after 30 Apr 2023

**Comment by AlexHladin** [comment]
> I'm very pro using native solutions instead of libraries, unfortunately Sequelize 7 still needs to support Node 14 and `crypto.randomUUID` is only available starting with node 16.7.0.
> 
> We will be able to accept this PR in the major that is released after 30 Apr 2023

@ephys `crypto.randomUUID` is available in Node 14. Take a look at [documentation](https://nodejs.org/docs/latest-v14.x/api/crypto.html#crypto_crypto_randomuuid_options)

**Comment by WikiRik** [comment]
Indeed added in Node 14.17.0 which is the lowest version we plan to support for v7 so this should be fine

**Comment by WikiRik** [comment]
It was indeed added in Node 14.17.0 which is the lowest version we support. If Node 16.0.0 has it as well we can use this

**Comment by ephys** [comment]
MDN lied to me 😱 very nice then!

**Review by ephys — APPROVED** [review]

**Pull request merged**
