### PR TITLE
ci: add other ts versions to ci

### PR DESCRIPTION
**Pull request by mmahalwy**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change
We are now on TS version 4.5! But our tests were only up to 4.1 😅 . This adds additional versions. My recommendation is to consider dropping version 3.9? 

### Todos

- [ ] 
- [ ] 
- [ ]

### CODE REVIEW

**Comment by WikiRik** [comment]
I'm not sure how TypeScript versions work with support, but DefinitelyTyped supports 3.8 and up so I think there's no need to drop 3.9 support. Unless there are features in 4.0 that we really want to use

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/docs/support-window.svg

**Comment by mmahalwy** [comment]
@WikiRik sounds good

**Review by sdepold — APPROVED** [review]

**Comment by sdepold** [comment]
> I'm not sure how TypeScript versions work with support, but DefinitelyTyped supports 3.8 and up so I think there's no need to drop 3.9 support. Unless there are features in 4.0 that we really want to use
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/docs/support-window.svg

Did this change drop any coverage?

**Comment by sdepold** [comment]
Ah never mind. I found the reference to your response

**Pull request merged**
