### PR TITLE
docs: fix a link in Model Basics page

### PR DESCRIPTION
**Pull request by nokazn**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This is a tiny change. Fix a link to `data-types.js` in [Data Types section of Model Basics page](https://sequelize.org/master/manual/model-basics.html#data-types).

### CODE REVIEW

**Review by nainkunal933 — COMMENTED** [review]
The current link is pointing to data types in lib and this commit changes it to src.

**Review by nainkunal933 — APPROVED** [review]

**Comment by nainkunal933** [comment]
@nokazn Thank you for fixing the link

**Comment by nainkunal933** [comment]
@papb This is good to be merged

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

It turns out we decided to halt the typescript refactor for now, so the code in the `main` branch (former `master` branch) is back into the `lib` folder, so this change is no longer necessary. Thank you though!

**Pull request closed without merging**
