### PR TITLE
My tests failed with docker before I did not include mocha and jshint installations globaly.

### PR DESCRIPTION
**Pull request by gintsgints**
### Description of change

My tests failed with docker before I did not include mocha and jshint installations globaly.

### CODE REVIEW

**Comment by janmeier** [comment]
Hmm, weird - All commands in the package.json file use `node_modules/.bin/` to reference the files - Which specific command was failing?

**Comment by gintsgints** [comment]
```
> sequelize@4.0.0-1 jshint /sequelize
> jshint lib test

sh: 1: jshint: not found

npm info lifecycle sequelize@4.0.0-1~jshint: Failed to exec jshint script
npm ERR! Linux 4.2.0-30-generic
npm
```

**Comment by janmeier** [comment]
Try `npm run jshint` :)

**Comment by gintsgints** [comment]
Hmm but that's what docker does

**Comment by gintsgints** [comment]
May be error is here? 

sequelize/docker-compose.yml:
```
   JSHINT: /node_modules/.bin/jshint
   MOCHA: /node_modules/.bin/mocha
```

**Comment by gintsgints** [comment]
Ok... I see now where problem lies. You have to npm install localy, before doing docker tests.

But then I do not see any reason for rows in Dockerfile:
```
COPY package.json /
RUN npm install
```

**Comment by gintsgints** [comment]
IMHO before any tests docker inside should do npm install it'self. That way you have clean test inside docker.

**Pull request closed without merging**
