### PR TITLE
Added beta ribbon to docs

### PR DESCRIPTION
**Pull request by robdvr**
_Thanks for wanting to fix something on Sequelize - we already love you long time! Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_If your PR only contains changes to documentation, you may skip the template below._
### Pull Request check-list

_Please make sure to review and check all of these items:_
- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Have you added an entry under `Future` in the changelog?

_NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open._
### Description of change

Added beta ribbon to docs
screen shot 2016-10-19 at 11 06 56 am

### CODE REVIEW

**Comment by felixfbecker** [comment]
There is no beta version of Sequelize out and v4 will have docs hosted on doclets, what is the reason for this PR?

**Comment by robdvr** [comment]
I talked to Felix about this on slack. It's particularly easy to land on latest docs especially if you come from a google search. This PR makes it hard to miss that you are reading beta docs.

**Comment by robdvr** [comment]
Here's an example
screen shot 2016-10-19 at 11 16 13 am

**Comment by janmeier** [comment]
Yeah ... I disabled the builds on readthedocs for `latest`, but unfortunately there is no way to remove the current builds, or prevent them from showing up in google searches.

For the final v4 release I guess it would be best if we keep both v3 and v4 on doclets to avoid confusion - So at some point I probably need to go through and clean up the API docs for v3 as well so they compile and look nice for doclets.

I think a beta ribbon is a good solution for now, since we can't really remove `latest`

**Comment by felixfbecker** [comment]
I just think Beta already implies some stability. We are Alpha at best

**Comment by janmeier** [comment]
Alpha (or mayhaps unstable) would be fine by me as well - As long as we can show users in some way that they are not viewing the stable version.

**Comment by sushantdhiman** [comment]
`Beta / Alpha` Looks like Sequelize doesn't have any stable release at all, can we add some text in ribbon to address this issue ?

**Comment by robdvr** [comment]
@janmeier @felixfbecker Do you want me to update the ribbon to say "alpha" then?

**Pull request closed without merging**
