### PR TITLE
fix(postgres): adds support for minifying through join aliases

### PR DESCRIPTION
**Pull request by JamieREvans**
## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

A fix was added to support minification of aliases to avoid character limits for PostgreSQL queries, but it did not account for through joins. I've abstracted the aliasing function and used it in both join generator functions.

## Todos

- [ ] Add new tests (need to know where to look)

### CODE REVIEW

**Comment by WikiRik** [comment]
Thanks for opening this PR! Can you replicate this PR for the `main` branch as well? We prefer to first merge new PRs into main before backporting to V6 so we don't lose the functionality in v7

**Comment by JamieREvans** [comment]
@WikiRik Sorry for the delay. This issue is resolved in v7 already, so this is specifically a v6 bug that I'm looking to solve. This code is largely refactored (both methods are merged together if I'm remembering correctly). Are you still looking for something to be done for v7?

**Comment by WikiRik** [comment]
Ah, I didn't know this was resolved in v7. If there is a missing test that makes sense for v7 you might open a PR for that, but for now this is fine

**Comment by JamieREvans** [comment]
@WikiRik is there anything you'd like me to add here or is this PR likely to get merged down? Having to manually build Sequelize makes our CI/CD significantly slower and requires extra dependencies (e.g. `python`).

**Review by WikiRik — APPROVED** [review]
I'd prefer that we add a test for this, but since it's not an issue on v7 and I do not see harm in this change I think it's fine this way

**Pull request merged**
