### PR TITLE
fix: multiple $ in `fn` args now properly escaped

### PR DESCRIPTION
**Pull request by claytoneast**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [x] Have you added new tests to prevent regressions?
- [x] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change
Fixes improper escaping of multiple dollar signs in strings sent to `sequelize.fn` as detailed in https://github.com/sequelize/sequelize/issues/14601. Also removes some trailing whitespace, since my editor did it automatically 🤷

### CODE REVIEW

**Comment by claytoneast** [comment]
Joke's on me, I got failing tests left and right. I'll see if I can get those fixed...

**Comment by WikiRik** [comment]
You can ignore the failing postgres test for the `special_schema` since that's a flaky test

**Comment by WikiRik** [comment]
Yes, the remaining failing test is indeed flaky. We'll review this PR soon

**Review by ephys — COMMENTED** [review]
This looks good to me, however I don't think it's necessary to add the integration tests, since everything is already covered by unit tests

**Review by ephys — APPROVED** [review]

**Comment by claytoneast** [comment]
Thanks @ephys !!! Any idea when the next release for v6 might take place? (aka when we can expect to use this without a fork haha)

**Pull request merged**
