### PR TITLE
build: remove v6 docs from repository

### PR DESCRIPTION
**Pull request by ephys**
Sister PR of https://github.com/sequelize/sequelize/pull/13914, the main description is in that PR.

The documentation for Sequelize v6 has been migrated to docusaurus, which resides in a repository dedicated to documentation.
This PR removes the documentation from this repository.

The new docs are here: https://github.com/sequelize/website/

`esdoc` is still built here for the API Reference, but doesn't include any guide anymore.

### CODE REVIEW

**Review by npereira-jc — DISMISSED** [review]

**Comment by ephys** [comment]
The new website is [very close to being ready](https://github.com/sequelize/website/issues/10), I think we can merge this PR and redirect all documentation changes PRs to the new repository.

**Comment by WikiRik** [comment]
We don't need to update parts of CI for this?

**Comment by ephys** [comment]
Yes, I'll update the target repo

**Comment by ephys** [comment]
pinging @sdepold to make sure the CI is correct :)

**Comment by sdepold** [comment]
> pinging @sdepold to make sure the CI is correct :)

Looks perfect 👌

**Review by sdepold — APPROVED** [review]

**Review by sdepold — APPROVED** [review]

**Pull request merged**
