### PR TITLE
meta: persist lockfile

### PR DESCRIPTION
**Pull request by Keimeno**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Persists a yarn lock-file. 
This allows us to create releases that are more transparent about the dependencies that were installed. It also reduces the risks we could get from dependencies with breaking changes.

### CODE REVIEW

**Comment by WikiRik** [comment]
Why move to yarn for this? npm also supports a lock file, but it was removed in https://github.com/sequelize/sequelize/commit/22d35953da85869cf742d223cd49498c99027d0c

**Comment by sdepold** [comment]
Because it's much faster I guess. Don't we have to ignore the file somehow when building the npm package?

**Comment by sdepold** [comment]
Or do we plan to ship the lockfile?

**Comment by Keimeno** [comment]
I don't think there's much of a reason to ship the file as well.

Also, yarn has resolutions, which allows us to easily overwrite sub-dependency versions

**Review by sdepold — APPROVED** [review]

**Pull request merged**
