### PR TITLE
Expose beforeUpsert/afterUpsert hooks

### PR DESCRIPTION
**Pull request by arsonik**
### Description of change

Allow Typescript users to use beforeUpsert and afterUpsert in their model hooks !

### CODE REVIEW

**Comment by brenwell** [comment]
I will be looking forward to this, thanks

**Comment by arsonik** [comment]
UP ?

**Comment by Keimeno** [comment]
@papb

**Comment by arsonik** [comment]
fixed I believe

**Comment by arsonik** [comment]
nope was fixed for before/after upsert
still missing 
```
        query<M extends Model>(sql: string | { query: string; values: unknown[] }, options: QueryOptionsWithModel<M> & { plain: true }): Promise<M | null>;```

**Comment by ephys** [comment]
Sorry for taking so long to review this.

I'm going around old TS PRs to merge them.

The plain query typing was fixed in https://github.com/sequelize/sequelize/pull/13899
@arsonik can you resolve the conflict?

Can you also add a test in `types/test` to prevent regressions? 
Simply call those methods with the right signature.

**Comment by papb** [comment]
Hi @arsonik, why did you close the PR?

**Comment by arsonik** [comment]
> Hi @arsonik, why did you close the PR?

Because a more recent PR that fixes the issue was merged 

https://github.com/sequelize/sequelize/pull/13899

**Comment by ephys** [comment]
Oh I didn't notice you closed this PR. It's still interesting for the `afterUpsert`/`beforeUpsert` part :)

**Comment by arsonik** [comment]
because that PR was merged 
https://github.com/sequelize/sequelize/pull/13394

**Comment by ephys** [comment]
Aaah! Thanks :)

**Pull request closed without merging**
