### PR TITLE
(WIP) feat(sqlite): array type

### PR DESCRIPTION
**Pull request by jaulz**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This PR will introduce an array type for SQLite which will be imitated by a JSON type.
You can find the previous issue here: https://github.com/sequelize/sequelize/issues/9209

### CODE REVIEW

**Comment by jaulz** [comment]
@papb I have some issues with the new Data Type which I defined here: https://github.com/sequelize/sequelize/blob/12c844029ab0314e556656c5b5014657da6e40a0/lib/dialects/sqlite/data-types.js#L188-L219

Unfortunately, it's not taken into account in the tests and only the standard array data type is used here:
https://github.com/sequelize/sequelize/blob/12c844029ab0314e556656c5b5014657da6e40a0/test/unit/sql/json.test.js#L58-L65

Do you know where the default data types are merged with the dialect specific data types so I can track down why the new data type is not used?

**Comment by papb** [comment]
@jaulz Sorry, I don't know. I tried to take a cursory look but didn't find it... I suggest you run your code in debug mode and put some breakpoints in your dialect specific datatype to help figuring this out. Good luck. Let me know if you get stuck.

**Comment by jaulz** [comment]
@papb hm, yes, this is what I tried for quite some time... thanks anyway.

**Comment by sushantdhiman** [comment]
Sorry I am going to close this PR for now, let's implement ARRAY type when SQLite can actually support this. As a workaround you can keep array data in JSON column

**Pull request closed without merging**
