### PR TITLE
Introduce `environment` configuration option. When `environment` set to `production`, prevent .sync({ force: true }) operation

### PR DESCRIPTION
**Pull request by hippich**
Related to https://github.com/sequelize/sequelize/issues/2670

### CODE REVIEW

**Comment by mickhansen** [comment]
For reference there's also the match: regex option like `{force: true, match: /_test$/}`

**Comment by mickhansen** [comment]
This will kill support for actually running sync on production, which i often do when deploying a service for the very first time, so we need a override switch.

**Comment by hippich** [comment]
So what you are saying that `match` should be used to prevent accidental sync({ force: true }) on production environment? If so - I guess I should update documentation then.

**Comment by hippich** [comment]
Here is PR with documentation update for `match` option - https://github.com/sequelize/sequelize/pull/3457

**Comment by mickhansen** [comment]
@hippich No, i was just remarking that that's an option for test suites aswell.

**Comment by hippich** [comment]
`match` seems like works just fine in my case, so I guess there is no need for my `environment` changes. It can be resurrected in case there is valid reason to have one in future.

Thank you!

**Pull request closed without merging**
