### PR TITLE
$in and $notIn support literals.

### PR DESCRIPTION
**Pull request by braddunbar**
```js
Model.findAll({
  where: {attr: {$in: sequelize.literal('…')}}
}).then(…);
```

### CODE REVIEW

**Comment by mickhansen** [comment]
What's the usecase here @braddunbar?

**Comment by braddunbar** [comment]
I need to do something like the following, but if there's a better way I'm quite open to it! :smile:

```js
Order.findAll({
  where: {
    status: 'open',
    id: {$in: sequelize.literal(
      '(select order_id from product_orders where product_id = ' + sequelize.escape(product_id) + ' )'
    )}
  },
  include: [{as: 'user', model: User}]
).then(function () { … })
```

**Comment by mickhansen** [comment]
@braddunbar Ah no that makes sense, could you update the unit tests to reflect something like that? Better to have closer-to-real-world tests than contrived ones :)

**Comment by braddunbar** [comment]
Happy to! Updated in 115600f.

**Comment by braddunbar** [comment]
Thanks for this! Been waiting to use it. :smiley_cat:

**Pull request merged**
