### PR TITLE
SEMVER: Fix findOrCreate logic. Closes #2970 and #2684

### LINKED ISSUE #2970: [BUG]findOrCreate will not work properly while using complex where clause
pieces of code below:

``` js
return SyncQueue.findOrCreate({
    where: {
        'UserId': self.userId,
        'status': { ne: 2 }
    },
    defaults: defaults
}).spread(function ($tmp, created) { $gQueue = $tmp; });
```

When these is no records match the searching, Sequelize is willing to insert an new record, but, it generate an wrong SQL below:

``` sql
INSERT INTO `zx_sync_queue` (`id`,`status`,`createdAt`,`updatedAt`,`UserId`) VALUES (DEFAULT,`ne` = 2,\'2015-01-20 09:06:39\',\'2015-01-20 09:06:39\',1);
```

so, an exception throws:

``` sql
SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'ne' in 'field list'
```

if i set the **defaults** options to be `{'status': 0}` to override the attribute in **where**, it will be ok.

### PR DESCRIPTION
**Pull request by BridgeAR**
Here's a BC: If defaults is set, it will only use the defaults object from now on. This is necessary to be sure what the user actually wants. Otherwise there will always be some problems by combining complex where with the defaults.

Only one test is breaking by this change. Other than that one issue is fixed and from now on it's possible to use complex where statements.

I also inserted a update lock as a default.

### CODE REVIEW

**Comment by mickhansen** [comment]
`where` should only be ignored if it's a complex object, it should not be ignored otherwise, making it only use defaults defeats most of the usability.

**Comment by BridgeAR** [comment]
How can you tell if it's a  complex object? It's somehow random for a user if it works once with writing something like:

**Comment by mickhansen** [comment]
It's bad in the way that it completely destroys the usability for a ton of cases.
I'd wager that people don't use complex arguments dynamically for findOrCreate.

**Comment by BridgeAR** [comment]
Well, what's so bad about writing
```js
User.findOrCreate({
  where: {
    email: email
  },
  defaults: {
    email: email,
    createdAt: new Date()
  }
});
```
That's way more intuitive and less error prone. I know this is a semver major change. But it's something where everyone can be sure that it works properly. Right now that's not possible and I can't think of a way to find a solution that won't have cases that will fail and might produce unintended behaviour.

**Comment by mickhansen** [comment]
> That's way more intuitive
I disagree. The most intuitive would be not to have `where/defaults` at all, but that disallow complex where's when that is absolutely needed.

I believe that the common case **by far** is a simple where, and that case is destroyed by this change.

**Comment by BridgeAR** [comment]
This fixes #3805 too (or at least makes it a lot easier to implement).

**Comment by mickhansen** [comment]
I don't see how this fixes #3805? We already support #3805.

**Comment by mickhansen** [comment]
Or hmm, we used to with `sequelize.or()` etc, it might have changed with the property comparisons.

**Comment by mickhansen** [comment]
@BridgeAR if you'd still like this in, i propose you introduce a `values` key that will ignore `where` completely.

**Pull request closed without merging**
