### PR TITLE
added @@ operator for postgres as "$matches" in query-generator 

### PR DESCRIPTION
**Pull request by wissebarkhof**
very simple addition of this operator to help me use postgres' full text search functionality

### CODE REVIEW

**Comment by mickhansen** [comment]
The diff contains 4000 changes, what did you do exactly?

**Comment by wissebarkhof** [comment]
Yeah I noticed that later too. I added in two lines of code in operatorMap, but somehow it shifted all the lines. Maybe my linting was off? I'll have another look tomorrow.

Date: Tue, 26 Jan 2016 02:10:18 -0800

**Comment by mickhansen** [comment]
Looks like your editor might have added a bunch of tabs to the entire file.

**Comment by janmeier** [comment]
@wissebarkhof Any updated on this?

**Pull request closed without merging**
