### PR TITLE
Add a `noImplicitTransactions` option

### PR DESCRIPTION
**Pull request by igrayson**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Have you added an entry under `Future` in the changelog?

### Description of change

This adds an *optional* assertion which permits applications to enforce
a declarative transaction style. Specifically, queries will no longer
open/create a connection ad-hoc, and instead throw a NoTransactionError.

This overcomes a chronic pain we have with inconsistent transaction management, and gives us an assertion that our application code will be explicit with when and where to open database transactions, and what parts of the application _should_ be aware of database transactions.

### CODE REVIEW

**Comment by igrayson** [comment]
Test failure looks unrelated to this change.

**Comment by igrayson** [comment]
Can someone take a look at this?

**Comment by felixfbecker** [comment]
so after enabling this option, even a find call will throw with a NoTransaction error? That seems a bit useless to me then because every GET route we have in our app would start to fail, there is no reason to run reads and also single writes in a transaction. Also not sure about the name -it implies that without this option, sequelize would use an implicit transaction for every query, which ia misleading - sequelize just sends the query to the DB

**Comment by igrayson** [comment]
This option will be more familiar to postgresql users, as postgresql _does_ implicitly place naked statements in their own transaction.

https://www.postgresql.org/docs/9.5/static/tutorial-transactions.html

> PostgreSQL actually treats every SQL statement as being executed within a transaction. If you do not issue a BEGIN command, then each individual statement has an implicit BEGIN and (if successful) COMMIT wrapped around it.

I have less experience with mysql and sqlite, but I understand both also have concepts of implicit transactions, which gives reason for users to prefer to avoid them.

**Comment by mickhansen** [comment]
This could be doable as a plugin instead.

**Comment by felixfbecker** [comment]
@igrayson what you are describing is called "auto commit mode" and exists in the other dialects too. There are actual options on the DB/SQL level to turn this on/off, but they will not result in an error, rather in a non-commited transaction. So I see point for confusion here.

Could you answer my other question about finds?

**Comment by sushantdhiman** [comment]
I agree with @mickhansen this can be done via plugin, we don't need to add this to sequelize code base

**Comment by igrayson** [comment]
Great. Can you point me towards the plugin interface that can be used to achieve this?

**Comment by sushantdhiman** [comment]
@igrayson We are still working on plugin system proposal #2508 , but you can see how others have implemented various plugins [Add-ons-&-Plugins](https://github.com/sequelize/sequelize/wiki/Add-ons-&-Plugins)

Please update the wiki once you have implemented `non implicit transaction` plugin so others in community can find it as well :)

**Pull request closed without merging**
