### PR TITLE
Update installation instructions to include MariaDB

### PR DESCRIPTION
**Pull request by knoxcard**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by knoxcard** [comment]
This just popped out 13 days ago, it's wayyyy more efficient than the mysql2 db connector, if one is using MariaDB.

https://github.com/MariaDB/mariadb-connector-nodejs

**Comment by sushantdhiman** [comment]
Looks really good, it doesn't look like they support prepared statements, do they? I only see placeholder replacements

**Comment by knoxcard** [comment]
hmmm, I can open an issue under their repo.  I am assuming this is an absolute must before integrating into Sequelize?  Are there other requirements as well?  That way I can just bundle all these requests up and submit one issue. :-)

**Comment by sushantdhiman** [comment]
We are going to need

1. typecast API (preferably for both query / execute)
2. prepared statements, it is not a must but all other dialects now support this and we are going to implement them everywhere if possible
3. `supportBigNumbers` / `bigNumberStrings` like api

**Comment by sushantdhiman** [comment]
Hmm I also see `Node.js 7.6+` is required

**Comment by knoxcard** [comment]
https://github.com/MariaDB/mariadb-connector-nodejs/issues/3

**Comment by sushantdhiman** [comment]
Closing this PR as we can't include `mariadb` to install instructions unless we actually add new dialect which is able to work with this new client library. Tracking that progress [here](https://github.com/sequelize/sequelize/issues/9677)

**Pull request closed without merging**
