### PR TITLE
meta(deps): Update retry-as-promised to 5.0.0

### PR DESCRIPTION
**Pull request by akre54**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Earlier versions of retry-as-promised rely on the package any-promise which depends on a global `window` object. This change makes Sequelize a bit easier to use on node environments, especially with server side rendering like next.js

### CODE REVIEW

**Review by WikiRik — APPROVED** [review]

**Comment by depoulo** [comment]
Looking at the diff, I wonder whether you guys really didn't have to change anything regarding this breaking change: https://github.com/mickhansen/retry-as-promised/pull/26

**Comment by depoulo** [comment]
Hm I see https://github.com/sequelize/sequelize/issues/13494

**Comment by WikiRik** [comment]
That breaking change is retry-as-promised v3 to v4. This PR is about v4 to v5; https://github.com/mickhansen/retry-as-promised/compare/v4.0.0...v5.0.0 so we didn't have to change anything

**Comment by depoulo** [comment]
Yeah sorry I meant 3 to 4.

**Comment by depoulo** [comment]
Anyway, I don't see a related change in #13729 but I guess that's ok.

**Pull request merged**
