### PR TITLE
Support include.separate for belongsToMany

### LINKED ISSUE #4376: Support separate:true for belongsToMany association types

### PR DESCRIPTION
**Pull request by PlasmaPower**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
  - Tested locally with postgresql, a couple GEOMETRY tests failed but I think that's an issue with my version of postgresql not this PR. We'll see if it works on Travis.
  - Eslint has a problem with the indentation in `test/unit/sql/select.test.js`, but that's unrelated to this PR as I didn't change that file.
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
  - Separate is not currently documented, so I can't modify the documentation. I might document separate in a separate PR (pardon the pun).
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?
  - I'm not quite sure how to categorize this, so tell me if I should change the commit message.

### Description of change

Fixes #4376, redo of #4525 (most of the changes were manually applied). There's probably more to do, but I'm creating this PR as a starting point.

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
@PlasmaPower any updates?

**Comment by PlasmaPower** [comment]
@DaAwesomeP Oops, totally forgot about this. I'll rebase and go from there, but I wouldn't get your hopes up.

**Comment by DaAwesomeP** [comment]
@PlasmaPower what more needs to be done besides at tests? Is what you have committed so far functional or did you just make it allow for hasMany and belongsToMany?

**Comment by PlasmaPower** [comment]
@DaAwesomeP I'm not entirely sure. There seems to be an issue with foreign constraints, but I'm not sure if it's a testing issue or an issue with the code itself.

**Comment by foisonocean** [comment]
Any updates ?

**Pull request closed without merging**
