### PR TITLE
fix(scopes): overwrite order correctly when merging scopes

### LINKED ISSUE #11415: Incorrect ordering for a findAll operation on a scoped model with predefined order
### What are you doing?

I have a Model `TheModel` with a scope `scoped` containing `order` , say `order1`.
On invoking a findAll with an `order`, say `order2`, the resulting order is `order1`, `order2`

```
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
TheModel.addScope('scoped', {
  order: [
    [associatedModel1, 'foo', 'ASC'],
    [associatedModel2, 'bar', 'ASC'],
  ]
});

scopedModel.findAll({
  order: [
    ['field1', 'ASC'],
    [associatedModel1, 'foo', 'ASC'],
  ]
});
```

### What do you expect to happen?

Resulting order: `field1` `ASC`, `associatedModel1`.`foo` `ASC`
(This was the actual order using sequelize version 3.30.4)

### What is actually happening?

Resulting order: `associatedModel1`.`foo` `ASC`, `associatedModel2`.`bar` `ASC`, `field1` `ASC`, `associatedModel1`.`foo` `ASC`

### Environment

- Sequelize version: 5.15.2
- Node.js version: 6.13.4
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

Note: I was able to come to this [line](https://github.com/sequelize/sequelize/blob/d5e4a10f4e8dc1e37fe46678f04bbfa66b1299cc/lib/model.js#L798) which is merging the two orders. However, I think the community needs to collectively decide what should be the expected behaviour. I think that the order provided by `findAll` should always override the scope order.

### PR DESCRIPTION
**Pull request by hugekoala**
- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md]

Fixes #11415 - scopes merge issue - changed merge to srcValue, and added support for include and where.

### CODE REVIEW

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future! :grimacing:

As you can see, our automatic tests failed:

image

This is because of a [linting error](https://travis-ci.org/sequelize/sequelize/jobs/585286183#L501).

Also, please add at least one test to make sure your implementation works as intented and to prevent regressions in the future. Take a look into recent merged PRs to see how others created tests. If you have trouble, let me know. I suggest you use the code in [the first post of the issue](https://github.com/sequelize/sequelize/issues/11415#issue-491699128) for the test.

**Comment by papb** [comment]
Also, I will take the liberty of editing your first post and PR title, I hope you don't mind.

**Comment by hugekoala** [comment]
Thank you very much for the support @papb,

So first - fixed the linting problem, and now trying to understand if there is an easy option to debug the tests besides running it locally.

Secondly, some tests related to the scopes(obviously) are failing, and I need some guidance on how to debug them.

Thanks

**Comment by papb** [comment]
Hello!

> an easy option to debug the tests besides running it locally.

I would recommend just running it locally. I suggest using SQLite since it is much easier to setup, and place breakpoints around the code.

> some tests related to the scopes(obviously) are failing, and I need some guidance on how to debug them.

I noticed that you changed the order of the `_.union` call (from `_.union(objValue, srcValue)` to `_.union(srcValue, objValue)`. Perhaps this caused a problem?

**Comment by madmonl** [comment]
Hi, back again from my main user,
Sorry for the confusion.
So - can I have more details on what and how to config for sqlite?
Installed it and CONRTIBUTING.MD didn't really help me figure out how to proceed in casse of sqlite.

**Comment by papb** [comment]
Hello! I will work on improving the contributing guidelines in the near future. For now:

There is a https://github.com/sequelize/sequelize/blob/master/sscce_template.js template in main repo.
* Clone the sequelize repository locally
* Copy sscce_template.js to new file sscce.js
* Add your code to that file
* npm run sscce-sqlite

Let me know if you need further help

**Comment by madmonl** [comment]
I managed to make tests run locally, by just running - 'npm run test-sqlite', and it made me wonder - what did you mean by 'Add your code to this file'? 
What should be the content of sscce.js?

**Comment by papb** [comment]
@madmonl Using sscce.js was a suggestion to help you run an SSCCE locally. But looks like existing tests are already failing, so if you just want to investigate them you can ignore what I said about the sscce.js. Let me know if you need more help :)

**Comment by papb** [comment]
@hugekoala @madmonl Are you still pursuing this?

By the way, we now have a dedicated repository for writing SSCCEs: [sequelize-sscce](https://github.com/papb/sequelize-sscce).

**Comment by WikiRik** [comment]
Closing this since it is still against `master`. Can be reopened if that changes.

**Pull request closed without merging**
