### PR TITLE
fix(abstract/querygenerator): remove duplicated order expression on outer query

### PR DESCRIPTION
**Pull request by Alexsey**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

There is a bug https://github.com/sequelize/sequelize/issues/8275 and it may be fixed by just removing part of SQL statement that looks like redundant (at list for me)

The point of change is that now `order` statement is applying to both main query and sub query. It looks like there is no need for second `order`ing. Also this would also fix a mentioned bug

### CODE REVIEW

**Comment by Alexsey** [comment]
Tests have pass ok but I think some one else should also think about is this part is really redundant. It so - I don't think there should any tests be added as far as it doesn't change the behavior. Just remove stuff that didn't work well

**Comment by Alexsey** [comment]
Keep in mind that it could have potential conflicts with deep includes with right or outer joins. As far as I can see Sequelize is not using them for now. But if it would - ordering of the main query will get some sense:
```sql
SELECT ...
FROM (... ORDER BY number) as A
RIGHT JOIN B ON ...
```
would return a result that is ordered by `A.number` mixed with `NULL`

**Comment by yonjah** [comment]
I've just noticed this change actually fails the tests when run on  my local instance with MariaDB (10.1.21).

The findCount at https://github.com/sequelize/sequelize/blob/master/test/integration/associations/belongs-to.test.js#L888 generates a query that does not actually follow the order -

```sql
SELECT `entry`.*, `mail->recipients`.`id` AS `mail.recipients.id`, `mail->recipients->MailRecipients`.`mailId` AS `mail.recipients.MailRecipients.mailId`, `mail->recipients->MailRecipients`.`recipientId` AS `mail.recipients.MailRecipients.recipientId` FROM (SELECT `entry`.`id`, `entry`.`ownerId`, `entry`.`mailId`, `mail`.`id` AS `mail.id` FROM `entries` AS `entry` INNER JOIN `mails` AS `mail` ON `entry`.`mailId` = `mail`.`id` WHERE ( SELECT `mail`.`id` FROM `mails` AS `mail` INNER JOIN ( `MailRecipients` AS `recipients->MailRecipients` INNER JOIN `users` AS `recipients` ON `recipients`.`id` = `recipients->MailRecipients`.`recipientId` AND `recipients->MailRecipients`.`recipientId` = 1) ON `mail`.`id` = `recipients->MailRecipients`.`mailId` WHERE `entry`.`mailId` = `mail`.`id` LIMIT 1 ) IS NOT NULL ORDER BY `entry`.`id` DESC LIMIT 0, 10) AS `entry` INNER JOIN ( `MailRecipients` AS `mail->recipients->MailRecipients` INNER JOIN `users` AS `mail->recipients` ON `mail->recipients`.`id` = `mail->recipients->MailRecipients`.`recipientId` AND `mail->recipients->MailRecipients`.`recipientId` = 1) ON `mail.id` = `mail->recipients->MailRecipients`.`mailId`;
```

**Comment by sushantdhiman** [comment]
Many users are complaining that this fix broke their queries. I am reverting it for now

**Comment by keyiis** [comment]
@sushantdhiman same issues in 4.13.6

**Comment by Djalmar** [comment]
same issue in 4.41.0

**Pull request merged**
