### PR TITLE
feat: support TypeScript 5.4, drop TypeScript 5.0

### LINKED ISSUE #17165: Incompatible with typescript 5.4
## Issue Creation Checklist

- [X] I understand that my issue will be automatically closed if I don't fill in the requested information
- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What do you expect to happen?

A project with latest typescript version should build successfully.

### What is actually happening?

I'm using the latest v7 alpha version. After updating to typescript `5.4.2` i can't build the project anymore. The problems are 9 errors like:

**Excessive stack depth comparing types 'PickRestType<ArrayTail<ArrayTail<Destination>>>[number]' and 'UnknownArrayOrTuple'.**

```ts
> = [
~
141  ...DoMergeDeepTupleAndTupleRecursive<OmitRestType<Destination>, OmitRestType<Source>, PickRestTypeFlat<Destination>, PickRestTypeFlat<Source>, Options>,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
142  ...MergeDeepArrayOrTupleElements<PickRestType<Destination>, PickRestType<Source>, Options>,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
];

```

### Environment

- Sequelize version: 7.0.0-alpha.37
- Node.js version: 20.9.0
- If TypeScript related: TypeScript version: 5.4.2

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

_Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed._

### PR DESCRIPTION
**Pull request by ephys**
Replacement PR for #17150

Closes #17165

This PR:

- Drops support for TypeScript 5.1
- Adds support for TypeScript 5.4
- Updates type-fest, which requires TS 5.1 as a minimum
- Removes legacy code kept for old TypeScript versions

TODO:

- [Document this PR in the website](https://github.com/orgs/sequelize/projects/5/views/1)

### CODE REVIEW

**Comment by WikiRik** [comment]
The description is off btw (4.5 and 4.1), but the title is correct (5.4 and 5.1)

**Comment by ephys** [comment]
Woops, fixed

**Review by WikiRik — APPROVED** [review]

**Comment by ephys** [comment]
I have no idea what is causing the windows issue, and I also have no idea how to debug it :(

**Comment by WikiRik** [comment]
I'll see what errors I get on my Windows PC

**Comment by WikiRik** [comment]
I get the same errors on my PC, but no clue why the types are generated this way. 

See for example what happens to data-types.d.ts;
```
/** This is a simple wrapper to make the DataType constructable without `new`. See the return type for all available options. */
export declare const GEOMETRY: typeof DataTypes.GEOMETRY & ((...args: [type: import("src/geo-json.js").GeoJsonType, srid?: number] | [options: DataTypes.GeometryOptions]) => DataTypes.GEOMETRY);
/** This is a simple wrapper to make the DataType constructable without `new`. See the return type for all available options. */
export declare const GEOGRAPHY: typeof DataTypes.GEOGRAPHY & ((...args: [type: import("src/geo-json.js").GeoJsonType, srid?: number] | [options: DataTypes.GeometryOptions]) => DataTypes.GEOGRAPHY);
```

When I use TypeScript 5.3.3 everything is fine, even with the updated typefest. So it is connected to that. Didn't have time to look through TS 5.4 release notes to see if they mention anything that could influence this

Just to make the picture complete, this is what is being compiled for data-types.d.ts on TS 5.3;
```
/** This is a simple wrapper to make the DataType constructable without `new`. See the return type for all available options. */
export declare const GEOMETRY: typeof DataTypes.GEOMETRY & ((...args: [type: import("./geo-json.js").GeoJsonType, srid?: number] | [options: DataTypes.GeometryOptions]) => DataTypes.GEOMETRY);
/** This is a simple wrapper to make the DataType constructable without `new`. See the return type for all available options. */
export declare const GEOGRAPHY: typeof DataTypes.GEOGRAPHY & ((...args: [type: import("./geo-json.js").GeoJsonType, srid?: number] | [options: DataTypes.GeometryOptions]) => DataTypes.GEOGRAPHY);
```

**Comment by ephys** [comment]
The second example is also what is generated on linux

**Comment by WikiRik** [comment]
> Maybe one of the options such as `root` is incorrectly configured? That's the only thing I would expect to behave differently on both OSes

Maybe, although it does work fine in most cases. Might just be an edge case that we'll need to look into further

**Comment by lohart13** [comment]
I've had a bit on a play on windows and it appears that the `baseUrl` in the tsconfig might be causing the issues.
After removing the `baseUrl` in each of the tsconfig's, the workspaces compile successfully.

Looking at the [docs](https://www.typescriptlang.org/tsconfig#baseUrl), this could be removed as per the below.
> This feature was designed for use in conjunction with AMD module loaders in the browser, and is not recommended in any other context. As of TypeScript 4.1, baseUrl is no longer required to be set when using [paths](https://www.typescriptlang.org/tsconfig#paths).

**Review by WikiRik — APPROVED** [review]
@lohart13 Thanks for figuring out the issue with Windows!

**Comment by WikiRik** [comment]
@ephys can you try to approve this, otherwise we'll need to change a GitHub setting. It tells me that the new changes require approval from someone other than me because I was the last pusher.

**Comment by ephys** [comment]
Thank you @lohart13!

I can't approve it as I'm the PR author but you can give admins protection bypass privilege temporarily

**Pull request merged**
