### PR TITLE
io.js has been merged into node.js so it doesn't need to be mentioned separately anymore

### PR DESCRIPTION
**Pull request by curiousdannii**
Also alter the Travis config: switch from io.js v1,2 to node.js v4.2 (LTS) and 'node' (currently v5)

### CODE REVIEW

**Comment by curiousdannii** [comment]
Travis doesn't seem to want to play nicely with node-gyp... I've never used it though so I have no idea what would be involved to fix it, but it really should be testing node 4.2 and 5 now.

**Comment by mickhansen** [comment]
node-pg does not currently support 4.x - believe it has something to do with an nvm bug.
there's an existing PR here on GH about 4.0 support, theres some relevant links

**Comment by curiousdannii** [comment]
The `pg` package? I have no trouble installing that on both 4.2 and 5, but that's just straight installing, not recompiling with node-gyp.

**Comment by mickhansen** [comment]
@curiousdannii pg with pg-native

**Pull request closed without merging**
