### PR TITLE
feat(postgres): minify include aliases over limit

### PR DESCRIPTION
**Pull request by mrrinot**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Have you added new tests to prevent regressions?
- [X] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Proposal to make the `minifyAliases` option also alias includes that go over the 63 POSTGRES character limit.

Closes https://github.com/sequelize/sequelize/issues/11937

### CODE REVIEW

**Comment by mrrinot** [comment]
Can't see the Codecov details, someone might be able to help me

**Comment by Nick-Riggs** [comment]
👍 Looking forward to having this merged. Since creating the issue, I've found a few more cases where our project is suffering from the length limit in the FROM clause. And it's becoming an issue having to put in hacks to get around the problem. Any chance this will be merged soon? What are the next steps?

**Comment by mrrinot** [comment]
I am waiting for a review and then hoping the tests pass

**Comment by Nick-Riggs** [comment]
I'm happy to see this merged. This will remove a lot of hackery from our codebase. Thanks for your work on it @mrrinot. 

Question: will this merge be included in a v5 release? Or just a future v6 release?

**Pull request merged**
