### PR TITLE
feat: rewrite the part of QueryGenerator responsible for `WHERE`

### PR DESCRIPTION
**Pull request by ephys**
Large WIP PR to completely rewrite how `WHERE` is generated.

This PR is dependent on https://github.com/sequelize/sequelize/pull/14022, as unit tests & types must be improved first to ensure this PR doesn't break anything.

It's definitely not ready yet. A lot of tests are still failing.

The bulk of changes are in https://github.com/sequelize/sequelize/blob/ephys/new-where-builder/lib/dialects/abstract/where-sql-builder.ts

The new system is much more type-safe, with each operator being typed individually.

With this new system, it's also easier for dialects to override how an operator is built. They can override the method specific to that operator without needing to modify the other.

Closes https://github.com/sequelize/sequelize/issues/13602
Closes https://github.com/sequelize/sequelize/issues/13753

Goals of this PR:

- Migrate the implementation of `where` to TypeScript
- Remove all differences between the implementations of `Sequelize.where()` and pojo where objects (i.e. `where: { firstName: 'zoé' }`). Fixes https://github.com/sequelize/sequelize/issues/13602
- Remove behavior differences between `{ attribute: value }` and `{ attribute: { [Op.eq]: value } }`
- Prepare the groundwork for a follow-up PR that implements [`Sequelize.attr`](https://github.com/sequelize/sequelize/issues/13773) as a attributeName-aware alternative to `Sequelize.col`
- Prepare the groundwork for a follow-up PR that implements bind parameters in `Sequelize.literal` (eg. `Sequelize.literal('name = ?name', { name: 'my name' })`)
- Accept all iterables in operators that do not explicitely need an array (eg. `{ attribute: { [Op.in]: new Set([1,2,3]) } }`)
- Be more strict: An invalid `where` object should throw with a message describing what is invalid, instead of crashing with an obscure message.
- Support using `or` inside another operator: `{ id: { [Op.eq]: or(1, 2) } }` should function

TODO

- Investigate supporting any value on both sides of `where`: `Sequelize.where([], Op.eq, [])`
- Ensure all queries in `types/where.ts` are actually tested
- Ensure `Op.any` and `Op.all` are supported in all/most operators
- Check if https://github.com/sequelize/sequelize/issues/14114 is fixed
- Support `literal` in `Op.match`: https://github.com/sequelize/sequelize/issues/14051
- fix https://github.com/sequelize/sequelize/discussions/15290#discussioncomment-4163339

### CODE REVIEW

**Comment by ephys** [comment]
If there are other open issues related to `WHERE` being incorrectly generated, don't hesitate to post them here so I can include them in the new implementation

**Comment by WikiRik** [comment]
Looking at the goals of this PR I don't really see any breaking changes. Is that correct? Since I do not think we'll land this in the initial release of v7 but postponing it to v8 would also be a waste

**Comment by ephys** [comment]
There is one breaking change: Writing the following is no longer supported

```ts
import { where } from '@sequelize/core';

User.findAll({
  where: where(col("a"), '=', col("b"))
})
```

instead users need to write the following:

```ts
import { where } from '@sequelize/core';

User.findAll({
  where: where(col("a"), Op.eq, col("b"))
});
```

This is because `where` needs to know which operator is used to build the query properly. The left and right operands are not always serialized in exactly the same way, depending on the operator.

If the user needs to write a raw query, they can do this instead:

```ts
import { sql } from '@sequelize/core';

User.findAll({
  where: sql`${col("a")} = ${col("b")}}`
});
```

Well... once I get to it https://github.com/sequelize/sequelize/issues/14299

**Comment by WikiRik** [comment]
No worries about working on it for v8, v7 already has some nice new and improved features that this can wait a bit. Thanks for the information!

**Comment by ephys** [comment]
Replaced by https://github.com/sequelize/sequelize/pull/15598

**Pull request closed without merging**
