### PR TITLE
fix: allow deep imports

### PR DESCRIPTION
**Pull request by ephys**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [x] Have you added new tests to prevent regressions?
- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [N/A] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [N/A] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Fixes https://github.com/sequelize/sequelize/issues/13787

The issue was that once `exports` is defined in package.json, node uses it as the source of truth for all valid exports of a package.

I've configured `exports` to replicate how the imports worked in v6.  
I also had to remove the alias in `registerEsbuild.js` as it was redundant with `exports`.  
It also matches reality better as the tests use the same export definition as the published build. :)

I recommend changing the export declaration for V7, see below

---

## Breaking changes recommendations for V7

In v7, we could change the export definition to

```json
{
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    },
    "./package.json": "./package.json",
    "./*": "./dist/lib/*.js"
  },
}
```

This way, instead of importing `sequelize/lib/model.js`, users could import `sequelize/model`.

If we still want users to specify `/lib` in v7, we can use this one instead

```json
{
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    },
    "./lib/*": "./dist/lib/*.js",
    "./package.json": "./package.json",
  },
}
```

**[recommended]** If we want to prevent users from importing `/lib` which could result in unexpected breaking changes, we could instead use this one which only allows importing `sequelize` & `sequelize/package.json`

```json
{
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    },
    "./package.json": "./package.json",
  },
}
```

### CODE REVIEW

**Comment by sdepold** [comment]
Completely agreed on the fact that people would better not import anything from the package other than the main entry point.

**Comment by ephys** [comment]
I'll PR v7 to completely forbid it once this is merged :)

**Comment by sdepold** [comment]
Thanks a bunch. I think I'll just release a new version straight away or was there anything else we need to fix?

**Comment by ephys** [comment]
@sdepold Yep!

**Pull request merged**
