### PR TITLE
Change regex

### PR DESCRIPTION
**Pull request by Tolsee**
https://github.com/sequelize/sequelize/issues/9838

### Pull Request check-list
- [x] Change regex

### Description of change

`Dialect: Mysql`

I have changed the regex which was used to match the error message when error string is more than 260 characters.

### Regex match:

Case I:

**Error string**

CONSTRAINT `iamputtingjusttheboringeststuff8lettersandrandomshitt` FOREIGN KEY (`merchant_site_tag_id`) REFERENCES `merchant_site_tags` (`id`)

group 1: `
group 2: iamputtingjusttheboringeststuff8lettersandrandomshitt
group 3: merchant_site_tag_id
group 4: merchant_site_tags
group 5: id

Case II:

**Error string**

CONSTRAINT `iamputtingjusttheboringeststuff8lettersandrandomshitt` FOREIGN KEY (`merchant_site_tag_id`) REFERENCES `merchant_site_tags` (`id

group 1: `
group 2: iamputtingjusttheboringeststuff8lettersandrandomshitt
group 3: merchant_site_tag_id
group 4: merchant_site_tags
group 5: empty

Case II:

**Error string**

Case III:

**Error string**

CONSTRAINT `iamputtingjusttheboringeststuff8lettersandrandomshitt` FOREIGN KEY (`merchant_site_tag_id`) REFERENCES `merchant_site_tags

group 1: `
group 2: iamputtingjusttheboringeststuff8lettersandrandomshitt
group 3: merchant_site_tag_id
group 4: empty
group 5: empty

Case IV:

**Error string**

CONSTRAINT `iamputtingjusttheboringeststuff8lettersandrandomshitt` FOREIGN KEY (`merchant_site_tag_id

group 1: `
group 2: iamputtingjusttheboringeststuff8lettersandrandomshitt
group 3: empty
group 4: empty
group 5: empty

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Please try to add some tests to prevent regressions

**Comment by sushantdhiman** [comment]
You can add tests here https://github.com/sequelize/sequelize/blob/master/test/integration/dialects/mysql/errors.test.js

**Comment by Tolsee** [comment]
@sushantdhiman Will do that.

**Comment by SimonSchick** [comment]
@Tolsee are you interested in continuing this?

**Comment by Tolsee** [comment]
Yeah, I will complete it in a couple of days.

**Comment by papb** [comment]
Hi @Tolsee, just passing by to remind you of this PR :) Are you interested in continuing it?

Also, there is a conflict.

Thanks for taking the time to help Sequelize!! :)

**Comment by sushantdhiman** [comment]
Closing, see reason https://github.com/sequelize/sequelize/issues/9838#issuecomment-629609178

**Pull request closed without merging**
