### PR TITLE
Fix MSSQL sub query issue occurring with renamed primary key fields

### PR DESCRIPTION
**Pull request by marcesengel**
This PR aims at fixing #11700. It prevents redundant selection of aliased fields in sub queries. For more details please refer to https://github.com/sequelize/sequelize/issues/11700#issuecomment-719980516.

### CODE REVIEW

**Comment by DragonRaider5** [comment]
As stated in https://github.com/sequelize/sequelize/issues/11700#issue-527181948 the issue was introduced with v5.18.4. Looking up the git blame for the changed lines of code reveals that the most recent changes to those lines where published in v5.18.4, which would make perfect sense.

**Comment by DragonRaider5** [comment]
@sdepold how do I continue from here?

**Comment by DragonRaider5** [comment]
@papb sorry for having to ping you, but could you help me finishing this PR please? Would be very much appreciated.

**Review by thisbechristian — APPROVED** [review]

**Comment by Keimeno** [comment]
@DragonRaider5 can you please target sequelize:main instead of sequelize:v6? The main dev branch was changed a few months ago.

**Comment by DragonRaider5** [comment]
@Keimeno done :+1:

**Comment by thisbechristian** [comment]
@Keimeno what are the next steps for getting this PR merged?

**Comment by Keimeno** [comment]
I believe the only thing missing is that a member of sequelize approves and merges this PR into the main branch.

@papb

**Comment by thisbechristian** [comment]
pinging @sdepold @janmeier

**Review by Keimeno — APPROVED** [review]

**Comment by tvaamorim** [comment]
I don't know if I'm doing right, but is possible to someone run again the failing test?

@thisbechristian @Keimeno @marcesengel

**Comment by marcesengel** [comment]
@tvaamorim @Keimeno sadly I can't rerun the tests myself, unless I push some kind of useless commit or something.

**Comment by marcesengel** [comment]
Maybe I should just merge the current main branch or revert the merge commits and rebase to current main in order to get the tests triggering 🤔

**Review by Keimeno — APPROVED** [review]

**Comment by marcesengel** [comment]
Thanks a lot @Keimeno ! Now we're only missing a merge and this issue #11700 is resolved 💪  sorry for having to annoy you like this and thanks again in advance 🥇 💯

**Comment by sdepold** [comment]
I took the liberty to merge this little guy :) Thanks!
I also just figured out why I never received notifications about sequelize, so sorry for the radio silence here :)

**Pull request merged**
