### PR TITLE
refactor(operators): use namespaced symbol names for operators

### PR DESCRIPTION
**Pull request by SimonSchick**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Using `Symbol.for` adds them to a global registry of symbols, this seems redundant in the case of sequelize, an alternative would be to namespace them (as nodejs does).

### CODE REVIEW

**Comment by sushantdhiman** [comment]
We can namespace them like `sequelize.op.<>`.  We use `Symbol.for` to prevent issues like https://github.com/sequelize/sequelize/issues/8663

This is probably a major change, there is no real benefit from this change either

**Comment by SimonSchick** [comment]
I read the issue you linked and I don't understand what is going on, did they install different versions of sequelize in the same project? As long as you always use `Op` consistently the references should always be the same.

I think renaming them is fine to (also helps when debugging), but I don't think the symbol names should be considered public API 😛

**Comment by sushantdhiman** [comment]
Yes this is useful when a project is using two version of sequelize, depends upon how they are included by `require`. If we use `Symbol`, we end up creating a new symbol which wont match other version of sequelize.

This is a breaking change because you can no longer mix symbols from various versions of Sequelize, not sure if someone's setup depends on that.

**Comment by SimonSchick** [comment]
Tbf, if someone loads 2 different versions of sequelize they probably have significantly worse problems than the symbols 😛 (instanceof checks etc.).
I will go ahead and namespace the symbols and target the PR against v6.

**Comment by SimonSchick** [comment]
Going to move this into v6.

**Pull request merged**
