### PR TITLE
doc: Add install tsc on configuration

### PR DESCRIPTION
**Pull request by JuarezLustosa**
Close this issue #12509

### CODE REVIEW

**Comment by nachocab** [comment]
Shouldn't this also be merged into master as well?

**Comment by JuarezLustosa** [comment]
> Shouldn't this also be merged into master as well? 

Yeah I think so. Open a new PR from master?

**Comment by papb** [comment]
Good catch @nachocab! @JuarezLustosa this time I have just cherry-picked the commit myself into 72bf6c01, so this is also in master now.

**Pull request merged**
