### PR TITLE
Make documentation responsive

### LINKED ISSUE #11453: v6: make documentation mobile friendly

### PR DESCRIPTION
**Pull request by soryy708**
### Description of change

closes #11453

### CODE REVIEW

**Comment by papb** [comment]
Hello, thanks for the PR, I will try to take a look later today

**Comment by soryy708** [comment]
@papb sup?

**Comment by sushantdhiman** [comment]
It seems device-width meta tag is missing

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

Is there a way to set this with esdocs? If not perhaps use Javascript to do that

**Comment by soryy708** [comment]
@sushantdhiman I made the requested changes

**Comment by sushantdhiman** [comment]
Thanks @soryy708

**Pull request merged**
