### PR TITLE
meta: clean up expectsql dialect combinations and order

### PR DESCRIPTION
**Pull request by WikiRik**
## Pull Request Checklist

- [X] Have you added new tests to prevent regressions?
- [X] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

With the merge of #15595 I wanted to clean up the tests where we make use of `expectsql`. It turned out to be a bigger PR than I initally had in mind. So I'm not sure if we want to merge it in the current state because of possible conflicts to other PRs. I'm open to hearing what people think about this PR

But basically what I did is the following;
- combined dialects expectations where they were the same (already or with tick replacements)
- where it made sense updated default or renamed single dialect to default where only one dialect is tested
- fixed the order of the dialects to be in line with how `test-unit-all` runs; `mariadb mysql postgres mssql sqlite snowflake db2 ibmi`
- some tests I removed unnecessary usage of backticks or added backticks in order to limit the quoted characters. Sometimes by replacing backticks with square brackets

### CODE REVIEW

**Comment by ephys** [comment]
I can get behind always putting `default` first but I think sorting the contents of the dialect strings & sorting these keys themselves is going to be very difficult to enforce without a linter

We could write our own eslint rule w/ autofix

**Comment by WikiRik** [comment]
An eslint rule with auto fix would be great but not something we need on the short term. I don't mind that much if dialects are not in the same order so if we miss some in the future that's not a big issue. I was just going through everything for this PR and felt like cleaning up

**Comment by WikiRik** [comment]
I'll revisit this once #15689 and #15598 have been merged

**Comment by WikiRik** [comment]
I still want to revisit this some time, but likely after the v7 release. Closing for now

**Pull request closed without merging**
