### PR TITLE
Show appropriate error message for model validation error

### PR DESCRIPTION
**Pull request by phanect**
Before:
Possibly unhandled SequelizeValidationError: Validation error
    at /home/phanect/dev/notel-api/node_modules/sequelize/lib/instance-validator.js:150:14
    ...

After:
Possibly unhandled SequelizeValidationError: field_name cannot be null
    at /home/phanect/dev/notel-api/node_modules/sequelize/lib/instance-validator.js:150:14
    ...

### CODE REVIEW

**Comment by janmeier** [comment]
Closed, no response

**Comment by phanect** [comment]
Sorry for late reply.
I fixed problems except for one issue: "[MSSQL] Timezone returns the same value for current timestamp"

This issue might be existing Sequelize bug, so can you reopen this PR and run Travis's test again? I'm not sure this test failure is caused by my change or it is existing Sequelize bug (and it is already fixed).

If this test failure is caused by my change, can you (or anyone else) please give me any advice? I have no idea how I can fix this.

(BTW I have already rebased my repo, as I post this one month ago...)

**Comment by phanect** [comment]
@janmeier

Sorry for late reply.
I fixed problems except for one issue: "[MSSQL] Timezone returns the same value for current timestamp"

This issue might be existing Sequelize bug, so can you reopen this PR and run Travis's test again? I'm not sure this test failure is caused by my change or it is existing Sequelize bug (and it is already fixed).

If this test failure is caused by my change, can you (or anyone else) please give me any advice? I have no idea how I can fix this.

(BTW I have already rebased my repo, as I post this one month ago...)

**Comment by janmeier** [comment]
@phanect I cannot re-open "the branch was force-pushed or recreated". Please open an new PR

**Comment by phanect** [comment]
@janmeier Oh, OK. I will.

**Pull request closed without merging**
