### PR TITLE
Create a shallow copy of scopeInclude in Model.$injectScope

### LINKED ISSUE #4470: Memory leak & maximum call stack exceeded using hasMany with scope
Considering the following model definitions:
```js
var User = sequelize.define('User', {
    name: Sequelize.STRING
});

var Project = sequelize.define('Project', {
    type: Sequelize.STRING,
    title: Sequelize.STRING
});

User.addScope('defaultScope', {
    include: [Project]
}, {
    override: true
});

Project.belongsTo(User);

User.hasMany(Project, {
    scope: {
        type: 'open'
    }
});
```
We create a user and a project:
```js
let user = yield User.create({
    name: 'John'
});
yield user.createProject({
    name: 'Project 1'
});
```
Then querying the user multiple times as following: 
```js
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
yield User.findById(user.id);
```
Result in a growing array `value` in `query-generator.js:1913` in `whereItemQuery` method. Logging the array `value` around line 1923 after the recursive call to `whereItemQuery`, we obtain the following: 
```sql
'((((((((((((("Projects"."type" = \'open\' AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\') AND "Projects"."type" = \'open\')',
  '"Projects"."type" = \'open\'' 
```
The size increase at each query.

### PR DESCRIPTION
**Pull request by Verdier**
Closes #4470.

### CODE REVIEW

**Comment by Verdier** [comment]
@mickhansen this pull request fix #4470 and avoid to modify `Model.$scope.include[]`.

**Comment by mickhansen** [comment]
That's probably a good idea aswell.
But ideally we should track down where the object is dirtied and make sure it's cloned before that.

**Comment by Verdier** [comment]
Tests fails because of a timeout that's not linked to the pull request.

**Comment by mickhansen** [comment]
Can you add a test for this so we don't have a regression?

**Comment by Verdier** [comment]
@mickhansen ok non problem. I've never cloned the repos...

**Pull request closed without merging**
