### PR TITLE
Ability to set custom connection timeout in postgres client.

### PR DESCRIPTION
**Pull request by gabrieloczkowski**
What's new:
- Ability to set `connectionTimeoutMillis` for postgres client using `config.dialectOptions`.

### CODE REVIEW

**Comment by gabrieloczkowski** [comment]
@papb @janmeier Hi. Please take a closer look into this small change and let me know if something else should be done before merge.

**Comment by matthewwhipple** [comment]
why was this closed?

**Comment by gabrieloczkowski** [comment]
I closed it because of no attention from anybody, I don't like zombie PRs. Let me know if we should reopen and make progress.

**Comment by matthewwhipple** [comment]
I ran up against this limitation and it seems worth having some solution or other for this behavior. This was also opened shortly after this one: https://github.com/sequelize/sequelize/pull/12636 but I'd speculate that one was closed in deference to this one.

At the moment I've switched to using `pg` directly but I'll be revisiting how sequelize fits in in a couple weeks.

**Comment by fncolon** [comment]
@gabrieloczkowski Hello do you mind to continue the work? i will look up to this, thank you!

**Comment by gabrieloczkowski** [comment]
@fncolon Feel free to use the PR (merge or close) 👍

**Comment by papb** [comment]
> @papb @janmeier Hi. Please take a closer look into this small change and let me know if something else should be done before merge.

@gabrieloczkowski Sorry to take 1.5 years... In the mean time, we switched our main branch from `master` to `main`. Can you open a new PR into `main`? The code around the lines you updated may have changed in the mean time. Also, to merge this, I'd like to ask two extra things:

* Find an appropriate `.md` manual page [here](https://github.com/sequelize/sequelize/tree/main/docs/manual) where you can add this information
* Change the URL of [the link you added in the comment here](https://github.com/sequelize/sequelize/pull/12621/files#diff-4ceab0ce7873d60045612d3ad5b59901b6270a8c8fbd6eb45f5e38f5ea6436f7R119), never use links to master like that, use a permalink instead (pointing to a specific commit) :)

Thank you very much!! :)

**Pull request closed without merging**
