### PR TITLE
Hooks Tests and Refractor

### LINKED ISSUE #4837: instance.update() not persisting changes made in hook to database
I'm using postgres 9.4.4, sequelize 3.13.0. I have a model hook that updates a column called `updatedById` whenever a user modifies a row in my database. I get the userId by passing it through via `options` when `instance.update()` is called.

Here is a repo I've set up with the smallest test case possible: https://github.com/eventhough/sequelize-test

The problem is, when my hook updates the `updatedById` column, the change is not being persisted to the database. The `updatedById` column even shows up when I call `.changed()` on my instance.

I'm *pretty* sure this used to work for me but for some reason it's not working now. I've also tried moving the hook to `beforeUpdate` but it's the same issue.

Here is my setup:

```javascript
var Sequelize = require('sequelize');

var sequelize = new Sequelize('sequelize_test', 'postgres', '', {
  host: 'localhost',
  dialect: 'postgres',
});

var User = sequelize.define('User', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
  },
});

var Widget = sequelize.define('Widget', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  name: {
    type: Sequelize.STRING,
  },
}, {
  hooks: {
    beforeValidate: function (widget, options) {
      if (!options.userId) {
        return Sequelize.Promise.reject(new Error('userId required in options for create or update'));
      }

      console.log('beforeValidate changed columns:', widget.changed());
      widget.name = widget.name + ' hello';

      if (!widget.createdById) {
        widget.createdById = options.userId;
      }

      if (widget.changed()) {
        widget.updatedById = options.userId;
      }

      return widget;
    }
  }
});

Widget.belongsTo(User, { as: 'createdBy', foreignKey: { allowNull: false } });
Widget.belongsTo(User, { as: 'updatedBy', foreignKey: { allowNull: false } });
```

If you run my example you'll see this in the console:

```bash
beforeValidate changed columns: [ 'name' ]
beforeValidate changed columns: [ 'name', 'updatedById' ]
Executing (default): UPDATE "Widgets" SET "name"='red horse hello hello',"updatedAt"='2015-11-10 23:31:52.029 +00:00' WHERE "id" = 1
```

I would expect the last line to include the `updatedById` column:

```bash
Executing (default): UPDATE "Widgets" SET "name"='red horse hello hello',"updatedById"=2,"updatedAt"='2015-11-10 23:31:52.029 +00:00' WHERE "id" = 1
```

### LINKED ISSUE #5142: Changes made in beforeCreate hook are not persisted to the database
Hello there!

I have an issue where changes made in `beforeCreate` hook are not saved to the database.

```javascript

console.log('Session.build()');
var session = Session.build({
  ipAddress: req.clientIp
});

console.log('setUser()');
session.setUser(user);

console.log('save()');
session.save();

```

```javascript

hooks: {
  beforeCreate: function (session) {

    console.log('Session.beforeCreate()');

    // Auto-generating token.
    // @todo: make sure it's unique
    session.token = randomstring.generate();

    console.log('Token set to: ' + session.token);

    // Setting default expiration time.
    if (!session.expiresAt) {
      session.expiresAt = new Date();
      console.log('Expiration set to: ' + session.expiresAt);
    }

  }
},

```

And here's the log:

```
Session.build()
setUser()
save()
Session.beforeCreate()
Token set to: usvnC9z76VNAJcCtch
Expiration set to: Tue Jan 05 2016 23:48:14 GMT+0300 (MSK)
Executing (default): INSERT INTO "sessions" ("userId","updatedAt","createdAt") VALUES (1,'2016-01-04 20:48:14.710 +00:00','2016-01-04 20:48:14.710 +00:00');
```

Is it related to #3534 and #4837?

---

Sequelize version: **3.15.1**
Node version: **5.3.0**

### PR DESCRIPTION
**Pull request by sushantdhiman**
Refractor hooks tests. Added tests to verify closing of `beforeValidate` instance changes not persisted issues.

Closes #4837
Closes #5142

### CODE REVIEW

**Comment by mickhansen** [comment]
Hmm, would probably have been ideal to have had the test move and the test refactor in seperate commits. Right now it's hard to see how much actually changed and how much is just tests being moved around.

Will take some time to review since we have to make sure that coverage didn't go down.

**Comment by janmeier** [comment]
Maybe its time for me to look at code climate again - PR integration should have landed so we can see if a PR changes coverage.

**Comment by janmeier** [comment]
On another note, I'd like to see a lot of these hooks tests move to stubbed out unit tests at some point, along the lines of https://github.com/sequelize/sequelize/blob/master/test/unit/model/findall.test.js

**Comment by sushantdhiman** [comment]
@mickhansen New test are added in 2nd commit only. You can check those new tests. Old tests are moved in first commit.

**Comment by mickhansen** [comment]
@sushantdhiman Ah okay great then :) The commit message just says "refactor" which usually implies some sort of change aswell.

**Comment by sushantdhiman** [comment]
@mickhansen did you get chance to review this one. I have added new tests, so coverage should be up.

**Comment by mickhansen** [comment]
Reviewed the new tests, trust you on moving the old ones.

**Comment by sushantdhiman** [comment]
Thanks @mickhansen

**Pull request merged**
