### PR TITLE
ci: test v7 against node 18

### PR DESCRIPTION
**Pull request by ephys**
### Description Of Change

This PR replaces node 16 with node 18 in our CI, so that we test against both our minimum and maximum supported node versions

### CODE REVIEW

**Comment by WikiRik** [comment]
Can we wait until 2022-10-25 with this so Node 18 has had its first LTS release?

**Comment by ephys** [comment]
We're going to need to wait a little bit more, until `eslint-plugin-jsdoc` supports node 18

**Comment by ephys** [comment]
> Can we wait until 2022-10-25 with this so Node 18 has had its first LTS release?

Should we? I can understand waiting until it reaches LTS before upgrading an app, but I think a library should be ready before then

**Comment by WikiRik** [comment]
We skipped Node 17 as well and currently Node 18 is in the same state. I agree that we should be ready to support it when the first LTS release is out, but don't think replacing Node 16 with this is the way to go at this moment. Maybe we can add the latest version as a third version to test?
Or we wait a bit until I finally have written down my ideas for a more comprehensive test suite that runs once a week (up for debate) and focusses on more combinations of Node versions, database connector versions and database versions.

**Comment by ephys** [comment]
We skipped node 17 because we didn't plan on supporting it at all, as the release is only maintained for 6 months.
There is no real difference in stability between node 18 current and node 18 LTS, if we want to support it we should start today instead of when it gets promoted to LTS

> Maybe we can add the latest version as a third version to test?

We can, but this would increase our CI time to ~22 minutes, from ~15 minutes currently.

**Comment by WikiRik** [comment]
> We're going to need to wait a little bit more, until `eslint-plugin-jsdoc` supports node 18

I have a feeling we'll get a new release from that later today.

**Comment by WikiRik** [comment]
Okay, after the update of `eslint-plugin-jsdoc` we still have `@azure/msal-node` left (through `tedious` -> `@azure/identity`). PR is open for that, afterwards we should be able to install dependencies without adding `--ignore-engines`

Just for now, you could just add `--ignore-engines` so we can at least make sure that tests pass.

**Comment by WikiRik** [comment]
Another update, it looks like `@azure/msal-node` will get a regular update in about 2 weeks which will most likely include the support for Node 18.

**Comment by WikiRik** [comment]
Linting fails, see https://github.com/lo1tuma/eslint-plugin-mocha/pull/325 for context

**Comment by WikiRik** [comment]
Let's wait until https://github.com/TypeStrong/typedoc/issues/1935 is solved and then we should be good to merge this

**Review by WikiRik — APPROVED** [review]
Tests pass, just need to update it in the repo settings.

**Comment by ephys** [comment]
Wooh 🥳

**Pull request merged**
