### PR TITLE
RFC: Allow "tenant keys" in associations, to query on composite foreign keys

### PR DESCRIPTION
**Pull request by stevehollaar**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](../CONTRIBUTING.md)?

### Description of change

Related to https://github.com/sequelize/sequelize/issues/311

This adds a new option key to `BelongsTo`, `HasMany`, and `HasOne` associations to allow querying and joining on tables that share a composite key. The motivation here is to allow sharding by a "tenant ID" in [Citus terminology](https://docs.citusdata.com/en/v7.0/sharding/data_modeling.html#distributing-by-tenant-id), but should be generalizable for any use of composite 2-column foreign keys.

With this PR:
```js
FooModel.Bar = FooModel.belongsTo(BarModel, {
  tenantKeys: {
    foreign: 'user_id',
    target: 'user_id',
  }
})
```
Will allow:
```js
fooInstance.getBar()
```
to query:
```
SELECT * FROM bar WHERE bar.id = <foo.bar_id> AND bar.user_id = <foo.user_id>
```
and:
```js
FooModel.findAll({ include: [BarModel] })
```
to query:
```
SELECT * FROM foo LEFT OUTER JOIN bar ON (foo.bar_id = bar.id AND foo.user_id = bar.user_id)
```

### CODE REVIEW

**Comment by janmeier** [comment]
@sushantdhiman What do you think about this?

**Comment by sushantdhiman** [comment]
What this PR try to achieve should ideally be possible with just scopes. But `scopes` are rather limited when comes to dynamic resolution, its still possible to do so by scope using `sequelize.col` and `as` but not that clean and rather limited.

As far as I understood this change, API looks limited to me

1) It only supports two column composite key
2) First source column is assumed to be primary key or `id`

After going through #311, I think @mickhansen suggested a good design https://github.com/sequelize/sequelize/issues/311#issuecomment-218080573

```js
hasMany(Target, {
  foreignKey: {
    key1: 'id1',
    key2: 'id2'
  }
});
```

Although I would like to mention https://github.com/sequelize/sequelize/issues/311#issuecomment-193822332

```js
An array seems right foreignKey: ['key1', ' key2', ' key3'] and in case of the belongsTo with targetKey -> foreignKey: ['key1', ' key2', ' key3'], targetKey: ['targetKey1ToMatchWithKey1', 'targetKey2ToMatchWithKey2', 'targetKey3ToMatchWithKey3']
```

Only because even I find my self confused with source/target notation, so some users may got confused with `{ key: id }` while array approach properly separates `foreignKey / targetKey` 

I think we can go with either of these, upto you guys @sequelize/orm 

```js
hasMany(Target, {
  foreignKeys: ['key1', 'key2', ....],
  targetKeys: ['id1', 'id2', ....]
});

OR

hasMany(Target, {
  foreignKeys: {
      'sourceKey1': 'targetKey1',
      'sourceKey2': 'targetKey2'
  }
});

OR Even 

// I like this one, I realise this is just a variant of Jan's proposal :D
hasMany(Target, {
  foreignKeys: [{
      foreignKey: '',  // can be string or attribute
      targetKey: '', // can be string or attribute
  }, {....}, .....]
});

```


> This will however clash a bit with how this works currently (conceptually at least). Right now foreignKey on specifies one side of the relation ..

Internally they are linked with primaryKey of other side so relation was already there, now we are trying to expose it

**Comment by jedwards1211** [comment]
"tenant" is definitely too specific to the author's use case.  There are many other potential use cases for composite foreign keys that have nothing to do with supporting multi-tenancy.

**Comment by jedwards1211** [comment]
I think that there shouldn't be a separate `extraForeignKeys` variable of any kind, and the existing case (single foreign key) should be treated as a subset of the compound foreign key case.

But, that would be a breaking change, and have to go in version 5.  What do you guys think?

**Comment by papb** [comment]
@stevehollaar Are you still able to pursue this?

**Comment by sushantdhiman** [comment]
Closing this PR for inactivity

**Pull request closed without merging**
