### PR TITLE
feat: migrate database queries to typescript

### PR DESCRIPTION
**Pull request by lohart13**
## Pull Request Checklist

- [x] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

Migrate the following methods to typescript:
- `createDatabase` and `createDatabaseQuery`
- `dropDatabase` and `dropDatabaseQuery`
- `listDatabases` and `listDatabasesQuery`

Also updated the test `clearDatabaseInternal` function to support removing test databases.

### CODE REVIEW

**Comment by lohart13** [comment]
I have a question around the name of `listDatabases` for the `queryInterface`.

What should the naming convention be?
For tables and schemas we have `showAll{x}` for the `queryInterface` and then `list{x}Query` for the queryGenerator.

**Comment by WikiRik** [comment]
> What should the naming convention be? For tables and schemas we have `showAll{x}` for the `queryInterface` and then `list{x}Query` for the queryGenerator.

Good question! I think list{x} would be better since showAll{x} is a bit weird if you use it in combination with the skip option and therefore not returning all tables/schemas.

**Comment by lohart13** [comment]
OK. I'll leave this PR as is and open a new one to move the `showAll{x}` methods to `list{x}`.

**Review by WikiRik — COMMENTED** [review]
Interesting that integration tests are untouched by the removal of the technical databases. Do we not have a test that checks which databases are returned? Or are we only checking if 'sequelize_test' is a part of it?

**Review by WikiRik — APPROVED** [review]

**Comment by lohart13** [comment]
The integration test is only testing that a database can be created listed, and then removed.
I've added a test now to check the list of databases.

Also, I've updated the `clearDatabaseInternal` support function to include dropping test databases

**Review by WikiRik — APPROVED** [review]

**Pull request merged**
