### PR TITLE
docs: ESM clarifications for migrations

### PR DESCRIPTION
**Pull request by corevo**
Doc changes for https://github.com/sequelize/cli/pull/982

### CODE REVIEW

**Comment by mariusa** [comment]
THanks so much for this! Looking forward to start using it!
Would you please provide an example of .sequelizerc with the ESM syntax?

**Comment by corevo** [comment]
This PR only fixes the config, I'll try to look into `.sequelizerc` over the weekend.

**Review by ephys — APPROVED** [review]

**Comment by ephys** [comment]
@corevo The branch is out of date with the base branch and I can't push the update myself. Can you enable to option to let maintainers update your branch or update the branch and ping one of us to merge?

**Comment by ephys** [comment]
Follow up on https://github.com/sequelize/cli/pull/987#issuecomment-1016300806

The documentation should specify that `.sequelizerc` can't be ESM yet.
But we could add an example of `config.mjs` to show that the config must be the default export.

**Comment by mariusa** [comment]
Thank you! Here's what would be good to have as `config.mjs` example, per my understanding of your comment:

```
let db = {
    dialect: "postgres",
    url: process.env.DATABASE_URL,
}

//console.log('process.env.DATABASE_URL', process.env.DATABASE_URL)

export default {
    development: { ...db },
    test: { ...db },
    production: {
        ...db,
        // https://github.com/sequelize/cli/blob/master/docs/README.md Ensure ssl is specified in both dialectOptions and in the base config.
        ssl: {
            require: true,
            rejectUnauthorized: false,
        },
        dialectOptions: {
            ssl: {
                require: true,
                rejectUnauthorized: false,
            },
        },
    },
}
```

**Comment by mariusa** [comment]
@corevo ping, please ?
https://github.com/sequelize/sequelize/pull/13669#issuecomment-1010228064

**Comment by corevo** [comment]
Sorry I was sick, I've enabled maintainer edits, I can also fix it up myself probably tomorrow.

**Comment by mariusa** [comment]
Hope you are well recovered!

**Comment by mariusa** [comment]
ping, please?

**Comment by WikiRik** [comment]
@ephys could you take care of this one in https://github.com/sequelize/website ?

**Comment by ephys** [comment]
https://github.com/sequelize/website/issues/440

**Pull request closed without merging**
