### PR TITLE
Fix some data types in mssql and postgres

### PR DESCRIPTION
**Pull request by BridgeAR**
This fixes the issue found in #3827

### CODE REVIEW

**Comment by BridgeAR** [comment]
I added support for TEXT('length'). This fixes #2793

**Comment by mickhansen** [comment]
@BridgeAR In the future please reference issues from the commits, makes the history much nicer.

**Comment by BridgeAR** [comment]
@mickhansen I stopped inserting the issues in the commit message because it'll reference the ticket with a new commit each time I rebase ;). So I referenced them once in [here] (https://github.com/sequelize/sequelize/pull/3836#issuecomment-107254995) (I might have edited that comment though)?

**Comment by mickhansen** [comment]
@BridgeAR Comments don't close tickets though and it's still way nicer being able to see issues form the commit history without having to find the original PR :)

But yeah it's annoying if it creates a new reference with each rebase.

**Comment by jehoshua02** [comment]
@BridgeAR @mickhansen any plans to update docs? http://docs.sequelizejs.com/en/latest/docs/models-definition/#data-types

**Comment by janmeier** [comment]
@jehoshua02 which options are missing? He tiny option is already shown. You can also just open a PR with the changes you'd like to see

**Pull request merged**
