### PR TITLE
fix(dialect-mysql): custom msg bug fix for duplicate entry on MySQL 8.0

### PR DESCRIPTION
**Pull request by Puvipavan**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

This is a fix for the issue #13601 

In MySQL Version 8.0, index name is displayed after appending the schema name. 
Sample Error on MySQL 5.7
`#1062 - Duplicate entry '1234567890' for key 'users_phone_unique'`

Sample Error on MySQL 8.0
`#1062 - Duplicate entry '1234567890' for key 'users.users_phone_unique'`

Therefore I added a small change which doesn't hurt anything regardless of MySQL Version.

### CODE REVIEW

**Comment by Puvipavan** [comment]
New commit includes the fix for the deprecated function `GeomFromText` on MySQL Version 8.0. Replaced that function by `ST_GeomFromText` which is supported from the version 5.6

**Comment by sdepold** [comment]
I think this one can be closed due to the just merged PR?

**Comment by sdepold** [comment]
Thanks a bunch for raising this and your changes!

**Comment by Puvipavan** [comment]
Thanks again @sdepold 😍

**Pull request closed without merging**
