### PR TITLE
Fix requires for bundlers like webpack

### LINKED ISSUE #6907: Error: Please install 'pg' module manually
I'm in the process of switching to Yarnpkg from npm, and i hit this issue. Was working fine before when i was using npm, but using yarn i get this error.

```js
Error: Please install 'pg' module manually
    at new ConnectionManager (/home/app/kerberos/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:27:13)
    at new PostgresDialect (/home/app/kerberos/node_modules/sequelize/lib/dialects/postgres/index.js:12:28)
    at new Sequelize (/home/app/kerberos/node_modules/sequelize/lib/sequelize.js:233:18)
```

### PR DESCRIPTION
**Pull request by wa4-fearless-otter**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Bundlers (like webpack) have a hard time to include libraries over variable names (as described [here](https://github.com/facebook/react-native/issues/6391#issuecomment-194568185)). This pull-request gives webpack a way to know which libraries are used by this library. This can potentially close #6907 and #7509.

### CODE REVIEW

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

I also don't like dynamic requires like these!

However, before merging this, I would like to first ask: did [this solution](https://github.com/sequelize/sequelize/issues/6907#issuecomment-577150117) work for you?

To me, the proper solution to this issue would be to have sequelize stop requiring these modules automatically. We should let the user provide the module. That alone should solve all these issues, right? In other words, I think the `dialectModulePath` option should not exist, and the `dialectModule` option should be mandatory... What do you think?

(my suggestion depends of course on the fact that the linked comment should work, and I don't know why it wouldn't)

**Comment by wa4-fearless-otter** [comment]
Yes this solutions works too, but I don't want to configure my webpack.config.js for sequelize.

**Comment by papb** [comment]
Can you please try the following instead and let me know?

If you're using typescript:

```ts
import pg = require('pg');
import { Sequelize } from 'sequelize';

const sequelize = new Sequelize('postgres://admin:admin@localhost:5432/mydb', {
  dialectModule: pg
});
```

Otherwise:

```ts
const pg = require('pg');
import { Sequelize } from 'sequelize';

const sequelize = new Sequelize('postgres://admin:admin@localhost:5432/mydb', {
  dialectModule: pg
});
```

(without adding anything to your webpack config, just the above)

**Comment by wa4-fearless-otter** [comment]
I tried this and get an error. I don't know why yet. If you have some idea. Here is the stack trace:

```
TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (webpack-internal:///./node_modules/bindings/bindings.js:143:16)
    at bindings (webpack-internal:///./node_modules/bindings/bindings.js:59:48)
    at Object.eval (webpack-internal:///./node_modules/libpq/index.js:1:158)
    at eval (webpack-internal:///./node_modules/libpq/index.js:387:30)
    at Object../node_modules/libpq/index.js (/home/roman-work/Documents/bt-graphql/dist/index.js:19429:1)
    at __webpack_require__ (/home/roman-work/Documents/bt-graphql/dist/index.js:20:30)
    at eval (webpack-internal:///./node_modules/pg-native/index.js:1:13)
    at Object../node_modules/pg-native/index.js (/home/roman-work/Documents/bt-graphql/dist/index.js:26260:1)
    at __webpack_require__ (/home/roman-work/Documents/bt-graphql/dist/index.js:20:30)
    at eval (webpack-internal:///./node_modules/pg/lib/native/client.js:11:14)
    at Object../node_modules/pg/lib/native/client.js (/home/roman-work/Documents/bt-graphql/dist/index.js:26494:1)
    at __webpack_require__ (/home/roman-work/Documents/bt-graphql/dist/index.js:20:30)
    at eval (webpack-internal:///./node_modules/pg/lib/native/index.js:3:18)
    at Object../node_modules/pg/lib/native/index.js (/home/roman-work/Documents/bt-graphql/dist/index.js:26506:1)
    at __webpack_require__ (/home/roman-work/Documents/bt-graphql/dist/index.js:20:30)
    at PG.eval (webpack-internal:///./node_modules/pg/lib/index.js:56:23)
    at eval (webpack-internal:///./node_modules/lodash/lodash.js:2915:27)
    at arrayEach (webpack-internal:///./node_modules/lodash/lodash.js:618:11)
    at baseClone (webpack-internal:///./node_modules/lodash/lodash.js:2912:7)
    at eval (webpack-internal:///./node_modules/lodash/lodash.js:2919:34)
    at arrayEach (webpack-internal:///./node_modules/lodash/lodash.js:618:11)
    at baseClone (webpack-internal:///./node_modules/lodash/lodash.js:2912:7)
```

But with the webpack config as described in the comment, it works.

**Comment by wa4-fearless-otter** [comment]
So, can this get merged?

**Comment by ceelian** [comment]
Makes sense to me too, is there anything preventing it from getting merged?

**Pull request merged**
