### PR TITLE
fix(order): Fix the sorting on a primary key with includes for MSSQL dialect

### LINKED ISSUE #7851: Sort a collection (containing belongsTo) with a primary key on MSSQL
I have a collection whose model has an association. The primarykey of this collection is constantly added as a sorting parameter on find query.

```js
var Model = sequelize.define('ProductCategory', {
    ProductCategoryID: {
        type: DataTypes.INTEGER,
        primaryKey: true
    },
    Name: { type: DataTypes.STRING },
}, {
    classMethods: {
        associate: () => {
            Model.hasMany(models.Product, { foreignKey: 'ProductCategoryID' });
        }
    }
}
```

## What do you expect to happen?
I want to sort the collection by the `ProductCategoryID` field.

## What is actually happening?
But the query crash because the field is added two times in the order parameters.

### Query
`Executing (default): SELECT [Product].[ProductID], [Product].[Name], [Product].[ProductNumber], [Product].[Color], [Product].[Size], [Product].[Weight], [Product].[ProductCategoryID], [Product].[ProductModelID], [Product].[SellStartDate], [Product].[SellEndDate], [Product].[DiscontinuedDate], [Product].[ThumbnailPhotoFileName], [Product].[rowguid], [Product].[ModifiedDate], [ProductCategory].[ProductCategoryID] AS [ProductCategory.ProductCategoryID], [ProductCategory].[ParentProductCategoryID] AS [ProductCategory.ParentProductCategoryID], [ProductCategory].[Name] AS [ProductCategory.Name], [ProductCategory].[rowguid] AS [ProductCategory.rowguid], [ProductCategory].[ModifiedDate] AS [ProductCategory.ModifiedDate] FROM [SalesLT].[Product] AS [Product] LEFT OUTER JOIN [SalesLT].[ProductCategory] AS [ProductCategory] ON [Product].[ProductCategoryID] = [ProductCategory].[ProductCategoryID] ORDER BY [Product].[ProductID] DESC, [ProductID] OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;`
**ORDER BY [Product].[ProductID] DESC, [ProductID]**

### Console error
SequelizeBaseError: A column has been specified more than once in the order by list. Columns in the order by list must be unique.

__Dialect:__ mssql
__Sequelize version:__ 3.29.0

### PR DESCRIPTION
**Pull request by arnaudbesnier**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

Closes #7851

Developers receive this error: `SequelizeBaseError: A column has been specified more than once in the order by list. Columns in the order by list must be unique.`

If they try to order their results on a `findAll` call with the primary key set in the `order` option value and have also the `include` option set with at least one value.

This fix prevent the issue by checking if the primary key is already defined by the developer.
The change is restricted in the MSSQL code.

### CODE REVIEW

**Comment by arnaudbesnier** [comment]
I know CI is failing... 😭 but I don't really know why. I only changed some code related on MSSQL and the builds fail.

**Comment by arnaudbesnier** [comment]
So sad that nobody can't help to finalize this fix.

**Comment by Na0ki** [comment]
I tried to run `npm run test-unit-mssql` and received following error.
```
TypeError: Cannot read property 'map' of undefined
```

This fix worked fine (Removing `Utils.`: https://github.com/Na0ki/sequelize/commit/12c0b32007f0a4660aacdea4245ae65b451f6005)

This PR is great and I really need this!

**Comment by dsbert** [comment]
This is still an issue.

**Comment by gabrielmla** [comment]
@Na0ki Removing `Utils` worked perfectly, thanks!

**Comment by papb** [comment]
So, it is working, finally :grimacing: 

However this PR can't be accepted as is yet, it needs a test.

**Pull request closed without merging**
