### PR TITLE
fix(sqlite): update primary key on sqlite upsert (#12683)

### LINKED ISSUE #12683: Model upsert does not return updated model for PK when autoincrement and SQLite dialect
## Issue Description
When using `sqlite` as dialect and using model's `upsert` method, the returned model does not have the primary key field updated if it's defined as `autoincrement`.

### What are you doing?
Upserting a model where its PK is defined as auto increment.

I could not use the repo for SSCCE because only supports v5 of Sequelize and this behaviour is with v6.
I have created a public repo in my github that reproduces the error:
**Here is the link to the SSCCE for this issue:** https://github.com/gborobio73/sqlite-upsert 

Here's the code (as a test) that reproduces the issue.
```js
// file upsert.test.js
const { Sequelize, Model, DataTypes } = require('sequelize');

const sequelize = new Sequelize('database', 'username', 'password', {
  dialect: 'sqlite',
  storage: 'database/database.sqlite', // or ':memory:'
  dialectOptions: {
    // Your sqlite3 options here
  }
});

class User extends Model {}
User.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  ssn: {
    type: DataTypes.STRING,
    unique: true,
  },
  username: DataTypes.STRING,
  birthday: DataTypes.DATE
}, { sequelize, modelName: 'user' });

afterAll(async () => {
  await sequelize.close();
});

test('should return model with id', async () => {
  await sequelize.sync({ force: true });

  const [jane] = await User.upsert({
    ssn: '123456-XXX',
    username: 'janedoe',
    birthday: new Date(1980, 6, 20)
  });

  console.log('janedoe upsert', jane.toJSON());
  expect(jane.id).not.toBeNull(); // fails because the id is null.
});
```

### What do you expect to happen?

_I expect that the PK of the model returned by `upsert` is updated to the correct value._

### What is actually happening?
_The PK of the model returned by `upsert` has `null` as value_

Here's the test output
```
  ● should return model with id

    expect(received).not.toBeNull()

    Received: null

      39 |
      40 |   console.log('janedoe upsert', jane.toJSON());
    > 41 |   expect(jane.id).not.toBeNull(); // fails because the id is null.
         |                       ^
      42 | });
      43 |

      at Object.<anonymous> (test/upsert.test.js:41:23)
```
Console output:
```
console.log
    janedoe upsert {
      id: null,
      ssn: '123456-XXX',
      username: 'janedoe',
      birthday: 1980-07-19T22:00:00.000Z
    }

      at Object.<anonymous> (test/upsert.test.js:40:11)
```

### Environment

- Sequelize version: 6.3.5 
- Node.js version: 12.18.2 
- Operating System: macOS Catalina 10.15.6 (19G2021)
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): SQLite 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by HelloWorld017**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
  - N/A
- [x] Did you update the typescript typings accordingly (if applicable)?
  - N/A
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

- Make `getDatabaseMethod()` return 'run', instead of 'exec', to
  retrieve the Statement metadata.
- Update primary key from Statement metadata on upsert.

Closes #12683

### CODE REVIEW

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

**Comment by papb** [comment]
I've basically undid what you did in 2d31ce0, in order to merge this asap. However, I am interested in knowing why we should always run those three tests, instead of only running if `current.dialect.supports.returnValues`.

**Comment by papb** [comment]
Also, next time, whenever you open a PR, please pretend you're the reviewer and go to the ["files changed" tab](https://github.com/sequelize/sequelize/pull/12991/files) and take a look. The diff on `test/integration/model/upsert.test.js` was very confusing. It took me over 20 minutes to realize that you just moved the tests around while not really changing their content at all. I invite you to look at the diff yourself again: 2d31ce0

Ideally you would have added to the PR description something like:

> Hello! The diff on `test/integration/model/upsert.test.js` looks crazy but I just moved three tests outside the if statement and put them into a new `describe` block.

This would have made my review much easier.

**Review by papb — APPROVED** [review]

**Comment by HelloWorld017** [comment]
Hello,

> Also, next time, whenever you open a PR, please pretend you're the reviewer and go to the "files changed" tab and take a look. The diff on test/integration/model/upsert.test.js was very confusing.

I'm very sorry about that. Next time when I open the PR, I'll add descriptions for diffs hard to recognize.

> However, I am interested in knowing why we should always run those three tests, instead of only running if current.dialect.supports.returnValues.

I have originally thought that at least PKs should be updated even the dialect doesn't support returnValues, and to make sure that, I have made those three tests run regardless the option.

But now, I think those test should be run only if returnValues are supported, as it is basically testing about returning option. And if a new dialect, without ability to get PK of updated row, is implemented, it could be problemsome. So I think it is good to revert the commit 2d31ce0baf844f1841250785d6be244c443adbbf.

Sorry for inconvenience and thank you for reviewing this PR.

**Comment by papb** [comment]
@HelloWorld017 Awesome, thank you very much!!

**Pull request merged**
