### PR TITLE
use QueryTypes.UPDATE instead of RAW when incrementing a value of an …

### PR DESCRIPTION
**Pull request by Bibernull**
…instance #4253

### CODE REVIEW

**Comment by janmeier** [comment]
LGTM, but needs an integration test. `if dialect.supports.returning check that values are updated

**Comment by Bibernull** [comment]
not sure if the failing test has anything to do with increment?

**Comment by janmeier** [comment]
Merged, thanks! :) https://github.com/sequelize/sequelize/commit/0ed07d90abc7612053c60760ee58c64a33153cfc

**Comment by janmeier** [comment]
Nope, the failure is unrelated - haven't managed to track down why that test keeps failing

**Pull request closed without merging**
