### PR TITLE
fix(data-types): unnecessary warning when getting data with DATE dataTypes

### PR DESCRIPTION
**Pull request by fncolon**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

unnecessary warning when getting data with DATE dataTypes attributes.

Capture

### Todos

- [x] check if value is date

### CODE REVIEW

**Comment by sdepold** [comment]
Can we have a test that ensures that the situation has improved?

**Comment by fncolon** [comment]
> Can we have a test that ensures that the situation has improved?

Look like checking this warning has resolve or not cannot be checked with unit test, only manual test. Correct me if I'm wrong.

**Comment by fncolon** [comment]
You can check by manual test with 

```
  const crowdFundings = await CrowdFunding.findAndCountAll({
    distinct: true, // don't count the include part https://github.com/sequelize/sequelize/pull/4016#issuecomment-116294996
    attributes: [
     'date_attributes' // <- will cause the warning from momentjs
    ],
    include: [{ all: true }],
    where: {
      ...data,
      [Op.or]: searchUtil.search(crowdFundingAttributes, query.q || ""),
    },
    ...pagination.getPaginationOptionsData(),
  });
```

I take this codebase from my project haha

**Comment by sdepold** [comment]
Is the result of the function different if it is not a date?

**Comment by fncolon** [comment]
> Is the result of the function different if it is not a date?

No, it's just produce momentjs warning which may some developers don't like, so I improve it to just apply timezone when the value in the correct format.

**Comment by WikiRik** [comment]
I don't think we need to merge this, especially if https://github.com/sequelize/sequelize/issues/13372 will be done soon

**Comment by fncolon** [comment]
> I don't think we need to merge this, especially if #13372 will be done soon

It might be implemented too but we don't have an updated PR for it. So merge this now wil lstill be needed so someone not confusing with this kind of error just because we apply timezone for non-Date values.

**Comment by fncolon** [comment]
Also we need to check the value first if it's date or not, whether it is using momentjs or others

**Comment by WikiRik** [comment]
Sure, then this looks good

**Comment by moonjoungyoung** [comment]
@fncolon @sdepold 

Hello.
After this PR, using moment objects are throwing error.
Is this an intended modification?

**Comment by fncolon** [comment]
> @fncolon @sdepold
> 
> Hello. After this PR, using moment objects are throwing error. Is this an intended modification?

Hello, can you reproduce your example in an issue, technicallly it's just check a raw date value.

**Comment by cmelendez** [comment]
> > @fncolon @sdepold
> > Hello. After this PR, using moment objects are throwing error. Is this an intended modification?
> 
> Hello, can you reproduce your example in an issue? technicallly it's just check a raw date value.

Hi @fncolon.

We upgraded from 6.9.0 to 6.12.1 today and our app started throwing errors when using a Moment object to do equality checks. I'm not sure if this PR is the cause but it seems to be similar to the problem described by @moonjoungyoung.

Here's a piece of code that is throwing a `Invalid value Moment<2021-12-21T19:52:23+00:00>` error.

```
phone_validation_until: {
   [Op.gte]: moment()
  },
```

Thanks.

**Comment by cmelendez** [comment]
Some extra info:

* When setting any date value with `moment`, the stored value is `0000-00-00 00:00:00`.
* We are using `mysql`.

**Comment by fncolon** [comment]
> @fncolon @sdepold
> 
> Hello. After this PR, using moment objects are throwing error. Is this an intended modification?

Just find out the problem, it was returning date instead of formatted date, also change isDate from `lodash` with isMoment from `moment`.

**Comment by fncolon** [comment]
> Some extra info:
> 
> * When setting any date value with `moment`, the stored value is `0000-00-00 00:00:00`.
> * We are using `mysql`.
> * Moment objects works perfectly up to 6.11.0. Issues starts with >=6.12.0.
> 
> edit: pinging @sdepold

Just created the pull request in #13818, thanks!

**Pull request merged**
