### PR TITLE
feat(query): introduce alias substitution

### LINKED ISSUE #2084: Max identifier length exceeded with nested includes
Postgres has a 63 character max for identifiers, which is pretty hard to hit in normal use, and pretty easy to hit with the current way nested includes are namespaced. Unfortunately this parameter is hardcoded into Postgres and can only be increased by changing a source file and recompiling.

### PR DESCRIPTION
**Pull request by clncln1**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

This is an attempt to fix #2084
The feature basically introduces an ordinal-based (deep) alias substitution for column names as well as table aliases for all includes within a query.
It allows more complex use cases/queries with sequelize and postgresql by avoiding to hit the 63 character limit for identifiers that soon.

Let me know what you think about the approach. If you are okay with it, I will update the PR to:
1) make substitution option default to false (currently true in order to show full compliance with the test suite)
2) implement substitution-specific tests to cover 100% of the added lines
3) update doc

### CODE REVIEW

**Comment by sushantdhiman** [comment]
This solution adds too much logic to an already complex base query generator. I think a better solution will be https://github.com/sequelize/sequelize/issues/5708 

But that fix of-course will require some serious refactoring work

**Comment by clncln1** [comment]
I agree that it's quite complex.
But even if you would remove column aliasing at all, you would still need to have table aliasing in place (where you also get bitten by the 63 character limit if you stick to the current aliasing scheme).
Is there somebody working on that?

**Comment by yohannprigent** [comment]
This PR would really help all users affected with #2084. Any news to merge this one ?

**Comment by javagaba** [comment]
+1

**Comment by Relequestual** [comment]
It would be great to see this merged. We are currenly having this issue.

**Comment by SimonSchick** [comment]
Closing this due to age and merge conflicts, feel free to rebase/refresh this PR and re-open.

**Pull request closed without merging**
