### PR TITLE
Adding logging to the error handling.

### PR DESCRIPTION
**Pull request by manchicken**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ Yes ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ No issue exists to my knowledge ] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ No, this isn't an issue ] Have you added new tests to prevent regressions?
- [ No, I don't think this affects documentation ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ No ] Have you added an entry under `Future` in the changelog?

_NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open._

### Description of change

This is just a simple change to add logging to where error formatting is being done. This way we can get a more raw log entry written whenever an error is encountered

### CODE REVIEW

**Comment by janmeier** [comment]
Hmm, not sure I like the idea of forcing logging on the user - For example if you do a `create` which might hit a unique index - you catch the `UniqueConstraintErrror`, because its expected and move on. You don't want those non-errors showing up in your logs.

I think it would be better to add a [rejection handler](http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events) to your own code. Or perhaps we could add an `onError` hook to sequelize.

Don't you agree @mickhansen ?

**Comment by mickhansen** [comment]
Isn't the original error attached to all errors, so a user can just inspect that?
I don't think we should introduce this code, rejection handlers are better since a lot of ours generally enjoy our exception handling

**Comment by janmeier** [comment]
Yep, the original error is always available in `original` and `parent`

**Comment by manchicken** [comment]
Don't you guys actually have this using the logging config setting? It
seems odd that you wouldn't have it log errors when the `logging` setting
is enabled.

**Comment by manchicken** [comment]
This isn't forcing logging, this is using logging if it is enabled with the `logging` setting.

**Comment by janmeier** [comment]
The problem is that this logs all errors - I think we should only log unhandled errors, which can be done with the bluebird settings I linked

**Comment by mickhansen** [comment]
I suppose there could be an argument for logging errors after the SQL has been executed, but in that case it should be the formatted error most likely

**Comment by manchicken** [comment]
The problem I'm trying to solve is one where the database has odd
transactional behavior going on - updated records which sporadically don't
seem to actually be updated, despite no error messages at all.

It seems in keeping with the spirit of the concept of having SQL logging
enabled to log the SQL error code and message in a more raw format for the
dbms being used.

The logging feature seems like a troubleshooting feature in that regard, so
anything but raw log messages seem like they could potentially obscure the
error for the user of sequelize.

**Pull request closed without merging**
