### PR TITLE
fix(ibmi): reconnect when connection drops because of 08S01 error

### PR DESCRIPTION
**Pull request by rcronin**
## Pull Request Checklist

- [ X ] Have you added new tests to prevent regressions?
   Tested via add a retry block on the Sequelize config locally and verified change allows connection to be re-established.
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

Changes here include a way to get sequelize when the IBM i connection drops. This change checks a specific SQL state on the IBM i and utilizes the ConnectionRefusedError to trigger a reconnect.

### CODE REVIEW

**Comment by sdepold** [comment]
I guess some sort of test would be much appreciated :)

**Comment by rcronin** [comment]
> I guess some sort of test would be much appreciated :)

I'd be happy to add them but I don't see any unit tests even started for the ibm i...

**Comment by WikiRik** [comment]
Unit tests are ran by the CI, using `yarn lerna run test-unit-ibmi --scope=@sequelize/core`. Integration tests are indeed not run since we as maintainers do not currently have access to an instance running IBM i

**Comment by rcronin** [comment]
With a change like this, is it the assumption I need to start creating the integration tests for this to get merged?

**Comment by WikiRik** [comment]
It would be nice if you could add a test so we can have an idea when this issue would occur and be fixed by this. Although we wouldn't actually be able to test it since we do not have access to an instance but we would at least have a general idea for the future

**Review by WikiRik — APPROVED** [review]

**Comment by WikiRik** [comment]
A test would have been nice, but I looked into it and it should be fine. Like I mentioned before; it's not like the test would get ran anyway

**Pull request merged**
