### PR TITLE
Task #5234 - remove old referenceKey code

### LINKED ISSUE #5234: Remove old references/referencesKey code

### PR DESCRIPTION
**Pull request by sushantdhiman**
Closes #5234

- Removed use of the old referenceKey code
- Removed test cases that use old reference code

### CODE REVIEW

**Comment by sushantdhiman** [comment]
@mickhansen @janmeier Please review

**Comment by mickhansen** [comment]
The diff is sort of muddled by the PR includng a bunch of merge/non-related commits.

**Comment by sushantdhiman** [comment]
Last two commits are what PR added, You can use github new comment switch to review separately OR you can update the v4.0.0 to current master. If you want I can resubmit by nuking all other commits

**Comment by mickhansen** [comment]
I'll look at commits for now, but we need a strategy for PRs that do not include a ton of commits from master.

Did you not fork of 4.0?

**Comment by sushantdhiman** [comment]
Yes I did forked from v4.0 but rebased it with master :), I will not include extra commits from now on.

**Comment by mickhansen** [comment]
Ah, let me rebase off master on v4.0.0 main, then you can rebase off of that.
Can you try rebasing this PR off of main v4.0.0 now and force push it?

**Comment by sushantdhiman** [comment]
I tried but it say Everything up-to-date, may be both commits at the HEAD are same

**Comment by sushantdhiman** [comment]
Ok I have amended the commit to generate different commit from current HEAD, its done now

**Comment by sushantdhiman** [comment]
Thank @mickhansen

**Pull request merged**
