### PR TITLE
fix: missing `raw` option in bulkCreate when using build method (v6)

### PR DESCRIPTION
**Pull request by fzn0x**
backport of #14699 for v6

### CODE REVIEW

**Comment by ephys** [comment]
Do the typings support this option?

**Comment by fzn0x** [comment]
Draft till the v7 port progress is stable

**Comment by ephys** [comment]
This PR points to v7, not v6

**Comment by fzn0x** [comment]
> This PR points to v7, not v6
> 
> I'm removing myself from the reviewer list but don't hesitate to re-request when this is ready

Looks like I will close this PR instead and creating a new one later

**Pull request closed without merging**
