### PR TITLE
fix(postgres): Support enum array

### PR DESCRIPTION
**Pull request by codemers**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

Currently when dealing with an array of enum using the Postgres dialect, Sequelize generates an invalid enumeration cast key while inserting data. 

Related issue (I think): https://github.com/sequelize/sequelize/issues/4048 

DDL of the table:

```
create table "Table"
(
    id uuid not null constraint "Table_pkey" primary key,
    "createdAt"      timestamp with time zone         not null,
    "updatedAt"      timestamp with time zone         not null,
    "deletedAt"      timestamp with time zone,
    column           "enum_Table_column"[] not null
);

```
DDL of the type 

```
create type "enum_Table_column" as enum ('Value1', 'Value2', 'Value3');
```

Then while inserting data here's the cast key generated by sequelize: 

```
array['Value1']::"enum_public.Table_Column"[]
```

The correct cast key should be:

```
array['Value1']::"enum_Table_Column"[]
```

This pr fixes this issue.

### CODE REVIEW

**Comment by sdepold** [comment]
@codemers Can you look into the tests and rebase your branch?

**Comment by sdepold** [comment]
Is this by any chance the same as https://github.com/sequelize/sequelize/pull/13807 ?

**Comment by sdepold** [comment]
cc @nahog

**Comment by nahog** [comment]
Yes, this is the same issue, but the PR here only works for public as is not passing the schema if its redefined, the #13807 fix handle both scenarios, when is using the public/empty schema, that both:
"enum_my_enum"[] and "public"."enum_my_enum"[] works
and the scenario where schemas are needed like:
"my_schema"."enum_my_enum"[]

@codemers try the current `main` branch (merged today) code to confirm the issue is fixed for you, but I think it is.

**Comment by nahog** [comment]
@codemers 6.12.2 was just released with a fix for this issue. Please try that version and if it works this bug can be probably closed.

**Pull request closed without merging**
