### PR TITLE
feat(postgres): change returning option to only return model attributes

### PR DESCRIPTION
**Pull request by Americas**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

If an underlying table has columns that don't exist in the model, when using `returning: true` the instance will be created with these extra attributes. This change alters this behavior to only return the fields defined in the model, provided a model definition is passed.

Note: this is a breaking change since the option `returning: true` will no longer create
attributes on the instance that are not defined in the model.

The old default behavior can be used by:

```diff
- returning: true
+ returning: ['*']
```

### CODE REVIEW

**Comment by sushantdhiman** [comment]
LGTM, This is a breaking change.

We have been planing to start work related to next major release. I think I'll have some time during weekend of 19-20th Oct. I'll start next beta cycle then and will include this change. Thanks

**Comment by TheOptimisticFactory** [comment]
## 01 - Issue

This appears to unfortunately break upsert feature of postgres.
In my case it fails with `SequelizeDatabaseError: invalid input syntax for integer: "2019-10-14 16:23:45.797+00"`

```javascript
const [ baseline ] = await db.session_users.findOrCreate({
    defaults: {
      start_at: moment.utc().toISOString(),
    },
    logging: console.log,
    where: {
      id_session: session.id_session,
      id_user: user.id_user,
    },
  });

//=========================
// OUTPUT FROM SEQUELIZE   
//=========================
 
Executing (95687979-1cf9-4c19-8d46-abe0ab0e706e): START TRANSACTION;

Executing (95687979-1cf9-4c19-8d46-abe0ab0e706e): SELECT 
  "id_session_user", "id_session", "id_user", "device_type", "start_at", "end_at", "state", "token", "active_time", "accept_recording", "created_at", "updated_at" 
  FROM "session_users" AS "session_users" 
  WHERE "session_users"."id_session" = 1 AND "session_users"."id_user" = 1 LIMIT 1;

Executing (95687979-1cf9-4c19-8d46-abe0ab0e706e): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "session_users", OUT sequelize_caught_exception text) 
  RETURNS RECORD AS $func_238212f3bd9f4e0c8b34e77774f9fd37$ 
  BEGIN INSERT INTO "session_users" ("id_session_user","id_session","id_user","start_at","state","active_time","accept_recording","created_at","updated_at") 
  VALUES (DEFAULT,1,1,'2019-10-14 16:23:45.794 +00:00','pending',NULL,NULL,'2019-10-14 16:23:45.797 +00:00','2019-10-14 16:23:45.797 +00:00')
  RETURNING "id_session_user","id_session","id_user","device_type","start_at","end_at","state","token","active_time","accept_recording","created_at","updated_at" INTO response; 
  EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_238212f3bd9f4e0c8b34e77774f9fd37$ LANGUAGE plpgsql; 
  SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();

Executing (95687979-1cf9-4c19-8d46-abe0ab0e706e): COMMIT;

//=========================
// OUTPUT FROM POSTGRES   
//=========================

2019-10-14 16:46:02.141 UTC [2900] ERROR:  invalid input syntax for integer: "2019-10-14 16:46:02.139+00"
2019-10-14 16:46:02.141 UTC [2900] CONTEXT:  PL/pgSQL function pg_temp_6.testfunc() line 1 at SQL statement
```

## 02 - Troubleshooting / fix

I haven't completely narrowed down why it does not work.

**BUT** I've noticed that enforcing the **return fragment** to equal `*` solves the problem :smiley: 

To do so, I've added `returnValues.query = 'RETURNING *';` here => https://github.com/sequelize/sequelize/pull/11526/files#diff-def52474024b12c7d133bb504cdf57d1R138

```javascript
//============================================
// OUTPUT FROM SEQUELIZE (with "RETURNING *")
//============================================

Executing (37209d5c-b8e2-42a1-af05-b718cde87431): START TRANSACTION;

Executing (37209d5c-b8e2-42a1-af05-b718cde87431): SELECT 
  "id_session_user", "id_session", "id_user", "device_type", "start_at", "end_at", "state", "token", "active_time", "accept_recording", "created_at", "updated_at" 
  FROM "session_users" AS "session_users" 
  WHERE "session_users"."id_session" = 1 AND "session_users"."id_user" = 1 LIMIT 1;

Executing (37209d5c-b8e2-42a1-af05-b718cde87431): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "session_users", OUT sequelize_caught_exception text) 
  RETURNS RECORD AS $func_ab6518d65b79441791ef8ccdbd4ec59d$ BEGIN INSERT INTO "session_users" ("id_session_user","id_session","id_user","start_at","state","active_time","accept_recording","created_at","updated_at") 
  VALUES (DEFAULT,1,1,'2019-10-14 16:49:29.275 +00:00','pending',NULL,NULL,'2019-10-14 16:49:29.277 +00:00','2019-10-14 16:49:29.277 +00:00')
  RETURNING * INTO response; 
  EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_ab6518d65b79441791ef8ccdbd4ec59d$ LANGUAGE plpgsql; 
  SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();

Executing (37209d5c-b8e2-42a1-af05-b718cde87431): COMMIT;
```

**Comment by TheOptimisticFactory** [comment]
Here is the model for full disclosure
```javascript
const SessionUsers = sequelize.define('session_users', {
    id_session_user: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    id_session: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    id_user: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    device_type: DataTypes.ENUM('web', 'ios'),
    start_at: DataTypes.DATE,
    end_at: DataTypes.DATE,
    state: {
      type: DataTypes.ENUM('declined', 'cancelled', 'joined', 'left', 'pending'),
      defaultValue: 'pending',
    },
    token: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    active_time: {
      allowNull: true,
      defaultValue: null,
      type: DataTypes.INTEGER,
    },
    accept_recording: {
      allowNull: true,
      defaultValue: null,
      type: DataTypes.BOOLEAN,
    },
    created_at: DataTypes.DATE,
    updated_at: DataTypes.DATE,
  }, {
    underscored: true,

    // WORKAROUND until https://github.com/sequelize/sequelize/issues/11225 gets fixed
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  });
```

**Comment by Americas** [comment]
@TheOptimisticFactory I'm going to need more information, because that query works for me. Postgres output shows no error, and the query returns the created or selected row as expected...

**Comment by TheOptimisticFactory** [comment]
> @TheOptimisticFactory I'm going to need more information, because that query works for me. Postgres output shows no error, and the query returns the created or selected row as expected...

Sure thing. I would be happy to help.
What additional information would you want to have?

**Comment by Americas** [comment]
Postgres version, is it running native or not? Do you have a migration for the table? Or did you create it using `sequelize.sync()`? Or better yet, can you show me the table schema?

**Comment by TheOptimisticFactory** [comment]
> Postgres version, is it running native or not? Do you have a migration for the table? Or did you create it using `sequelize.sync()`? Or better yet, can you show me the table schema?

#### Environment #####

- Node: `v12.11.1`, NPM: `v6.11.3`
- Using  **postgres** `v10` (docker image pulled from `library/postgres:10-alpine`)
- Using the dependencies **sequelize** `v5.19.0` modified with the diffs of this PR, along with **pg** `v7.12.1`

#### Context #####

- Models are deleted in cascade and migrations rerun from scratch prior to running my tests (`snippet n°1`)
- I cant disclose all migrations (97 files) but ultimately the model is exactly as shown in my previous comment: https://github.com/sequelize/sequelize/pull/11526#issuecomment-541806211
- You'll be able to find the table properties extracted from DBeaver in `snippet n°2`

### Snippet n°1 ###

```javascript
'use strict';

const path = require('path');
const Umzug = require('umzug');

const { database: db } = require('~API_SERVICES');

async function runMigrations() {

  await db.sequelize.drop({
    cascade: true,
  });

  const umzug = new Umzug({
    migrations: {
      params: [
        db.sequelize.getQueryInterface(),
        db.Sequelize,
      ],
      path: path.join(process.cwd(), './services/database/migrations/scripts'),
    },
    storage: 'none',
  });

  await umzug.up();
}

module.exports = runMigrations;
```

### Snippet n°2 ###

image

**Comment by Americas** [comment]
Still nothing...

Judging by the error context `pg_temp_6.testfunc()` do you have any triggers running on this table? or any sequelize hooks?

**Comment by TheOptimisticFactory** [comment]
> Still nothing...
> 
> Judging by the error context `pg_temp_6.testfunc()` do you have any triggers running on this table? or any sequelize hooks?

No trigger nor any sequelize hook. 

I have just made another discovery
- The diffs of this PR applied on top of sequelize `v5.19.0` throws the aforementioned error
- The diffs of this PR applied on top of sequelize `v5.19.6` works as expected :thinking:

**Comment by Americas** [comment]
I checked out to v5.19.0 and cherry-picked this commit on top of it. It had no issues running the `findOrCreate`. 

git log:
```
* 2d74388a - (HEAD) feat(postgres): change returning option to only return model attributes (48 minutes ago) <Ricardo Proença>
* 8b53f721 - (tag: v5.19.0) fix(showTablesQuery): ignore views for mssql/mysql (#11439) (4 weeks ago) <João Eiras>
```

**Comment by TheOptimisticFactory** [comment]
Nevermind, I am dumb. I am facing the issue using both `v5.19.0` and `v5.19.6` as baselines.
It is unrelated to the version

-- My stash diffs included the workaround `returnValues.query = 'RETURNING *';`. 
-- I have edited my previous comment to avoid any confusion

**Comment by TheOptimisticFactory** [comment]
Removing `created_at` and `updated_at` from the `RETURNING`-fragment makes the query work

The thing is another model with a similar `findOrCreate` call works without any `RETURNING`-fragment workaround :thinking:

**Comment by TheOptimisticFactory** [comment]
Enforcing `await db.sequelize.sync({ force: true });` prior to running the tests also makes the query work.

In the `snippet n°1` of this comment: https://github.com/sequelize/sequelize/pull/11526#issuecomment-542160326, I was using `db.sequelize.drop({ cascade: true })` to "reset" the database

Is there a difference I am missing between this operation and `db.sequelize.sync({ force: true })`?
Is it possible to log what operations Sequelize is running for a given model during sync?

**Comment by TheOptimisticFactory** [comment]
Adding an additional field after the table creation through a migration, seems to be the root cause of the error.

I suspect a mismatch between the order of returned columns and their value somehow

**Comment by Americas** [comment]
Yes, if I order the table as the diff, I get that error, hurray :smile:

**Comment by Americas** [comment]
This is a bigger bug related to the `exception` option, trying to run this with `returning: false` will throw in master. But it seems the fix is not too complex :smile:

**Comment by Americas** [comment]
@TheOptimisticFactory I fixed the issue with the insert while using option `exception: true` which is what happens on the `findOrCreate` method.

The only issue now is that if that option is true, it will return all the table's columns, so I'll have to fix that as well now :laughing: 

Can you confirm that this fixes your use case? It works for me.

**Comment by TheOptimisticFactory** [comment]
@Americas I am out of the office ATM. I will try your hotfix tomorrow first thing (CEST timezone) 😃

**Comment by TheOptimisticFactory** [comment]
> @TheOptimisticFactory I fixed the issue with the insert while using option `exception: true` which is what happens on the `findOrCreate` method.
> 
> The only issue now is that if that option is true, it will return all the table's columns, so I'll have to fix that as well now 
> 
> Can you confirm that this fixes your use case? It works for me.

I can confirm your hotfix did also fix the issue I was encountering! :tada:

**Comment by Americas** [comment]
Awesome! I'll update tests then, and fix this to return only model attributes as well.

**Pull request merged**
