### PR TITLE
meta: update comment in bug report template

### PR DESCRIPTION
**Pull request by WikiRik**
The inline comment () does not like it when there are two dashes which caused the comment to be rendered as normal text. This fixes that but unfortunately does space out the three points as separate paragraphs. So it's the lesser of two evils in my view

### CODE REVIEW

**Review by sdepold — APPROVED** [review]
Lgtm

**Comment by ephys** [comment]
Since the list isn't very long, maybe we could move all instructions before the list? It would solve the list being split into 3 lists

**Comment by WikiRik** [comment]
Sure I can do that

**Comment by bl0cknumber** [comment]
Or 

- Sequelize version: XXX
```sh
# run `npm list sequelize` or `yarn list --pattern sequelize` to obtain sequelize version
npm list sequelize # or
yarn list --pattern sequelize
```

- Node.js version: XXX
```sh
# run `node -v` to obtain Node.js version
node -v
```

- If TypeScript related: TypeScript version: XXX 
```sh
# run `npm list typescript` / `yarn list --pattern typescript` to obtain TypeScript version
npm list typescript # or
yarn list --pattern typescript
```

**Comment by ephys** [comment]
That would add a lot of noise to issues, and they're already noisy. I'd prefer this remained a comment

**Review by ephys — APPROVED** [review]

**Pull request merged**
