### PR TITLE
refactor: remove joinTableDependent exception for sqlite

### PR DESCRIPTION
**Pull request by adrienboulle**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This PR was initiated by this issue: https://github.com/sequelize/sequelize/issues/10126

When generating a through join SQL statement, an exception was done for SQLITE
At the time this was written, sqlite 3.8.9 was used, now it's 3.31.1

I've tested some sqlite versions to find what version introduced new feature / fixes that made this exception not necessary anymore.
It appears that since [sqlite v3.24.0](https://sqlite.org/changes.html) is used ([sqlite3 v4.0.1](https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#401)) added such feature

When using sqlite3 v4.0.1, almost all sequelize test passes, with sqlite3 v4.2.0 all passes

### CODE REVIEW

**Comment by adrienboulle** [comment]
@slickmb hi! would it be possible for you to have a look at this PR please ?

**Comment by adrienboulle** [comment]
@papb maybe you could have a look ?

**Comment by adrienboulle** [comment]
@papb sorry to insist, could you please have a look ?

**Comment by adrienboulle** [comment]
@Keimeno i see you are active on this repo, could you help me here, almost one year, not signe answer :/

**Comment by adrienboulle** [comment]
@sdepold rebased

**Comment by sdepold** [comment]
@adrienboulle I'm semi-confused what is happening here :) Are we removing support for SQLite or are we generalizing the code so that it also works for SQLite?

**Review by sdepold — APPROVED** [review]

**Comment by adrienboulle** [comment]
@sdepold I'm generalizing because now SQLite does support the join statement as every other SQL engine, so the exception is no longer needed

**Pull request merged**
