### PR TITLE
Fixed attribute:[] issues when using them in include or through

### LINKED ISSUE #4222: Bug with include query on many to many relationship
When you make a query on a table with a many to many relationship (i.e. belongs to many through), including the related model, using `attributes: []` causes an error.

We were using this feature to make queries based on conditions in the related model and previously this would prevent the related model from being hydrated.

Introduced between 3.0.0. and 3.1.1

Test case for the bug here:

```
sequelize.define('Cat', { name: Sequelize.STRING });
sequelize.define('Food', { title: Sequelize.STRING });
sequelize.define('CatFood', { type: Sequelize.STRING });

var db = sequelize.models;

db.Cat.belongsToMany(db.Food, { as: 'meals', foreignKey: { name: 'catId' }, through: 'CatFood' });

db.Cat.sync()
  .then(function() { return db.Food.sync(); })
  .then(function() { return db.CatFood.sync(); })
  .then(function() {
    return db.Food.create({ title: 'Miaow Mix' })
  })
  .then(function(food) {
    return db.Cat.create({ name: 'Fluffy' })
    .then(function(cat) {
      return cat.addMeal(food, { type: 'snack' });
    });
  })
  .then(function() {
    db.Cat.findAll({
      include: {
        model: db.Food,
        as: 'meals',
        attributes: []
      }
    });
  }).then(function(cats) {
    console.log(cats);
  });
```

Error is:

```
TypeError: Cannot set property 'CatFood' of undefined
    at groupJoinData (/.../node_modules/sequelize/lib/dialects/abstract/query.js:329:37)
    at AbstractQuery.handleSelectQuery (/.../node_modules/sequelize/lib/dialects/abstract/query.js:537:15)
    at Statement.<anonymous> (/.../node_modules/sequelize/lib/dialects/sqlite/query.js:93:33)
```

### LINKED ISSUE #4866: TypeError when using include[].through.where
A call to findAll that uses include[].through.where fails with a rejected promise: `TypeError: Cannot call method 'replace' of undefined`. Copying and pasting from the [StackOverflow question](https://stackoverflow.com/questions/33596558/nm-association-error-when-using-include-through):

```javascript
User.hasMany(Tag, {foreignKey: 'owner_id', foreignKeyConstraint: true});
Tag.belongsTo(User, {foreignKey: 'owner_id', foreignKeyConstraint: true});

Tag.hasMany(Transaction, {foreignKey: 'tag_id', foreignKeyConstraint: true});
Transaction.belongsTo(Tag, {foreignKey: 'tag_id', foreignKeyConstraint: true});

User.belongsToMany(Transaction, {through: {model: UserTx, unique: false}, foreignKey: 'user_id'});
Transaction.belongsToMany(User, {through: {model: UserTx, unique: false}, foreignKey: 'tx_id'});

// ...

Tag.findAll({
      where: { owner_id: userId }, // missing OR user_transaction.user_id = userId
      include: [{
        model: Transaction,
        attributes: ['id'],
        through: {model: UserTx, where: {user_id: userId}, attributes: ['user_id', 'tx_id']},
        where: {
          active: true
        },
        required: false, // include Tags that do not have an associated Transaction
      }]
})
```

Leads to:

```
Unhandled rejection TypeError: Cannot call method 'replace' of undefined
at Object.module.exports.removeTicks (/site/services/node_modules/sequelize/lib/utils.js:343:14)
at Object.module.exports.addTicks (/site/services/node_modules/sequelize/lib/utils.js:339:29)
at Object.QueryGenerator.quoteIdentifier (/site/services/node_modules/sequelize/lib/dialects/postgres/query-generator.js:843:20)
at generateJoinQueries (/site/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1207:72)
at Object.<anonymous> (/site/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1388:27)
at Array.forEach (native)
at Object.QueryGenerator.selectQuery (/site/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1387:10)
at QueryInterface.select (/site/services/node_modules/sequelize/lib/query-interface.js:679:25)
at null.<anonymous> (/site/services/node_modules/sequelize/lib/model.js:1386:32)
```

With some debugging on `s`, the column name attribute:

```
s = "Transactions"
s = "Transactions.id"
s = "Transactions.undefined" // should be Transactions.UserTx ?
s = "user_id"
s = "Transactions.undefined.user_id"
s = "Transactions.undefined"
s = "tx_id"
s = "Transactions.undefined.tx_id"
```

For a repro of this bug, see [here](https://github.com/cfogelberg/sequelize-playground/tree/master/tests/05-nm-through-error).

### LINKED ISSUE #5078: Hide eager loaded n:m associations
I have a requirement to get all "Roles" associated with a specified "User" where the output does not include any associations and restrictions added to the model definitions (e.g. not soft-deleted) should automatically be included in the generated SQL. 

I would have thought that the following code should have solved it for me;
```javascript
Role.findAll({
  include: [{
    model: User,
    where: { id: 1 },
    required: true,
    through: { attributes: [] },
    attributes: [],
  }]
}).then((instances) => {
    console.log(instances);
});
```
Maybe I am going about this the wrong way, but this results in:
```
'TypeError: Cannot set property \'User_Roles\' of undefined',
     '    at groupJoinData (d:\\test\\node_modules\\sequelize\\lib\\dialects\\abstract\\query.js:364:37)',
```

Going to query.js:364 and changing the line to: `if ($parent) $parent[$lastKeyPrefix] = resultMap[itemHash] = values;` solves it and I get the desired output as described below. 

Working code, but gives the wrong output:
```javascript
Role.findAll({
  include: [{
    model: User,
    where: { id: 1 },
    required: true,
    through: { attributes: [] },
    attributes: ['id'],
  }]
}).then((instances) => {
    console.log(instances);
});
```
Current output:
```javascript
[
  {
    "id": 1,
    "name": "Administrator",
    "createdAt": "2015-12-20T13:40:59.224Z",
    "updatedAt": "2015-12-20T13:40:59.224Z",
    "deletedAt": null,
    "Users": [
      {
        "id": 1
      }
    ]
  }
]
```
Desired output:
```javascript
[
  {
    "id": 1,
    "name": "Administrator",
    "createdAt": "2015-12-20T13:40:59.224Z",
    "updatedAt": "2015-12-20T13:40:59.224Z",
    "deletedAt": null
  }
]
```

Is there a better way of solving this that does not include modifying sequelize files? I thought of querying directly on Role, but I need the inner join to User using sequelize association to get an empty result when the User shouldn't be found (e.g is deleted.).

Edit: Using Sequelize v3.15.0

### LINKED ISSUE #5590: through: {attributes: []} does not remove attributes
Setting through attributes to [] doesn't exclude the id columns from being selected.

The model query:
```
componentsPromise = models.Component.findAll({
    include: [{
        attributes: [],
        model: models.Platform,
        through: {
            attributes: []
        },
        as: 'platforms',
        where: {
            id: {
                in: ids
            }
        }
    }],
    group: ['component.id'],
    having: ['COUNT(?) = ?', 'component.id', ids.length]
})
```
Defining the association:

```
Component.belongsToMany(Platform, {
    through: 'platform_components',
    as: 'platforms',
    foreignKey: 'component_id',
    otherKey: 'platform_id'
});

Platform.belongsToMany(Component, {
    through: 'platform_components',
    as: 'components',
    foreignKey: 'platform_id',
    otherKey: 'component_id'
});
```

The result query:
```
SELECT
  "component"."id",
  "component"."component_name",
  "component"."component_type",
  "component"."created_at",
  "component"."updated_at",
  "platforms.platform_components"."platform_id"  AS "platforms.platform_components.platform_id",
  "platforms.platform_components"."component_id" AS "platforms.platform_components.component_id"
FROM "components" AS "component" INNER JOIN
  ("platform_components" AS "platforms.platform_components" INNER JOIN "platforms" AS "platforms"
      ON "platforms"."id" = "platforms.platform_components"."platform_id")
    ON "component"."id" = "platforms.platform_components"."component_id" AND "platforms"."id" IN ('1', '2', '3')
GROUP BY "component"."id", "platforms.platform_components.platform_id", "platforms.platform_components.component_id"
HAVING COUNT('component.id') = 3;
```

This is a major problem in postgres, as this query will fail because the group by must include the through table primary keys, which subsequently makes the query not function.

### LINKED ISSUE #5958: Exception thrown when eager loading n:m association with `require: true` and `attributes: []`
I found a bug while trying to eager load a n:m association and using both `require: true` and `attributes: []` at the same time.

To reproduce please use the two following files : 

 - server.js for the code itself
 - package.json for Sequelize version and extra dependencies

Then simply `npm start`

Here is the server.js file :

```js
var _         = require( 'lodash' )
var fs        = require( 'fs' )
var sqlite3   = require( 'sqlite3' ).verbose();
var Sequelize = require( 'sequelize' )
​
​
const fileName = 'test.db'
​
var exists = fs.existsSync( fileName )
​
var db = new sqlite3.Database( fileName )
​
var orm = new Sequelize( 'database', 'username', 'password', {
  dialect: 'sqlite',
  storage: fileName
})
​
// table definitions
var News = orm.define( 'News', {
	title: {
      type: Sequelize.STRING( 128 ),
      allowNull: false
  	},
  	description: {
      type: Sequelize.STRING( 2048 ),
      allowNull: true
  	}
} )
​
var Tag = orm.define( 'Tag', {
	value: {
      type: Sequelize.STRING( 64 ),
      allowNull: false
  	},
  	description: {
      type: Sequelize.STRING( 256 ),
      allowNull: true
  	}
} )
​
// n:m association definition
News.belongsToMany( Tag, { through: 'news_tag' } )
Tag.belongsToMany( News, { through: 'news_tag' } )
​
// let's feed database with something :
orm.sync( {force: true} )
.then( afterSyncResult =>{
	return orm.Promise.all( [
		Tag.create( { value: 'Music' } ),
		Tag.create( { value: 'Sport' } ),
		Tag.create( { value: 'Canada' } ),
		Tag.create( { value: 'France' } ),
		News.create( { title: 'Euro is about to start and stades are not ready' } ),
		News.create( { title: 'Mainsquare festival will host Renaud this year' } ),
		News.create( { title: 'Next Devin Townsend album will be a musical' } ),
		News.create( { title: 'Golden Canada at hokey world championship !' } ) ] )
} )
.then( instanceArray => {
	// store those datas into dedicated maps :
	var tagsArray = instanceArray.slice( 0, 4 )
	var newsArray = instanceArray.slice( 4 )
​
	var tagMap = _.keyBy( tagsArray, e => e.value )
	var newsMap = _.keyBy( newsArray, e => e.title )
​
	// knit the relashionships :
	return orm.Promise.all( [
		// newsMap[ 'Euro is about to start and stades are not ready' ].addTags( [ tagMap.Sport, tagMap.France ] ),
		// newsMap[ 'Mainsquare festival will host Renaud this year' ].addTags( [ tagMap.Music, tagMap.France ] ),
		// newsMap[ 'Next Devin Townsend album will be a musical' ].addTags( [ tagMap.Music, tagMap.Canada ] ),
		newsMap[ 'Golden Canada at hokey world championship !' ].addTags( [ tagMap.Sport, tagMap.Canada ] ),
	] )
​
} )
.then( placeHolder => {
	// test a request that eager load all news been related to Sport or Canada tags but whithout loading any of the tags fields (attributes : []) :
	return News.findAll( {
		include: [ {
			required: true, // mixing required: true and attributes: [] lead to an exception
			model: Tag,
			attributes: [], // comment this line out and it will work fine
			where: {
				value: {
					$in: ['Sport', 'Canada']
				}
			}
		} ]
	} )
} )
.then( result => {
	console.log( "It's working !!" )
} )
.catch( err => {
	console.log( "It's NOT working :( ... reason :" )
	console.log( err )
} )
```

And here is the package.json file :

```json
{
  "name": "sequelize_bug_test",
  "version": "1.0.0",
  "description": "a project to test a sequelize bug",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "prewindebug": "start node-inspector",
    "postwindebug": "powershell -Command \"Get-WmiObject Win32_Process ^| where-object {$_.Name -eq 'node.exe' -and $_.CommandLine -match 'inspector.js'} ^| Stop-Process -id {$_.ProcessId}\"",
    "windebug": "nodemon --debug --harmony --throw-deprecation --use_strict server.js",
    "prewindebugbrk": "start node-inspector",
    "postwindebugbrk": "powershell -Command \"Get-WmiObject Win32_Process ^| where-object {$_.Name -eq 'node.exe' -and $_.CommandLine -match 'inspector.js'} ^| Stop-Process -id {$_.ProcessId}\"",
    "windebugbrk": "nodemon --debug-brk --harmony --throw-deprecation --use_strict server.js"
  },
  "author": "benoit lefevre",
  "license": "ISC",
  "dependencies": {
    "lodash": "^4.13.1",
    "sequelize": "^3.23.2",
    "sqlite3": "^3.1.4"
  }
}
```
## What do you expect to happen?
I expected that eager loading with `require: true` and `attributes: []` both set at the same time would work in order to simulate some kind of EXISTS behavior without having to use a raw query

## What is actually happening?
Using both of these options at the same time lead to an exception. `npm start` to reproduce it.

## Output :
it will output the exception and its call stack :

```text
C:\Dev\Project\nc\testBugSequlize\node_modules\sqlite3\lib\trace.js:28
                    throw err;
                    ^

TypeError: Cannot set property 'news_tag' of undefined
    at groupJoinData (C:\Dev\Project\nc\testBugSequlize\node_modules\sequelize\lib\dialects\abstract\query.js:364:37)
    at AbstractQuery.handleSelectQuery (C:\Dev\Project\nc\testBugSequlize\node_modules\sequelize\lib\dialects\abstract\query.js:658:15)
    at Statement.afterExecute (C:\Dev\Project\nc\testBugSequlize\node_modules\sequelize\lib\dialects\sqlite\query.js:178:33)
--> in Database#all('SELECT `News`.`id`, `News`.`title`, `News`.`description`, `News`.`createdAt`, `News`.`updatedAt`, `Tags.news_tag`.`createdAt` AS `Tags.news_tag.createdAt`, `Tags.news_tag`.`updatedAt` AS `Tags.news_tag.updatedAt`, `Tags.news_tag`.`NewsId` AS `Tags.news_tag.NewsId`, `Tags.news_tag`.`TagId` AS `Tags.news_tag.TagId` FROM `News` AS `News` INNER JOIN `news_tag` AS `Tags.news_tag` ON `News`.`id` = `Tags.news_tag`.`NewsId` INNER JOIN `Tags` AS `Tags` ON `Tags`.`id` = `Tags.news_tag`.`TagId` AND `Tags`.`value` IN (\'Sport\', \'Canada\');', [], [Function])
    at C:\Dev\Project\nc\testBugSequlize\node_modules\sequelize\lib\dialects\sqlite\query.js:241:36
    at Promise._execute (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:77:14)
    at executeSql (C:\Dev\Project\nc\testBugSequlize\node_modules\sequelize\lib\dialects\sqlite\query.js:103:19)
    at tryCatcher (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:628:18)
    at MappingPromiseArray.PromiseArray._resolve (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\map.js:97:18)
    at Promise._settlePromise (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:564:26)
    at Promise._settlePromise0 (C:\Dev\Project\nc\testBugSequlize\node_modules\bluebird\js\release\promise.js:604:10)
```

## Dialect & versions :
__Dialect:__ sqlite for ease of reproducing the bug but not relevant in that case
__Database version:__ not relevant
__Sequelize version:__ see the package.json file

## Notice
The code where the exception occurs been awfully complex and lacking of comments I can't help with any pull request.
On the other hand I think the previous sample code can be easily turned into a test

## Extra thoughts :
Would using `options.include[].separate: true` would cause extra troubles ?

### LINKED ISSUE #6139: Error when executing findAll query on entities associated by many-to-many relationship and specifying include.attributes = []
## What you are doing?
I'm trying to execute a query on an entity with a many to many relationship, including the related model and using attributes.

```js
// entityA definition
module.exports = function (sequelize, DataTypes, sanitize) {
	...
	var EntityA = sequelize.define('entityA', {
		// SOME PROPERTIES
		...
	},
	{
		paranoid: true,
      	classMethods: {
	        associate: function (models) {
	        	...
	          	EntityA.belongsToMany(models.entityB, {through: models.entityA_entityB});
	          	...
	        }
      	},
      	...
	});
	return EntityA;
};

// entityB definition
module.exports = function (sequelize, DataTypes) {
	...
	var EntityB = sequelize.define('entityB', {
		// SOME PROPERTIES
		...
	},
	{
      	paranoid: true,
      	classMethods: {
        	associate: function (models) {
        		...
          		EntityB.belongsToMany(models.entityA, {through: models.entityA_entityB});
          		...
      		}
        },
        ...
  	});
	return EntityB;
};

// entityA_entityB definition
module.exports = function(sequelize, DataTypes) {
  	return sequelize.define('entityA_entityB', {
    	// SOME PROPERTIES
    	...
  	},
  	{
    	paranoid: true
  	});
};

// Querying the entities
models.entityA.findAll({
	where: {
		id: {
			$ne: SOME_VALUE
		}
	},
    include: [{
    	model: models.entityB,
    	where: {
      		id: req.query.entityBId
    	},
    	attributes: ['id'], // MUST BE SPECIFIED FOR THE QUERY TO BE EXECUTED SUCCESSFULLY
    	through: {
      		where: {
        		status: {
          			$ne: 'SOME_VALUE'
        		}
      		},
      		attributes: []
    	}
  	},
  	{
    	// OTHER INCLUSIONS
    	...
  	}],
    attributes: ['id', 'some_other_attribute']
}).then(function (entitiesA) {
    return callback(null, entitiesA);
}, function (err) {
    return callback(err);
});
```

## Test case that reproduces the error

```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('DB_NAME, 'DB_USERNAME', 'DB_PASSWORD', {
  host: "DB_HOST",
  dialect: "mysql",
  logging: false,
  charset: "utf8",
  collate: "utf8_general_ci",
  pool: {
    maxIdleTime: 60000,
    minConnections: 0
  }
});

var EntityAEntityB = sequelize.define('EntityAEntityB', { type: Sequelize.STRING });

var EntityA = sequelize.define('EntityA',
  {
    name: Sequelize.STRING
  });

var EntityB = sequelize.define('EntityB',
  {
    name: Sequelize.STRING
  });

EntityA.belongsToMany(EntityB, {through: 'EntityAEntityB'});

EntityB.belongsToMany(EntityA, {through: 'EntityAEntityB'});

EntityA.sync()
  .then(function () { return EntityB.sync(); })
  .then(function () { return EntityAEntityB.sync(); })
  .then(function () {
    return EntityB.create({ name: 'My Entity B' });
  })
  .then(function (entityB) {
    return EntityA.create({ name: 'My Entity A' })
      .then(function (entityA) {
        return entityA.addEntityBs(entityB, { type: 'My type' });
      });
  })
  .then(function () {
    console.log('Running');
    EntityA.findAll({
      include: [{
        model: EntityB,
        attributes: [],
        // attributes: ['id'], // uncomment this and it will work!
        through: {
          attributes: []
        }
      }]
    }).then(function (entitiesA) {
      console.log('Entities A -> ', entitiesA);
      process.exit(0);
    });
  });
```

## What do you expect to happen?
I expect the query to be executed without having to specify the attribute 'id' in the include.attribute array.

## What is actually happening?
The findAll query fails with the following message:

Uncaught TypeError: Cannot set property 'entityA_entityB' of undefined
      at groupJoinData (node_modules/sequelize/lib/dialects/abstract/query.js:276:41)
      at AbstractQuery.handleSelectQuery (node_modules/sequelize/lib/dialects/abstract/query.js:583:15)
      at Query.formatResults (node_modules/sequelize/lib/dialects/mysql/query.js:73:19)
      at Query._callback (node_modules/sequelize/lib/dialects/mysql/query.js:37:22)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:531:20)

IMPORTANT NOTE:  I tried the findAll query mentioned above with different versions of Sequelize. This issue couldn't be reproduced from version 3.1.1 to version 3.11.0
When using version 3.12.0 the issue appeared. Versions above 3.12.0 and until 3.19.2 (included) were not tested. As mentioned below, the Sequelize version that I intend to use is 3.19.3

__Dialect:__ mysql
__Database version:__ 5.5.49
__Sequelize version:__ 3.19.3

### LINKED ISSUE #6242: How to prevent inner join when querying
Hi~
Two models is associated by `belongsToMany` function, eg: `Project.belongsToMany(User, { through: UserProject })` , I can get all user datas which are associated with the project by `project.getUsers()` . However, the join table will be selected by inner join at the same time. I hope to prevent that.
AnyOne, who can help me ? Thanks inadvance.

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Have you added an entry under `Future` in the changelog?

### Description of change

Using `through.attributes:[]` or `include.attributes: []` doesn't ignore any attributes, It throws error in most cases. Fixed it by checking if parent include exists before trying to push child include in it.

Closes #5078
Closes #4222
Closes #5958
Closes #5590
Closes #6139
Closes #4866
Closes #6242

### CODE REVIEW

**Comment by mickhansen** [comment]
`include.attributes: []` has always worked fine for me, did the unit test you added fail before applying fixes?

**Comment by mickhansen** [comment]
Ah i guess it might have failed specifically for N:M

**Comment by sushantdhiman** [comment]
`N:M with ignoring through.attributes only` worked before the fixes

**Comment by markdboyd** [comment]
Just want to say that this is awesome. Thanks so much!

**Comment by mickhansen** [comment]
@markdboyd master is gunning for 4.0, we have a lot of stuff on the roadmap though so might be a while

**Comment by markdboyd** [comment]
Got it. Thanks!

**Comment by felixfbecker** [comment]
@markdboyd I use [Sibell](https://sibbell.com/about/). You can of course also backport this to the v3 branch, there have not been many changes to the codebase so far besides ES6 refactoring.

**Comment by dodderjs** [comment]
Is it in the latest tag? 3.24.6 is not contain this commit.

**Comment by felixfbecker** [comment]
@dodderjs this has been merged into master, not v3.

**Comment by dodderjs** [comment]
Will it be merged into v3 at anytime? :)

**Comment by janmeier** [comment]
If anyone takes the time to backport, then yes :)

**Comment by Esya** [comment]
It seems this just "hides" the attributes but still gets them from the database.

For my use case, running on `master`, I have "User", "UserProject" and "Project".
When I do a `findAll` on `User`, with `include: Project` and specify some attributes for the `through` relationship, in the end **it appears to work**, my object only has the attributes I asked for if I do `User.toJSON().projects` for example.

But when I look at the SQL Query, it did query every attribute of the joint table. Is there any specific reason for that? In my use case the joint table is a bit heavy and I'm fetching quite a bit of data too, so querying one or two fields instead of 15 will have a high impact.

**Comment by felixfbecker** [comment]
@Esya at least the IDs are needed I think. But anything else of course is unneeded

**Comment by sushantdhiman** [comment]
@Esya  IIRC we at least need to query for Ids, rest we can ignore but haven'y tried, I guess required for populating the instances

**Comment by Esya** [comment]
I'm going to try to explicitly put the column names of the two Ids, but in
any case sequelize could and should figure out that the two keys are not
included and add those to the query, but not include the whole structure of
the join table, thoughts?

**Comment by Esya** [comment]
@felixfbecker @sushantdhiman I can confirm that I get the same behavior if I specify that I want the IDs in the attributes. 

Below is my scope, that should return the users, and each projects that the user is linked to, and for each User<->Project it should give me the startTime (when User started Project). It should **omit** all the other UserProject fields.

```
db.User.addScope('list', {
   attributes: ['id','name','firstname'],
   include: [{
     association: db.User.Projects,
     attributes: ['id','title'],
     through: {
       attributes: ['userId','projectId','startTime'],
     }
   }]
 });
```

What I get when doing `console.log(users[0].toJSON().projects)` looks fine (I only have `userId`,`projectId` and `startTime`), but I do see that Sequelize sent to postgres the full list of fields of the `UserProject` table. Am I missing something here?

**Comment by sushantdhiman** [comment]
@Esya we need to build the instances for all included and parent model so we have to query for all attributes. We can't have instances with missing data.

**Comment by felixfbecker** [comment]
@sushantdhiman I don't understand - isn't that exactly what `attributes` is for, omitting data?

**Comment by Esya** [comment]
Then why does the [documentation](http://docs.sequelizejs.com/en/latest/docs/associations/) mention that it's possible to do so ? 

> With Belongs-To-Many you can query based on through relation and select specific attributes

**Comment by Esya** [comment]
I went around the problem for my use case which is, defining the 3 schemas as usual, then : 

```javascript
UserProject.belongsTo(User)
UserProject.belongsTo(Project)
User.hasMany(UserProject)
Project.hasMany(UserProject)
```

Now if I do : 

```javascript
User.addScope('list', {
   attributes: ['id','name','firstname'],
   include: [{
     model: UserProject,
     attributes: ['startTime'],
     include: [{ model: Project, attributes: ['title']}]
   }]
 });
```

Then it works and Sequelize builds a sane query. I don't know how 2 hasMany + 2 belongsTo like that works better than belongsToMany, but that's a good workaround for me.

**Comment by rodrigoclp** [comment]
includeIgnoreAttributes: false, solves the problem in sequelize 4.

**Comment by rhietala** [comment]
> includeIgnoreAttributes: false, solves the problem in sequelize 4.

This is probably a workaround if you want to omit all attributes (i.e. `through: { attributes: [] }`), but will not solve the problem if you want to include only some attributes.

I have a use case where there are two user accounts to the same database with different privileges. The restricted account is not allowed to query all fields from the through-table, so querying will not work as I can't actually restrict the attribute querying.

This would be ideal but will *not* work:

```javascript
Course.belongsToMany(models.Period, { through: models.CoursePeriod });

Course.findAll({ include: [
  {
    model: db.models.Period,
    attributes: ['name'],
    through: {
        attributes: ['startdate', 'enddate']
      }
    ]
  }
]});
```

My workaround is basically the same as @Esya showed https://github.com/sequelize/sequelize/pull/6297#issuecomment-260604346 except that I cannot refactor the `belongsToMany` relation.

```javascript
Course.belongsToMany(models.Period, { through: models.CoursePeriod });
Course.hasMany(models.CoursePeriod, { as: 'CoursePeriod2' });

Course.findAll({ include: [
  {
    model: db.models.CoursePeriod,
    as: 'CoursePeriod2',
    attributes: ['startdate', 'enddate'],
    include: [
      {
        model: db.models.Period,
        attributes: ['name']
      }
    ]
  }
]});
```

I'm using sequelize v. 4.27.34

**Pull request merged**
