### PR TITLE
Hotfix

### PR DESCRIPTION
**Pull request by BridgeAR**

### CODE REVIEW

**Comment by mickhansen** [comment]
What does this fix exactly? findOne calls findAll

**Comment by mickhansen** [comment]
Nvm, i see it :)

**Comment by mickhansen** [comment]
Or no i still don't, findOne should still be passing the primitive to findAll which should fail. But i suppose more verbose error messages are still better.

**Comment by BridgeAR** [comment]
It did not fail :/
Am 29.05.2015 23:26 schrieb "Mick Hansen" <notifications@github.com>:

**Pull request merged**
