### PR TITLE
Evict stale connections

### PR DESCRIPTION
**Pull request by swordfish444**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

Adding a new option to `defaultPoolingConfig` for overiding the default _evictionRunIntervalMillis_ when instantiating connection pools using `node-pool`. You can see how evictions are never ran if this setting remains 0 https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L351

This PR is a bandaid for several recent "open" issues: https://github.com/sequelize/sequelize/issues/7884 and https://github.com/sequelize/sequelize/issues/7882 and possibly https://github.com/sequelize/sequelize/issues/7616

### CODE REVIEW

**Comment by swordfish444** [comment]
@felixfbecker It looks like you broke the CI with this commit https://github.com/sequelize/sequelize/commit/8d4700fba93530e15b459806cd5b5dc5c3024a17

Why are you commiting directly to master to begin with? This is extremely risky and is bound to cause friction with both new PRs and on-going releases.

**Comment by felixfbecker** [comment]
> Why are you committing directly to master to begin with? This is extremely risky and is bound to cause friction with both new PRs and on-going releases.

I didn't. I merged a PR (which is linked in the commit message, btw) from Greenkeeper that updates ESLint, was approved by two other maintainers, passed locally and on CI on multiple jobs on Travis. It failed then on AppVeyor, Node 4, Windows, because for whatever black magic [this line](https://sourcegraph.com/github.com/eslint/eslint/-/blob/lib/ignored-paths.js#L176-177) throws an error in that environment (but works on Linux Node 4, 6 and Windows Node 6). Excuse me for valuing my free time in that moment higher than the absolute certainty of something so unpredictable not happening.

**Comment by janmeier** [comment]
My comment is still pending, please add the option to the api docs :)

**Comment by felixfbecker** [comment]
Sorry for pinging you!

**Comment by swordfish444** [comment]
@janmeier Thanks for taking the time to review this PR and apologies for the lapse in time before addressing your feedback.

I've updated the api docs  in `lib/sequelize.js`. Are we clear to ship?

**Comment by euqen** [comment]
@sushantdhiman @janmeier Hi guys, can you please proceed with review, we need to merge it ASAP, otherwise we will need to downgrade sequelize version because of this issue: [sidorares/node-mysql2#447](https://github.com/sidorares/node-mysql2/issues/447)

**Comment by sushantdhiman** [comment]
@euqen I will do the merge once CI shows the green flag :)

**Comment by euqen** [comment]
@sushantdhiman great, thank you!

**Comment by sushantdhiman** [comment]
Failing MSSQL builds should now be fixed after https://github.com/sequelize/sequelize/commit/05f3c6d815d4e8cb0b98a8376af5941ffaf46d32

I have updated this branch, its pretty late here in India 23:51 :laughing: , so any one with merge rights should merge this branch as soon as it gets green.

**Comment by euqen** [comment]
@sushantdhiman thanks for merging. Can you please clarify for me when are you planning to create new release which includes this changes? Thanks

**Comment by dtjohnson** [comment]
Thanks for getting this released, but is this fix actually working for anyone else? The eviction scheduler doesn't seem to be getting called at all for me. I tracked it down to the `autostart: false` config setting on the pool on [line 113](https://github.com/sequelize/sequelize/blob/8de9a2735468442951428578962af36b05bd232e/lib/dialects/abstract/connection-manager.js#L113). From the pool [docs](https://github.com/coopernurse/node-pool) it seems this flag is necessary to start the pool automatically. The default behavior is true but this setting turns it off. If I change this to true it works as expected and evicts connections.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/8126 addresses this issue, but we cant just set `autostart: true`. AFAIR other dialect pool will be initialized, need to verify at least

**Comment by dtjohnson** [comment]
Looks like calling this will fix it in the meantime:
```js
sequelize.connectionManager.pool.start();
```

I'm seeing the connections get evicted as expected now.

**Comment by xdamman** [comment]
This will also solve https://github.com/sequelize/sequelize/issues/8133

(I'm also impacted by this using Sequelize 4.8.0 and Sequelize-cli 2.8.0)

**Comment by kchokhawala** [comment]
@dtjohnson : Man, you saved my life. Past 2 days I am was breaking my head over this. 
putting autostart: true in pool object, made it work smooth as I would love it to be. 

Thanks,

**Pull request merged**
