### PR TITLE
(#2964) - added test for findAll(), ordering by attribute of nested 1:1 association...

### PR DESCRIPTION
**Pull request by shaunerikson**
#2964

Wasn't able to get tests running on my (windows) machine...I am a relative noob.
I tried to quickly get things going with cygwin, no dice.  
Here's a test that I added to my fork, I hope that helps

### CODE REVIEW

**Comment by mickhansen** [comment]
Please don't create an additional test for this, add it to the existing test suite.

**Comment by mickhansen** [comment]
Next to this one: https://github.com/sequelize/sequelize/blob/master/test/include/findAll.test.js#L2134 perhaps

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/pull/2973/files
Why is there now 4K changes?

**Comment by mickhansen** [comment]
Also it appears the test case is passing now.

**Comment by shaunerikson** [comment]
I think all the changes are because my editor is using different tab/space
settings.  I just added that one test.  Do contributors standardize on
particular editor settings?

I think you can close the issue.  It seems to be fixed in rc8.  Sorry for
using your time on this.

On Wed, Jan 21, 2015 at 9:53 AM, Mick Hansen <notifications@github.com>
wrote:

> Also it appears the test case is passing now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/sequelize/pull/2973#issuecomment-70886611>.
>



-- 
Shaun

**Comment by mickhansen** [comment]
Yes we have a standardized editor setting :) 2 spaces per tabs.

**Pull request closed without merging**
