### PR TITLE
fix: Backport #9879 to v4

### PR DESCRIPTION
**Pull request by papandreou**
Cherry-pick of 27e449413d9fbf4a18e2438d0a97dc56fd466ae3 with some trivial `require` conflicts sorted out.

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Backport of #9879 to v4. I'm abusing CI to run the tests, as I don't have a working sequelize test setup locally.

### CODE REVIEW

**Comment by sushantdhiman** [comment]
This is a breaking change because error type returned in case of acquire timeout is changed, can't be backported

**Comment by papandreou** [comment]
I don't mind too much as we need to run a fork anyway, but that sounds like an overly strict interpretation of semver. I wouldn't consider a different error class being thrown as enough of a breaking change to delay an important fix to the next major release.

**Comment by sushantdhiman** [comment]
This is an important fix but returning different Error class entirely for some condition is definitely a breaking change. User could be catching old `TimeoutError` and retrying transactions.

There is still a way to make this change non breaking, you can just include `transaction.js` changes which prevent rollback in case of no connection. I'll happily merge that change :)

**Pull request merged**
