### PR TITLE
ES6 refactor: sequelize.js

### PR DESCRIPTION
**Pull request by felixfbecker**
see #6009

### CODE REVIEW

**Comment by janmeier** [comment]
LGTM

**Comment by mickhansen** [comment]
Appears to be an issue with where/or/and etc. They only exists as statics now and not on the instance aswell.

```
-Sequelize.where = Sequelize.condition = Sequelize.prototype.condition = Sequelize.prototype.where = function(attr, comparator, logic) {
+  static where(attr, comparator, logic) {
     return new Utils.where(attr, comparator, logic);
-};
+  }
```

**Comment by mickhansen** [comment]
```
- * sequelize.transaction().then(function (t) {
- *   return User.find(..., { transaction: t}).then(function (user) {
- *     return user.updateAttributes(..., { transaction: t});
- *   })
- *   .then(t.commit.bind(t))
- *   .catch(t.rollback.bind(t));
- * })
+   * sequelize.transaction().then(transaction =>
+   *   User.find(..., {transaction})
+   *     .then(user => user.updateAttributes(..., {transaction}))
+   *     .then(() => transaction.commit())
+   *     .catch(() => transaction.rollback());
+   * )
```

Should have a return statement (like we discussed).

**Comment by felixfbecker** [comment]
@mickhansen changed the arrow functions. The aliases are added [here](https://github.com/felixfbecker/sequelize/blob/es6-refactor-sequelize/lib/sequelize.js#L1176-L1185)

**Comment by mickhansen** [comment]
So they are, sorry about that, my diff thought it was done.

**Comment by mickhansen** [comment]
LGTM!

Will merge on green

**Pull request merged**
