### PR TITLE
Support `{ plain: true }` in typescript typings for sequelize.query

### LINKED ISSUE #11595: Typescript bindings incomplete when using `sequelize.query()`
###  Issue Description
It seems that the Typescript bindings are incomplete when using `.query()` with the `plain: true`.
It always returns an array of objects and doesn't take the `plain` option into account which should return a single row.

Adding the following typing resolves the issue but not entirely sure if it's the way to go.

```
public query<T extends object>(sql: string | { query: string; values: unknown[] }, options: QueryOptionsWithType<QueryTypes.SELECT> & { plain: true }): Promise<T>;
```

### What are you doing?

```js
const { count } = await sequelize.query(
    `
    SELECT COUNT(1) as count
    FROM foo f
    WHERE
      f.status = 'OK'
  `,
    {
      plain: true,
    },
  );
```

### What do you expect to happen?

The above query should return a single row and successfully destructure `count` from the single row that was returned using the `plain` option.

### What is actually happening?

Instead Typescript complains about the following:
`Property 'count' does not exist on type 'object[]'.`

### Environment

- Sequelize version: `5.21.1`
- Node.js version: `10.15.3`
- Operating System: `macOS Mojave`
- If TypeScript related: TypeScript version: `3.6.2`

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s):
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by segersniels**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Closes #11595

### Related PR's
- https://github.com/sequelize/sequelize/pull/11596

### CODE REVIEW

**Comment by papb** [comment]
It looks like I am not able to add commits on top of your branch. This never happened to me before, maybe you did not check the box 'allow edits from maintainers'? Or do you have any other idea what could be causing this?

Please apply the changes from the other PR yourself here then :) thanks!

**Comment by segersniels** [comment]
@papb I cherry-picked the required changes 🚀

**Comment by papb** [comment]
Thank you!! :tada:

**Pull request merged**
