### PR TITLE
Add hint about migrations section

### PR DESCRIPTION
**Pull request by azranel**
### Description of change

I was just browsing through documentation and it wasn't really too easy for me to find about migrations when I was in "Working with table schemas". So I just added a hint where user can read more about below functions since they don't link to

### CODE REVIEW

**Comment by sushantdhiman** [comment]
@janmeier will this generate correct link, I am not sure about MkDocs. Please review and merge

**Comment by azranel** [comment]
...why?

**Comment by sushantdhiman** [comment]
I am not familiar with MkDocs stuff, how it currently generates these link. @janmeier is familiar with that, will wait for him to review.

Can you link me to some resource which can tell me how the generated link will look like? Then I can do a merge myself

**Comment by azranel** [comment]
@sushantdhiman hey, sorry for such a long delay. Here you can see movie from mkDocs run localhost: https://monosnap.com/file/vicdNBgUyiQZfy0zrdFcI309ChOSrR . It generates correct link 😄

**Comment by janmeier** [comment]
Docs for v4 are not deployed to mkdocs currently though ;) - But I will add it to https://github.com/sequelize/sequelize/pull/7490

**Comment by janmeier** [comment]
So, turns out I removed this file completely in the PR because it was almost empty :)

**Pull request merged**
