### PR TITLE
V3 Fix sourceKey for hasMany, issue: #4258

### LINKED ISSUE #4258: targetKey for hasMany and hasOne
I have two legacy tables in a 1:m association:
**Property**(id, statistical_id, name, ...), **VisitorStats**(id, statistical_id, total, ...)

The following works:

`VisitorStats.belongsTo(Property, { foreignKey: 'statistical_id', targetKey: 'statistical_id'} );`

Then, in the controller, I can query for VisitorStats and eager-load the Property for it.

However, I want to query the Property table and include the VisitorStats model. For this, I would have to do a hasMany association, like this:

`Property.hasMany(VisitorStats, { foreignKey: 'statistical_id' });`

**hasMany's doesn't support the targetKey parameter option, and automatically joins VisitorStats.statistical_id on Property.id when I query.** I expected the targetKey property to work like at a belongsTo association.

Is it possible to change the target key using hasMany? If not, how should I represent this 1:m association?

### PR DESCRIPTION
**Pull request by Paxa**
_Thanks for wanting to fix something on Sequelize - we already love you long time! Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_If your PR only contains changes to documentation, you may skip the template below._
### Pull Request check-list

_Please make sure to review and check all of these items:_
- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Have you added an entry under `Future` in the changelog?

_NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open._
### Description of change

_Please provide a description of the change here._

Closes #4258

### CODE REVIEW

**Comment by Paxa** [comment]
Any chance it got accepted?

**Comment by felixfbecker** [comment]
It's still labeled as WIP? Also, tests are failing. Could you link the PR this is a backport for?

**Comment by Paxa** [comment]
@felixfbecker tests passed this time
Sorry forgot to remove WIP

**Comment by sushantdhiman** [comment]
@Paxa Please link or create the PR which add this fix to `master` as well. Only then we can merge this change to v3 :)

**Comment by garrypolley** [comment]
I may be misusing this PR. 

Should this work when using an `include`?  Given the example, I am attempting a query where I basically do: 

```
CountryModel(where={somestuff}, include=[{model: CityModel, where: {somecase}}])
```

It still seems to be querying on the primary key in this case. (it's possible my syntax is off above, but that is essentially what's happening in the end).

**Comment by Paxa** [comment]
Can anybody help me with this please?

**Comment by felixfbecker** [comment]
Is there a PR to master? Need that first before you can do a backport

**Comment by twolfson** [comment]
I have ported the changes over to `master` and opened a PR here:

https://github.com/sequelize/sequelize/pull/7113

**Comment by LoneWolfPR** [comment]
So, am I misreading this or is this basically ready to go into V3 except for a merge conflict in changelog.md?

**Comment by janmeier** [comment]
You are correct, thanks for bringing it up @LoneWolfPR  :)

Published in `v3.30.0` :tada:

**Comment by Paxa** [comment]
Thank you

**Comment by LoneWolfPR** [comment]
A million times thank you! This has made my life so much easier!

**Pull request merged**
