### PR TITLE
docs: clarify how the `limit` option works

### PR DESCRIPTION
**Pull request by ephys**
### Pull Request Checklist

- [x] Have you added new tests to prevent regressions?
- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

I'm attempting to clarify what `FindOptions#limit` does and its interaction with `FindOptions#subQuery`

Related to https://github.com/sequelize/sequelize/issues/9605

### CODE REVIEW

**Review by WikiRik — DISMISSED** [review]
Looks good. Just to check; do we have tests for these three examples to ensure that's the actual behavior?

**Comment by ephys** [comment]
We test for `limit + include` here: https://github.com/sequelize/sequelize/blob/main/test/unit/sql/select.test.js#L281
However we never test `limit + include + subQuery: false`. But we do it: https://github.com/sequelize/sequelize/blob/main/lib/dialects/abstract/query-generator.js#L1164

There is also an undocumented `groupedLimit` option, I'm not sure of what it does.

**Comment by ephys** [comment]
I've removed the third example I added as it's an unrelated limit option with a different behavior.

**Comment by WikiRik** [comment]
> However we never test `limit + include + subQuery: false`. But we do it: https://github.com/sequelize/sequelize/blob/main/lib/dialects/abstract/query-generator.js#L1164

Could you add tests for this?

**Comment by ephys** [comment]
Sounds good, I'll look into it :)

**Comment by ephys** [comment]
Test added

**Review by WikiRik — DISMISSED** [review]

**Review by WikiRik — COMMENTED** [review]
Woops, was too early with the approval. Do fix the mssql assertion first

**Comment by ephys** [comment]
That's weird. Why does mssql produce 
`ORDER BY [user].[last_name] ASC, [user].[id_user]` 
instead of 
`ORDER BY [user].[last_name] ASC`

it doesn't seem to be doing that in other queries or when `subQuery` is true

**Comment by ephys** [comment]
Ok it should be fixed

**Comment by ephys** [comment]
Not in this PR but we'll eventually get to it as we migrate to TS

**Pull request merged**
