### PR TITLE
Docs: Instance.{Model,sequelize} aren't functions

### PR DESCRIPTION
**Pull request by tremby**

### CODE REVIEW

**Comment by tremby** [comment]
Side question: should `Instance.Model` really have a capital M?

**Comment by sushantdhiman** [comment]
You will also have to update the actual comments from`/lib`, these files are auto-generated by `JS-Doc`

**Comment by tremby** [comment]
Ah, wasn't aware. I'll do that.

**Comment by sushantdhiman** [comment]
Also this may help, https://github.com/sequelize/sequelize/issues/4193, I was actually trying to fix this but our JS-Doc generation is a bit `custom` I think.

**Comment by tremby** [comment]
Ah, this isn't something I want to learn right now, then. I'll close this and comment on the other thread.

**Pull request closed without merging**
