### PR TITLE
meta: implement bug report form

### PR DESCRIPTION
**Pull request by ephys**
This PR replaces the current bug report template with a bug report form, to ensure users cannot bypass the template.

The result can be tested on https://github.com/ephys/sequelize-test/issues

The resulting markdown is not super pretty. I hope GitHub's form will support adding maintainer-defined markdown to the output

---

Screen Shot 2024-03-17 at 11 26 48

### CODE REVIEW

**Comment by WikiRik** [comment]
It's not the nicest, but we can make the 👍 comment a mandatory checkbox as well. At least it is then submitted

**Comment by ephys** [comment]
That would work

Alternatively https://github.com/sequelize/meetings/issues/36 (or both)

**Comment by WikiRik** [comment]
I was taking a look at the feedback submitted to GitHub, doesn't seem like there's a lot of priority for this exiting beta or improving behaviour. There's also no responses on the discussion of 7 months back where they asked for explicit feedback on issue forms (a feature that's now been in beta for almost three years).

Especially we need to see what happens if people want to update their issue after submitting, since that will not change if we use issue forms. Once it's submitted, it's just a regular issue again. Does the guiding markdown get added as comments in the issue still?

**Comment by ephys** [comment]
Sadly it does not. All instructions are removed. Basically only the title of the input and the value are outputted

**Comment by ephys** [comment]
By this way this is PR is a proposal so I have no issues with dropping this if the output is not satisfactory

**Comment by WikiRik** [comment]
Personally I'd hold off from implementing this for now. Once GitHub improves this feature we can look into it again

**Pull request closed without merging**
