### PR TITLE
static dialect requires. Fixes #4517

### LINKED ISSUE #4517: Make Dialect Requiring Static
### The bundling applications fail to include the dialects.

[The Code](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L179):
```js
try {
    var Dialect = require('./dialects/' + this.getDialect());
    this.dialect = new Dialect(this);
  } catch (err) {
    throw new Error('The dialect ' + this.getDialect() + ' is not supported. ('+err+')');
  }
```
This would better be handled with a switch case:
```js
try {
    var Dialect;
    swtich(this.getDialect())
    {
         case '...':
             Dialect = require('./dialects/...'); break; 
         .
         .
         .
    }
    this.dialect = new Dialect(this);
  } ...
```

This isn't so hard to fix, should I make a pull request? or do you guys have time yourselves to fix this? ^^

### PR DESCRIPTION
**Pull request by subjectix**
I couldn't run the tests, I would appreciate it if someone does it.

### CODE REVIEW

**Comment by janmeier** [comment]
Thanks :)

**Comment by subjectix** [comment]
You are welcome ^^

**Comment by mickhansen** [comment]
Published in 3.9.0

**Comment by yonjah** [comment]
@alitaheri Wondering if this still being used.
Seem a bit like a hack that should have been solved by Browserify either by offering some kind of
config option or partly parse those dynamic properties (Webpack seem to solve this)

**Pull request merged**
