### PR TITLE
feat: stop testing against TypeScript < 4.4

### PR DESCRIPTION
**Pull request by ephys**
TypeScript 4.2 has been out for a little over a year now.

Based on our policy that offers one year of support for a given TypeScript version, we can now stop testing against TypeScript 4.1 & 4.2.

We now only officially support TypeScript 4.4, 4.5, and 4.6

### CODE REVIEW

**Review by WikiRik — APPROVED** [review]

**Comment by WikiRik** [comment]
Did we document somewhere that we support 4.1 and up?

**Comment by ephys** [comment]
yes, in the typescript documentation, I'll update that too :)

**Comment by ephys** [comment]
Updated

**Review by WikiRik — APPROVED** [review]

**Comment by ephys** [comment]
Dropped 4.3 too as per https://github.com/sequelize/sequelize/pull/14022#issuecomment-1056848886 as v7 is not planned to be released before may

**Comment by ephys** [comment]
Done :)

**Comment by WikiRik** [comment]
Thanks!

**Pull request merged**
