### PR TITLE
Add support for keyword `after` in options of a field

### PR DESCRIPTION
**Pull request by sitexw**
Add support for keyword `after` in options of a field (useful for migrations), only for MySQL.
And add unit test.

### CODE REVIEW

**Comment by sitexw** [comment]
Up

**Comment by mickhansen** [comment]
@sitexw can you do a rebase?

**Comment by sitexw** [comment]
I can not make the rebase, can you give me quickly what to do?

**Comment by mickhansen** [comment]
@sitexw https://help.github.com/articles/about-git-rebase/

**Comment by mickhansen** [comment]
ping @sitexw

**Comment by sitexw** [comment]
`Reply from @mickhansen: bytes=32 time=50400000ms TTL=56`

Hi, I'm sorry but I have not managed / understood why we must make a rebase. But also, what I have to commit to change.

**Comment by mickhansen** [comment]
@sitexw You have to rebase so i can merge it. The branch is out of sync with master.

**Comment by BridgeAR** [comment]
@sitexw 

0) git fetch upstream
1) git rebase --interactive #lastestMasterCommitHash#
2) Pick your commit
2.1) Resolve possible conflicts
2.1.1) git add --all .
2.1.2) git rebase --continue
3) git push -f

Done

**Comment by keithvsr** [comment]
This change doesn't add support in "options" of a field, it adds to "attributes", causing a clash with the queryInterface API documentation (https://sequelize.org/api/v6/class/src/dialects/abstract/query-interface.js~queryinterface#instance-method-addColumn) which in the example shows "after" as a key within "options" when it's actually within "attributes"

I think it makes sense to keep it as a column attribute, but the docs should match to avoid confusion. This example:
```
queryInterface.addColumn('tableA', 'columnC', Sequelize.STRING, {
    after: 'columnB' // after option is only supported by MySQL
});
```

should probably look like this instead:
```
queryInterface.addColumn('tableA', 'columnC', {
    type: Sequelize.STRING,
    after: 'columnB' // after option is only supported by MySQL
});
```

**Pull request closed without merging**
