### PR TITLE
Eliminate random MSSQL build failures

### PR DESCRIPTION
**Pull request by Uko**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

Looks like the mssql docker image has a weird behaviour when you can't connect to the DB after stratup. The solution in the PR is to run the creation of the MSSQL test DB inside the health check command.

### CODE REVIEW

**Comment by Keimeno** [comment]
Possibly related: https://github.com/Microsoft/mssql-docker/issues/203

**Comment by Uko** [comment]
@Keimeno thanks a lot!!!

**Comment by Keimeno** [comment]
This issue first occurred [here](https://github.com/sequelize/sequelize/runs/2262841241?check_suite_focus=true) 9 days ago, from a commit that changed GitHub actions.

My guess would be that this might be a caching problem, or the commit triggered an update of `mssql` onto a newer version.

**Comment by Uko** [comment]
I'm not an expert in containers, but from my experiments, it seems that if the DB creation script fails once, it will also fail on the following retries. On the other hand, the jobs never failed when I created the DB in the health-check script.

One person mentioned that SQL commands should be done from the same layer where you start the server https://github.com/microsoft/mssql-docker/issues/203#issuecomment-623470495. Maybe we need a custom image that creates the DB on startup?

**Comment by Uko** [comment]
@Keimeno I don't see how the task from the commit that you referenced can impact the mssql builds. I also tried to rollback those changes, and that didn't help

**Comment by Keimeno** [comment]
I don't think that the changes itself changed something about the pipeline, I think the changes triggered something within GitHub pipelines to either clear the cache everywhere and/or update the mssql servers

**Review by Keimeno — APPROVED** [review]

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

**Comment by papb** [comment]
Thanks for looking into this... Indeed this is super crazy. Isn't it a little dangerous to do this in the healthcheck script, though? The health check is something that I'd expect to execute many times, to keep checking the health, so it seems bad to try to put code there that was supposed to only execute once. Thoughts?

I noticed in the issue linked by @Keimeno (thank you!) that some people seem to have gotten away with it with a sleep, maybe we could wrap that `/opt/mssql-tools/bin/sqlcmd` call retrying it a few times if it fails, with `sleep 2` in between or something?

**Comment by papb** [comment]
Also, there was a mistake with the healthcheck command that I fixed after this PR was opened: https://github.com/sequelize/sequelize/commit/830909244e02ff7e0ddaa31166462a30d1f09ec6#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR158

It's probably the cause of the current conflict. Maybe it was just that? To be honest I have no idea how it could be even working before I made the above fix.

**Pull request closed without merging**
