### PR TITLE
fix(types): export `GroupedCountResultItem` interface

### PR DESCRIPTION
**Pull request by emilio-notable**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [x] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change
Needed to use this type but it wasn't exported. And since the rest of the types are, it feels like it would be more consistent to also export this one

### CODE REVIEW

**Review by ephys — APPROVED** [review]

**Comment by ephys** [comment]
Thank you for your PR. LGTM :)

@emilio-notable the branch is out of date, can you allow maintainers to add commits to your branch? This way I can sync the branch before merging

**Review by WikiRik — APPROVED** [review]

**Comment by emilio-notable** [comment]
> Thank you for your PR. LGTM :)
> 
> @emilio-notable the branch is out of date, can you allow maintainers to add commits to your branch? This way I can sync the branch before merging

@ephys sorry, i'm not seeing the option to allow maintainers to add commits. Maybe that's because i mistakenly opened the PR with a different user than the fork owner (my bad)?

I just rebased the branch onto main. Let me know if that's good enough, or if you prefer i can close this PR and open it again with the same user as the fork, and hopefully it lets me allow maintainer commits, or let me know if there's another way to allow maintainer commits

**Comment by WikiRik** [comment]
> > Thank you for your PR. LGTM :)
> > @emilio-notable the branch is out of date, can you allow maintainers to add commits to your branch? This way I can sync the branch before merging
> 
> @ephys sorry, i'm not seeing the option to allow maintainers to add commits. Maybe that's because i mistakenly opened the PR with a different user than the fork owner (my bad)?
> 
> I just rebased the branch onto main. Let me know if that's good enough, or if you prefer i can close this PR and open it again with the same user as the fork, and hopefully it lets me allow maintainer commits, or let me know if there's another way to allow maintainer commits

That might be the case but it's all good. Your rebase is good enough, I will merge this as soon as the checks pass.

**Comment by ephys** [comment]
thanks :)

**Pull request merged**
