### PR TITLE
Add Postgres inheritance

### PR DESCRIPTION
**Pull request by fixe**
Concept only. Refs #1679.

@mickhansen, @janmeier is this something that you guys are willing to merge?

### CODE REVIEW

**Comment by fixe** [comment]
@mickhansen, @janmeier is this something that you guys are willing to merge?

**Comment by janmeier** [comment]
Yep, this sounds like a reasonable approach. We would probably need to support the `ONLY` keyword in the relevant methods to exclude child tables

**Comment by mickhansen** [comment]
Application-level attribute inheritance for other dialects and real `INHERITS` for postgres.
That might make sense, but doesn't postgres inheritance actually support selecting parent table to get all children (with shared attributes)?

**Comment by janmeier** [comment]
Yeah without the `ONLY` keyword it willl return rows from both parent and child tables - but since we always qualify the attributes in selects, it shouldn't be a problem attribute wise. 

Of course the behaviour would be different between postgres and other dialects then, which would not be great :(

**Comment by mickhansen** [comment]
Having `only` be the default and supported a children select with joins for other dialects could work in the future.

**Comment by janmeier** [comment]
PR CLEANUP: No response for a _long_ time

**Pull request closed without merging**
