### PR TITLE
Add support for multiple databases

### PR DESCRIPTION
**Pull request by ackerdev**
Matt originally wrote these changes for MSSQL multiple catalog support at my request.

It is not 100% functional. Some meta queries may not support multiple databases or may be outright broken.

I cannot further this work myself, so I am offering it in the state that mbroadst left it so that maybe someone can give it the love it needs and help it get integrated, and I can stop maintaining it myself. :smile:

### CODE REVIEW

**Comment by janmeier** [comment]
Unfortunately no-one took up the task :(

**Comment by alexraju** [comment]
@janmeier  This is a much essential feature. Even though I have separate connection, when I do join between tables from different databases, db name is getting appended before the table name causing query to fail. If you could get some priority to this, It will be great. 

It would be great if you could assign someone to this task.

**Comment by mickhansen** [comment]
@alexraju The someone who have to be either me or @janmeier, since we can't really assign anyone from the community (for a lot of reasons).

We've had very few requests for this so whether or not it's essential is highly debateable.
If it's highly essential to you, you can help contribute (that's how me and @janmeier even got started contributing to Sequelize)

**Comment by AckerApple** [comment]
@alexraju We still use the @ackerdev forked version that has Sequelize multidatabase support. The forked version is 3.13 and the current version is 3.23 . The multi database support works great for all general purpose CRUD functionality. This branch as seen above: https://github.com/ackerdev/sequelize/tree/multiple-databases

**Pull request closed without merging**
