### PR TITLE
feat: drop support for Node 14 and add for Node 20

### PR DESCRIPTION
**Pull request by WikiRik**
## Pull Request Checklist

- [X] Have you added new tests to prevent regressions?
- [X] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

This PR drops the support for Node 14 since it's been EOL since eind of April 2023.
In related news, Node 20 testing will be added when Node 20 is in LTS.

Unblocks #15928

## Commit message

```

BREAKING CHANGE: Sequelize now requires Node >=16.0.0
```

### CODE REVIEW

**Review by ephys — APPROVED** [review]

**Comment by ephys** [comment]
@WikiRik small conflict :(

**Review by ephys — APPROVED** [review]

**Comment by ephys** [comment]
Uh, the merge queue does not let us change the merge description to include the `BREAKING CHANGE` tag (not all config generators support !, I hope lerna does)

**Comment by WikiRik** [comment]
I also forgot to include the breaking change tag, so we should indeed merge this manually

**Comment by ephys** [comment]
That means we need to disable the merge queue to merge this PR / https://github.com/orgs/community/discussions/15925

**Comment by WikiRik** [comment]
When we merge this, we need to update the required checks as well

@ephys how did you get the commit body in the mariadb connector upgrade merge? Did you disable the merge queue temporarily in the settings?

**Comment by ephys** [comment]
While doing this, should we set the latest node version to 20 in the same PR?

**Comment by ephys** [comment]
Sorry I did not see that
We added support for 18 in May to be ready by the time it becomes LTS (https://github.com/sequelize/sequelize/pull/14415)

**Comment by WikiRik** [comment]
Ah, I see. I wanted to wait, but in the end we didn't. I'll add Node 20 here as well then

**Comment by ephys** [comment]
Ok!

**Review by ephys — DISMISSED** [review]

**Comment by WikiRik** [comment]
Okay, nevermind. It didn't complain about dependencies so I changed it here

**Review by ephys — APPROVED** [review]

**Pull request merged**
