### PR TITLE
docs(query-interface): add inline 'bulkUpdate' docs

### PR DESCRIPTION
**Pull request by c-moss-talk**
Adds missing documentation on 'bulkUpdate' inline at query-interface.js. Addresses https://github.com/sequelize/sequelize/issues/8820

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Thanks @c-moss-talk

**Comment by jeanmarcprevost** [comment]
I don't understand the documentation...
```@param {Object} identifier    A hash with conditions OR an ID as integer OR a string with conditions```

**Comment by sushantdhiman** [comment]
`where` conditions

```js
{
   name: "ABC",
   [Op.and]: [ .... ],
   ....
}
```

**Comment by c-moss-talk** [comment]
Yeah, that's a hash example, but actually I tried to use and ID as integer and it resulted in unexpected behavior. I want to look into it.

**Comment by jeanmarcprevost** [comment]
Oh yes thank @sushantdhiman !

**Pull request merged**
