### PR TITLE
fix(mssql/async-queue): fix unable to start mysql due to circular ref

### PR DESCRIPTION
**Pull request by zorji**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Fix unable to start mysql docker in test due to circular reference

Why this happen? Because on this line, it attempts to export an Error that's outside `errors` dir and this outside AsyncQueueError has circular reference to `errors/index.ts`

https://github.com/sequelize/sequelize/blob/8cdce6aeb32b09e4bc1359250efcfacc6742501f/lib/errors/index.ts#L36

It's a bit weird to me that `errors/index.ts` attempts to expose an Error that's outside this dir, maybe it shouldn't do it in the first place but removing it will be a breaking change so I'll not change it in this PR. Taking it out requires a different discussion.

#### Steps to reproduce

Node: v14.18.1

run the follow command
```
npm run start-mysql 
```

and received the following error
```
class AsyncQueueError extends import_errors.BaseError {
                                            ^

TypeError: Class extends value undefined is not a constructor or null
```

### CODE REVIEW

**Comment by WikiRik** [comment]
Thanks for the Pull Request! Are there any tests that we can add to this?

**Comment by sdepold** [comment]
Hm. I just started the MySQL setup and it worked perfectly fine. Will have another look tomorrow

**Comment by sdepold** [comment]
```[main][~/Projects/sequelize]$ node -v
v14.18.1
[main][~/Projects/sequelize]$ yarn build
yarn run v1.22.17
$ node ./build.js
Compiling sequelize...
✨  Done in 1.86s.
[main][~/Projects/sequelize]$ yarn start-mysql
yarn run v1.22.17
$ bash dev/mysql/5.7/start.sh
++ dirname -- dev/mysql/5.7/start.sh
+ cd -P -- dev/mysql/5.7
+ docker-compose -p sequelize-mysql-57 down --remove-orphans
Removing network sequelize-mysql-57-network
WARNING: Network sequelize-mysql-57-network not found.
+ docker-compose -p sequelize-mysql-57 up -d
Creating network "sequelize-mysql-57-network" with the default driver
Creating sequelize-mysql-57 ... done
+ ./../../wait-until-healthy.sh sequelize-mysql-57
sequelize-mysql-57 is healthy!
+ docker exec sequelize-mysql-57 mysql --host 127.0.0.1 --port 3306 -uroot -psequelize_test -e 'GRANT ALL ON *.* TO '\''sequelize_test'\''@'\''%'\'' with grant option; FLUSH PRIVILEGES;'
mysql: [Warning] Using a password on the command line interface can be insecure.
+ node check.js
+ echo 'Local MySQL-5.7 instance is ready for Sequelize tests.'
Local MySQL-5.7 instance is ready for Sequelize tests.
✨  Done in 20.71s.```

**Comment by sdepold** [comment]
That is on master. Not sure if we need to fix anything?!

**Comment by joaoe** [comment]
If `lib/errors/index.ts` must have `AsyncQueueError ` then that class should move to the errors or dialect/abstract folders. Doesn't make sense to expose something that is dialect specific to the rest of the world.

**Comment by joaoe** [comment]
> Thanks for the Pull Request! Are there any tests that we can add to this?

Well, the test is that sequelize can be imported and runs :) Because a circular ref breaks everything. I'm not sure how this kind of error was merged to the main branch undetected.

**Comment by sdepold** [comment]
As much as I cannot reproduce this issue, I think the change makes sense in general

**Review by sdepold — APPROVED** [review]

**Comment by sdepold** [comment]
Released in 6.12.4

**Comment by zorji** [comment]
Hi @sdepold @joaoe 

Merry Xmas! Thanks for reviewing this PR.

I did notice the build did not fail in CI but I didn't have much time to investigate further.

I tried again today I notice I can reproduce the error with `npm install` but I couldn't reproduce with `yarn`.

Then I think it's an issue with lock file because there isn't an `package-lock.json` so all packages installed by `npm` are latest.

Then I tried to upgrade `typescript` and `esbuild` and found I can reproduce it with latest `esbuild@0.14.9` and might be related to this reported issue. https://github.com/evanw/esbuild/issues/1427

To reproduce with npm

```
rm -rf node_modules
git checkout 0a4fbb0^ # << the commit before mine
npm i
npm run build
npm run start-mysql
node dev/mysql/5.7/check.js
```

To reproduce with yarn

```
rm -rf node_modules
git checkout 0a4fbb0^ # << the commit before mine
yarn
yarn add esbuild@latest
yarn build
yarn run start-mysql
node dev/mysql/5.7/check.js
```

**Comment by joaoe** [comment]
> Merry Xmas! Thanks for reviewing this PR.

Likewise.

> Then I tried to upgrade `typescript` and `esbuild` and found I can reproduce it with latest `esbuild@0.14.9` and might be related to this reported issue. [evanw/esbuild#1427](https://github.com/evanw/esbuild/issues/1427)

Right. That is what I did, `npm install`. The newer esbuild also caused another [problem with exports](https://github.com/sequelize/sequelize/issues/13791#issuecomment-1001785866).

Cheers.

**Comment by sdepold** [comment]
Cash you confirm that it works in the new version?

**Comment by zorji** [comment]
> Cash you confirm that it works in the new version?

Yes, the change in this PR works with the new version.

**Comment by sdepold** [comment]
Sweet

**Pull request merged**
