### PR TITLE
feat: add typescript typings

### LINKED ISSUE #9285: Ship official TypeScript typings
I'd really recommend converting the src to TS. You will def catch a few bugs and will help make the lib maintainable over the long-haul.

If you haven't written a lib in TS before - it's easy to convert since you can convert gradually, don't have to convert to TS all at once.

### PR DESCRIPTION
**Pull request by SimonSchick**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [?] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Closes #9285

TODO: Documentation?

Please note that these typings are based on https://github.com/types/sequelize but have been heavily modified and updated for v5 use by me.

These typings are generally not compatible with the current DT typings as they are considered incomplete and outdated (no class support etc).

I'd ask like to ask types/sequelize contributors:
@felixfbecker
@louy
@eseliger
@ppetzold
@prokopsimek
@lumaxis
@C45tr0
@d6u
@modulitos
@rokoroku
@MorpheusXAUT
@SwadicalRag
@JD-Robbs
@munsellj
@Thylossus

And DT contributors:
@samuelneff
@codeanimal
@drinchev
@babolivier
@kukoo1
@oktapodia
@morpheusxaut
@TitaneBoy
@zjy01
@nidzov
@Raigen
@todd
@nrschultz
@thomas-b
@Antoine38660
@smff

to leave feedback on this PR

@felixfbecker @louy as you are core authors of `types/sequelize`, do you have any concerns regarding the licensing?
Currently your `package.json` only specifies `ISC` without a license file which is generally compatible with the `MIT` license of sequelize.

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Is this ready or still under WIP @SimonSchick ?

**Comment by SimonSchick** [comment]
@sushantdhiman I was hoping for some feedback, I highly doubt that this PR is ready as is.
Unfortunately none of the people I mentioned replied.

I'm not exactly sure what to add in terms of documentation.
In particular the licensing still needs to be figured out.

**Comment by drinchev** [comment]
Unfortunately I'm not using sequelize at the current project I'm working on and the last one is with outdated typescript version. Saying this it is really difficult for me to test the PR.

Anyway the definition file for sequelize is somehow a different program ( e.g. `BelongsToGetAssociationMixin` are not part of sequelize, but just a helper to make your code easier to read ), so it is as well opinionated and not 1:1 to the code base. For me this always meant that there is a need to have additional docs on the project website how to use the typings.

Thanks guys for adding the definition files to the project. 👍

**Comment by todd** [comment]
Link to the DT test file: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/sequelize-tests.ts

Moment did something similar after an errant typo broke their declaration files:
Discussion: https://github.com/moment/moment/pull/3280
Work: https://github.com/moment/moment/pull/3282

**Comment by SimonSchick** [comment]
@todd I already added test files?

**Comment by todd** [comment]
@SimonSchick Oh, yikes - I clearly didn't do a deep dive on the changes in this PR 😆 

If the tests pass, I assume that's probably good enough to get started, at least for pre-5.0. But, again, I'll try to put the code in this PR through its paces in the next couple of days and see if I run across anything.

From a purely pragmatic standpoint, I might recommend contributing these changes to Types or DT for 5.0 before adding them directly to this package. Not sure if we're worried about churn, but the DT declaration files see somewhat consistent changes and updates (maybe ~2-3 PRs/month on average). Totally up to you guys, though.

**Comment by C45tr0** [comment]
I would love to have these definitions inside of the primary repo. I find they stay in sync easier that way. Thanks for starting this! 

@SimonSchick Was wondering why remove the `Utils.sliceArgs` inside of this pr and not a separate PR? 

Also, I'll try and take a look at these this weekend also. Looking to use v5 in my next project anyway.

**Comment by SimonSchick** [comment]
sliceArgs slipped into this PR, if that's an issue I will revert that.

**Comment by SimonSchick** [comment]
Removed WIP tag for now, I have not really gotten any feedback but I've been using these typings in a few projects and they seem pretty stable.

**Comment by rokoroku** [comment]
We can improve typings after it ships to the npm prerelease or release, integrating with real projects.

**Comment by sushantdhiman** [comment]
@SimonSchick Great work :100:

**Comment by SimonSchick** [comment]
Oh boy.

**Comment by janmeier** [comment]
I wonder if we can somehow generate the api docs from typescript typings, or typescript typings from jsdoc? It seems kinda of stupid to keep two different forms of api docs in the code

**Comment by SimonSchick** [comment]
I've seen this happen with https://github.com/GoogleChrome/puppeteer/pull/3744 but I strongly suggest against it, not only will it add a build step but will also be much less flexible than raw typings.

Generating the docs from typing files seems like a much better approach

Ideally we would just move sequelize to TS entirely, this would give all benefits.

I believe the counter arguments were:
 - More complicated
   - It actually makes the code easier to understand without ctrl+f every function call
 - Build step (no github install)
    - Invalid imo, this is what pre-releases or nightly builds are for

But obviously that's a stupid amount of work :)

**Comment by Pomax** [comment]
While an old PR, was there a guide somewhere to help folks migrate from the 4.28 "definitelytyped" definition so the native v5 ones? (particularly problematic with old codebases that still need uplifting). Some things are easy to rewrite, but others are a puzzle that no amount of Google or Stackoverflow seems to explain (like what to do with projects that rely on `Sequelize.Instance`)

**Pull request merged**
