### PR TITLE
fix: use singular association name to generate FK

### LINKED ISSUE #15895: Singular/plural not used in RETURNING clause (7.0.0-alpha25)
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

In a RETURNING close, for a foreign key, the singularized version of my table name is not used.  
It was working on Sequelize v6.

### Reproducible Example

```
// Model : Boks
sequelizeInstance.define<Boks, BoksCreationAttributes>('boks', { ...}, {
      name: {
      singular: 'boks',
      plural: 'boks'
    }
})

  Logs.belongsTo(Boks, {
    foreignKeyConstraints: false
  })
```

A call to Logs.create generates following query :
```
INSERT INTO "logs" ("id_log","type","data","timestamp","boks_id","pcb_mac_address","created_at","updated_at") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING "id_log", "type", "data", "timestamp", "boks_id", "pcb_mac_address", "created_at", "updated_at", "bok_id";
Server error : column "bok_id" does not exist
Server error stack : SequelizeDatabaseError: column "bok_id" does not exist
```

### What do you expect to happen?

It should be boks_id instead of bok_id in RETURNING clause

### Environment

- Sequelize version: v7.0.0-alpha25
- Node.js version: 18.12
- Database & Version: postgresql

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

### PR DESCRIPTION
**Pull request by ephys**
## Pull Request Checklist

- [x] Have you added new tests to prevent regressions?
- [x] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

Closes #15895

Fairly straightforward fix. Instead of inferring the singular form, use the one that was already provided in the configuration of the association, or the model

### CODE REVIEW

**Review by WikiRik — APPROVED** [review]

**Comment by WikiRik** [comment]
It's less than optimal that we disabled required checks upon merging to `main` but the merge queue does do an additional check in which we cannot rerun a single job. But it is nice to be able to queue some PRs so I think we'll just have to accept this

**Comment by ephys** [comment]
> It's less than optimal that we disabled required checks upon merging to main

We did? The only one I disabled was the requirement to be up-to-date with the target branch, as that's what the queue was enabled for

**Comment by WikiRik** [comment]
> > It's less than optimal that we disabled required checks upon merging to main
> 
> We did? The only one I disabled was the requirement to be up-to-date with the target branch, as that's what the queue was enabled for

I think I didn't write it properly. What I meant is that when we merged to `main` in the past, we relied on the CI running by the PR. It didn't check again when it was merged to limit the flaky tests and resources needed. When we only have 1 PR in the queue now it does run the checks again, even if the target branch is already up to date which causes flaky tests to fail sometimes and we need to bring PRs to the queue twice

**Comment by ephys** [comment]
Ah ok I see!
Yes it'd be nice is github were able to re-use the checks if it's the first PR in the queue and it's up to date

**Pull request merged**
