### PR TITLE
Run MSSQL tests in AppVeyor

### LINKED ISSUE #6510: Run MSSQL tests on AppVeyor
Discussed this with @mickhansen on Slack. [AppVeyor has MSSQL server pre-installed](https://www.appveyor.com/docs/services-databases/), so we would not need to host our own server anymore. Every build would have their own isolated environment and not share the same server across all builds (even across forks atm). We would only run MSSQL tests on AppVeyor, so 2 jobs per build. Status checks still work.

One downside is that the free tier only has one concurrent job, but the AppVeyor build would run in parallel to the Travis build.
I propose we try it out while keeping current Travis setup, and see how the build time is.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #6510 and #6509 

The first thing I did was actually making all the test scripts work on Windows, which is a good thing anyways. They used a lot of bash syntax before which doesn't work on Windows. I couldn't find a replacement for `if` though, so I put it in the travis/appveyor.yml with os-specific syntax.

Now to the AppVeyor setup. I mostly tried to copy it from https://github.com/tediousjs/tedious/blob/master/scripts/appveyor/config.ps1.

Reference https://www.appveyor.com/docs/services-databases/#sql-server-2016

I also exclude sqlite and pg-native from the devDependencies because so the native modules do not have to compile.

I am not quite sure if coverage reporting works. It would be nice if someone could take a look at it.

And finally I removed MSSQL from the Travis build matrix, as it can now run much faster in parallel on AppVeyor.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Maybe @arthurschreiber can help?

**Comment by felixfbecker** [comment]
The tests run, and they are sooo much faster than Travis + external server!

**But** there is an actual test failure:
```
  1) [MSSQL] QueryInterface dropAllTables should drop all tables:

     AssertionError: expected [ Array(1) ] to be empty
      at null.<anonymous> (C:\projects\sequelize\node_modules\chai\lib\chai\core\assertions.js:423:10)
      at addProperty (C:\projects\sequelize\node_modules\chai\lib\chai\utils\addProperty.js:43:29)
      at doAsserterAsyncAndAddThen (C:\projects\sequelize\node_modules\chai-as-promised\lib\chai-as-promised.js:296:33)
      at null.<anonymous> (C:\projects\sequelize\node_modules\chai-as-promised\lib\chai-as-promised.js:286:25)
      at Object.defineProperty.get (C:\projects\sequelize\node_modules\chai\lib\chai\utils\overwriteProperty.js:50:37)
      at C:\projects\sequelize\test\integration\query-interface.test.js:33:35
  From previous event:
      at Promise.then (C:\projects\sequelize\lib\promise.js:21:17)
      at Context.<anonymous> (C:\projects\sequelize\test\integration\query-interface.test.js:31:50)
      at callFn (C:\projects\sequelize\node_modules\mocha\lib\runnable.js:334:21)
      at Test.Runnable.run (C:\projects\sequelize\node_modules\mocha\lib\runnable.js:327:7)
      at Runner.runTest (C:\projects\sequelize\node_modules\mocha\lib\runner.js:429:10)
      at C:\projects\sequelize\node_modules\mocha\lib\runner.js:535:12
      at next (C:\projects\sequelize\node_modules\mocha\lib\runner.js:349:14)
      at C:\projects\sequelize\node_modules\mocha\lib\runner.js:359:7
      at next (C:\projects\sequelize\node_modules\mocha\lib\runner.js:285:14)
      at Immediate._onImmediate (C:\projects\sequelize\node_modules\mocha\lib\runner.js:327:5)
```
That one has slipt through because we couldn't test MSSQL for quite some time now.
I propose that we still merge this PR (as it only add CI config), so any PR that might fix the failed test can actually verify it through AppVeyor.

**Comment by janmeier** [comment]
LGTM - Lets hope travis catches up soon ...

**Comment by felixfbecker** [comment]
Both AppVeyor and Travis fail at reporting coverage, don't know why.
```
> sequelize@4.0.0-1 merge-coverage /home/travis/build/sequelize/sequelize
> lcov-result-merger "coverage/*.info" "coverage/lcov.info"


/home/travis/build/sequelize/sequelize/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```
https://travis-ci.org/sequelize/sequelize/jobs/156093154#L4080
https://ci.appveyor.com/project/felixfbecker/sequelize/build/2/job/anstg1r0jfo65kuy#L2304

Maybe my `fs.renameSync()` is not working?

**Comment by janmeier** [comment]
Hmm, seems we did get some coverage from travis https://coveralls.io/builds/7661335

**Comment by felixfbecker** [comment]
yeah, 7 hours ago, but not on the newest build. And no coverage from AppVeyor so far (docs say they support AppVeyor)

**Comment by janmeier** [comment]
I think thats because coverage results are not sent if the tests fail

**Comment by felixfbecker** [comment]
The Travis tests didn't fail though

**Comment by felixfbecker** [comment]
We should backport this to v3, otherwise we still need the server there.

**Pull request merged**
