### PR TITLE
Bugfix 13638

### PR DESCRIPTION
**Pull request by sschwenker**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [X] Have you added new tests to prevent regressions?
- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [NA] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [NA] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

This PR is an implementation to fix issue #13638 . I updated the code, fixed affected unit test and added a new unit test.

### CODE REVIEW

**Comment by sschwenker** [comment]
Hey.  Are we able to re-run the build/tests?  I didn't touch any of the mysql code.

**Comment by WikiRik** [comment]
Yeah, it seems that this test fails on main as well sometimes. Seems to be related to MySQL 8 and not Node.

**Comment by sschwenker** [comment]
However.  I'm going to make an adjustment to the code to only generate the extended query if there is an include.  If there is no includes, then it's not needed and it can slow down the query.  So it will continue to generate the older query.

**Comment by sschwenker** [comment]
Ok.  Done.

**Pull request merged**
