### PR TITLE
meta(deps): update dependencies to latest version

### PR DESCRIPTION
**Pull request by sdepold**
This PR updates all currently available dependencies to the latest version

### CODE REVIEW

**Comment by WikiRik** [comment]
Why only update the yarn.lock file and not the package.json file?

**Comment by sdepold** [comment]
I guess because of https://github.com/yarnpkg/yarn/issues/4390

**Comment by sdepold** [comment]
I have just enabled renovate again and maybe we should the bot do the heavy lifting :D

**Review by WikiRik — APPROVED** [review]

**Comment by WikiRik** [comment]
Sounds good!

**Comment by sdepold** [comment]
Closing this in favor of #13729

**Pull request closed without merging**
