### PR TITLE
fix(mssql): avoid default `encrypt` option

### PR DESCRIPTION
**Pull request by davidjb**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Having `encrypt: false` set by default in the internal options for MSSQL connections means that Sequelize is overriding the now-default behaviour of Tedious v6.0.0 to use encrypted connections
(https://github.com/tediousjs/tedious/commit/70ffe4a).

This change allows Tedious to use its own defaults for its connections, which makes configuration more obvious whilst improving the security of the Sequelize users since encryption is used by default.

For note, Tedious > 6.0.0 no longer outputs the `options.encrypt`
warning, which means the solution to https://github.com/sequelize/sequelize/issues/9574 in PR
https://github.com/sequelize/sequelize/pull/9588 is no longer required.

This is a breaking change and not backwards compatible, and so needs documenting accordingly; users who want keep using unencrypted connections would need to set `dialectOptions: { options: { encrypt: false } }` in their config.

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Put `encrypt: false` https://github.com/sequelize/sequelize/blob/master/test/config/config.js#L34 so CI can run

**Comment by davidjb** [comment]
@sushantdhiman Done and pushed

**Comment by papb** [comment]
@sushantdhiman looks like MSSQL CI is still not working, do you know what might be happening here?

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/12300

**Pull request closed without merging**
