### PR TITLE
V3 Added sourceKey support for hasOne

### PR DESCRIPTION
**Pull request by twolfson**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Have you added an entry under `Future` in the changelog?

_NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open._

### Description of change

In my current repo, I have a scenario where using `belongsTo` with includes for selects isn't feasible. The scenario is:

- User has tasks
- Each of these tasks can have an active reminder as well as past inactive reminders
- We want to have a screen which lists these tasks and their reminders

The model structure is:

```
User({id})
Task({id, user_id, active_reminder_id})
Reminder({id, task_id, user_id})

User.hasMany(Task);
Task.belongsTo(User);

Task.hasOne(Reminder, {as: 'active_reminder', sourceKey: 'active_reminder_id', foreignKey: 'id'});
Reminder.belongsTo(Task);
Reminder.belongsTo(User);
```

There are alternatives to this:

- Add an `active` boolean to the `Reminder` table but then we risk 0 or 2 becoming enabled which requires prevention enforcement via triggers

But I would prefer to not go down those rabbit holes as it seems likely to cause more problems later on.

This PR is on top of #7113 and has completed the logic for `sourceKey` support in `hasOne` but I'm unable to test it due to Sequelize wanting to generate a `userId` association despite not requesting one in the tests. As a result, we are getting circular dependency issues on table drop/creation =/

Any help in that department or telling me that I'm doing it wrong would be appreciated =)

Related issues: #4258, #6652, #7113

### CODE REVIEW

**Comment by twolfson** [comment]
Okay, I took another look at this today. It looks like `hasOne` has a lot of built-in logic for updating attributes on the target instead of the source whereas we want to update the source. This makes me think we actually want to use `belongsTo` but we can't because it doesn't set associations for `include` on the `source`. That is I can't do:

```
User({id, active_task_id})
Task({id})

Task.belongsTo(User, {as: 'active_task'});

User.findAll({include: [{model: Task, as: 'active_task'}]});
```

Thankfully this PR **seems** to work for selects which is all I really needed (I don't do nested saves as they currently don't support transactions):

```
User({id, active_task_id})
Task({id})

User.hasOne(Task, {as: 'active_task', sourceKey: 'active_task_id', foreignKey: 'id'});

User.findAll({include: [{model: Task, as: 'active_task'}]});
```

That being said, it would be great to find a solution that works and fits this repo (e.g. `belongsTo` that defines association on `source`)

**Comment by twolfson** [comment]
Aaaaand after digging around some more I found out what I was doing wrong. I shouldn't be using `model/as`, I should be using `association` for include -_-;;

https://github.com/sequelize/sequelize/pull/6651/files#diff-bea10850a51c66a27b66d3cbbd7fc57fR896

```
User({id, active_task_id})
Task({id})

Task.belongsTo(User, {as: 'active_task'});

User.findAll({include: [{association: User.associations.active_task}]});
```

**Comment by twolfson** [comment]
Sorry, that is:

```
User.belongsTo(Task, {as: 'active_task'});
```

and we don't need to use association:

```
User.findAll({include: [{model: Task, as: 'active_task'}]});
```

That being said, using a `belongsTo` on the parent feels very strange but I guess it works =/

**Comment by mattfysh** [comment]
@twolfson - would it be possible to make this change also for V4? I would owe you one!

**Pull request closed without merging**
