### PR TITLE
refactor: use sequelize-pool for pooling

### PR DESCRIPTION
**Pull request by mikeringrose**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This fixes an issue with generic-pool not allowing the node process to exit, referenced in #8468. This PR pool over the work done by sushantdhiman in #10051.

> This PR will migrate Sequelize to https://github.com/sushantdhiman/sequelize-pool which is a modernized fork of generic-pool@2.5
>
>In theory this should solve issues like
>
> #9541
> #8468

### CODE REVIEW

**Comment by sushantdhiman** [comment]
@mikeringrose I can't accept this PR for v4. It swaps pooling library this can have unintended side effects on someone's production, lots of pooling code base has been refactored which again could have introduced breaking change.

**Comment by mikeringrose** [comment]
That’s unfortunate as a fair number of people running sequelize in lambdas are experiencing timeouts.

**Comment by sushantdhiman** [comment]
@mikeringrose So you expect me to break things for others, I've to follow semver. If you want you can use this branch in your code or upgrade to v5

**Comment by mikeringrose** [comment]
@sushantdhiman that's assuming others would be broken by this, which is why there are unit and integration tests. with that said, i'd prefer to fix this issue that people are experiencing while maintaining the current code base for others.

**Comment by sushantdhiman** [comment]
@mikeringrose I migrated that old code base from `generic-pool` and even I can't guarantee if it will be fully compatible (actually it can't be as generic-pool@2.5 and 3 are breaking).

Passing unit tests and integrations tests is fine but I don't want try swapping semver breaking libraries in same major version, when used for such critical component. I am certain there will be some hidden case which we both can't consider right now, but users will later complain, which I will have to hear.

I am just trying to keep v4 non breaking, it's not like I don't want this patch to be ported over to v4. Historically most v4 ports has been accepted and released pretty fast.

**Pull request closed without merging**
