### PR TITLE
Patch with static decrement method types

### PR DESCRIPTION
**Pull request by Jerry-zhk**
Patch with missing type definitions for static decrement method

### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change
Adding missing type definitions for static decrement method

### CODE REVIEW

**Comment by yuvalt** [comment]
Can this be merged please? Thank you!

**Review by oesukam — COMMENTED** [review]
Are we having this merged soon?

**Comment by eliemugenzi** [comment]
When will this be merged please?

**Comment by fabrykowski** [comment]
@sequelize – not cool to just close via bot a PR solving an issue!

**Comment by WikiRik** [comment]
Yeah, this is something that will be addressed in #13648
For now I've reopened it, is this PR ready to be merged you think?

**Review by fncolon — APPROVED** [review]

**Comment by fncolon** [comment]
Thx!

**Pull request merged**
