### PR TITLE
fix(query-generator): handle field names in scope exclude…

### PR DESCRIPTION
**Pull request by amitaymolko**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Additional fix to issue: https://github.com/sequelize/sequelize/issues/10399
Adds fix for using attribute field names

### CODE REVIEW

**Comment by eseliger** [comment]
could you explain what didn't work before with the field names?

**Comment by amitaymolko** [comment]
If you had default scope with includes that exclude attributes with a cutom field name it didn't work.
The fix provided here: https://github.com/sequelize/sequelize/commit/e07a7beae2be62fb4ac586f844974dbd0a343a3d
Didn't handle the case for custom attribute names.

You can see the test changes in the commit.
```
this.DefaultScopeExclude = this.sequelize.define('DefaultScopeExclude', {
        name: Sequelize.STRING,
        other_value: {
          type: Sequelize.STRING,
          field: 'otherValue'
        }
      }
```
if the model was defined with a `field` name like `other_value` in the test, it would try to access the column as `other_value` instead of `otherValue` and would throw an error

Cheers

**Comment by amitaymolko** [comment]
Thanks for the quick release :)

**Pull request merged**
