### PR TITLE
fix: postgres-array no loaded correctly

### PR DESCRIPTION
**Pull request by arcaela**
The correction is minimal, but the loadDialectModule method automatically loads the postgres-array dependency, however the "pg" library does not have the ".parse()" method which causes an error when using the loadDialectModule with the library original postgres, therefore I have loaded the postgress-array using require(), in this way we load the postgress-array.

### CODE REVIEW

**Comment by WikiRik** [comment]
I'm not sure what you are trying to do. `.parse()` is called on the postgres-array dependency, not pg. Do you have a small reproducible example that shows what goes wrong with the current code?

**Comment by arcaela** [comment]
> I'm not sure what you are trying to do. `.parse()` is called on the postgres-array dependency, not pg. Do you have a small reproducible example that shows what goes wrong with the current code?

Example of code:
```
export const db = new Sequelize(process.env.DATABASE_NAME as string, {
    dialect: 'postgres',
```
Error produced:
`Please install pg manually`


Example of code:
```
import pg from 'pg'
export const db = new Sequelize(process.env.DATABASE_NAME as string, {
    dialectModule: pg,
    dialect: 'postgres',
```
Error produced:
`#arrayParseLib.parse() is not a function`

Temporary Fix:
```
import pg from 'pg'
pg.parse = require('postgres-array').parse

export const db = new Sequelize(process.env.DATABASE_NAME as string, {
    dialectModule: pg,
    dialect: 'postgres',
```



Causes:
```
// packages/core/src/dialects/postgres/connection-manager.ts#67
this.#arrayParserLib = this._loadDialectModule('postgres-array') as ArrayParserLib;
```
"_loadDialectModule" load packages when dialectModule is undefined, if dialectModule is defined then "#arrayParseLib" is equal that "dialectModule", but "pg" dont have ".parse()".


```
// Error: Because this.#arrayParserLib is "pg", not "postgres-array"
   return this.#arrayParserLib.parse(source, subTypeParser);
```

**Comment by WikiRik** [comment]
I can't reproduce this with the following code and therefore I will close this issue. It might be a different dependency (possibly a bundler) that is causing your issue, but it's not due to sequelize.

```mjs
// index.mjs
import { Sequelize } from '@sequelize/core';

// postgres 15 is running on 127.0.0.1:5432, database is sequelize_test, username is sequelize_test, password is sequelize_test
const sequelize = new Sequelize('sequelize_test', 'sequelize_test', 'sequelize_test', {
  dialect: 'postgres',
  host: '127.0.0.1',
  port: 5432,
});

try {
    await sequelize.authenticate();
    console.log('Connection has been established successfully.');
  } catch (error) {
    console.error('Unable to connect to the database:', error);
  }
```

Only dependencies I have installed are; 
```json
  "dependencies": {
    "@sequelize/core": "^7.0.0-alpha.34",
    "pg": "^8.11.3"
  }
```

**Comment by YuziO2** [comment]
> pg.parse = require('postgres-array').parse

我复现了这个bug，此bug只在出现数组类型时出现，以下是我的示例：(I have reproduced the bug, which only occurs when an array type is present, here is my example)

DB model：
```ts
@Table({ timestamps: false, modelName: "keyword" })
export class Keyword extends Model<
  InferAttributes<Keyword>,
  InferCreationAttributes<Keyword>
> {
  @Attribute(DataTypes.INTEGER)
  @PrimaryKey
  @AutoIncrement
  declare id: CreationOptional<number>;

  @Attribute(DataTypes.STRING)
  @NotNull
  declare type: string;

  @Attribute(DataTypes.ARRAY(DataTypes.STRING))
  @Default([])
  declare words?: string[];
}
```
usage:
```ts
import { Keyword } from "@/backend/database/models";
const keywords = await Keyword.findAll();
```
此时报错（At this point, the error is reported）：
 ⨯ node_modules\.pnpm\@sequelize+core@7.0.0-alpha.39_pg@8.11.3\node_modules\@sequelize\core\lib\dialects\postgres\query.js (345:0) @ PostgresQuery.formatError
 ⨯ SequelizeDatabaseError: this[#arrayParserLib].parse is not a function

报错后程序便退出，无法正常解析包含数组的表，解决方法同楼主所述（The program exits after the error is reported, and the table containing the array cannot be parsed properly, the solution is the same as that described by the owner.）
```ts
import { Sequelize } from "@sequelize/core";
import pg from "pg";
import * as tables from "./models";

// @ts-ignore
pg.parse = require("postgres-array").parse;

const sequelize = new Sequelize(
  "postgres://...",
  {
    dialectModule: pg,
    models: Object.values(tables),
    define: {
      freezeTableName: true,
    },
  }
);
```
这样写之后就可以正常解析（When written this way, it parses correctly）

**Comment by YuziO2** [comment]
> I can't reproduce this with the following code and therefore I will close this issue. It might be a different dependency (possibly a bundler) that is causing your issue, but it's not due to sequelize.
> 
> ```js
> // index.mjs
> import { Sequelize } from '@sequelize/core';
> 
> // postgres 15 is running on 127.0.0.1:5432, database is sequelize_test, username is sequelize_test, password is sequelize_test
> const sequelize = new Sequelize('sequelize_test', 'sequelize_test', 'sequelize_test', {
>   dialect: 'postgres',
>   host: '127.0.0.1',
>   port: 5432,
> });
> 
> try {
>     await sequelize.authenticate();
>     console.log('Connection has been established successfully.');
>   } catch (error) {
>     console.error('Unable to connect to the database:', error);
>   }
> ```
> 
> Only dependencies I have installed are;
> 
> ```json
>   "dependencies": {
>     "@sequelize/core": "^7.0.0-alpha.34",
>     "pg": "^8.11.3"
>   }
> ```

顺便，版本号如下(BTW, the package.json are as follows)：
```json
  "dependencies": {
    "@sequelize/core": "^7.0.0-alpha.39",
    "pg": "^8.11.3"
  }
```

**Comment by ephys** [comment]
The fix makes sense, calling `_loadDialectModule` for anything other than the connector library (in this instance, `pg`) will break if the user supplied the `dialectModule` or `dialectModulePath` option

However, we have some good news. We have separated our dialects into their own packages, and `postgres-array` is now a direct dependency of `@sequelize/postgres` and is not loaded via `_loadDialectModule` anymore: 

- https://github.com/sequelize/sequelize/blob/54f1e18748180b72da045066d7a5798f12cb1beb/packages/postgres/src/connection-manager.ts#L19
- https://github.com/sequelize/sequelize/blob/54f1e18748180b72da045066d7a5798f12cb1beb/packages/postgres/package.json#L43

This change is not yet released, we have a few more changes to implement. You can track the progress in https://github.com/sequelize/sequelize/issues/13722

If you are using v6, feel free to implement these changes against the v6 branch

**Comment by arcaela** [comment]
> This fix makes sense. As you indicated, calling `_loadDialectModule` for anything other than the connector library (in this instance, `pg`) will break if the user supplied the `dialectModule` or `dialectModulePath` option
> 
> However, we have some news. We have separated our dialects into their own packages, and `postgres-array` is now a direct dependency of `@sequelize/postgres` and is not loaded via `_loadDialectModule` anymore:
> 
> * https://github.com/sequelize/sequelize/blob/54f1e18748180b72da045066d7a5798f12cb1beb/packages/postgres/src/connection-manager.ts#L19
> * https://github.com/sequelize/sequelize/blob/54f1e18748180b72da045066d7a5798f12cb1beb/packages/postgres/package.json#L43
> 
> This change is not yet released, we have a few more changes to implement. You can track the progress in #13722
> 
> If you are using v6, feel free to implement these changes against the v6 branch

It is not necessary to incorporate an independent version of array-parse since it could bring compatibility problems, but we can only make use of the require or import of the version already existing in "pg", for this reason this PR only includes the call to "array- parse" and not the installation of the dependency.

**Pull request closed without merging**
