### PR TITLE
docs(legacy): clarify implications on models without primary keys

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [ ] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [x] Documentation update is included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by WikiRik** [comment]
Thanks for the PR! We'll take a look at it soon.
Don't worry about the failing tests. The MariaDB tests have failed since this evening suddenly and the DB2 tests are very flaky

**Comment by ephys** [comment]
We should consider resolving https://github.com/sequelize/sequelize/pull/13819 first. I've also found it weird that it stored the query used to select the model on the Model instead of the instance.
My opinion of the solution is that using instance methods that rely on the primary key when there are no primary keys is dangerous and prone to introducing bugs. I think we forbid using methods that are PK-dependent if there are no primary keys, and only allowing to use static methods.

**Comment by dilyanpalauzov** [comment]
I opened this case, as I assumed that https://github.com/sequelize/sequelize/pull/13819 will not be resolved any time soon.  Once the other case is resolved, this documentation change shall not be necessary.

**Comment by dilyanpalauzov** [comment]
Integrating the proposed change in the documentation will save one day struggling with undocumented bugs.  At least it costed me one day and by updating the documentation I am contributing to prevent others from having the same troubles.

Are there compelling reasons against integrating the proposed change?

**Comment by ephys** [comment]
I'll close this PR since https://github.com/sequelize/sequelize/pull/13819 is its replacement

**Pull request closed without merging**
