### PR TITLE
test(integration/dialects): asyncify

### PR DESCRIPTION
**Pull request by jedwards1211**
_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by SimonSchick** [comment]
@jedwards1211 feel free to open multiple PRs at the same time 😛

**Comment by sushantdhiman** [comment]
@jedwards1211  I thought you already added `// eslint-disable-line` for this

```diff
-          it.skip('should make aliased attributes available', function() {
+          it('should make aliased attributes available', async function() {
```

**Comment by jedwards1211** [comment]
@sushantdhiman I probably got removed by `recast` after the AST transform lol...I can't win 😂

**Comment by jedwards1211** [comment]
@sushantdhiman I think these build failures aren't caused by my PR

**Pull request merged**
