### PR TITLE
fix(log): output query is not bind parameters #11151

### PR DESCRIPTION
**Pull request by ryuki0628**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change
pass query string bound parameters to this._logQuery

### CODE REVIEW

**Comment by papb** [comment]
Nice! Can you add a test for this?

Also, you forgot to mention somewhere in the post that this fixes issue #11151 (so it was not linked by GitHub, even though it is in title...) - With my comment it is probably linked now.

**Comment by ryuki0628** [comment]
> Nice! Can you add a test for this?
> 
> Also, you forgot to mention somewhere in the post that this fixes issue #11151 (so it was not linked by GitHub, even though it is in title...) - With my comment it is probably linked now.

**Comment by ryuki0628** [comment]
Thank you check!
i try to fix test error

**Comment by papb** [comment]
Don't worry about the Travis build failing for now. First, try to create a test for the issue that you're solving, in order to guarantee that no regressions will happen.

**Comment by ryuki0628** [comment]
Thank you for comment!
I got it.

**Comment by ryuki0628** [comment]
Add test for this issue([#11151](https://github.com/sequelize/sequelize/issues/11151)).
Please check.

**Comment by ryuki0628** [comment]
OK!
I try to fix!

**Comment by superlbr** [comment]
consider occupancy of mysql, it's emergency. should be merged frist.

**Comment by ryuki0628** [comment]
fix all dialect.
please check.

**Comment by papb** [comment]
@ryuki0628 Thanks. Several tests are failing though.

Also, we now have two equivalent PRs, what to do? Perhaps you two can join forces instead?

#11159 #11238

**Comment by papb** [comment]
Hello @ryuki0628, the other PR (#11238) is much closer to be complete, just a few little tweaks are needed, so in order to save time and prevent duplicate work I will close this pull request in favor of the other one.

I'm sorry... I hope to see you helping again with other issues later :+1:

**Comment by superlbr** [comment]
@papb to the opposite, #11238 is rejected, consider this again?

**Comment by papb** [comment]
@superlbr Hi, the original idea was indeed discarded, but this PR follows the same idea so it doesn't make sense to be reopened. Also, #11238 was "rejected" in a way but @supperchong will rework it with the new idea (and that's why it is still open)

**Pull request closed without merging**
