### PR TITLE
WhereMerge option to provide alternative strategy for merging scopes

### PR DESCRIPTION
**Pull request by PatrickGeyer**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change
https://github.com/sequelize/sequelize/issues/10873

Added option for where merge strategy so that don't have to use default of Object.assign, but can AND the two scopes instead

### CODE REVIEW

**Comment by SimonSchick** [comment]
I think this is a bit too specific and should instead be handled on a broader scale under `scopeMergeStrategy`

**Comment by PatrickGeyer** [comment]
@SimonSchick agreed. As long as there's an easy way to keep the default merging behavior without having to code it all into your own merge strategy function.

**Comment by papb** [comment]
@PatrickGeyer Is this ready, in your opinion? Or WIP?

**Comment by PatrickGeyer** [comment]
@papb it's WIP, don't think I'm going to get anything mergeable done myself to be honest.

**Comment by WikiRik** [comment]
Closing this since it is still against `master`. Can be reopened if that changes.

**Pull request closed without merging**
