### PR TITLE
UUID datatype mapping for mssql

### PR DESCRIPTION
**Pull request by nsilberman**

### CODE REVIEW

**Comment by mickhansen** [comment]
@mbroadst

**Comment by mickhansen** [comment]
Would be helpfull if you could add a test @nsilberman, so we guard ourselves against agressions.

**Comment by mbroadst** [comment]
I don't get it. UNIQUEIDENTIFIER is in fact a UUID in mssql term, but instead you're replacing it with a char of length 36? Seems to me that the proper solution is: if you want a unique identifier in this fashion, you should just create a column of type CHAR(36)? 

Or could you provide more info in the description describing why you needed this change?

**Comment by nsilberman** [comment]
Yes I know, but because of tedious, the UUID was returned in upper cases (but stored in the DB in lower cases). UNIQUEIDENTIFIER is a GUID in mssql term, not a UUID

**Comment by mbroadst** [comment]
Ah, well we could fix that on the query level by making sure to call toLowerCase on it. Would that solve your specific issue? GUID is technically microsoft's implementation of the rfc UUID, this datatype returns essentially the same value types as e.g. the mysql dialect's use of UUID()

**Comment by nsilberman** [comment]
My specific issue was having UUID working with mssql. So we can let UNIQUEIDENTIFIER, but we need to update 'lib/dialects/mssql/query-generator.js'

**Comment by mbroadst** [comment]
@nsilberman can you give me a small test case of it not working for you? I apologize for the pain, but it would really speed up the process of getting this fix in today

**Comment by nsilberman** [comment]
@mbroadst yes !

my model : 
```
  id: {
    type: Sequelize.UUID,
    primaryKey: true
  },
```
and the error when I just want to create the DB
```
"err":{"message":"Column, parameter, or variable #1: Cannot find data type UUID.","name":"SequelizeDatabaseError","stack":"SequelizeDatabaseError: Column, parameter, or variable #1: Cannot find data type UUID.\n    at module.exports.Query.formatError (/Users/nicolas/Sites/thankyoumotion/sequelize/lib/dialects/mssql/query.js:216:12)\n
```

**Comment by mbroadst** [comment]
@nsilberman https://github.com/sequelize/sequelize/blob/master/test/associations/has-many.test.js#L1488 we have a test case that creates a column called id in exactly the same way, and it passes. Can you provide more of your model? Or can you specify which version of SQL Server you're testing against?

**Comment by mbroadst** [comment]
@nsilberman it would also be very helpful to see debug output, if you pass "logging: console.log" to your sequelize constructor it will print it out

**Comment by nsilberman** [comment]
Oh sorry, I forgot the most important thing... I'm using Azure SQL Database V11

**Comment by mbroadst** [comment]
@nsilberman can you please provide the sql logs, I don't have access to an Azure server ATM (I called microsoft to get a free server for us but they refused)

**Comment by nsilberman** [comment]
@mbroadst unfortunately, I do not have any logs : it's a service. And for a free server, maybe you can try to apply to the bizpark program ? 150$ /months for 3 years

**Comment by mickhansen** [comment]
@nsilberman we'll need some kinds of steps to reproduce, logs, whatever, having to access some service that requires us to pay or go through some kind of program is just not feasible i'm sorry.

**Comment by mbroadst** [comment]
@nsilberman I understand you don't want to publicly disclose your schema, but maybe you can make a small test case that uses the UUID type and then enable sequelize logging for that. It will only show us the SQL statements that are used. http://sequelize.readthedocs.org/en/latest/api/sequelize/index.html?highlight=logging

**Comment by nsilberman** [comment]
@mickhansen the program give you 150$ of credits each month
@mbroadst no problem to send you information, just have to prepare my post :)

**Comment by nsilberman** [comment]
@mickhansen if you are eligible, it's free of charge for you

**Comment by mickhansen** [comment]
@nsilberman just to be clear, what version are you working off?

**Comment by nsilberman** [comment]
@mbroadst the full model : 
```javascript
var Sequelize = require('sequelize');

var db = require('../db');

module.exports = db.define('provider', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true
  },
  name: {
    type: Sequelize.STRING(100),
    allowNull: false,
    unique: true
  }
}, {
  classMethods: {
    associate: function() {
      db.provider.hasMany(db.source);
      db.provider.belongsToMany(db.user, {through: db['user-provider']});
      db.provider.hasMany(db['user-provider']);
    }
  }
});

```
and the log
```
Executing (default): IF OBJECT_ID('[providers]', 'U') IS NOT NULL DROP TABLE [providers];
Executing (default): IF OBJECT_ID('[providers]', 'U') IS NOT NULL DROP TABLE [providers];
Executing (default): IF OBJECT_ID('[providers]', 'U') IS NULL CREATE TABLE [providers] ([id] UUID , [name] NVARCHAR(100) NOT NULL UNIQUE, [createdAt] DATETIME2 NOT NULL, [updatedAt] DATETIME2 NOT NULL, CONSTRAINT [providers_name_unique] UNIQUE ([name]), PRIMARY KEY ([id]));
{"name":"tym-api","hostname":"pro-ns.local","pid":24941,"type":"sync-script","level":50,"err":{"message":"Column, parameter, or variable #1: Cannot find data type UUID.","name":"SequelizeDatabaseError","stack":"SequelizeDatabaseError: Column, parameter, or variable #1: Cannot find data type UUID.\n    at module.exports.Query.formatError (/Users/nicolas/Sites/thankyoumotion/sequelize/lib/dialects/mssql/query.js:216:12)\n    at Request.userCallback (/Users/nicolas/Sites/thankyoumotion/sequelize/lib/dialects/mssql/query.js:73:27)\n    at Request.callback (/Users/nicolas/Sites/thankyoumotion/sequelize/node_modules/tedious/lib/request.js:30:27)\n    at Connection.STATE.SENT_CLIENT_REQUEST.events.message (/Users/nicolas/Sites/thankyoumotion/sequelize/node_modules/tedious/lib/connection.js:283:29)\n    at Connection.dispatchEvent (/Users/nicolas/Sites/thankyoumotion/sequelize/node_modules/tedious/lib/connection.js:739:59)\n    at MessageIO.<anonymous> (/Users/nicolas/Sites/thankyoumotion/sequelize/node_modules/tedious/lib/connection.js:672:22)\n    at MessageIO.EventEmitter.emit (events.js:92:17)\n    at MessageIO.eventData (/Users/nicolas/Sites/thankyoumotion/sequelize/node_modules/tedious/lib/message-io.js:58:21)\n    at CleartextStream.<anonymous> (/Users/nicolas/Sites/thankyoumotion/sequelize/node_modules/tedious/lib/message-io.js:3:59)\n    at CleartextStream.EventEmitter.emit (events.js:95:17)"},"msg":"Cannot sync database schema","time":"2015-01-22T21:21:36.340Z","src":{"file":"/Users/nicolas/Sites/thankyoumotion/api.tym.cool/backend/scripts/sync.js","line":17,"func":"syncError"},"v":0}
```

**Comment by nsilberman** [comment]
@mickhansen 2.0rc8

**Comment by nsilberman** [comment]
no sorry, the master

**Comment by mickhansen** [comment]
That should really be saying `UNIQUEIDENTIFIER` and not `UUID`, which it does when tested on AWS SQL.

Are you running multiple instances of Sequelize per chance?

**Comment by nsilberman** [comment]
@mickhansen I have to ask someone in my team to really check, but I don't think so. It's just a simple init database script.

**Comment by vvo** [comment]
Using the current sequelize version with azure sql server and trying to use UUID field it fails because the mapping to UNIQUEIDENTIFIER was not done.

When we did it in the dialect and used UNIQUEIDENTIFIER, it worked but then when inserting lowercase UUID, which is the correct rfc implementation, tedious sent us uppercase uuids. 

Why? Because UNIQUEIDENTIFIER is a GUID and as tedious does, a GUID is not a uuid, since it's uppercased, always.

This made us think "well it would be a hack to store uuid in sql server using UNIQUEIDENTIFIER it is clearly not meant to store uuid v4 as postgresql UUID datatype is". 

So we did as it was done in mysql dialect: use char(36).

**Comment by vvo** [comment]
> That should really be saying UNIQUEIDENTIFIER and not UUID, which it does when tested on AWS SQL.

As the mapping was not done and as tedious does not accept [UUID datatype](http://pekim.github.io/tedious/api-datatypes.html). Something must be wrong with the current test suite if mssql UUIDs are tested.

**Comment by mbroadst** [comment]
@vvo CHAR(36) is used in mysql because it has no default UUID type. As you can clearly see your attempt to switch it to CHAR(36) with mssql actually has broken the test suite (see the TravisCI build has failed, right above this box). A GUID is just a another name for an implementation of the UUID rfc (please see: http://en.wikipedia.org/wiki/Globally_unique_identifier. Specifically the second sentence of that article "The term GUID typically refers to various implementations of the universally unique identifier (UUID) standard")

It seems to me that you really have two issues here:
a) you want the value returned as a lowercase value every time (okay this seems rather trivially implemented to me)

b) you have actually uncovered a bug where the sql being generated is actually sending "UUID" as the datatype instead of "UNIQUEIDENTIFIER". There is nothing wrong with the current test suite because when it generates sql, it uses "UNIQUEIDENTIFIER" as the data type for the column - and passes that way - but as we discovered above the sql generated in your case somehow defaults back to UUID. This is why @mickhansen was asking if you happen to be running multiple instances of sequelize in process, because there is a chance once instance could revert the prototype for DataType and therefore reset the switch from 'UUID' => 'UNIQUEIDENTIFIER'

I'm not convinced at this point that the switch to a CHAR(36) is the correct choice, and frankly if that is what you want for a column instead I believe you can do

```
module.exports = db.define('provider', {
  id: {
    type: 'CHAR(36)',
    primaryKey: true
  },
....
```

I would really like to track down the bug though, so hopefully you'll bear with us a little longer :smile:

**Comment by vvo** [comment]
Hi @mbroadst 

> CHAR(36) is used in mysql because it has no default UUID type.

I got this.

> therefore reset the switch from 'UUID' => 'UNIQUEIDENTIFIER'

Can you point to the code of the mssql dialect where when the datatype is UUID we switch to UNIQUEIDENTIFIER?

It may be done "automagically" but why would we need this code then: https://github.com/sequelize/sequelize/blob/6a0912ad82915fd7bf20bd71ad7707abd473a137/lib/dialects/mssql/query-generator.js#L611? (Only asking the obvious)

> a) you want the value returned as a lowercase value every time (okay this seems rather trivially implemented to me)

That's the RFC of uuids: http://en.wikipedia.org/wiki/Universally_unique_identifier#Definition

**About using UNIQUEIDENTIFIER** which are GUID. As you pointed out ("The term GUID typically refers to various implementations of the universally unique identifier (UUID) standard"), the implementation of GUID seems to depends on developer mood rather than an actual RFC.

It seems from a simple [google search](https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=sql%20server%20uniqueidentifier%20lowercase) that a lot of people are struggling with the "Coming as lowercase, coming as uppercase" case (:p).

So as an ORM, the safest choice to avoid things like this issue and things like "We use sequelize for our node.js, but then when using php and querying sql server, we get all uppercase/lowercase IDS, what's wrong? We use the ID as an url parameter, our website is down..".

The safest choice would be to avoid UNIQUEIDENTIFIER because those are as broken as any microsoft self invented rfc and use the safe char(36) mechanism for mssql.

Here's the model of "provider" along with the way we load models:

model/provider.js
```js
var Sequelize = require('sequelize');

var db = require('../db');

module.exports = db.define('provider', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true
  },
  name: {
    type: Sequelize.STRING(100),
    allowNull: false,
    unique: true
  }
}, {
  classMethods: {
    associate: function() {
      db.provider.hasMany(db.source);
      db.provider.belongsToMany(db.user, {through: db['user-provider']});

      // mickhansen  vvo: oh, you only have User N:M provcider?
      // mickhansen  vvo: you'll need to manually create the user > userprovider relation
      // mickhansen  we dont set that up automatically
      // mickhansen  vvo: sounds like you need User.hasMany(UserProvider)
      db.provider.hasMany(db['user-provider']);
    }
  }
});
```

sync.js
```
if (process.env.DB_SYNC_ALLOWED !== 'yes') {
  throw new Error('You cannot sync the database in this environment');
}

var db = require('../db');
var log = require('../log').child({type: 'sync-script'});

db.sync({
  // drop and recreate tables each time
  force: true
})
.then(function syncSucces() {
  log.info('Database schema synced');
  process.exit(0);
})
.catch(function syncError(err) {
  log.error(err, 'Cannot sync database schema');
  process.exit(1);
});
```

db.js
```js
var bulk = require('bulk-require');
var path = require('path');
var Sequelize = require('sequelize');

var log = require('./log').child({type: 'db'});
var sequelizeLogger = log.child({type: 'sequelize'});

var dialectOptions;

if (process.env.DB_DIALECT === 'mssql') {
  dialectOptions = {
    encrypt: true
  };
}

var db = module.exports = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USER,
  process.env.DB_PASSWORD, {
    host: process.env.DB_HOSTNAME,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    dialectOptions: dialectOptions,
    logging: function logQuery(query/*, sequelizeOptions*/) {
      sequelizeLogger.info(query);
    }
  });

// auth to Database
db
  .authenticate()
  .then(function connected() {
    log.info('Connected to the database');
  })
  .catch(function connectionProblem(err) {
    log.error(err, 'Could not connect to the database');
  });

// load models
var models = bulk(path.join(__dirname, 'models'), ['*.js']);

Object.keys(models).forEach(function addModel(modelName) {
  db[models[modelName].name] = models[modelName];
});

// associate models
Object.keys(db.models).forEach(function(modelName) {
  if ('associate' in db[modelName]) {
    db[modelName].associate();
  }
});
```

**Comment by vvo** [comment]
On a side note, looking at [the way tedious](https://github.com/pekim/tedious/blob/fc19fba187b205671decfd4f056d482b5357d126/src/guid-parser.coffee) "uppercase" every GUID on every request, it may be faster to not do it.

Please consider this: Sequelize states that it has a UUID Datatype. Postgresql states that it has a UUID datatype. Sql server claims it has a UNIQUEIDENTIFIER data type. But we should not get lost, PG UUID datatype is not the same thing at all than sql server UNIQUEIDENTIFIER.

I do understand it may be "implementation details". But detail is important here.

Would we want to uppercase every GUID and then lowercase them? Seems hacky and uneeded.

**Comment by vvo** [comment]
> I'm not convinced at this point that the switch to a CHAR(36) is the correct choice, and frankly if that is what you want for a column instead I believe you can do
> 
> module.exports = db.define('provider', {
>   id: {
>     type: 'CHAR(36)',
>     primaryKey: true
>   },
> ....

I do not want to mess with my models just because I use mssql, that would not be a good idea either.

**Comment by vvo** [comment]
Updated the code as we decided on IRC: use char(36).

I had to change two tests and remove and if in tests. Now mssql tests are ok, mariadb and mysql failed, dunno how.

**Comment by vvo** [comment]
@sdepold Can you relaunch this PR so that it passes, seems like it had an issue with travis dates

**Comment by mickhansen** [comment]
@vvo rerunning - next time you should probably ping someone involved with the issue though ;)

**Comment by vvo** [comment]
Lst time @mbroadst asked you on IRC, I thought you were the only one capable of relaunching.

**Comment by mickhansen** [comment]
@vvo what i meant is that you pinged sdepold, who hasn't been involved in this issue :)

**Comment by vvo** [comment]
Oh I am just mixing you guys :D sorry

**Comment by vvo** [comment]
@mickhansen All green :D

**Comment by sdepold** [comment]
Sorry :) Didn't check my messages yesterday.

**Comment by mickhansen** [comment]
@mbroadst do we merge?

**Comment by mbroadst** [comment]
:+1:, I can add the GUID separately

**Pull request merged**
