### PR TITLE
fix(postgres): schema for index and relations

### LINKED ISSUE #11276: Postgres: Schema does not default to current schema for references when model is set only on parent model
## What are you doing?

I need to switch schemas dynamically for multi tenancy in an application and when I change the schema for a model, I would like sequalize to default to that schema also for references and indexes. This is not the case yet and I would consider this a bug as it's the only sensible default behaviour.
The main point where this happens is when I call `sync({ schema: 'archive' })` on a model,

## What do you expect to happen?

Sequalize to default to the schema of the model I'm using.

## What is actually happening?

If I sync a model into a schema for example (I have used `sync({ schema: 'archive' })` on the models before), for references the current schema is not applied but no schema prefix at all.

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: XXX
Database version: XXX
Sequelize version: XXX
Node Version: XXX
OS: XXX
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version:

### PR DESCRIPTION
**Pull request by vanthome**
Relations and Indexes created from models that have set a schema are not properly prefixed with the schema. This patch solves this.

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

In several cases, the schema prefix was not applied for generated indexes and related tables. This PR fixes this.

Fixes #11276.

### CODE REVIEW

**Comment by vanthome** [comment]
From my perspective this is complete now, please merge it.

**Comment by papb** [comment]
@vanthome I see you did not add any test... Please add at least one simple test that wouldn't pass before your PR and passes after your PR. Thanks.

**Comment by vanthome** [comment]
Added a test. For whatever reason now the tests fail although they run locally?

**Comment by vanthome** [comment]
Seems like MySQL tests fail due to some code that I integrated through rebasing. So will you merge this?

**Comment by papb** [comment]
@vanthome The test you added is running for all dialects, and failing for every dialect which is not postgres. You have to add your test in a way that it will run only for postgres. Let me know if you need further help.

**Comment by papb** [comment]
@vanthome Just add your test [here](https://github.com/sequelize/sequelize/blob/master/test/integration/dialects/postgres/associations.test.js) instead and it should work.

**Comment by vanthome** [comment]
Strange because previously the tests passed I think. Anyways, I have moved it there.

**Comment by vanthome** [comment]
Now the PG native test seems to fail which has nothing to do with my change. What to do now?

**Comment by papb** [comment]
@vanthome Nothing else to do! That error in postgres-native is an intermittent error that has been happening in Sequelize for a while... We can all ignore it.

Thank you very much for the PR! Looks ready to merge.

Let's wait for @sushantdhiman

**Comment by vanthome** [comment]
Great, looking forward.

**Comment by papb** [comment]
@vanthome There are conflicts with master, can you please resolve them?

**Comment by vanthome** [comment]
Oh crap, I just pushed another update to my local branch, I did not want to add this to this PR. Do you know how I can revert this?

**Comment by papb** [comment]
@vanthome Ah, that explains the last commit :grimacing:

You can just revert the commit normally (`git revert`), don't worry about the "ugly git history" because everything will be squashed on merge anyway.

**Comment by vanthome** [comment]
I have undone the malicious change. When will this be merged now?

**Comment by papb** [comment]
Hi! There are still conflicts...

**Comment by vanthome** [comment]
Well this was w/o conflicts. why has it not been merged then?
I mean why should I put more effort into this, is it does not get merged anyway?

**Comment by papb** [comment]
> Well this was w/o conflicts.

Indeed! But as time passes, conflicts may appear, it's normal.

> why has it not been merged then?

Because maintainers are busy

> I mean why should I put more effort into this, is it does not get merged anyway?

You don't have to do anything. In open source no one is forced to anything... I, like you, would like to see every PR merged as well.

**Comment by papb** [comment]
I fixed the conflict for you :+1:

**Comment by vanthome** [comment]
Great, looking forward for a merge.

**Pull request merged**
