### PR TITLE
fix(mysql): use public TypeCastField type

### PR DESCRIPTION
**Pull request by WikiRik**
## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description of Changes

The same type as Field, but now imported from the root

## List of Breaking Changes

Not a breaking change yet, but TypeScript users will need mysql2 v3.9.2 (or higher when new versions get released). I think I'll bring back my old plans for the testing strategy so that we'll not only test for oldest database versions, but also oldest adapter versions (possibly only before making a release or on a weekly basis, so not to overload CI more)

### CODE REVIEW

**Comment by WikiRik** [comment]
@ephys this fixes one of the TODOs in #17168

**Review by ephys — APPROVED** [review]

**Comment by wellwelwel** [comment]
Hi @WikiRik, here I am (again) 😅

> but TypeScript users will need mysql2 v3.9.2

There is a way prevent it:

```ts
{
  typeCast?: QueryOptions['typeCast'];
}
```

By this way:

- **MySQL2** >= 3.9.2: `typeCast` option will be `TypeCastField`
- **MySQL2** >= 3.8.0: `typeCast` option will be `Field` from the `TypeCast` (_same `TypeCastField`, but not exposed at this moment_):
  - https://github.com/sequelize/sequelize/blob/34f2413e7984039b0e47d73ae971a6e417eae954/packages/core/src/dialects/mysql/connection-manager.ts#L9
- **MySQL2** < 3.8.0: `typeCast` option will be `any`

---

Sorry I didn't see it before 🙋🏻‍♂️

**Comment by WikiRik** [comment]
No worries, thanks for your comment!

I can look into this, but since we haven't released v7 yet we also have not been fixed on the minimum version of the adapter we require.
Personally I'm fine with setting that to 3.9.2 for all users, while a lower version might work as well for most users.
Also; we're looking into publishing dialect specific packages for v7 because we've seen lately that 'breaking' changes occur quite often so we want to change the responsibility from a certain adapter version from the side of the user to our side. (That's different from splitting dialect specific code for now, but it's a first step)

@ephys any additional thoughts?

**Comment by wellwelwel** [comment]
> we've seen lately that 'breaking' changes occur quite often

My apologies for that.

I conducted exhaustive tests to ensure that the changes to `typeCast` wouldn't bring significant changes.
But externally, I can see the problems caused here.

That's why I've been around here ever since 🙋🏻‍♂️

**Comment by WikiRik** [comment]
It wasn't personal towards you, we've seen this with other adapters as well. Thanks for being around!

**Comment by ephys** [comment]
> @ephys any additional thoughts?

Pretty much as you said. It's always been difficult to support a connector that is installed separately as we can't fully control which version is installed, but it's even more apparent the more we embrace TypeScript

Choosing the connector version ourselves will be a relief

**Pull request merged**
