### PR TITLE
fix(types): Allow augmentation on model interfaces

### PR DESCRIPTION
**Pull request by hhhonzik**
Written export instead of star export for Model declarations to allow module augmentation

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Currently extending any Model interface is ignored, due to [specific Typescript behaviour](https://github.com/microsoft/TypeScript/issues/18877#issuecomment-476921038)

This PR enables full usage of augmentation on Model interfaces like this:

```
declare module 'sequelize' {
  export interface CreateOptions {
    auditLog?: ...;
  }
}
```

- Fixes (closes) https://github.com/sequelize/sequelize/issues/10591
- similar on [StackOverflow](https://stackoverflow.com/questions/53366179/typescript-module-augmentation-with-modules-in-multiple-files
)

Example demo repository [is here](https://github.com/hhhonzik/typescript-module-augmentation-sequelize)

### CODE REVIEW

**Comment by hhhonzik** [comment]
Btw I've took all the exports from `lib/model.d.ts` file, maybe just a handpicked ones that are probably the most used could be enough.

```
export * from './lib/model';
export {
  CreateOptions,
  UpdateOptions,
  UpsertOptions,
  BulkCreateOptions,
  BuildOptions,
  Model,
  ModelType,
 } from './lib/model';
```

**Comment by hhhonzik** [comment]
Also possible current workaround - you can override types like this:

```
// sequelize-fix.d.ts
declare module 'sequelize' {
  export * from 'sequelize/types';

  export {
    Model,
    BulkCreateOptions,
    UpdateOptions,
    InstanceUpdateOptions,
    CreateOptions,
  } from 'sequelize/types/lib/model';
}


// sequelize.d.ts
import 'sequelize';

declare module 'sequelize' {
  interface BulkCreateOptions {
    metadata?: any;
  }
}

```

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

Let's wait for @SimonSchick :)

**Comment by SimonSchick** [comment]
They can already be augmented as is but I don't see harm in exporting them from root regardless.

**Pull request merged**
