### PR TITLE
docs: fix forgetting the comma

### PR DESCRIPTION
**Pull request by ia17011**
This change is really tiny. I just added the commna.
so skip below.

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

Can you please update the target branch from `master` to `v6`? Currently our documentation pull requests need to be sent there instead. There should be a button somewhere in the GitHub interface for you to change this. Only the PR author can do it, otherwise I would do it myself. Thanks!

**Comment by ia17011** [comment]
@papb Hello, thanks!
I changed base branch master to v6.
There are some conflict files, should I solve it?

**Comment by ia17011** [comment]
@papb 
Sorry, I recreated the PR to solve branch problems. 
At: https://github.com/sequelize/sequelize/pull/12786

**Comment by papb** [comment]
@ia17011 Great, thank you!!

**Pull request closed without merging**
