### PR TITLE
include with separate:true fails if id is not part of the attributes list

### PR DESCRIPTION
**Pull request by sorin**
Should sequelize attempt to include the missing id field? Should it raise an appropriate error?

### CODE REVIEW

**Comment by sorin** [comment]
@mickhansen thoughts? I can try to fix it if you think we should do something about it

**Comment by mickhansen** [comment]
Hmm yes, we need to make sure that the id and needed foreign keys are added to `attributes`.
I actually thought i had already considered this, maybe i did and just postponed fixing it :)

**Comment by sorin** [comment]
@mickhansen take a look please

**Comment by mickhansen** [comment]
LGTM, do you mind squashing your commits?

**Comment by sorin** [comment]
Done, thanks for reviewing this! BTW, any immediate plans to support separate:true for BTM? I'm tempted to give it a try.

**Comment by mickhansen** [comment]
Not sure, currently a lot of my implementations are driven by the needs of my startup, so it comes and goes how much i get done :)

Hopefully soon.

**Comment by sorin** [comment]
Haha sounds like our story as well, all of these bug fixes / features are coming from stuff we need. We actually have our own implementation outside Sequelize for the separate:true BTM use case, it's probably time to try and contribute it. Created feature request here: https://github.com/sequelize/sequelize/issues/4376

**Pull request merged**
