### PR TITLE
fix(types): Add beforeSave and afterSave typings

### PR DESCRIPTION
**Pull request by diego3g**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Added `beforeSave` and `afterSave` hooks typings.

### CODE REVIEW

**Comment by jaulz** [comment]
Similar, `beforeUpsert` and `afterUpsert` is missing. Should we take this up in the same PR?

**Comment by SimonSchick** [comment]
Sure.

**Comment by jaulz** [comment]
@diego3g are you still working on it and could you please implement it at the same time?

**Comment by kroleg** [comment]
@jaulz seems like i don't have time to add `beforeUpsert` and `afterUpsert`.
If you want you can add them like i've added `beforeSave` and `afterSave` in #10987

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/10987

**Pull request closed without merging**
