### PR TITLE
MSSQL upsert implementation

### PR DESCRIPTION
**Pull request by derstrassi**
Implemented "upsert" for MSSQL dialect using a MERGE statement (see https://msdn.microsoft.com/en-us/library/bb510625(v=sql.120).aspx).
Tests for the new method are missing but all existing ones are passing.

### CODE REVIEW

**Comment by mickhansen** [comment]
You should also upload the dialect file: https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/index.js#L29

Otherwise it won't actually test your code: https://github.com/sequelize/sequelize/blob/master/test/integration/model/upsert.test.js#L58

**Comment by derstrassi** [comment]
Ah, thanks for this hint, I have enabled upsert support in the MSSQL index.js file.

**Comment by derstrassi** [comment]
There are issues with identity (autoIncrement) columns, will have a look at that.

**Comment by janmeier** [comment]
Ping @derstrassi

**Comment by janmeier** [comment]
Closing, since there has been no activity for over a month. @derstrassi or anyone else are welcome to open a new PR adressing the last small changes - We'd definitely like to support this!

**Comment by harshithkashyap** [comment]
@janmeier Are autoIncrement columns the only missing case in this PR? I'd like to submit a PR with changes from this.

**Comment by janmeier** [comment]
@harshithkashyap I don't have a lot of experience with mssql, but I believe so - You are very welcome to pick it up :)

**Comment by smassin** [comment]
@janmeier I have updated the code to solve the identity issue and as a bonus solved two other issues: it can support multi column indexes and properly supports all insertValues.

What's the best way to share the change?

**Comment by felixfbecker** [comment]
@smassin [open a pull request](https://help.github.com/articles/about-pull-requests/)

**Comment by harshithkashyap** [comment]
PR submitted via #6842

**Comment by smassin** [comment]
Looks like @harshithkashyap beat me to it :)

**Pull request closed without merging**
