### PR TITLE
feat(postgres): native updateOnConflict for upsert

### LINKED ISSUE #4132: Postgres UPSERT native support
Looks like Postgres [recently added UPSERT](https://news.ycombinator.com/item?id=9509870) ([9.5alpha is it?](http://www.postgresql.org/about/news/1595/)). Seems Sequelize handles psql upsert fine presently with its workaround, so obviously no rush.

Me personally (and maybe I need re-architecting), my current project's most common SQL operation is UPSERT. That operation seems quite slow; this is the resultant SQL which _looks_ like it would be slow:

`CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $func$ BEGIN INSERT INTO ... VALUES ...; RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE ... SET ... WHERE ...; RETURN 2; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();`

So I'd personally upgrade to Postgres 9.5 if native upsert becomes supported in sequelize

### PR DESCRIPTION
**Pull request by bmeriaux**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

replace the function to catch exception on existing element for upsert method with Postgres by the native method ON CONFLICT () UPDATE SET, it is supported by postgres >= 9.5, is this blocking ?

Closes #4132

### CODE REVIEW

**Comment by papb** [comment]
> postgres >= 9.5, is this blocking ?

Without your PR, what is the minimum required postgres version? (I probably should know this, but I don't...)

**Comment by bmeriaux** [comment]
if we look at the previous default version, it was 9.4
but a previous PR  #11163 on bulkInsert with the same ON CONFLICT syntax already implicit set required version to 9.5

**Comment by papb** [comment]
I see. Thanks! I think it is better for @sushantdhiman to take a look.

**Comment by sushantdhiman** [comment]
Tests are failing

**Comment by up73k** [comment]
@bmeriaux, will you fix tests in nearest future?

**Comment by papb** [comment]
Also, there are conflicts with the master branch, @bmeriaux please rebase your branch.

**Comment by bmeriaux** [comment]
I will try this week.
But I find out that with this native upsert, we lose the information if it is an insert or an update,
And it may not work on case with 2 distinct unique constraints.
So i do not know if we must detect in which case we are to keep existing temp function for some edge case, and use native upsert for others ?
What did you think ?



Le 13 août 2019 à 14:37:41, Pedro Augusto de Paula Barbosa (notifications@github.com<mailto:notifications@github.com>) a écrit:

Also, there are conflicts with the master branch, @bmeriaux<https://github.com/bmeriaux> please rebase your branch.

**Comment by papb** [comment]
> I will try this week. But I find out that with this native upsert, we lose the information if it is an insert or an update, And it may not work on case with 2 distinct unique constraints. So i do not know if we must detect in which case we are to keep existing temp function for some edge case, and use native upsert for others ? What did you think ?

Can you show a SSCCE/MVCE/reprex for the situation that is covered by Sequelize's workaround that is not covered by the native implementation?

**Pull request closed without merging**
