### PR TITLE
fix include association as

### PR DESCRIPTION
**Pull request by ivnivnch**
Aliases for associations:

```
Model.findAll({
  include: [
    {association: Model.associations.someAssociation, as: 'name1', where: {/* where1 */}},
    {association: Model.associations.someAssociation, as: 'name2', where: {/* where2 */}}
  ]
})
```

### CODE REVIEW

**Comment by mickhansen** [comment]
We don't currently support `as` differing from `as` on the defined association.
We'd be open to this but we'd need a larger PR covering a lot more test cases.

**Comment by janmeier** [comment]
Ping @ivnivnch

**Comment by janmeier** [comment]
@ivnivnch We don't get notified of new commits, just so you know :)

We'd need both unit and integration tests

**Comment by janmeier** [comment]
PR CLEANUP: No response for a _long_ time

**Pull request closed without merging**
