### PR TITLE
updated transaction docs.

### PR DESCRIPTION
**Pull request by calvintwr**

### CODE REVIEW

**Comment by janmeier** [comment]
Needs a rebase - otherwise looks good.

If you have time, it would be awesome if you could mention this as well: https://github.com/sequelize/sequelize/pull/3687/files

**Comment by janmeier** [comment]
ping @calvintwr 

Btw, the issue I mentioned has already been documented, so this just needs to be rebased

**Comment by calvintwr** [comment]
i don't know how to squash these commits....

**Comment by janmeier** [comment]
Using interactive rebase `git rebase -i sequelize/master` https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i

Remember to force-push once you are done :)

**Comment by calvintwr** [comment]
i can't. i tried all sorts of ways. i simply run into all sorts of problems.

can you just make the changes to the master?

**Comment by janmeier** [comment]
@BridgeAR got it sorted out - thanks for taking the time to write it @calvintwr  :)

**Comment by calvintwr** [comment]
hey no worries man. anytime.

**Pull request closed without merging**
