### PR TITLE
fix(mssql): match aggregate errors

### PR DESCRIPTION
**Pull request by WikiRik**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [X] Have you added new tests to prevent regressions?
- [X] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [X] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Adds support for aggregate errors as introduced in tedious 14.5.0
Unblocks #14484

### CODE REVIEW

**Review by sdepold — APPROVED** [review]
Should we have a test for this? Or will the fact that the referenced pr no longer fail, suffice?

**Comment by WikiRik** [comment]
I was thinking about that as well but I couldn't come up with a proper new test. The referenced PR should be fine. Earlier I was also thinking if this code should only be used with the new version of tedious but I decided not to since no behaviour should be changed in the older versions of tedious

**Comment by WikiRik** [comment]
@ephys check this out for the multiple tedious errors. Maybe we should not return the errors directly but first collect them all

**Comment by ephys** [comment]
Definitely should :)

**Comment by WikiRik** [comment]
Can you add that to #14505 or #14999 ? Or a third separate PR?

**Comment by ephys** [comment]
Separate PR, it's not related to either :)

**Comment by WikiRik** [comment]
I know, it's just that you're working on those PRs and might have encountered some issues because of this

**Pull request merged**
