### PR TITLE
PR for MySQL, CREATE INDEX renames table to lowercase

### PR DESCRIPTION
**Pull request by psayre23**
https://github.com/sequelize/sequelize/issues/3598

### CODE REVIEW

**Comment by janmeier** [comment]
A couple of tests need to be changed, otherwise looks good

**Comment by mickhansen** [comment]
@janmeier this is really a lot of code duplication from the abstract one.

**Comment by mickhansen** [comment]
Is there any syntactical difference other than `CREATE INDEX` => `ALTER TABLE ADD INDEX`?
If there isn't we should rework abstract addIndexQuery to support ALTER.

**Comment by janmeier** [comment]
I don't think there is a difference so yes that would probably be a better solution

**Comment by psayre23** [comment]
That sounds like a fine solution, though I don't know how to implement
that. Feel free to kill my PR.

**Comment by janmeier** [comment]
@psayre23 Its basically the same as you did already, just in the abstract query generator instead of mysql https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L459

**Comment by janmeier** [comment]
@psayre23 Are you up for this - it should only be a tiny bit more work to more the code you already have int othe abstract query generator

**Comment by psayre23** [comment]
I'm not sure how to make this change. Moreover, I don't have the
environment to test it.

**Comment by janmeier** [comment]
Environment setup https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#1-prepare-your-environment

Add the modified code you have here to lib/dialects/abstract/query-generator

**Pull request closed without merging**
