### PR TITLE
Update Postgres connect manager (browserify fix).

### PR DESCRIPTION
**Pull request by icereval**
Like #5025

### CODE REVIEW

**Comment by janmeier** [comment]
jshint errors:
```js
lib/dialects/postgres/connection-manager.js: line 21, col 11, 'pg' is already defined.
lib/dialects/postgres/connection-manager.js: line 23, col 42, 'pg' used out of scope.
lib/dialects/postgres/connection-manager.js: line 23, col 54, 'pg' used out of scope.
```

**Comment by mickhansen** [comment]
You need to hoist `var pg`

**Comment by janmeier** [comment]
Added in https://github.com/sequelize/sequelize/commit/35e68f67b9be2702109157b6d066781555d43202

**Comment by janmeier** [comment]
Thanks :)

**Pull request closed without merging**
