### PR TITLE
fix(transaction): delete autocommit when transaction begin (#9877)

### LINKED ISSUE #9877: MySQL connections have autocommit disabled after transaction with autocommit: false.
## What are you doing?

```js
const Sequelize = require('sequelize');

async function run() {

    const s = new Sequelize('test', 'user', 'password', {
        host: 'mysql',
        port: '3606',
        dialect: 'mysql',
        pool: {
            max: 1,
            min: 1,
            acquire: 30000,
            idle: 10000,
            log: true
        }
    });

    return s.transaction({autocommit: false}).then((txn) => {
        return s.query('SELECT @@SESSION.autocommit', {transaction: txn}).spread((results, metadata) => {
            console.log(results);
        }).then(() => {
            return txn.commit();
        });
    }).then(() => {
        return s.query('SELECT @@SESSION.autocommit').spread((results, meta) => { console.log(results); });
    }).catch((err) => {
        console.log(err);
    });
}
run();
```

## What do you expect to happen?
I expect the second SELECT statement to show autocommit=1.

## What is actually happening?
autocommit=0. The 'SET AUTOCOMMIT = 0' is run inside of the transaction, but affects the session. So when the connection goes back into the pool it's in an unexpected state. Unless the application does all reads within an explicit transaction, it can lead to inconsistent reads.

Executing (b74d6416-e1ed-4e88-9a70-47f076e9bfc8): START TRANSACTION;
Executing (b74d6416-e1ed-4e88-9a70-47f076e9bfc8): SET autocommit = 0;
Executing (b74d6416-e1ed-4e88-9a70-47f076e9bfc8): SELECT @@SESSION.autocommit
[ TextRow { '@@SESSION.autocommit': 0 } ]
Executing (b74d6416-e1ed-4e88-9a70-47f076e9bfc8): COMMIT;
Executing (default): SELECT @@SESSION.autocommit
[ TextRow { '@@SESSION.autocommit': 0 } ]

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ 5.6.34
__Sequelize version:__ 4.38.0
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

### PR DESCRIPTION
**Pull request by tsasaki609**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change
fix #9877 
Statements within a transaction should either be all successful, or all fail. Autocommit arguments that initiate transactions are misleading and should not be provided. If we want to enable autocommit, we should explicitly call auto-commit. How do you think?

### CODE REVIEW

**Comment by sushantdhiman** [comment]
MySQL transaction with AUTO COMMIT = 1 does defeat purpose of having transaction i.e. each statement is committed as soon as it is finished without any chance of rollback. This is also default behaviour of MySQL.

Two things can be done here

1. Set `autocommit = false` by default, so transactions is predictable
2. Related to fixing #9877 , we need to reset AUTO COMMIT status when transaction exits. How we will do that is not sure, may be a session variable to store current auto commit value and reset it after transaction

**Comment by tsasaki609** [comment]
Since we are executing START TRANSACTION internally, is not it possible to do SET autocommit = 0 to affect the behavior until the end of the transaction?

If we explicitly use a transaction, it seems that it was behavior that autocommit had no effect until you explicitly commit or roll back.

Sorry if my understanding was wrong.

**Comment by tsasaki609** [comment]
@sushantdhiman 
I am glad you understood.

In addition to MySQL, PostgreSQL, SQLite, and MS SQL Server seem to have autocommit statement.
https://www.postgresql.jp/document/9.4/html/ecpg-sql-set-autocommit.html
https://www.sqlite.org/c3ref/get_autocommit.html
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms187878(v=sql.105)

However, the essential meaning of the autocommut statement is that any product is similar,
we don't need to think about separately.


I also deleted options and query generation methods.

Thank you for your review.

**Comment by sushantdhiman** [comment]
> In addition to MySQL, PostgreSQL, SQLite, and MS SQL Server seem to have autocommit statement.
https://www.postgresql.jp/document/9.4/html/ecpg-sql-set-autocommit.html
https://www.sqlite.org/c3ref/get_autocommit.html
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms187878(v=sql.105)

Yeah I meant more at Sequelize level, where we only support/implemented this for MySQL.

**Comment by sushantdhiman** [comment]
Thanks @tsasaki609

**Pull request merged**
