### PR TITLE
Must quote reserved keywords after AS to avoid SQL syntax error

### PR DESCRIPTION
**Pull request by idris**
When using Postgres and `quoteIdentifiers: false`, I get a syntax error if the table name is a reserved keyword (in my case, `User`) when attempting to find that model.

The offending SQL generated by sequelize is:

``` sql
SELECT id FROM Users AS User;
```

And it's generated when I run:

``` js
var User = sequelize.define('User');
User.findAll();
```

The same problem occurs if the String passed to `sequelize.define` is any of the reserved keywords listed on this page: http://www.postgresql.org/docs/9.4/static/sql-keywords-appendix.html

I've included failing unit and integration tests.  Not sure which is better, but the integration test seems like such a common use case that maybe it's good to have in there :)

### CODE REVIEW

**Comment by idris** [comment]
Found a workaround I can use temporarily:

```js
var User = sequelize.define('User');
User.findAll({ tableAs: 'UserTable' });
```

Specifying `tableAs` manually using a something that's not a reserved keyword works.

**Comment by janmeier** [comment]
Hmm, no really sure whats the best thing to do here.. I guess we can always quote the `AS` part, since it is not part of the table schema. Are you up for trying that @idris ?

**Comment by idris** [comment]
I tried playing around with this a bit but I don't know enough about this part of the codebase to make a fix.   Can someone else give it a shot?

**Comment by janmeier** [comment]
PR CLEANUP: No response for a _long_ time

Since quoteIdentifiers is a rather niche feature, I don't want to keep this PR open - If anyone wants to fix it they are still welcome to

**Pull request closed without merging**
