### PR TITLE
fix(types): Add missing type definitions in models

### PR DESCRIPTION
**Pull request by l2ysho**
This commit fixes problem with type definitions for typescript > 4.4

Type definitions for [Op.eq] and [Op.is] added to model.d.ts

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

Modifying model.d.ts to resolve issiue in typescript 4.4. described in issue https://github.com/sequelize/sequelize/issues/13505

### CODE REVIEW

**Comment by PurkkaKoodari** [comment]
@l2ysho You might want to add `Op.not` as mentioned in https://github.com/sequelize/sequelize/issues/13505#issuecomment-939814003. We should probably also go through `Op` and add other missing ones if there are any.

**Comment by l2ysho** [comment]
@sdepold Is there any problem? If It is let me know and a will fix it. This PR waiting only for your approval.

**Comment by sdepold** [comment]
thanks :)

**Comment by sdepold** [comment]
> @sdepold Is there any problem? If It is let me know and a will fix it. This PR waiting only for your approval.

Sorry for the delay. Best thing to ping me on Slack if there is anything urgent. If I turn on the notification on Github, I'll go crazy in no time.

**Pull request merged**
