### PR TITLE
meta: add codeowners

### PR DESCRIPTION
**Pull request by ephys**
This PR adds the codeowners file. The entire repo is covered by the "code-reviewers" team as the goal is to automatically assign members of the team (or the team itself) when a PR is created.

I'm adding this so we can filter PRs to review by using the following filter: `is:open is:pr review-requested:@me sort:created-asc -is:draft -author:@me -status:failure`

This is part of a series of PRs designed to improve our review process

Review team is @sequelize/code-reviewers

### CODE REVIEW

**Review by WikiRik — APPROVED** [review]
We do need to change some repository setting for this as well right?

**Comment by ephys** [comment]
Yep! But already done :)

**Comment by WikiRik** [comment]
Do we want to set this to @sequelize/maintainers or @sequelize/code-reviewers ? I didn't see before that you added that group

**Comment by ephys** [comment]
I used a new one because I wanted to automatically assign the members that were the most common reviewers via this setting: https://github.com/orgs/sequelize/teams/code-reviewers/edit/review_assignment

Alternatively, we could just assign @sequelize/maintainers but not enable auto-assignment

**Comment by WikiRik** [comment]
I'll look into that tomorrow and get back to you

**Review by WikiRik — APPROVED** [review]
This looks good. We'll require that one of the maintainers approves the PR and set up auto-assigment to @sequelize/code-reviewers to not message too many people.

About those settings; do we want to enable the 'Count existing requests' option? Doesn't really change anything now, but might be nice when we have more code reviewers

**Comment by ephys** [comment]
> About those settings; do we want to enable the 'Count existing requests' option?

Sure! But depending on how many people are in code-reviewers we could also assign the team itself, or the team + specific people. We can always adapt it to fit the team at any given time

PS: I added a note about the prettier vscode extension

**Review by WikiRik — COMMENTED** [review]
Can you also update the section https://github.com/sequelize/sequelize/blob/ephys/codeowners/CONTRIBUTING.md#coding-guidelines ?

**Comment by ephys** [comment]
Like this?

**Review by WikiRik — APPROVED** [review]

**Comment by WikiRik** [comment]
One thing about the new autoupdate; it doesn't run when you enable auto-merge. That should be added. Do you want to do it here or in a different PR?

Should just be adding the following to the triggers;
```
  pull_request:
    types: [auto_merge_enabled]
```

**Comment by WikiRik** [comment]
And on the new team; I gave them write access to this repo so they are suggested when you request reviews

**Comment by ephys** [comment]
> One thing about the new autoupdate; it doesn't run when you enable auto-merge.

That's not necessary, it doesn't react to pull request events. It runs when a commit is added on main and searches for any PR targeting main currently in "automerge"

If the branch is out of date at the time of automerge, we need to press the button ourselves. This script will only be useful when we're merging more than one PR at a time

**Comment by ephys** [comment]
Yay! That one was triggered by the bot (the bot uses my account to be able to trigger workflows)

**Comment by WikiRik** [comment]
> If the branch is out of date at the time of automerge, we need to press the button ourselves. This script will only be useful when we're merging more than one PR at a time

I was thinking it would be nice to not have to do both steps ourselves. So when we set automerge to enabled then the PR also gets updated if it's outdated. Saves just that little bit of time, even though it doesn't happen often

**Comment by ephys** [comment]
Nevermind I'm wrong, it's another action that did not support pr events. This one does: https://github.com/chinthakagodawita/autoupdate/blob/master/src/router.ts#L20

**Comment by ephys** [comment]
Let's wait until another PR is merged so we can test that this gets updated when auto-merge is enabled

**Review by WikiRik — APPROVED** [review]

**Comment by WikiRik** [comment]
Works great!

**Comment by WikiRik** [comment]
Works great!

**Comment by ephys** [comment]
Yay!

Now to one day get rid of all flaky tests :D

**Comment by WikiRik** [comment]
Okay, this is not working exactly as I wanted. I hoped that we could require an approval from one of the maintainers to merge this, but auto request review from the @sequelize/code-reviewers group (which would be auto assigned to one of us). So not to inform the others all the time. But that's not what it does. Do we maybe want to change the CODEOWNERS file? Or just accept that we will request reviews from the others as well?

**Comment by ephys** [comment]
Requiring a review from a maintainer is the default state, auto adding reviewers is what codeowners is for
So we just need to change the codeowner back to the initial plan and not enable the "require review from code owner" protection (it will then only assign them but not require these specific people)

**Pull request merged**
