### PR TITLE
change count type from number to string

### LINKED ISSUE #10757: model.count doesn't always return a Promise<number>
https://github.com/sequelize/sequelize/blob/728707cda2de842439130a6e7a20be0e36c8a91b/types/lib/model.d.ts#L1751

if you use group/attributes it will return an array of objects

### PR DESCRIPTION
**Pull request by mjdavidson**
fixes #10757

### CODE REVIEW

**Comment by SimonSchick** [comment]
I am not sure what do here exactly, it should *never* return a string, this is a bug and the typings shouldn't really reflect that. @sushantdhiman any ideas on how to fix this?

**Comment by mjdavidson** [comment]
@SimonSchick so is this a deeper routed problem

**Comment by SimonSchick** [comment]
Correct, for now we can make this `number | string` so people will have to ensure it's actually a number they will process, so this will be non-breaking once it's fixed.

**Comment by eseliger** [comment]
I checked and could not find a case where this happens
Could you provide a repro?

**Comment by papb** [comment]
Apparently this is [no longer an issue](https://github.com/sequelize/sequelize/issues/10757#issuecomment-515265638).

**Pull request closed without merging**
