### PR TITLE
fix abstract/connection-manager.js pool configuration problem

### PR DESCRIPTION
**Pull request by RayneHwang**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions? no test needed
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)? *no changes to public APIs*
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

As described in issue [#7882](https://github.com/sequelize/sequelize/issues/7882) , current [pool confiuration](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L112) in `/lib/dialects/abstract/connection-manager.js` initPool method sets `autostart` to false when no replication is configured, which causes generic-pool `_scheduleEvictorRun` check routine [never gets invoked](https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L119). As a result idle connections never get evicted even if the database server's already closed the connection.
To fix that problem, simply set `autostart` option to true and the evict check routine gets scheduled.
As documented in node-pool, the `softIdleTimeoutMillis`(default to -1 ) is checked before `idleTimeoutMillis`, so if `softIdleTimeoutMillis` is not set, the connection will be considered stale no matter what `idleTimeoutMillis` is

### CODE REVIEW

**Comment by swordfish444** [comment]
@RayneHwang That was fast!

**Comment by RayneHwang** [comment]
@swordfish444 😄

**Comment by swordfish444** [comment]
@RayneHwang I've opened https://github.com/sequelize/sequelize/pull/7924 to resolve for stale connections by ensuring evictions are ran.

**Comment by RayneHwang** [comment]
@swordfish444 I've tested your [PR](https://github.com/sequelize/sequelize/pull/7924) in my project, doesn't seem to successfully evict stale connections.

- `autostart` must be `true`
The default value of `autostart` is `true`, but in asbtract/connection-manager.js `autostart` is manually set to `false`.
In generic-pool [constructor](https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L119) ,if `autostart` is not set to `true`, the [evict routine](https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L372) won't be called for the first time, and the following check relies on `setTimeout` inside the [_scheduleEvictorRun](https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L352) ,so no evict will be scheduled. 

- `softIdleTimeoutMillis` must be set
Though node-pool doc claims that `idleTimeoutMillis` supercedes `softIdleTimeoutMillis`, but in  the [default evictor implementation](https://github.com/coopernurse/node-pool/blob/master/lib/DefaultEvictor.js#L7) `softIdleTimeoutMillis` is checked before `idleTimeoutMillis`. If `softIdleTimeoutMillis` is not set, the default value( -1 ) always makes the connection stale, when `availableObjectsCount` is larger than `config.min`

```javascript
if (config.softIdleTimeoutMillis < idleTime && config.min < availableObjectsCount) {
     return true
}
if (config.idleTimeoutMillis < idleTime) {
    return true;
}
```
So every time `_scheduleEvictorRun` gets ran, the connection will be evicted, no matter what `idleTimeoutMillis` is. It's really a confusing option. 

- `evictionRunIntervalMillis`
Sorry I forgot to commit that option. I will push some updates.

**Comment by sushantdhiman** [comment]
`autostart: false` is not acceptable, this will be fixed by https://github.com/coopernurse/node-pool/pull/201

As a workaround you can call `start` from pooling library to initialize evictor https://github.com/sequelize/sequelize/pull/7924#issuecomment-325378123

**Comment by DiegoRBaquero** [comment]
The `softIdleTimeoutMillis` change was somehow reverted, and thus set to -1, which thens marks all connections as idle.

**Pull request closed without merging**
