### PR TITLE
feat(find-count-associations): added findAndCount to hasMany association

### PR DESCRIPTION
**Pull request by marziply**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

FindAndCountAll is available directly on models but was not available on hasMany associations. I've added a new method for associations with hasMany that has the same functionality as the FindAndCountAll method on models.

### CODE REVIEW

**Comment by bakewellcake** [comment]
References #[4829]

**Comment by bakewellcake** [comment]
Added tests and defs. Not that familiar with TypeScript and tests so let me know what needs improving :)

**Comment by bdunham** [comment]
+1

**Comment by domwlkr** [comment]
Need this!

**Comment by WikiRik** [comment]
Closing this since it is still against `master`. Can be reopened if that changes.

**Comment by marziply** [comment]
I no longer use Sequelize, so I haven't found the bandwidth to fix this. When I get the time to, I might look into this again!

**Pull request closed without merging**
