### PR TITLE
removeColumn for column with foreign key constraint

### PR DESCRIPTION
**Pull request by treythomas123**
This is failing for me on MS SQL Server 2k8 R2. It might not be an issue on other database types, or newer versions of MSSQL.

Just adding failing tests for now, and will look into implementing a fix soon.

### CODE REVIEW

**Comment by treythomas123** [comment]
The error message coming back from SQL Server is:

```
ALTER TABLE DROP COLUMN manager failed because one or more objects access this column.
```

This seems like a similar problem to the one that was addressed in PR [4990](https://github.com/sequelize/sequelize/pull/4990), but this is for foreign key constraints rather than default constraints.

**Comment by treythomas123** [comment]
Looks like I may have inadvertently discovered another issue with schemas with this same PR (I don't see a way to tell the FK column which schema the referenced model is in). Took out the schema test for now, and will look into that separately.

**Comment by mickhansen** [comment]
Lots of failures currently

**Comment by treythomas123** [comment]
Yeah not sure why that's happening on mysql and mariadb. Seems like
the test is causing it. I'll try to look into it later today.

**Comment by treythomas123** [comment]
Should be good now. Had to add the same logic (dropping foreign key constraints before the column) for MySQL/Maria.

**Comment by mickhansen** [comment]
Thanks @treythomas123

**Pull request merged**
