### PR TITLE
Prevent closing connections on transaction commit on sqlite in-memory databases

### PR DESCRIPTION
**Pull request by little-big-h**
When committing transactions on in-memory (:memory:) sqlite databases the connection should not be closed - closing the connection causes the database to be dropped/reset. This request contains a test as well as a (somewhat hacky) solution to this problem.

### CODE REVIEW

**Comment by rbudiharso** [comment]
Also bump into this problem, any progress on this PR?

**Comment by janmeier** [comment]
This just needs some minor refactoring and a rebase to be mergeable - feel free to provide a new PR @rbudiharso  :)

**Comment by rfink** [comment]
Did this make it into any of the 2.0.x release candidates?

**Comment by mickhansen** [comment]
Merged 2 days ago so not yet

**Pull request merged**
