### PR TITLE
Fix nav links of synonymous sub-headings under Associations

### LINKED ISSUE #12197: The Philosophy Goal Implementation links all point to One-to-One
### What was unclear/insufficient/not covered in the documentation

The Philosophy, Goal, Implementation links under One-to-Many and Many-to-Many all point to the headings with the same names under One-to-One.

### If possible: Provide some suggestion on how we can enhance the docs

Fix the links to point to their corresponding headings.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by louy2**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Added new transform `fix-ids.js` to fix sub-heading ids and links under Association.

Closes #12197

### CODE REVIEW

**Comment by louy2** [comment]
Not sure how to add test for this one.

**Comment by louy2** [comment]
Got confused by the mechanics of `_.chain` but got it working

**Comment by louy2** [comment]
Also apparently `id` can only be set with `attr`.

**Comment by papb** [comment]
Great work @louy2, thank you very much!!

**Pull request merged**
