### PR TITLE
check result[0] is exists before read it.

### PR DESCRIPTION
**Pull request by pentium100**
Some times the variable results will be a 0 size array. 
when read results[0][autoIncrementFieldAlias] will cause app crash. 
so we need to check it before we read it.

### CODE REVIEW

**Comment by janmeier** [comment]
How can you have an insert query that doen't return anything? At least an insert coming from sequelize will always have `OUTPUT INSERTED` set.

Also, we need some regression tests

**Comment by pentium100** [comment]
when we save a model with options: {returning: false}, then insert query while return nothing.

**Comment by janmeier** [comment]
Ah, thats true :)

Just needs a regression test then

**Comment by janmeier** [comment]
Ping @pentium100

**Comment by janmeier** [comment]
Closing, no activity

**Pull request closed without merging**
