### PR TITLE
fix(5033): redefine message for mysql 8.0

### PR DESCRIPTION
**Pull request by lamuertepeluda**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

This PR should address the issue #5033 at least on MySQL 8.0, where the message for [ER_DUP_ENTRY](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_dup_entry) can be different from MySQL 5.7.

More into details, the error message will contain the table name dot-separated from the key (field name), causing the error message to be ignored, as explained [in this comment to the related issue](https://github.com/sequelize/sequelize/issues/5033#issuecomment-818652247)

### CODE REVIEW

**Comment by lamuertepeluda** [comment]
The relevant (only) commit is [this one](https://github.com/lamuertepeluda/sequelize/commit/b7fe0f75f205af3555fec5fbb469ba3e78a438bd).

I don't know why the MSSQL 2017 / Node 10 check is failing, but, after looking at the logs, this is more likely a CI pipeline issue.

**Comment by lamuertepeluda** [comment]
@papb I don't know if it is you the right person to ask to check, but this PR was previously failing because of #13193 , even if the fix is absolutely not related to MSSQL. It is rather a minor fix for MySQL 8.0 error messages.

**Comment by franklinjpt** [comment]
That really worked for me, thanks!

**Comment by WikiRik** [comment]
I looked into this, but isn't this already fixed in v6.9.0? When https://github.com/sequelize/sequelize/issues/13601 was fixed in https://github.com/sequelize/sequelize/pull/13610

**Comment by WikiRik** [comment]
Will close this since I believe this has been fixed in v6.9.0. If not we can always reopen.

**Pull request closed without merging**
