### PR TITLE
fix(paranoid): use Utils.now to query for paranoid records

### LINKED ISSUE #8006: Soft deleted rows are being returned in findAll using paranoid mode
## What you are doing?
Soft deletion of row sets `deletedAt` column with ```utils.now()``` ([look here](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L2473)). That means that the value would be machine's current timestamp. But when you'll try to retrieve data, the query for ignoring soft deleted rows would be using `CURRENT_TIMESTAMP` ([look here](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L81)) which is the DB's machine timestamp. If these two machines (Server and DB) clocks are not synced you'll end up with soft deleted rows included in your results. 

```js
const res = model.findAll(...)
```

## What do you expect to happen?
Shouldn't get soft deleted rows at all. The value that should be set upon deletion is `CURRENT_TIMESTAMP` as well.

## What is actually happening?
I'm getting rows which I've deleted.

__Dialect: postgres 
__Database version: 9.5
__Sequelize version: 4.3.2

### LINKED ISSUE #8202: Same second query for paranoid tables returning soft deleted records
## What you are doing?

```js
sequelize.define('user', {
  //...column definitions
}, {
  paranoid: true
});

User.find({
  where: {
    id: req.params.id
  }
}).then((user) => {
  console.log(user);
  user.destroy().then(() => {
    User.find({
      where: {
        id: req.params.id
      }
    }).then((deletedUser) => {
      console.log(deletedUser);
      console.log(new Date(new Date().toUTCString()).toISOString());
    });
  });
});

//run a second later
User.find({
  where: {
    id: req.params.id
  }
}).then((user) => {
  console.log(user);
});
```

## What do you expect to happen?
Second console.log should return null.

## What is actually happening?
Second console.log is returning the object again with a deletedAt field entered that matches the third console.log's output.  Remote MySQL server runs in UTC time.  Occurs on local development stations in EST as well as servers running in UTC time.  Similar to #7204.

Running another query a second later will return null.

__Dialect:__ mysql
__Database version:__ 5.7.11
__Sequelize version:__ 4.7.5

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

Fixes #8202
Fixes #8006
Closes #8204
Closes #7787

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Will also close https://github.com/sequelize/sequelize/pull/7787 but we dont have proper way to test that db / app server timezone difference.

If we distill what all those threads are saying, we can conclude 

1) `destroy` use `Utils.now` to set `deletedAt`
2) `_paranoidClause` use `CURRENT_TIMESTAMP` to query for those records

If db and app server use different timezone, this will surely get incorrect records.

I think we should use application server time, hence changing `_paranoidClause` to use `Utils.now` (Although a few of these threads suggest otherwise, i.e. use database server time in `destroy`)

**Comment by eseliger** [comment]
@sushantdhiman This sounds good! I'm down to using application server time for the clause.
One reason: 
If other logic might create dates in the application as well, those should match dates in the database.

**Comment by gabegorelick** [comment]
Correct me if I'm wrong, but I don't think this fundamentally fixes a lot of the linked issues because `Date` in JS is not a monotonic time source. In other words, it can move backwards (NTP, leap seconds etc) which would mess queries up. 

Happy to file an issue if you want to move discussion elsewhere.

**Comment by sushantdhiman** [comment]
@gabegorelick Most of linked issue are appearing because querying and setting of deletedAt are using entirely different construct (new Date vs CURRENT_TIMESTAMP), which would always fail for cross timezone interactions.

With this PR both construct aligns to use singular source i.e. new Date. This will ensure paranoid records aren't returned even if clocks aren't synced, because now we are using only app server clock for all cases.

Leap seconds like issues are a bit hard to test and honestly I don't worry about them in current context which is failing paranoid for every cross timezone case.

But you are free to discuss this among other contributors by opening an issue if you like to

**Comment by gabegorelick** [comment]
Thanks @sushantdhiman. We can continue discussion in https://github.com/sequelize/sequelize/issues/8496.

**Pull request merged**
