### PR TITLE
docs(data-types): move data-types.js to data-types/index.js

### PR DESCRIPTION
**Pull request by ALiangLiang**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

The `esdoc` group the classes by path. So I move `data-types.js` to `data-types/index.js` to separate to be a group.

image

to

image

### CODE REVIEW

**Comment by SimonSchick** [comment]
You will probably have to fix a bunch of include paths.

**Comment by sushantdhiman** [comment]
I don't think we should be moving file just for documentation stake. I would rather go for some different solution if available like `esdoc` config, CSS or a plugin may be

**Comment by papb** [comment]
@sushantdhiman Hi, any chance you would reconsider this? My PR #10898 improved things a bit but the [API Reference main page](https://sequelize.org/master/identifiers.html) is still cluttered. I could do something similar of #10898, but I think this would start getting way too complicated. With a separated folder we could also link directly to it, improving the datatypes manual, etc.

**Comment by papb** [comment]
Of course, to merge this my PR #10898 should be reverted, which I don't mind.

**Pull request closed without merging**
