### PR TITLE
fix: queryinterface does not provide existing fkeys when schema is used

### PR DESCRIPTION
**Pull request by denizkanmaz**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

`queryinterface.getForeignKeyReferencesForTable` (Postgres) does not provide existing foreign keys (when schema is used) therefore the ORM creates the same foreign key for every `sync` execution. Eventually, this causes to have multiple foreign keys for the same relation.

An example code block reproduces the issue can be found [here](https://stackoverflow.com/questions/64806845/sequelize-sync-duplicates-existing-foreign-key-associations).

This issue reproduced with the followings:
Postgres: 10.5
Node: 14.5
Dependencies:
pg: 8.5
pg-hstore: 2.3.3

The original PR: #12833

### CODE REVIEW

**Comment by sdepold** [comment]
Why are we doing this? What's the problem with passing the actual table name to the function instead of an object containing the table name?

**Comment by sdepold** [comment]
Never mind. I just found the typescript definition

**Review by sdepold — APPROVED** [review]

**Comment by liv1n9** [comment]
```
sequelize: 6.35.2
pg: 8.11.3
```
I still get this error
image

**Comment by liv1n9** [comment]
> ```
> sequelize: 6.35.2
> pg: 8.11.3
> ```
> 
> I still get this error after syncing database image
> 
> I'm using NestJS + sequelize-typescript. My config: image

I find the cause of it. It is due to the `schema` property, which is `"public"` in my case. After I remove it, the duplicate foreign keys and constraints are disapeared

**Pull request merged**
