### PR TITLE
fix the example at the docs home page

### PR DESCRIPTION
**Pull request by subjectix**
The previous code was calling then on the promise returned by `sync()` which obviously doesn't resolve into a `jane` instance!

### CODE REVIEW

**Comment by janmeier** [comment]
Woops, good catch :D

**Comment by subjectix** [comment]
thanks :grin:

**Comment by mickhansen** [comment]
Actually the previous code worked as well. The result of the outer chain is the result of any inner calls.

**Comment by subjectix** [comment]
@mickhansen Yeah you are right :+1:, since the callback returns a promise, the outer promise resolves to what the inner promise resolves to, I kinda didn't pay attention to the return. But i would guess it's clearer this way anyway: *you use what you create*.

**Pull request merged**
