### PR TITLE
Bump validator version to fix PRISMA-2021-0063 vulnerability

### PR DESCRIPTION
**Pull request by abdulgit2021**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

I've just merged #13350, so this is no longer needed.

**Comment by abdulgit2021** [comment]
Thanks Pedro,

Can you please publish the latest version.

**Comment by papb** [comment]
Done, the update is now available at [v6.6.5](https://github.com/sequelize/sequelize/releases/tag/v6.6.5)!

**Comment by abdulgit2021** [comment]
Thanks alot Pedro!

**Comment by abdulgit2021** [comment]
Hi Pedro,  looks like the latest version is still not available.. I am
facing the below error when trying to get it.

[image: image.png]


Thanks,
Abdul Samad

**Comment by papb** [comment]
@abdulgit2021 The image you attached did not appear here on GitHub. Also, I just ran `npm i sequelize` and got version `6.6.5` correctly.

**Comment by abdulgit2021** [comment]
It's working now.. thanks!

**Pull request closed without merging**
