### PR TITLE
Hotfix/docs nav nesting

### PR DESCRIPTION
**Pull request by sdepold**
Things will look like this afterwards (on the left currently online, on the right locally):

bildschirmfoto 2015-04-10 um 05 36 02

### CODE REVIEW

**Comment by janmeier** [comment]
Sweet :)!

**Comment by mickhansen** [comment]
Ah neat, the lack of nesting was bothering me too.

**Comment by mickhansen** [comment]
@sdepold mind squashing to a descriptive commit then i think it's good to merge.

**Comment by mickhansen** [comment]
Just noticed that the code highlighting looks really broken on the second image.

**Comment by janmeier** [comment]
Thats because rtd injects a highlight library for us - so the PR won't affect that

**Pull request merged**
