### PR TITLE
fix MSSQL select all tables

### PR DESCRIPTION
**Pull request by Groxot**
lib/query-interface.js

332 if (typeof tableName === 'object') {
333      schema = tableName.schema;
334      tableName = tableName.tableName;

### CODE REVIEW

**Comment by janmeier** [comment]
Cool, I like this way of fixing the issue better, since it keeps the change in mssql specific code.
Still needs a test though :)

Also, please squash all changes into a single commit once your are done

**Comment by Groxot** [comment]
I dont know how to work on GitHub, And my english is very bad =)
Sorry.

**Comment by janmeier** [comment]
I'd suggest you read some of githubs own articles on working with git / github then :)

https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/using-pull-requests/

It seems you are editing the files directly on github - you don't need to do that, [you can clone the repository to your own computer](https://help.github.com/articles/cloning-a-repository/), work on and commit the files from there. That will also allow you to run the tests locally and make sure they are passing before you push the change

**Comment by janmeier** [comment]
Your change is failing for mssql. Right now the same mapping (changing TABLE_NAME to tableName) is already happing in JS code [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query.js#L164-L171). However, I actually think it makes sense to have this directly in SQL so you may be able to just remove those lines

**Comment by Groxot** [comment]
But, i see that https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L333-L334 use same query...

**Comment by janmeier** [comment]
Those lines use the same properties yes - that is desired, since that code is used for all dialects - we want to do the same thing for all dialects.

Right now the mapping from `TABLE_NAME` to `tableName` for mssql is done in the query.js file in the lines i linked. Your PR is fixing the same issue, but in sql instead of JS code. I like your fix better, but that means you need to remove / rewrite the lines I linked. Right now the issue is being 'fixed' twice, thus the tests fail.

**Comment by mbroadst** [comment]
@Groxot if you just click on that link he posted above and completely remove the "handleShowTablesQuery" in the mssql query.js, then your code will work and we can merge this (given you also squash your commits)

**Pull request closed without merging**
