### PR TITLE
fix(postgres): reuse `searchPath` in `extractTableDetails`

### PR DESCRIPTION
**Pull request by WikiRik**
## Pull Request Checklist

- [X] Have you added new tests to prevent regressions?
- [X] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

This PR is just a simple recreation of #13045 but for `main`. Additional information can be found there

Closes #13045

### CODE REVIEW

**Comment by ephys** [comment]
I think this PR would be a good opportunity to extract https://github.com/sequelize/sequelize/pull/14687/files#diff-54c14e4744281a47d62196b5892c4004fec6e2f3c4d90f444aa3bd0a880f2209R83 which fixes many schema issues and has a different schema per dialect instead of 'public'

**Review by ephys — CHANGES_REQUESTED** [review]

**Comment by WikiRik** [comment]
I just copied that PR over to `main` since it was the only one that was open on v5 and seemed to pass the tests. But I will work on the schema issues as well, that will also help with some skipped tests in #15235

**Comment by ephys** [comment]
Should we reject #13045 based on my above comment (plus the fact that it's targeting v5)?

**Comment by WikiRik** [comment]
> Should we reject #13045 based on my above comment (plus the fact that it's targeting v5)?

Yes, let's close both and mention in the original PR that `searchPath` should not be used but we will fix the mentioned issue in an upcoming PR.

**Pull request closed without merging**
