### PR TITLE
ci: tag releases as alpha

### PR DESCRIPTION
**Pull request by sdepold**
Try to release new versions as alpha

### CODE REVIEW

**Comment by sdepold** [comment]
@ephys @ChrisCrewdson could this work?

**Comment by sdepold** [comment]
Since things cannot get worse by much, I'll merge it and see what happens

**Comment by sdepold** [comment]
tada:

```
alpha: 7.0.0-alpha.5
latest: 6.12.5
v4: 4.44.4
v5: 5.22.5```

**Comment by ChrisCrewdson** [comment]
Nice! That looks perfect! I'm glad you were able to solve this.

**Pull request merged**
