### PR TITLE
Singular through model

### PR DESCRIPTION
**Pull request by overlookmotel**
PR for https://github.com/sequelize/sequelize/issues/2415

When a through table model is auto-created in defining a many-to-many association, the current behaviour is for the model's name to be pluralized and the same as the table name. This behaviour is at odds with the general Sequelize convention of singular model names and plural table names.

This PR changes that behaviour to make the model names singular.

So now:

    Person.hasMany(Task);
    Task.hasMany(Person);

creates a through model called `PersonTask` with table name `PeopleTasks`.

When retrieving a many-to-many associated table using eager-loading, the attributes of the join table are available in a key named the same as the through model (i.e. singular). It used to be plural, which makes little sense since there is only a single row.

e.g.

    Person.findAll( { include: Task } )

returns:

    [ {
      name: 'Bob',
      Tasks: [ {
        name: 'Do the washing',
        PersonTask: { ... }
      } ]
    } ]

This PR also fixes a few places in the code where the table name was used where it should have been the model name.

### CODE REVIEW

**Comment by mickhansen** [comment]
@overlookmotel Any progress here? Would like to have it in before the 2.0 final release.

**Comment by overlookmotel** [comment]
@mickhansen Sorry, I've been overtaken by other work past two weeks. How long have I got before 2.0 final is released?

**Comment by mickhansen** [comment]
@overlookmotel in the coming days likely.

**Comment by overlookmotel** [comment]
Hahaha yes I never finished this did I? And after arguing so hard that it was an important things to do. Other things in life seem to be encroaching more and more into time I'd like to spend on projects like this. Ho hum... :(

So is the behavior re: model names now the same as it always was? Or did someone else make this change in the meantime?

**Comment by mickhansen** [comment]
@overlookmotel I think it's the same as always, in any case it's solved easily by defining the model yourself :)

I just figured i'd start closing the PR's that were older than a year ;p

**Comment by diurchenko** [comment]
Hi. In my current case I am trying to create magic functions that wrap my business logic entities and automatically provide db queries using sequelize. Any name transformations make generic code more complicated and less reliable :-/ Now I've bumped into pluralized `through` models.  Too bad this PR haven't made its way to the end.
Anyway, thank you all for your hard work 🙏

**Pull request closed without merging**
