### PR TITLE
Properly escape number 0 in query generator

### PR DESCRIPTION
**Pull request by zaggino**
This fixes issue #5300

### CODE REVIEW

**Comment by mickhansen** [comment]
#5300 deals with `false`, can you add a test for that aswell?

**Comment by zaggino** [comment]
@mickhansen it should be fine now

**Comment by mickhansen** [comment]
Great, now if i could simply ask you to squash your commits into a single descriptive one ala `fix #5300: false and 0 are now properly encoded when using JSON/JSONB`

**Comment by zaggino** [comment]
@mickhansen done

**Comment by mickhansen** [comment]
Thanks @zaggino

**Pull request merged**
