### PR TITLE
bug fix: queryType error in write pool

### PR DESCRIPTION
**Pull request by starfalling**

### CODE REVIEW

**Comment by starfalling** [comment]
Would you please apply this pull request? Thanks very much ~

**Comment by mickhansen** [comment]
Hi @starfalling, i'll make sure to get around to it soon.

**Comment by starfalling** [comment]
Would you please apply this pull request? Thanks very much ~

**Comment by mickhansen** [comment]
Sorry for the long wait, 1.7 hasn't really been a focus.

**Comment by starfalling** [comment]
And would you please help release an update version?

Because read, write pool doesn't work at all when this bug exists, we need it can be installed with npm.

Thanks a lot~

**Comment by starfalling** [comment]
We have some old system running on version 1.7*

**Comment by mickhansen** [comment]
Looking at it, i assume you've just pointed your package.json at git this whole time?

**Comment by mickhansen** [comment]
Alright, just to let you know we don't support it, we are on 3.2.x now

**Comment by mickhansen** [comment]
Published as 1.7.11

**Comment by starfalling** [comment]
Thanks very much~

**Pull request merged**
