### PR TITLE
feat(postgres): support connectionTimeoutMillis dialectOption

### PR DESCRIPTION
**Pull request by mmfKupl**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [x] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Add support of "connectionTimeoutMillis" option for PostgreSQL dialect
https://node-postgres.com/api/client

### CODE REVIEW

**Comment by sdepold** [comment]
I think this should target main and we cherry pick it over. How confident are we that the camel case notation is correct where all the other props seem to prefer underscores.

To be investigated:

Do we have tests for that?
Do we document the supported options somewhere?
Is there actually any reason to not just forward all passes option to the driver in question? Why would sequelize do a sanity check in the first place?
Can we make use of the drivers typescript annotations to prevent people passing rubbish?

**Comment by sdepold** [comment]
Thanks for your pr :)

**Comment by ephys** [comment]
I agree with the sanity check being redundant. I think dialectOptions should be passed to the dialect as-is

**Comment by sdepold** [comment]
> I agree with the sanity check being redundant. I think dialectOptions should be passed to the dialect as-is

@mmfKupl Interested in doing that change?

**Comment by mmfKupl** [comment]
> > I agree with the sanity check being redundant. I think dialectOptions should be passed to the dialect as-is
> 
> @mmfKupl Interested in doing that change?

Yes. I will change my pr with this comment

**Comment by ephys** [comment]
`clientMinMessages`, `odbcConnectionString` `authentication`, `debug`, and `prependSearchPath` are the 5 dialect options I could find that are handled by Sequelize

I think we'll leave things as they are right now and we'll revisit what dialectOptions is meant to be in Sequelize 8 when we split the dialects to their own packages. It should allow us to strictly type `dialectOptions` based on the dialect.

**Review by ephys — APPROVED** [review]

**Pull request merged**
