### PR TITLE
Fix some cases where $or is not correctly converted

### PR DESCRIPTION
**Pull request by Verdier**

### CODE REVIEW

**Comment by mickhansen** [comment]
Dumb mistake on my part, will merge when tests pass.

**Comment by Verdier** [comment]
Is there a problem with CI? No test pass...

**Comment by mickhansen** [comment]
If you check the build errors you will see that your change does not pass linting.

**Comment by mickhansen** [comment]
Looks like you broke some unit tests.

**Comment by Verdier** [comment]
Ok I'll have a look on that tomorrow.

2015-11-30 19:45 GMT+01:00 Mick Hansen <notifications@github.com>:

**Comment by Verdier** [comment]
@mickhansen could you comfirm that the test is bad:
```js
        testsql('$or', [
          {
            roleName: 'NEW'
          }, {
            roleName: 'CLIENT',
            type: 'CLIENT'
          }
        ], {
          default: "([roleName] = 'NEW' OR ([roleName] = 'CLIENT' AND [type] = 'CLIENT'))"
        });
```
should be:
```js
        testsql('$or', [
          {
            roleName: 'NEW'
          }, {
            roleName: 'CLIENT',
            type: 'CLIENT'
          }
        ], {
          default: "([roleName] = 'NEW' OR ([roleName] = 'CLIENT' OR [type] = 'CLIENT'))"
        });
```

**Comment by Verdier** [comment]
Mmm... no, not sur. Looks like it's a bite more complicated.

**Comment by mickhansen** [comment]
No that test is correct. $or with array supports multiple conditions per array item, those conditions use AND unless specified with $or aswell.

**Pull request closed without merging**
