### PR TITLE
fix(types): adds missing function signature to Model.prototype.previous() types

### PR DESCRIPTION
**Pull request by danielschwartz**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [N/A] Have you added new tests to prevent regressions?
- [N/A] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

In the type definition for `previous()` on a model instance, the only specified signature is for when you pass in an argument to get a specific properties previous value. However, Sequelize will let you call `previous()` with no arguments and get an object back that maps all changed properties to their previous values. This PR adds that additional function signature to the type definitions so you can use `previous()` that way as well.

### CODE REVIEW

**Comment by Keimeno** [comment]
The type `Record<string, unknown>` definitely is a good addition, but doesn't offer strict type safety. Wouldn't it make more sense to return the type `TCreationAttributes`?

**Comment by danielschwartz** [comment]
@Keimeno good call, I will update the PR with `Partial<TCreationAttributes>` as the return type and then hopefully we should be good to go

**Comment by papb** [comment]
Hello! Thanks for the PR. I see a lot of formatting changes here though, such as newlines and changing single-quotes to double-quotes, maybe you have prettier enabled or something, can you undo those and focus your PR on the exact intended change please?

**Comment by danielschwartz** [comment]
@Keimeno @papb sorry about the auto formatting stuff. My VSCode was set to `formatOnSave`. Those formatting changes are now backed out and all the checks are passing. Let me know if you need anything else from me to get this merged. Thanks! 🚀

**Comment by Keimeno** [comment]
@danielschwartz happened to me all the time as well 😃.

A hacky fix I've found for this:
1. Download the `tbremer.path-settings` extension
2. Add the following setting to your settings.json:
```json
"pathSettings.rules": [
    {
      "path": "sequelize",
      "settings": {
        "editor.formatOnSave": false,
      }
    }
  ]
```

This automatically disables the `formatOnSave` rule if `sequelize` is in your path name.

**Comment by danielschwartz** [comment]
@papb @Keimeno I saw a new release was cut today but this wasn’t merged in yet. I also see this PR still has an “awaiting response” status.

Is there anything else this PR needs to be merged? Would love to have this fix merged in so I can stop patching my local version. Thanks!

**Comment by Keimeno** [comment]
We need to tag @papb for that, this PR was probably overlooked.

It's good if you additionally add typing tests with [expect-type](https://www.npmjs.com/package/expect-type), but that can also be done in a separate PR.

**Comment by papb** [comment]
Hello! I am sorry for the delay. Can you please fix the conflict?

**Comment by danielschwartz** [comment]
@papb this should be good to go. I've fixed the merge conflict caused by the latest release and also added a test. Let me know if you need anything else to get this merged in.

**Review by papb — APPROVED** [review]
Nice! Thanks!

**Pull request merged**
