### PR TITLE
Return null to tell Bluebird non-return is intentional

### PR DESCRIPTION
**Pull request by scragg0x**

### CODE REVIEW

**Comment by mickhansen** [comment]
I don't believe it's needed for `new Promise` since it's not actually inside a `then` or chain otherwise.

**Comment by scragg0x** [comment]
hmm, I still see a bunch of these.  Are you saying it will go away once Bluebird is updated on sequelize?

**Comment by mickhansen** [comment]
@scragg0x If they are originated from the sequelize codebase it needs to be updated in Sequelize, i just don't think the line you changed has any effect since it's not a promsie chain callback, its a `new Promise` call which would ignore its return value.

**Comment by mickhansen** [comment]
Hmm interesting, well can't hurt i guess.

**Pull request merged**
