### PR TITLE
Foreign keys with allowNull: false with new default values

### LINKED ISSUE #2831: ON DELETE constraint should default to CASCADE if foreignKey has allowNull: false
```js
var Foo = this.sequelize.define('Foo', { 
  bar_id: { type: Sequelize.INTEGER, allowNull: false }
});
var Bar = this.sequelize.define('Bar', {});

Foo.belongsTo(Bar, { foreignKey: 'bar_id'});

return Bar.sync({force: true}).then(function () {
  return Foo.sync({force: true});
});
```

Will fail on MySQL (haven't tested others so far) because the cascade defaults to SET NULL which "obviously" (took me a while to figure it out) obviously doesn't work well with a field that can't be NULL'ed.

Sequelize should check the foreignkey attribute definition, and if allowNull is false it should perhaps either use CASCADE by default or turn off constraints.

### PR DESCRIPTION
**Pull request by Americas**
* CASCADE on hasOne/hasMany
* NO ACTION on belongsTo

Fixes #2831

### CODE REVIEW

**Comment by janmeier** [comment]
Changes look good - could you add a couple of tests? Unit tests that just check the constraints are set to the right thing are fine, no need for integration tests for this change

**Comment by Americas** [comment]
OK, I will add them ASAP, hopefully today!

**Comment by Americas** [comment]
I love this git voodoo magic.. :laughing: 

Tests were added.

**Comment by mickhansen** [comment]
Some breaks for mysql/pg

**Comment by mickhansen** [comment]
Errors look unrelated though, trying a rerun

**Comment by Americas** [comment]
the schema part is related to the change, I'm checking it now

**Comment by Americas** [comment]
I changed the behavior of the associations in a way that the first association would set the defaults, and that is what broke the tests. Changed it back to the hasOne association doing a default override when it exists.

**Comment by mickhansen** [comment]
Looks like it needs a rebase @Americas

**Comment by Americas** [comment]
rebased

**Comment by mickhansen** [comment]
Thank you for your work @Americas

**Pull request merged**
