### PR TITLE
fix(types): add keepDefaultTimezone to Options interface

### PR DESCRIPTION
**Pull request by BeeMargarida**
### Pull Request Checklist

- [X] Have you added new tests to prevent regressions?
- [X] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [X] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

The `Options` interface did not include the attribute `keepDefaultTimezone`, which can be received as an option (by looking at the Sequelize constructor).
This PR adds that attribute to the `Options` interface.

### CODE REVIEW

**Review by sdepold — CHANGES_REQUESTED** [review]
I think we should add a description on what it's doing and the default value too?

**Comment by BeeMargarida** [comment]
> I think we should add a description on what it's doing and the default value too?

I don't wanna commit mistakes, is the following correct?
```
Uses the default timezone to convert dates from the database.

@default false
```

**Comment by sdepold** [comment]
It actually seems that the option is undefined by default, which is a bit of a problem. Should we explicitly set it to false here? https://github.com/sequelize/sequelize/blob/main/src/sequelize.js#L213

**Comment by BeeMargarida** [comment]
> It actually seems that the option is undefined by default, which is a bit of a problem. Should we explicitly set it to false here? https://github.com/sequelize/sequelize/blob/main/src/sequelize.js#L213

Seems good to me, already made that change 👍 I'll push the commit

**Review by sdepold — CHANGES_REQUESTED** [review]
One last detail: Can you add the new property to this test? https://github.com/sequelize/sequelize/blob/main/test/types/sequelize.ts#L11

**Comment by BeeMargarida** [comment]
> One last detail: Can you add the new property to this test? https://github.com/sequelize/sequelize/blob/main/test/types/sequelize.ts#L11

Yap, done!

**Review by sdepold — APPROVED** [review]
Thanks :)

**Pull request merged**
