### PR TITLE
fix(mariadb): properly escape json path key

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Properly escape JSON path keys for mariadb dialect

### CODE REVIEW

**Comment by shivasurya** [comment]
@sushantdhiman  thank you for the fix and time. 
1. can you please elaborate on the fix and security report. ( i subscribed to snyk for security updates and CVE as this may be helpful for others -> https://snyk.io/vuln/SNYK-JS-SEQUELIZE-450222 , https://snyk.io/vuln/SNYK-JS-SEQUELIZE-450221 )
2. can we add additional security label and dedicated security release page with alerts in website which will be helpful for getting instant alerts on security release.

Once again thank you for this library and updates 🙏

**Comment by jansoltis** [comment]
Is there any chance this will be released also as part of Sequelize 4.x
Thank you for fixing it!

**Comment by papb** [comment]
@jansoltis - Out of curiosity, may I ask what is preventing you from updating to v5? (just to better understand the problems faced by the user base)

**Comment by jansoltis** [comment]
@papb That's a good point. Somehow I thought it is difficult for us to update to v5, but now that I'm looking at the release notes it seems doable (there are still quite some changes though). We were planning to update at some point anyway so perhaps it's the right time. Thank you for asking the right questions!

**Comment by sushantdhiman** [comment]
@jansoltis If you can backport these changes to v4 we can push new release for you

**Comment by papb** [comment]
@sushantdhiman Why did semantic-release bot trigger for so many PRs for v7?

**Comment by sushantdhiman** [comment]
Not sure @papb , I will delete that release

**Pull request merged**
