### PR TITLE
Fix subquery check required association exists ☀️ v4

### PR DESCRIPTION
**Pull request by 4e1ovek**
When checking the required association exists, it is not considered necessary the name of the alias table to work properly WHERE.

```diff
Query before making any changes:
- SELECT "User".*, "postaliasname"."id" AS "postaliasname.id", "postaliasname"."title" AS "postaliasname.title" FROM (SELECT "User"."name", "User"."age", "User"."id" AS "id" FROM "User" AS "User" WHERE ( SELECT "user_id" FROM "Post" AS "Post" WHERE ("Post"."user_id" = "User"."id") LIMIT 1 ) IS NOT NULL) AS "User" INNER JOIN "Post" AS "postaliasname" ON "Model"."id" = "postaliasname"."user_id";

Query after making changes:
+ SELECT "User".*, "postaliasname"."id" AS "postaliasname.id", "postaliasname"."title" AS "postaliasname.title" FROM (SELECT "User"."name", "User"."age", "User"."id" AS "id" FROM "User" AS "User" WHERE ( SELECT "user_id" FROM "Post" AS "postaliasname" WHERE ("postaliasname"."user_id" = "User"."id") LIMIT 1 ) IS NOT NULL) AS "User" INNER JOIN "Post" AS "postaliasname" ON "Model"."id" = "postaliasname"."user_id";
```

Earlier I sent a request with this bug for version 3 (https://github.com/sequelize/sequelize/pull/7741) but the problem persists to this day in version 4.2.1

### CODE REVIEW

**Comment by 4e1ovek** [comment]
The testing platform does not work correctly and gives different results for the same source code. In my opinion is due to errors in connecting to databases.

**Comment by felixfbecker** [comment]
Build is broken

**Comment by 4e1ovek** [comment]
@janmeier @sushantdhiman
Hi guys, please Merge approved request. I want to move my project from version 3 to version 4. At the moment, use the hard code fixes this problem.

**Comment by felixfbecker** [comment]
You need to fix what is breaking the build before we can merge.

**Comment by 4e1ovek** [comment]
@janmeier @sushantdhiman
Guys, all ready to merge in master.

**Pull request merged**
