### PR TITLE
fix(sqlite): don't break when adding a 2nd constraint to a table

### PR DESCRIPTION
**Pull request by knoid**
This PR just shows an error. I'm not sure how to solve it. It's related to #11066

### CODE REVIEW

**Comment by knoid** [comment]
Not sure how elegant this solution is, but the modified test now passes.

**Comment by SimonSchick** [comment]
Tests are failing tho.

**Comment by knoid** [comment]
https://travis-ci.org/sequelize/sequelize/jobs/545942214 failed and doesn't look related. I can even find the test I changed in those logs.

https://ci.appveyor.com/project/sushantdhiman/sequelize/builds/25295246 failed in `[MSSQL] Configuration` and seems to be failing randomly on previous PRs.

Anyway to run them again?

**Comment by knoid** [comment]
@SimonSchick travis' tests are passing now 😄

**Comment by papb** [comment]
@knoid Thanks for this! Sorry for the delay to respond.

Could you please add a whole new test instead of modifying one that already exists (as you did)?

**Comment by knoid** [comment]
done! I had to fix removeConstraint too :stuck_out_tongue:

**Pull request merged**
