### PR TITLE
fix: dont treat `?&` or `?|` as replacements

### PR DESCRIPTION
**Pull request by ephys**
Special cases the `?&` and `?|` postgres operators so their question mark is not treated as a replacement. 

See https://github.com/sequelize/sequelize/issues/14358 for details.

Closes https://github.com/sequelize/sequelize/issues/14358

### CODE REVIEW

**Review by fzn0x — APPROVED** [review]

**Comment by WikiRik** [comment]
What is the intended behaviour for things like `?|?`, `??|` or  ?||`?

**Comment by ephys** [comment]
Very good question :) Let's add tests, especially since `||` is an actual operator

**Comment by ephys** [comment]
`?|?` would be treated as `?|<replacement>`
`??|` would be treated as `<replacement>?|`
`?||` would be treated as `?||`

Should we make all `?` preceded or succeded by `?`, `&` or `|` as not being replacements?

**Comment by WikiRik** [comment]
No, I think this should be fine. But I think we should add these operators to sequelize directly so they are more robust. That's for another PR though

**Comment by WikiRik** [comment]
Maybe the `?||` should become `<replacement>||` though, but not sure

**Comment by ephys** [comment]
> should add these operators to sequelize directly so they are more robust

Unfortunately, because of when bind & replacements are parsed, they would still be interpreted as replacements (cf the recent conversation we had in core), until https://github.com/sequelize/sequelize/tree/ephys/fix-13817 is implemented that is

> Maybe the `?||` should become `<replacement>||` though, but not sure

I would actually say the opposite: always consider that ? to not be a replacement so people learn to surround their replacement with a space, to avoid clashes with potential future operators

**Comment by WikiRik** [comment]
> > should add these operators to sequelize directly so they are more robust
> 
> Unfortunately, because of when bind & replacements are parsed, they would still be interpreted as replacements (cf the recent conversation we had in core), until https://github.com/sequelize/sequelize/tree/ephys/fix-13817 is implemented that is

Ah yes

> > Maybe the `?||` should become `<replacement>||` though, but not sure
> 
> I would actually say the opposite: always consider that ? to not be a replacement so people learn to surround their replacement with a space, to avoid clashes with potential future operators

Hmm... I did not really consider that before. That might not be too bad. I think we should just merge this one for now and think about this again later (but before we release v7)

**Comment by ephys** [comment]
Sounds good to me

**Pull request merged**
