### PR TITLE
fix(typings): added 'fieldMaps' to QueryOptions typings

### PR DESCRIPTION
**Pull request by techguysid**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This PR fixes the [https://github.com/sequelize/sequelize/issues/11567](https://github.com/sequelize/sequelize/issues/11567) issue.

### CODE REVIEW

**Comment by zanctor** [comment]
@techguysid, seems like "fieldMap" property name is singular, not plural.

**Comment by techguysid** [comment]
@zanctor @papb - This is ok I mean all checks are passing, can you let me know if it looks good?

**Comment by zanctor** [comment]
@papb, will you have a chance to review and merge this pull request?

**Comment by sushantdhiman** [comment]
No tests but not critical for typings. Thanks for this contribution

**Comment by Ciul** [comment]
Would be nice if `fieldMap` could be a function too, for example, to camel case every field name in raw queries.

**Pull request merged**
