### PR TITLE
Fix non public schema for PostgreSQL

### PR DESCRIPTION
**Pull request by inDream**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Have you added an entry under `Future` in the changelog?

_NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open._

### Description of change
Assign schema value to model to fix the following issues:
#7624 #7085 #6832 #6336 #5901 #5864 #5233

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Needs tests @inDream where schema wont work without your fix

**Comment by inDream** [comment]
@sunshinewyin I assume `new Sequelize(options)` would apply option.schema to all tables but it's not and this fixes is needed. And where should I place the tests as I need to change the connect config.

**Comment by inDream** [comment]
@sushantdhiman Test added and could you help me restart the failed test.

**Comment by inDream** [comment]
@sushantdhiman ping

**Comment by inDream** [comment]
@sushantdhiman @eseliger @felixfbecker @janmeier ping

**Comment by sushantdhiman** [comment]
Sorry @inDream it took so long to address this issue. This will be auto deployed as `v4.4.9` once Travis CI finishes https://travis-ci.org/sequelize/sequelize/builds/264251980?utm_source=github_status&utm_medium=notification

**Comment by inDream** [comment]
@sushantdhiman Thank you very much.

**Comment by stonedraider** [comment]
is this still not fixed? I was looking for many solutions by nothing worked for me. Is it not possible to specify custom schemas in postgres with sequelize properly?

**Comment by bkvittal** [comment]
> is this still not fixed? I was looking for many solutions but nothing worked for me. Is it not possible to specify custom schemas in postgres with sequelize properly?
> I tried to set "schema" : "xyz" in config.json, added the code for custom_schema in index.js and have schemas specified in files with sequelize.define and migration files with "up" method. however I still get "ERROR: relation "Todos" does not exist" for TodoItems which have a reference on Todos in not public schema.
> 
> When I only specify schema in config.json - which should be enough to fix the issues(?) - the only table that will be created in custom schema is "Sequelize Meta". All other tables will still be created in public schema.
> I use latest version of sequelize 4.26.0

Hello stonedraider,

Were you able to find the solution to the problem where you were not able to use your own custom schema in nodejs / postgresql / sequelizejs ? If you did please share the solution with me. thank you.

**Pull request merged**
