### PR TITLE
meta: replace release on push to v7 branch with manual releases

### PR DESCRIPTION
**Pull request by ephys**
Currently, the way we publish changes for v7 is by merging main into v7

This sounds a bit unnecessary complex to me. This also requires separate branch protection rules for the v7 branch that are less restrictive, and means that the code we publish is not guaranteed to be the same as the one on main.

I think it's better to delete the v7 branch, and publish from the main branch by running a manually triggered workflow

If we want to do automatic releases, we'll just need to add the 'push' event to the condition

### CODE REVIEW

**Comment by WikiRik** [comment]
I think we didn't consider manually triggering workflows before (not sure if that was even an option back then).

While we're not working on v8, I think releasing from main sounds good.

**Review by WikiRik — APPROVED** [review]

**Comment by WikiRik** [comment]
Do we have other references to the v7 branch that we need to update? In the settings of the repo or on our website? Or maybe even the README?

**Comment by ephys** [comment]
I couldn't find any other reference, I hope I didn't miss anything

I added an auto-deletion the CHANGELOG files to avoid duplication. It's on the precommit hook because I couldn't find any good way of doing this in lerna directly

**Comment by WikiRik** [comment]
I see other projects sometimes have a Unreleased heading at the top of the CHANGELOG file, is that something we can use as well? Might be good to have a CHANGELOG somewhere in the repo since that is often used

**Comment by ephys** [comment]
That could be done, but I don't see anything in lerna that can be used for this

I propose to set that up separately

There is also the issue that our changelog often has mistakes in it, or missing breaking changes, so I often update the changelog in our releases tab. For this reason I'd love to have our changelog be centralized there so I don't have 3 other places to update (CHANGELOG.md, twitter, opencollective)

**Review by WikiRik — APPROVED** [review]

**Comment by ephys** [comment]
I forgot one important detail with this PR: We need to allow lerna to push to the main branch without going through a pull request

That's not possible using `GITHUB_TOKEN` for good reasons: https://github.com/orgs/community/discussions/25305#discussioncomment-3247401. The `GITHUB_TOKEN` is available in all PRs, including the ones made by people outside of the org, so they could just modify the workflow to add arbitrary code to `main` then trigger a publish.

That means we need to use a PAT instead. Could be mine, could be a bot. This is safer because these secrets are not available in PRs made by users outside of the sequelize org.

**Comment by WikiRik** [comment]
Shared account sounds good, including passkeys. We can use the shared account for some other workflows as well, like the AUTHORS.md update (which is broken due to an automerged update)

**Comment by ephys** [comment]
Actually, I'll see how easy it would be to create a GitHub App that belongs to our org first

**Comment by ephys** [comment]
Edit: done & added the app ID and private key to our repo secrets

All that remains is updating the workflows:

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow

**Pull request merged**
