### PR TITLE
consistent results from instance.update/destroy and Model.update/dest…

### PR DESCRIPTION
**Pull request by alekbarszczewski**
…roy (respecting returning option).

WARNING: breaks BC with 3.x

``` javascript
instance.update({}, options)
// beforeUpdate: (instance, options)
// afterUpdate: (instance, options) - instance is null if not updated, instance contains fetched data if options.returning
.then(function(instance){}) // - instance is null if not updated, instance contains fetched data if options.returning

instance.destroy(options)
// beforeDestroy: (instance, options)
// afterDestroy: (instance, options) - instance is null if not deleted, instance contains fetched (deleted) data if options.returning
.then(function(instance){}) // - instance is null if not deleted, instance contains fetched (deleted) data if options.returning

Model.update({}, options)
// beforeBulkUpdate (options)
// afterBulkUpdate (options)
.then(function([rows, instances]){}) // instances not present if result array if !options.returning

Model.destroy({}, options)
// beforeBulkDestroy (options)
// afterBulkDestroy (options)
.then(function([rows, instances]){}) // instances not present if result array if !options.returning
```

### CODE REVIEW

**Comment by janmeier** [comment]
Looks good, except for a few tests which need to be change to the new return format

However, we still haven't decided how we want to handle bc breaks - maintaining a separate branch turned out to be a PITA in the past ...

**Comment by janmeier** [comment]
@alekbarszczewski so, finally master is now 4.0 - Are you up for re-applying this :) ?

**Comment by janmeier** [comment]
PR CLEANUP: No response for a _long_ time

**Comment by suratovvlad** [comment]
@alekbarszczewski @janmeier 
Hi! What's about this feature for destroy?

**Pull request closed without merging**
