### PR TITLE
meta: update updated_at on upsert

### PR DESCRIPTION
**Pull request by joker00777**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [ ] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Todos

- [ ] 
- [ ] 
- [ ]

### CODE REVIEW

**Comment by WikiRik** [comment]
Interesting that tests pass without any changed test. Might that be because of line 2522?

Either way, can you provide a test that is failing on `main` but passes now with this change?

**Comment by joker00777** [comment]
Sure : )

**Comment by joker00777** [comment]
After reading the code , I think they have made an assumption that the user can send updatedAt during upsert and if they have send a custom updatedAt in that case we will use that otherwise we will update updatedAt to current time.

**Comment by sdepold** [comment]
I tend to recall that we have just recently changed this to cater for the insertattributes. Maybe it should check both attributes?

Anyway, a test case is a good idea

**Comment by joker00777** [comment]
insertValues have all the values including primaryKey in the other hand updateValues have all values other than primary key.
So I don;t think there is a test case which will fail while checking with insertValues.

**Comment by WikiRik** [comment]
So what would be the benefit of this PR? Just a simple refactor in case we do something with `insertValues` in the future that would break this?

**Comment by joker00777** [comment]
I think updated_at should come from updateValues as it makes sense there.In future this could help if updatedValues and insertValues differ from more than just primary key

**Comment by WikiRik** [comment]
Agree

**Review by WikiRik — APPROVED** [review]

**Pull request merged**
