### PR TITLE
[WIP] Hooks refactoring proposal using stack-queue

### PR DESCRIPTION
**Pull request by cusspvz**
Proposal related with discussion on #2932

### CODE REVIEW

**Comment by cusspvz** [comment]
Since i can't test locally (problems with my own docker), I'm gonna use travis, sorry... :/

**Comment by cusspvz** [comment]
```
1) [SQLITE] Hooks #destroy via DAOFactory .hook() method with multiple hooks on success should run all hooks:
     TypeError: Bad hook type, please check docs for right constructor hook names
      at Hooks.hook.Hooks.addHook (/home/travis/build/sequelize/sequelize/lib/hooks.js:201:11)
      at Context.<anonymous> (/home/travis/build/sequelize/sequelize/test/integration/hooks.test.js:2418:25)
      at Test.Runnable.run (/home/travis/build/sequelize/sequelize/node_modules/mocha/lib/runnable.js:217:15)
      at Runner.runTest (/home/travis/build/sequelize/sequelize/node_modules/mocha/lib/runner.js:373:10)
      at /home/travis/build/sequelize/sequelize/node_modules/mocha/lib/runner.js:451:12
      at next (/home/travis/build/sequelize/sequelize/node_modules/mocha/lib/runner.js:298:14)
      at /home/travis/build/sequelize/sequelize/node_modules/mocha/lib/runner.js:308:7
      at next (/home/travis/build/sequelize/sequelize/node_modules/mocha/lib/runner.js:246:23)
      at Object.<anonymous> (/home/travis/build/sequelize/sequelize/node_modules/mocha/lib/runner.js:275:5)
      at Object._onImmediate (/home/travis/build/sequelize/sequelize/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

Is [this](https://github.com/sequelize/sequelize/blob/master/test/integration/hooks.test.js#L2418) a typo error or is it intended?

**Comment by cusspvz** [comment]
@janmeier @mickhansen how is the support for universal hooks?

Seems that currently all them are binded into `sequelize` instance, shouldn't them be hooked at `Model` constructor instead?

For compability with `stack-queue` i've just created a system that creates stacks for each hook type on `Constructor` itself or either on `Prototype` for their instances.

Sequelize constructor example:
```
  // Hooks for constructor
  Hooks.ify( Sequelize, [ 'before', 'after' ], [
    'init'
  ]);

  // Hooks for constructor instances
  Hooks.ifyPrototype( Sequelize, [ 'before', 'after' ], [
    'define'
  ]);
```

For aliased support I'm sharing the same stack across the `hooks` object with different keys, configuration example:

```js
  Hooks.ifyPrototype( Model, [ 'before', 'after' ], [
    // ...
    'bulkCreate', // single hook stack
    [ 'destroy', 'delete' ], // shared hook stack
  ]);
```

**Comment by mickhansen** [comment]
We have support for defining stuff like `beforeUpdate` on the sequelize instance.
It's not terrible well documented but a know a few production systems that use it.

**Comment by cusspvz** [comment]
What do you think i should do here? Break old support?

IMHO, makes more sense to apply global hooks on an `afterDefine` hook.

**Comment by mickhansen** [comment]
@cusspvz "old" being?
We're not really looking to break that much more backwards compat in 2.0.

**Comment by cusspvz** [comment]
In that case, i would support it by binding proxy functions. If today i met my milestones, i would finish this up! :)

This PR should give an advance also on `beforeFind` short-circuit/results returning.
I would appreciate if you place your opinion about next stack-queue control API on findhit/stack-queue#2 issue.

**Pull request closed without merging**
