### PR TITLE
Bug in docs: mysql package needed, NOT mysql2?

### PR DESCRIPTION
**Pull request by TheNotary**
The example connection code would throw an error until I installed mysql as apposed to mysql2.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Sequelize 4 uses mysql2, Sequelize 3 mysql. The docs on master are correct.

**Comment by TheNotary** [comment]
ah, my mistake

**Comment by TheNotary** [comment]
You know, now that I think about it, the `npm install sequelize` isn't a correct form either, because that defaults to sequelize v3 at present.  Maybe that bit of it should be updated instead?

**Comment by sushantdhiman** [comment]
@TheNotary `npm` is correct as it installs stable version i.e. `v3`, `v4` or `master` is currently under development and not that stable. Once we think its stable enough `npm` will default to `v4` as well

**Pull request closed without merging**
