### PR TITLE
Bugfix/order clause in subquery 

### PR DESCRIPTION
**Pull request by fogine**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Have you added an entry under `Future` in the changelog?

Note: because I use `postgres v9.3` few test cases (14) does not pass because of unsupported new features which were introduces in postgres v9.4 like (jsonb, type geometry)... I expect the tests to work including those which are using new features of postgres v9.4. Although I did not run tests wit postgres v9.4 installed.

### Description of change

The problem is that if you make a select query with `order`,`limit`,`offset` clauses and with `include` of a association which will cause subquery generation. The `order` clause is not included in the subquery when you provide `order` option in form of plain string (not an array). This pull request fixes that.

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Bad merge, you will need to rebase :)

**Comment by sushantdhiman** [comment]
Also is this intended to merge with `v3` or `master`, It contain commits from `v3` that we will not be merged back to `master`.

You need to create PR with correct `base` and `target` branches

**Comment by fogine** [comment]
> Also is this intended to merge with v3 or master, It contain commits from v3 that we will not be merged back to master.

It's intended to merge with `v3`

**Comment by sushantdhiman** [comment]
Looks like its being merged to `master` atm, change the `base` branch

**Pull request closed without merging**
