### PR TITLE
fix(types): fix incorrect type for Op.overlap argument

### PR DESCRIPTION
**Pull request by werkshy**
The overlap operator `&&` is true when any element from one array is
present in the other array. For this reason the type of the
right-hand-side of the Op.overlap operator should be an array, not a
Rangeable.

This problem was exposed with the upgrade to Typescript 4.4.

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by sdepold** [comment]
@werkshy just seeing now that there is no test case. do you have an example for this change?

**Comment by sdepold** [comment]
@AllAwesome497 Would you like to create a replacement for this PR?

**Comment by werkshy** [comment]
Sorry folks, I clearly don't have time to work on this. I would have added tests but I found the tests didn't run to completion in a reasonable time on my laptop and it wasn't clear how to run a subset.

**Comment by ephys** [comment]
You can use `npm run test-typings` (i think) to only run typing tests

I'm still interested in seeing this merged, I'll keep it open and tag it as need maintainer until we have a replacement :)

**Comment by ephys** [comment]
I'm taking over this PR and including it in https://github.com/sequelize/sequelize/pull/14022

**Pull request closed without merging**
