### PR TITLE
build(deps): move @types/validator to prod deps

### PR DESCRIPTION
**Pull request by WikiRik**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [X] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

I've moved @types/validator to the prod dependencies since their respective dependency is also a prod dependency and we need the types available for the TS migration.
I've also regenerated the yarn.lock file. This cleaned up unnecessary versions of some packages. But probably dependabot or renovate will not agree with it fully so some of these changes will be undone in their next PR

### CODE REVIEW

**Comment by ephys** [comment]
OK for `@types/validator` but `@types/node` should remain in devDeps as its version is controlled by the user

**Comment by WikiRik** [comment]
> OK for `@types/validator` but `@types/node` should remain in devDeps as its version is controlled by the user

I believe that it also mentions in the typedocs what version things were added but to be safe I put that back

**Review by ephys — APPROVED** [review]
Can you update the typescript.md documentation to remove the mention of `@types/validator`?

**Comment by WikiRik** [comment]
Ah yes, I forgot about the docs. Done

**Review by ephys — APPROVED** [review]
good to go :)

**Pull request merged**
