### PR TITLE
fix: where condition on joined table in correct part of query (#10962)

### PR DESCRIPTION
**Pull request by felamaslen**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes #[10962].

Please review this intensely. As far as I can tell, the test coverage
for the query generator isn't 100%, and my implementation is only tested
  with a relatively simple test case.

### CODE REVIEW

**Comment by Goblinlordx** [comment]
Fixes https://github.com/sequelize/sequelize/issues/10962

**Comment by papb** [comment]
Would you be willing to fix this to address [this comment](https://github.com/sequelize/sequelize/issues/10962#issuecomment-511788913)?

**Comment by fesaza** [comment]
Any plan to merge this?

**Comment by WikiRik** [comment]
The implementation here is probably not fully correct, and it hasn't been rebased since it was initially made. So unless @felamaslen updated this PR or somebody makes a new PR this won't be solved yet

**Comment by WikiRik** [comment]
Closing this since it is still against `master`. Can be reopened if that changes.

**Pull request closed without merging**
