### PR TITLE
docs: update theme + changelog + logo + cleanup

### PR DESCRIPTION
**Pull request by sushantdhiman**
**New Theme (with lighter colors now)**

new-theme 1

### CODE REVIEW

**Comment by felixfbecker** [comment]
The background colors of the nav items are too dark imo. I like the use of blue, but it should be a pastell color like before

**Comment by sushantdhiman** [comment]
I have used lighter shades of color now, also worked on reference section colors, tables etc

**Comment by mkaufmaner** [comment]
LGTM!

**Comment by janmeier** [comment]
Merged in https://github.com/sequelize/sequelize/commit/b7ca3c4486f3cfde08f9f7e866a76dcbcac987d5

**Comment by janmeier** [comment]
:+1:

**Pull request closed without merging**
