### PR TITLE
chore(build): never close PRs

### PR DESCRIPTION
**Pull request by fncolon**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

Look like some important PRs is staled and closed, so I'm adding `days-before-pr-close: -1` to avoid PRs being closed without assignees or contributors permission.

### Todos

- [x] Add `days-before-pr-close: -1`

### CODE REVIEW

**Comment by WikiRik** [comment]
On that note, maybe also add a label that prevents issues from becoming stale?

**Comment by sdepold** [comment]
That would be extremely good indeed

**Comment by fncolon** [comment]
🐈 nice tip @WikiRik would happy to progress on it

**Comment by WikiRik** [comment]
@fncolon is it okay if we merge this now and I'll make a PR for the exempt labels? Before more PRs get closed by the bot

**Comment by fncolon** [comment]
> @fncolon is it okay if we merge this now and I'll make a PR for the exempt labels? Before more PRs get closed by the bot

It's okay, i would appreciate it.

**Review by WikiRik — APPROVED** [review]
Looks good, I will make a new PR for the exempt labels tomorrow or on Monday

**Pull request merged**
