### PR TITLE
Fix various typos/misspellings/formatting issues in the docs

### PR DESCRIPTION
**Pull request by treythomas123**
I noticed a misspelling when reading the docs, so I ran a spellcheck on all the doc files and found lots of typos.

I also noticed some of the doc files used character entity names (`&period;`, `&comma;`, `&lpar;`, `&rpar;` etc.) in places where they were unnecessary, so I replaced those instances with the actual characters.

The second commit in this PR is just the result of running `npm run docs`.

### CODE REVIEW

**Comment by mickhansen** [comment]
Can you remove the second commit? Kills the diff and we autogenerate on deploy.

**Comment by treythomas123** [comment]
Would it be better to just remove the generated docs from source control? Having them there could be a little confusing to people coming in to edit them. I actually started editing some of the files directly before I noticed they had been auto-generated.

**Comment by treythomas123** [comment]
Removed the commit with the generated docs. I'll write another PR to discuss removing the docs from source control.

**Comment by mickhansen** [comment]
I think we need them in source for readthedocs.

**Pull request merged**
