### PR TITLE
fix(types): allow specifying additional options for db.query and add missing retry

### LINKED ISSUE #10506: sequelize.query typings are not allowing model property in typings (v5)
## What are you doing?

```js
sequelize.query(/* my query here */, {
  type: QueryTypes.SELECT,
  model: ResolvedTag,
  transaction: tx
})
```

## What do you expect to happen?

Should permit specifying the model that should be returned (populated) for rows selected.

## What is actually happening?

`error TS2345: Argument of type '{ type: QueryTypes; model: typeof ResolvedTag; transaction: Transaction; }' is not assignable to parameter of type 'QueryOptions \| QueryOptionsWithType \| u ndefined'.`

__Dialect:__ mysql
__Dialect version:__ 1.6.5
__Database version:__ `mariadb:10.2` - `907f5f6c749d`
__Sequelize version:__ 5.0.0-beta.16
__Tested with latest release:__ Yes

### PR DESCRIPTION
**Pull request by SimonSchick**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

See title
fixes #10506

@sushantdhiman can you clarify if you can specify BOTH the query `type` AND `model`?
It seems that when model is specified it implicitly uses `SELECT` but what if `type` is specified?

### CODE REVIEW

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/blob/45648dd034450f754500bfdf27b2f1d7b7a22d98/lib/sequelize.js#L482-L488

Both `type` and `model` can be specified, when there is no `type` we use `options.model` to set it to `SELECT` type.

**Comment by sushantdhiman** [comment]
Let me know if this is ready

**Comment by SimonSchick** [comment]
@sushantdhiman what exactly is the return type if, for example `model` and `type: INSERT` is specified?

**Comment by sushantdhiman** [comment]
`type: INSERT`, as `model` won't modify `type` if it's already set

**Comment by SimonSchick** [comment]
So does `setting` model have any effect for any type except `SELECT`? Sorry the code is really hard to understand..

**Comment by sushantdhiman** [comment]
Setting model has no effect on type, if type is already set

**Comment by SimonSchick** [comment]
So, in typings we should probably not support setting both at the same time then as it's pointless and probably an error.

In this case this PR is complete.

**Pull request merged**
