### PR TITLE
mssql: describe table: include auto increment flag

### PR DESCRIPTION
**Pull request by jpillora**
Set my DIALECT env var to `mssql and ran `npm install` and `npm test`, and got:

```
  840 passing (5s)


> sequelize@0.0.0-development test-integration /Users/jpillora/Code/Node/sequelize
> mocha $npm_package_options_mocha "test/integration/**/*.test.js"

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators lib/sequelize.js:242:13
FIXME: I want to be supported in this dialect as well :-(

  [MSSQL] Alias
    1) "before each" hook for "should uppercase the first letter in alias getter, but not in eager loading"
    2) "after each" hook for "should uppercase the first letter in alias getter, but not in eager loading"

  0 passing (93ms)
  2 failing

  1) "before each" hook for "should uppercase the first letter in alias getter, but not in eager loading":
     SequelizeAccessDeniedError: Login failed for user 'sequelize'.
      at Connection.connection.on.err (lib/dialects/mssql/connection-manager.js:107:20)
      at Connection.processLogin7Response (node_modules/tedious/lib/connection.js:672:16)
      at Connection.message (node_modules/tedious/lib/connection.js:1082:21)
```

This happens on master without my changes. My 4 line edit doesn't change the results of `npm test`. Any ideas?

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Dont know why tests failing locally, which version of MSSQL you are using?

**Comment by jpillora** [comment]
Thanks for merging!

@sunshinewyin I'm running docker image `microsoft/mssql-server-linux`, exposing 1433, which is reporting:

```
2018-03-13 05:06:13.74 Server      Microsoft SQL Server 2017 (RTM-CU1) (KB4038634) - 14.0.3006.16 (X64)
	Oct 19 2017 02:42:29
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.3 LTS)
```

**Comment by jpillora** [comment]
> Login failed for user 'sequelize'.

Doh. That's why. It had `sa:password`.

**Pull request merged**
