### PR TITLE
Fix Option Typings in QueryInterface

### LINKED ISSUE #11049: Typings for bulkInsert options are wrong
## Issue:

image

For `bulkInsert` the options typings are wrong. According to them, `replacements: boolean` doesn't exist while it clearly has an impact if in place. In `query-interface.d.ts` `bulkInsert` should probably have `BulkCreateOptions` instead of `QueryOptions`.

**Docs are correct:**
image

### PR DESCRIPTION
**Pull request by CanKattwinkel**
Closes #11049

I'm not sure about `bulkDelete`'s options.

### CODE REVIEW

**Comment by papb** [comment]
@CanKattwinkel are you willing to add the tests?

**Comment by CanKattwinkel** [comment]
@papb @SimonSchick can you elaborate on how to test the typings?

**Comment by papb** [comment]
@CanKattwinkel Testing typings is easy. We have a folder [types/test](https://github.com/sequelize/sequelize/tree/master/types/test) with many `.ts` files. The test consists in simply trying to compile every file in that folder, if it works, tests passed, otherwise tests failed. See [here](https://github.com/sequelize/sequelize/blob/7bde29c6328c9ee82409240cf4f15925fc028b71/.travis.yml#L48) and [here](https://github.com/sequelize/sequelize/blob/7bde29c6328c9ee82409240cf4f15925fc028b71/package.json#L152).

For examples of other PRs which included tests for typings, see [11115](https://github.com/sequelize/sequelize/pull/11115/files), [11068](https://github.com/sequelize/sequelize/pull/11068/files) and [11051](https://github.com/sequelize/sequelize/pull/11051/files).

Let me know if you need further help!

**Comment by sushantdhiman** [comment]
Closing this PR, Please open a new one with tests if you want to continue

**Pull request closed without merging**
