### PR TITLE
Fixed(tedious) Update returning in dialect 

### PR DESCRIPTION
**Pull request by wilmerhmg**
This pull request solves the bug that I will explain next, only with mssql

**1. Define model InfoClientes**

```js
module.exports = (sequelize, DataType) => {

  const ModelDefinition = sequelize.define('ModelName', {
    ...fields...
  }, {
    tableName: 'TableNameInDB',
    timestamps: false,
    hasTrigger: true //this table have a trigger
  });

  ModelDefinition.associate = (models) => {
  };

  return ModelDefinition ;
};
```
**2. Using the model without persistent mode**
```js
const ModelNameResovler = function ModelNameResovler(data){
    return true;
};

const ModelNameException = function ModelNameException(ErrorUpdate){
    return false;
};

ModelName.update(UpdateValues, {
  where: {
    IdClientes: UpdateValues.IdClientes
  },
  returning: false, //This should not include the clause OUTPUT INSERTED. *
}).then(
  ModelNameResovler
).catch(
  ModelNameException
);
```
**See error**
```js
//Message: The target table 'ModelName' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause. 
//SQL Generate By Sequelize: UPDATE [ModelName] SET [Names]=@0,[OtherDate]=@1 OUTPUT INSERTED.* WHERE [Id] = @2
```

### The solution in this pull request
The generated update strings should have been. 
`UPDATE [InfoClientes] SET [Nombre]=@0,[ManejaCopago]=@1 WHERE [IdClientes] = @2`
This because clearly specified that nothing returns (`returning: false`)

https://github.com/sequelize/sequelize/blob/715a82fd0278672d665386a34d0684cdc7dbeb68/lib/dialects/abstract/query-generator.js#L349

Add option.returning
https://github.com/wilmerhmg/sequelize/blob/76dc3aa7b746367261c3e2a058eeeec54ff23b53/lib/dialects/abstract/query-generator.js#L349

### CODE REVIEW

**Comment by SimonSchick** [comment]
Need a test.

**Comment by papb** [comment]
Hello @wilmerhmg, thank you very much for submitting this PR. As SimonSchick said, please add a test to prevent regressions for your fix.

We look forward to getting more PRs from you in the future!

**Comment by wilmerhmg** [comment]
test integration add as 'not returning in update when table include a trigger' in
https://github.com/wilmerhmg/sequelize/blob/33b414adcae632497e048193e4ef608b13beb581/test/integration/dialects/mssql/regressions.test.js#L99-L142

**Comment by papb** [comment]
Looks like the [test failed with three errors on MSSQL](https://ci.appveyor.com/project/sushantdhiman/sequelize/builds/26108985#L3905)...

**Comment by wilmerhmg** [comment]
> Looks like the [test failed with three errors on MSSQL](https://ci.appveyor.com/project/sushantdhiman/sequelize/builds/26108985#L3905)...

Thanks, @papb,keep in mind, that two of the errors in the test, currently exist in the master branch. The code to perform the test, is corrected as recommended

**Comment by papb** [comment]
> two of the errors in the test, currently exist in the master branch

Can you provide a link that shows this? I was not able to verify that

**Comment by wilmerhmg** [comment]
> > two of the errors in the test, currently exist in the master branch
> 
> Can you provide a link that shows this? I was not able to verify that

Well, I do not know how to send a link to indicate this. but you can verify it with

```
npm run test-mssql
```
*Output*
```
> sequelize@0.0.0-development test-integration-mssql D:\ProyectosNode\sequelize
> cross-env DIALECT=mssql npm run test-integration


> sequelize@0.0.0-development test-integration D:\ProyectosNode\sequelize
> mocha --require scripts/mocha-bootload --globals setImmediate,clearImmediate --exit --check-leaks --colors -t 30000 --reporter spec "test/integration/**/*.test.js"

FIXME: I want to be supported in this dialect as well :-(


  √ sets the varchar(max) length correctly on describeTable (201ms)
  √ not returning in update when table include a trigger (48ms)
  [MSSQL] Alias
    √ should uppercase the first letter in alias getter, but not in eager loading (82ms)
    √ shouldnt touch the passed alias (64ms)
    √ should allow me to pass my own plural and singular forms to hasMany (51ms)
    √ should allow me to define plural and singular forms on the model (50ms)

  [MSSQL] BelongsToMany
    getAssociations
      1) supports transactions
      2) "after each" hook for "supports transactions"


  6 passing (31s)
  2 failing

  1) [MSSQL] BelongsToMany
       getAssociations
         supports transactions:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\ProyectosNode\sequelize\test\integration\associations\belongs-to-many.test.js)
  

  2) "after each" hook for "supports transactions":
     Error: Expected 0 running queries. 1 queries still running in [MSSQL] BelongsToMany getAssociations supports transactions
      at Context.<anonymous> (test\integration\support.js:24:9)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! sequelize@0.0.0-development test-integration: `mocha --require scripts/mocha-bootload --globals setImmediate,clearImmediate --exit --check-leaks --colors -t 30000 --reporter spec "test/integration/**/*.test.js"`
npm ERR! Exit status 2

```
configure the environment to work with an mssql connection

**Comment by papb** [comment]
There are indeed those two errors in the master branch, but the [three errors](https://ci.appveyor.com/project/sushantdhiman/sequelize/builds/26156964#L3907) I am talking about are all different, see?

**Comment by wilmerhmg** [comment]
> There are indeed those two errors in the master branch, but the [three errors](https://ci.appveyor.com/project/sushantdhiman/sequelize/builds/26156964#L3907) I am talking about are all different, see?

This is because by default `options.retruting` is equal to false, and as it was added
https://github.com/wilmerhmg/sequelize/blob/76dc3aa7b746367261c3e2a058eeeec54ff23b53/lib/dialects/abstract/query-generator.js#L349

now it must be specified in each update `option.returning: true`

**Comment by papb** [comment]
Ah, I see! So this is a breaking change.

* Please change your PR to target the `v6` branch instead of the master branch (and rebase)
* Please update your commit message to include the fact that it is a `BREAKING CHANGE` (see AngularJS Commit Message Conventions)
* Please add instructions on how to upgrade on the [upgrade-to-v6](https://github.com/sequelize/sequelize/blob/v6/docs/upgrade-to-v6.md) file

I see this is your first-time contribution, please don't be scared with all these steps, if you have trouble in one of these steps let me know!

**Comment by wilmerhmg** [comment]
@papb I don't know how to do that, could you explain me step by step?

**Comment by papb** [comment]
@wilmerhmg Sure!

First of all, do you understand why I said it is a breaking change? Do you agree?

**Pull request closed without merging**
