### PR TITLE
ES6 refactor of validator-extras.js

### PR DESCRIPTION
**Pull request by felixfbecker**
See #6009 

One thing I would like to discuss is if we can somehow avoid patching the global validator.

### CODE REVIEW

**Comment by janmeier** [comment]
We should definitely avoid patching the global validator - Actually we'd like to remove specific validations completely from core, and only have a validate function that users can hook into - validator.js validations can then be provided as a plugin, and sequelize core won't break when validator changes their API

**Comment by felixfbecker** [comment]
Like this?
```js
import {Model} from 'sequelize';
import {isEmail} from 'sequelize/lib/validations';

class MyModel extends Model {}
MyModel.init({
  email: {
    type: Sequelize.STRING,
    validate: {isEmail}
  }
})
```

**Comment by mickhansen** [comment]
@felixfbecker I was actually thinking more than `validate` can hold ANY value, and plugins then validate via a hook and lookup the options internally.

**Comment by mickhansen** [comment]
Merging for now.

**Pull request merged**
