### PR TITLE
[Minor refactoring] Removed unnecessary code from instance validator

### PR DESCRIPTION
**Pull request by Znarkus**

### CODE REVIEW

**Comment by Znarkus** [comment]
Weird about the tests failing, seems to be a before each hook that fails? 

```
  1) [MSSQL] Model "before each" hook:
     SequelizeDatabaseError: The object '[Users]' does not exist in database 'sequelize_test_93' or is invalid for this operation.

  2)  "before each" hook:
     SequelizeDatabaseError: Could not drop object 'dbo.users' because it is referenced by a FOREIGN KEY constraint.
```

**Comment by janmeier** [comment]
Yeah, thats some silly code :). The error is probably because someone else interfered with the mssql server at that point (mssql servers are hosted on amazon since the travis VM does not run sql server)

**Comment by janmeier** [comment]
Thanks :)!

**Comment by Znarkus** [comment]
Great :)

**Pull request merged**
