### PR TITLE
ES6 refactor: errors

### PR DESCRIPTION
**Pull request by felixfbecker**
See #6009

### CODE REVIEW

**Comment by mickhansen** [comment]
Does this maintain stack trace? I thought something like https://www.npmjs.com/package/es6-error was required

**Comment by felixfbecker** [comment]
I don't know, could you write a test to find out?

**Comment by mickhansen** [comment]
I'm not sure exactly how to test this, i've just been using es6-error in all my projects - I'm pretty sure it's required.

**Comment by felixfbecker** [comment]
@mickhansen I tested it in Node 6
```js
function throwError() {
  throw new errors.BaseError('this is a message');
}
```
results in
```
SequelizeBaseError: this is a message
    at BaseError (C:\Users\felix\git\OpenSource\sequelize\lib\errors.js:19:5)
    at throwError (C:\Users\felix\git\OpenSource\sequelize\test\unit\errors.test.js:8:13)
```
should I add this as a unit test?

**Comment by mickhansen** [comment]
This adds the base error code to the stack, i'm not sure if es6-error keeps the original stack instead?

**Comment by felixfbecker** [comment]
But isnt that the expected behaviour? The stack trace is captured the moment you call `super()`. I don't really like the idea of all the stuff es6-error is doing - with `captureStackTrace()` and `stack: (new Error()).stack`. Subclassing `Error` is an explicit feature of ES6

**Comment by mickhansen** [comment]
@felixfbecker No, the stack trace should never include the error class i would think.

/cc @janmeier

**Comment by felixfbecker** [comment]
@mickhansen I think in Java a stack is always captured at the time the exception is thrown, but in JS and PHP it is always at the time the error is created (eg the `Error` constructor is called, for example with `super()`). You can hack around this by using
```js
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, this.constructor);
    } else {
      Object.defineProperty(this, 'stack', {
        value: (new Error()).stack
      });
    }
```
but you would have to do this not only in `BaseError`, but in all subclasses like `ValidationError`, `UniqueConstraintError` etc. Imo this is unneeded effort and code just to change Javascript's error stack semantics... It might also have a performance impact.

**Comment by mickhansen** [comment]
@felixfbecker You would only need it in BaseError with es6-error as far as i can tell.
Performance impact should be negligble compared to readable stacks.

http://stackoverflow.com/questions/31089801/extending-error-in-javascript-with-es6-syntax

**Comment by felixfbecker** [comment]
@mickhansen I used `captureStackTrace` since we are targeting Node 4+ and adapted the test to verify it for a subclass.

**Comment by mickhansen** [comment]
@felixfbecker Great!

LGTM, /cc @janmeier

**Pull request merged**
