### PR TITLE
fix(transaction): Only rollback if connection was acquired

### LINKED ISSUE #8087: Unhandled rejection TypeError: Cannot read property 'query' of undefined
## What you are doing?

```js
    return sequelize.transaction((tx) => {
      return Topping.destroy({where: {pizza_id: request.params.id}, transaction: tx})
        .then((res) => {
          return Pizza.destroy({
            where: {id: request.params.id},
            transaction: tx
          })
        })
    }).then((res) => reply('Pizza removed'))
      .catch((err) => reply(err)
  })

```

## What do you expect to happen?
A Transaction!

## What is actually happening?
```
Unhandled rejection TypeError: Cannot read property 'query' of undefined
at parameters.length.Promise (/Users/me/projects/pizza-api/node_modules/sequelize/lib/dialects/postgres/query.js:65:53)
    at Promise._execute (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:79:10)
    at Query.run (/Users/me/projects/pizza-api/node_modules/sequelize/lib/dialects/postgres/query.js:65:9)
    at retry (/Users/me/projects/pizza-api/node_modules/sequelize/lib/sequelize.js:529:32)
    at /Users/me/projects/pizza-api/node_modules/retry-as-promised/index.js:40:21
    at Promise._execute (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:79:10)
    at retryAsPromised (/Users/me/projects/pizza-api/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/Users/me/projects/pizza-api/node_modules/sequelize/lib/sequelize.js:529:14)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
```

__Dialect:__ postgres
__Database version:__ 9.4.5.0
__Sequelize version:__ 4.4.2
__Bluebird version:__ 3.5.0

To note I downgraded to version __Sequelize version:__ 3.29.0, code above goes through fine as expected as a transaction

### PR DESCRIPTION
**Pull request by holm**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](../CONTRIBUTING.md)?

### Description of change

This fixes #8087. Before a transaction was always attempted to be rolled back, even if the transaction had not started yet. This could happen when a connection could not be acquired, for whatever reason. 

I don't think writing a test for this is worth the effort.

### CODE REVIEW

**Comment by holm** [comment]
I guess we can try to make a testcase, but it will be very messy. We have to stub a failure in acquiring a connection and then check for unhandled rejections. I am not sure such a testcase will do much good, but happy to take suggestions on how to build a proper testcase.

**Comment by AlexeyKhristov** [comment]
Have same issue. This PR fixes it.
+1 to merge it.

**Comment by holm** [comment]
We get this error from time to time, and it would be really helpful to have this merged.

**Comment by holm** [comment]
It is getting a bit frustrating to have submitted PR's to fix issues, and they are just left to rot. Can we get this properly reviewed please`

**Comment by sushantdhiman** [comment]
@holm Have some patience please. Its a large project, I have a job, I am working on v5, still reviewing and merging stuff almost on daily basis.

Thanks for debugging and fixing this. As I said before this PR is missing a test case, which I think is important and I am trying to eventually get back to this, but that will take some time.

**Comment by robdvr** [comment]
We appreciate all your hardwork @sushantdhiman! We are actually using @holm's commit in prod, and it's working well (thank you for the fix!). What can we, community members do to help?

**Comment by clncln1** [comment]
@sushantdhiman @holm 

I also think this is a rather critical issue since it results in unhandled promise rejections at least under load. I have created a test case for this one that should clearly show the impact.
Let me know if you need changes to that one

**Comment by holm** [comment]
Thanks, I merged your testcase into this PR

**Comment by itsmepetrov** [comment]
@sushantdhiman as I can see, @holm has already added testcase for that PR, do you have any plans to merge it?

**Comment by sushantdhiman** [comment]
@itsmepetrov Yes, I'll verify and merge this fix tomorrow morning

**Pull request merged**
