### PR TITLE
fix(typings): restrict update typings

### PR DESCRIPTION
**Pull request by JacobLey**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

Stricter enforcement of valid keys, while looser enforcement of values (can be utility methods)

### CODE REVIEW

**Comment by JacobLey** [comment]
@papb Opened a couple typescript PRs, but figured I should just ping once for review/feedback

this + https://github.com/sequelize/sequelize/pull/13214 + https://github.com/sequelize/sequelize/pull/13215 + https://github.com/sequelize/sequelize/pull/12921

**Comment by mkadirtan** [comment]
Is sequelize maintained? Why such a small change is drifting around for months?

**Review by Keimeno — APPROVED** [review]

**Comment by papb** [comment]
Thank you!!

**Comment by papb** [comment]
> Is sequelize maintained? Why such a small change is drifting around for months?

@mkadirtan I am sorry.

**Pull request merged**
