### PR TITLE
feat: support ignoreDuplicates in Postgres >= 9.5

### LINKED ISSUE #9882: Feature request: support ignoreDuplicates in bulkCreate for Postgres 9.5+ (using ON CONFLICT DO NOTHING)
## What are you doing?

I'd like to use `bulkCreate` within a transaction with Postgres without causing the transaction to rollback if there are duplicate keys.

## What do you expect to happen?
_I wanted Foo!_
`bulkCreate` with `ignoreDuplicates` uses `ON CONFLICT DO NOTHING` now that Postgres supports it.

## What is actually happening?
_But the output was bar!_
**According to the docs**, `ignoreDuplicates` is not supported in Postgres.

_Output, either JSON or SQL_

__Dialect:__ postgres
__Dialect version:__ *current docs*
__Database version:__ > 9.5
__Sequelize version:__ *current docs*
__Tested with latest release:__ N/A (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

### PR DESCRIPTION
**Pull request by jedwards1211**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Closes #9882

### CODE REVIEW

**Comment by jedwards1211** [comment]
@sushantdhiman looks like AppVeyor failed for no good reason, I can't see why in the log

**Comment by sushantdhiman** [comment]
Make sure this test is running for postgres https://github.com/sequelize/sequelize/blob/master/test/integration/model/bulk-create.test.js#L425

You will need to include `onConflictDoNothing` to if condition

**Comment by sushantdhiman** [comment]
Thanks @jedwards1211

**Comment by jedwards1211** [comment]
Thank you!

**Comment by jhiner** [comment]
Hello, do you have any idea when this will be released?

**Pull request merged**
