### PR TITLE
refactor: remove bluebird Promise.map and chained .map usage

### PR DESCRIPTION
**Pull request by jedwards1211**
removing bluebird-specific API usage will allow https://github.com/sgilroy/async-await-codemod
to convert more things to async.

@sushantdhiman probably a lot of these changes aren't going to be covered by existing tests and
hence will fail CI.  I enjoy working on automated refactorings like this but I'm not interested
in doing the huge amount of work to make the diff coverage tests pass.

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by sushantdhiman** [comment]
@jedwards1211 Thanks for this PR, code coverage is not important for modernization attempts

**Comment by papb** [comment]
Hi @jedwards1211, I see that you have been opening several PRs for modernizing promises, thank you very much for doing this! Excellent!

**Comment by papb** [comment]
P.S.: just out of curiosity - I see you used `pMap` once in this refactor, I am a big fan of that module as well, I wonder why didn't you use it everywhere?

**Comment by jedwards1211** [comment]
so that I could keep it as just a `devDependency` (needed in tests for the `concurrency` option)

**Pull request merged**
