### PR TITLE
Fix issues №5755 for v3 branch

### LINKED ISSUE #5755: Can not execute raw SQL queries for sqlite3 (sequelize.query)
I try to use raw SQL queries with `sqlite` adapter:

```
    q = db.query(
      `SELECT c.* FROM cities c ....`,
      {
        type: db.QueryTypes.SELECT,
        model: City,
        replacements: { ... }
      }
    );
```

But I'm getting this error:

```
Executed (default): SELECT c.* FROM ... in 5ms
/Users/laise/Work/itowl/eps-online-service-countries/node_modules/sqlite3/lib/trace.js:28
                    throw err;
                    ^

TypeError: Cannot read property 'geonameid' of undefined
    at /Users/laise/Work/itowl/eps-online-service-countries/node_modules/sequelize/lib/dialects/sqlite/query.js:161:46
    at /Users/laise/Work/itowl/eps-online-service-countries/node_modules/lodash/lodash.js:12449:23
    at /Users/laise/Work/itowl/eps-online-service-countries/node_modules/lodash/lodash.js:4332:15
    at baseForOwn (/Users/laise/Work/itowl/eps-online-service-countries/node_modules/lodash/lodash.js:2731:24)
```

SQL is valid and successfully executes.

Furthemore, a query with (undocumented?) `raw: true` option set executes succesfully:

```
    q = db.query(
      `SELECT c.* FROM cities c ....`,
      {
        raw: true,
        type: db.QueryTypes.SELECT,
        model: City,
        replacements: { ... }
      }
    );
```

The source of the issue is `type = tableTypes[name]` assignment [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L159).
`tableTypes` is always `undefined`, because it is being assigned in `tableTypes = columnTypes[tableName]` line [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L147) and `columnTypes` is always equal to `{}`.

__Dialect:__ sqlite
__Database version:__ sqlite3
__Sequelize version:__ 3.21.0

### PR DESCRIPTION
**Pull request by witem**
Backport for: #5931
Closes #5755

### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Have you added an entry under `Future` in the changelog?

### Description of change

Port changes from #5755 to **v3** branch.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Please link the original PR this is a backport for

**Comment by witem** [comment]
done

**Comment by sushantdhiman** [comment]
@janmeier or @mickhansen will release new patch version soon @witem

**Comment by janmeier** [comment]
`+ sequelize@3.25.1`

**Pull request merged**
