### PR TITLE
Add SMALLDATETIME type for MSSQL

### PR DESCRIPTION
**Pull request by moberegger**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Adds a `SMALLDATETIME` type to be used by MSSQL. 

If the MSSQL database is setup to use `SMALLDATETIME`, the Sequelize `DATE` type doesn't work as expected because it includes a timezone, which gets dropped by the database. The only way `SMALLDATETIME` differs from `DATE` is that the former forces UTC on write.

Solution inspired from https://github.com/sequelize/sequelize/issues/7879#issuecomment-329971730 and a previous attempt that was done in https://github.com/sequelize/sequelize/pull/10167. The solution proposed in this PR differs slightly, though; this PR uses [`toISOString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) to ensure UTC, rather than specifying a specific format.

TODO:
[ ] Add additional test(s) to ensure proper `stringify`ing

### CODE REVIEW

**Comment by moberegger** [comment]
I have added some preliminary tests already, but I'd really like to add something to ensure a proper write to the DB. I looked around the existing tests around the DATE type and got quite lost.

Any recommendations of where a good place to write this test would be? Or existing test(s) to use as inspiration?

**Comment by moberegger** [comment]
I have no idea how to get the new test to pass:

```
1616 passing (4m)
  1 pending
  1 failing
  1) [MSSQL] DataTypes
       calls parse and stringify for SMALLDATETIME:
     AssertionError: expected spy to have been called at least once, but it was never called
      at null.<anonymous> (node_modules\sinon-chai\lib\sinon-chai.js:83:18)
      at propertyGetter (node_modules\chai\lib\chai\utils\addProperty.js:62:29)
      at Object.proxyGetter [as get] (node_modules\chai\lib\chai\utils\proxify.js:98:22)
      at current.sync.then.then.then (test\integration\data-types.test.js:92:33)
      at C:\projects\sequelize\node_modules\continuation-local-storage\context.js:84:17
  From previous event:
      at Promise.then (node_modules\cls-bluebird\lib\shimMethod.js:38:20)
      at testSuccess (test\integration\data-types.test.js:91:8)
      at Context.it (test\integration\data-types.test.js:165:14)
```

I haven't defined a `parse` function anywhere, and I don't see the other Date types having a `parse` either (although those ones pass).

Is there date-specific logic somewhere that checks for certain data types that I need to include `SMALLDATETIME` to?

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

> this PR uses [`toISOString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) to ensure UTC, rather than specifying a specific format.

Seems a good idea!

> TODO:
> [ ] Add additional test(s) to ensure proper `stringify`ing

Can you clarify what you meant by this?

> I have added some preliminary tests already, but I'd really like to add something to ensure a proper write to the DB. I looked around the existing tests around the DATE type and got quite lost.
> 
> Any recommendations of where a good place to write this test would be? Or existing test(s) to use as inspiration?

Don't worry about the place for now, you can place it anywhere and later I will suggest a location (I don't have much time right now, sorry). Don't worry about "git history" being weird because everything will be squashed upon merging anyway.

As for how to do it, I am not sure I understood your question correctly, but wouldn't simply defining a basic model, calling `create`, then `findOne` and checking if the field is properly filled suffice?

**Comment by papb** [comment]
As for [your last comment](https://github.com/sequelize/sequelize/pull/11344#issuecomment-523635024), I don't have the time to investigate right now, sorry... It would be great if you could dig into it further for me!

**Comment by sushantdhiman** [comment]
Have you considered a custom data type for this? https://sequelize.org/master/manual/data-types.html#extending-datatypes

**Comment by papb** [comment]
@sushantdhiman he did look at it in #11177

**Comment by moberegger** [comment]
Closing this for a few reasons.

>If the MSSQL database is setup to use SMALLDATETIME, the Sequelize DATE type doesn't work as expected because it includes a timezone, which gets dropped by the database.

As far as I can tell, that is no longer true. This looks like it was an issue at some point, but this no longer seems to happen. Perhaps the `tedious` driver takes care of this for us now.

The MSSQL documentation also [recommends](https://docs.microsoft.com/en-us/sql/t-sql/data-types/smalldatetime-transact-sql?view=sql-server-ver15) to use types other than SMALLDATETIME:
> Use the time, date, datetime2 and datetimeoffset data types for new work. These types align with the SQL Standard. They are more portable. time, datetime2 and datetimeoffset provide more seconds precision. datetimeoffset provides time zone support for globally deployed applications. 

I don't think it makes sense to include support for a data type that shouldn't be used. This feels like something more appropriately handled by a custom data type.

**Pull request closed without merging**
