### PR TITLE
repaire a bug; when Duplicate with \r ,that makes match() return null

### PR DESCRIPTION
**Pull request by zhangshichun**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ yes ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ yes ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ no ] Have you added new tests to prevent regressions?
- [ no ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ no ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change
as this issue
https://github.com/sequelize/sequelize/issues/6725
when get a \r in the err.message，match() will return null

### CODE REVIEW

**Comment by SimonSchick** [comment]
Where in the error message would this newline be, when are newlines contained in error messages, please provide more info, this seems like a larger issue.

**Comment by zhangshichun** [comment]
> Where in the error message would this newline be, when are newlines contained in error messages, please provide more info, this seems like a larger issue.

with using mysql，this may case the error:
`user.create({
name: 'john\r'
});
user.create({
name: 'john\r'
});
`
the error code is 1062，and the match() just return null.

**Comment by SimonSchick** [comment]
In this case your fix is not sufficient.
There are many occurrences where `err.message` is matched via regex and `.replace(string, string)` only replaces a single occurrences, my suggestion is you add a `util` method called `removeNewlines(str) { return str.replace(/[\r\n]/g, '');` and apply it to all of them.

**Comment by zhangshichun** [comment]
> In this case your fix is not sufficient.
> There are many occurrences where `err.message` is matched via regex and `.replace(string, string)` only replaces a single occurrences, my suggestion is you add a `util` method called `removeNewlines(str) { return str.replace(/[\r\n]/g, '');` and apply it to all of them.

do you think that is a good idea to change
`(.*)`
to
`([\s\S]*)`
when match err.message?

**Comment by SimonSchick** [comment]
That could work too, depending on @sushantdhiman stance on v5 node version we could also use the `/s` flag (dotall) if we were to target v10.

**Comment by sushantdhiman** [comment]
Hehe, at this point I just want to release v5 asap. Please just use simple Node 6 constructs for now

**Comment by SimonSchick** [comment]
Some tests randomly fail due to timing issues, you can ignore these.

**Comment by knoxcard** [comment]
v5 really is the way to go!

**Pull request merged**
