### PR TITLE
feat(sqlite): enable `RIGHT JOIN` capability for sqlite

### LINKED ISSUE #14965: SQLite Right Joins
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Describe the feature you'd like to see implemented
The Sequelize documentation says [that right joins are not supported with SQLite](https://sequelize.org/docs/v6/advanced-association-concepts/eager-loading/#fetching-with-right-outer-join-mysql-mariadb-postgresql-and-mssql-only), but on [SQLite's page of omitted features](https://www.sqlite.org/omitted.html), right joins are not present. It looks like "long overdue" right joins [were added in SQLite 3.39](https://www.sqlite.org/releaselog/3_39_3.html), and that the sqlite3 package that Sequelize is using [has SQLite 3.39](https://github.com/TryGhost/node-sqlite3/commit/bbdb2ef4a54edfe7cc77de482eee942ba47a2c3d); would adding support for these right joins in SQLite be possible now?

### Describe why you would like this feature to be added to Sequelize
If the underlying libraries now allow us to run right joins against a SQLite database, I think it makes sense to stop disabling the generation in Sequelize.

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [x] Yes. This feature only applies to the following dialect(s): SQLite

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

### PR DESCRIPTION
**Pull request by frostzt**
## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

This issue was first mentioned by #14965 , SQLite now supports `RIGHT JOIN`s https://www.sqlite.org/releaselog/3_39_3.html. This PR enables RIGHT JOIN support for SQLite.

Closes #14965

### CODE REVIEW

**Comment by WikiRik** [comment]
Can you check if the existing unit/integration tests are running for SQLite as well with this change or that we need to update those?

**Comment by ephys** [comment]
Agreed, we need to double-check that there is an integration test that checks right joins on sqlite. If that's the case this is good to go :)

**Comment by frostzt** [comment]
@WikiRik Yes indeed I have checked the tests seems like the current ones are working with this code however I do think as @ephys said we need to have checks for right joins, I kinda needed some guidance on that, would you like to just give me an idea of tests on the repo and especially for RIGHT JOINs for SQLite.

**Review by ephys — APPROVED** [review]
Looks like the test RIGHT JOIN already exists and is enabled based if the flag is true! :)

https://github.com/sequelize/sequelize/blob/main/test/integration/include.test.js#L966

Thank you for this PR

**Comment by frostzt** [comment]
Thanks a lot @ephys I actually am getting started with more OSS stuff, actually sequelize is something that I have been using for long, so I guess I will keep contributing to this library!

**Pull request merged**
