### PR TITLE
Update validation to return null

### PR DESCRIPTION
**Pull request by yads**
Clarify validate documentation as validate emits undefined if there are no errors not null.

### CODE REVIEW

**Comment by mickhansen** [comment]
`docs/api` are generated from code, so your edit will be overwritten.
We should probably look at actually returning null :)

**Comment by yads** [comment]
Oh hah, didn't know that, there was an 'edit this in github' link on the page. I'll take a look at having the code return null.

**Comment by yads** [comment]
@mickhansen I've updated the PR to return null on validation success

**Comment by janmeier** [comment]
Thanks @yads 

(And thanks to github for adding a squash and merge button :)! https://github.com/sequelize/sequelize/commit/ac9e3d1c3dce24c7555bfd348425d49eecd0a344

**Pull request merged**
