### PR TITLE
fix(scope): fix issue on count w/scope merging where and added a regression test

### PR DESCRIPTION
**Pull request by dario1985**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Porting scope fix for #9787 from `master` to `v4` branch.

### CODE REVIEW

**Comment by dario1985** [comment]
@sushantdhiman the build fails due to an external dependency/npm error.
What do you suggest? Do you have any restriction on dependencies regards back-compat on the v4 branch? Are you still supporting node4 on the v4 branch?

**Comment by sushantdhiman** [comment]
Remove es-docs changes, it is a dev-dependency so it is ok. We support Node v4 on v4 branch

**Comment by dario1985** [comment]
I can remove it as it doesn't fix it https://travis-ci.org/sequelize/sequelize/builds/418242969

**Pull request merged**
