### PR TITLE
add options.silent support for Instance increment and decrement.

### PR DESCRIPTION
**Pull request by iyuq**
_Thanks for wanting to fix something on Sequelize - we already love you long time! Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_If your PR only contains changes to documentation, you may skip the template below._

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [√ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [√] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Have you added an entry under `Future` in the changelog?

_NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open._

### Description of change
add options.silent support for Instance increment and decrement method, so you can use 
```
user.increment('count', {silent: true} 
```
to prevent update the updatedAt field.

But I got a error run npm run docs, so I don't update the docs, please help me do this.

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Need this for `master` as well @iyuq

**Comment by iyuq** [comment]
@felixfbecker  okay, I will add a pull request for master latter. So this PR is acceptable?

**Comment by iyuq** [comment]
I add this for master as well, see [PR#6795](https://github.com/sequelize/sequelize/pull/6795), @felixfbecker

**Comment by janmeier** [comment]
Thanks a lot @iyuq ! :)

**Pull request merged**
