### PR TITLE
fix(types): add literal to possible where options

### PR DESCRIPTION
**Pull request by sHooKDT**
I faced a problem with typing during usage of raw query for where.
Since WhereOptions didn't accept Literal, compiler complained. But with since it works ok with ts-ignore, I decided to fix typings here.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Needs test.

**Comment by sHooKDT** [comment]
@SimonSchick test for behaviour with literal or test for typings?

**Comment by SimonSchick** [comment]
Just for tests.

**Comment by sHooKDT** [comment]
Finally I found some time for it.
So, check this out. I'm not sure what CodeCov is talking about, because my changes couldn't affect coverage in any way.

**Pull request merged**
