### PR TITLE
Add in escapeValues option for raw queries

### PR DESCRIPTION
**Pull request by toddbluhm**
Ran into an issue when trying to execute a raw query with an IN statement where arrays get converted to `Array[]` in the query and so I decided to go around this by doing `array.join("', '")` but it turns out that all `'` are auto escaped without the option to disable that. This PR adds in the option `escapeValues` for named replacements in raw queries. The default value for this option is `true` for backwards compatibility, but setting to `false` will skip all value escaping so that you can pass single quotes in around values an not have to worry about them being escaped.

Also updated docs as I added in some method comments for this option.

```js
sql.query("SELECT * FROM User WHERE name IN (:names)", {
  replacements: {
    names: "'leia', 'luke', 'skywalker'" // or `'${array.join("', '")}'` with es6
  }
}, {
  escapeValues: false
});
// = SELECT * FROM User WHERE name IN ('leia', 'luke', 'skywalker');
```

Added test cases to demonstrate the new option. This PR should provided a work around for issues: #3769 and #1969.

### CODE REVIEW

**Comment by mickhansen** [comment]
Mind removing changes to `docs/api/*` from the PR? It clutters the diff and we autogenerate all that from jsdoc anyways.

**Comment by toddbluhm** [comment]
Done. Just trying to follow the contrib guidelines. Let me know if you want me to update the changelog.md file.

**Comment by mickhansen** [comment]
Just merged: https://github.com/sequelize/sequelize/pull/5032 which might fix this by reverting the regression

**Comment by toddbluhm** [comment]
Indeed fixed by #5032

**Pull request closed without merging**
