### PR TITLE
ES6 Refactor: dialects / abstract

### PR DESCRIPTION
**Pull request by felixfbecker**
See #6009

### CODE REVIEW

**Comment by felixfbecker** [comment]
Hold on, tests are failing

**Comment by felixfbecker** [comment]
Cannot refactor abstract without refactoring the dialects 😒

**Comment by mickhansen** [comment]
All right, add all the dialects @felixfbecker and we'll go through it.

**Comment by felixfbecker** [comment]
Seems like I can refactor the implementations first, _then_ abstract 👍

**Comment by felixfbecker** [comment]
Rebased on master. Hopefully passes now

**Comment by felixfbecker** [comment]
Tests pass 🎉

**Comment by janmeier** [comment]
LGTM

**Pull request merged**
