### PR TITLE
docs(jsdoc): add example for createSchema if it does not exist

### PR DESCRIPTION
**Pull request by tobiasbueschel**
I stumbled upon this issue: https://github.com/sequelize/sequelize/issues/8846#issuecomment-771482541 and ran into problems when creating a schema within a Postgres DB that already had the schema defined.

### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [N/A] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

To help others who might run into a similar situation, this PR adds improved documentation to the `createSchema` call to instruct developers to `authenticate` first so the `databaseVersion` is set correctly and the create schema if not exists call can function correctly.

### CODE REVIEW

**Comment by shivamklr** [comment]
Hey, sorry for replying so late. We value your contribution. I will be working on your code to be added in the right branch.

**Comment by tobiasbueschel** [comment]
Hi @papb 👋 

Hope you are well and healthy! Is there anything else I should add to this PR or do you think it's ready to go?

Thanks

**Comment by WikiRik** [comment]
I've looked at this PR. The `databaseVersion` is not required anymore and with our [TypeDoc](https://sequelize.org/api/v7/classes/sequelize#createSchema) it is clear which options are supported. I think therefore we can close this issue. Thanks for making this and our apologies we did not review this before

**Comment by ephys** [comment]
@WikiRik just a random thought but I think we should add a getter for databaseVersion and only use that getter internally. If databaseVersion hasn't been fetched yet, the getter would throw explaining to the user to call authenticate first?

**Comment by WikiRik** [comment]
That's not a bad idea. Could you make an issue for that?

**Comment by ephys** [comment]
Ok it!

**Pull request closed without merging**
