### PR TITLE
More eslint fixes

### PR DESCRIPTION
**Pull request by felixfbecker**
#6436 did not include the tests.

It's 95% `eslint test --fix` and 5% manual fixup where JSHint was failing for no reason afterwards.

Before:

```
13067 problems (8871 errors, 4196 warnings)
```

After:

```
 9417 problems (7356 errors, 2061 warnings)
```

### CODE REVIEW

**Comment by janmeier** [comment]
I'm not going to argue with the output of `eslint --fix`, so you are free to commit those directly to master :)

**Comment by janmeier** [comment]
This has falled way behind  @felixfbecker, I'm going to apply `--fix` again, remove jshint and push directly to master

**Comment by felixfbecker** [comment]
yeah, sorry, there were too many manual fixes required. It would still be nice if you could do it through a PR just for CI checks.

**Comment by janmeier** [comment]
Alright, ninja PR coming up.

It's not going to "fit" into a single PR so we will have to live without lint for a day or two ;)

**Pull request closed without merging**
