### PR TITLE
Added the ability to catch invalid scopes

### PR DESCRIPTION
**Pull request by KieronWiltshire**
I literally just added the ability to catch invalid scope errors. My api allows user's to input scopes, and I need a way of catching those input errors. Adding this to the sequelize package seemed like the perfect work around for me, and it doesn't hurt to be there ;)

### CODE REVIEW

**Comment by KieronWiltshire** [comment]
Just stating, I'd also like to see things errors as AssociationError defined, this will make my api really easy to catch these errors and return my custom BadRequestError.

**Comment by mickhansen** [comment]
LGTM, /cc @janmeier

**Comment by mickhansen** [comment]
Ideally we should NEVER throw `Error`, always atleast use `BaseError` so that users can identify sequelize errors.

**Comment by KieronWiltshire** [comment]
@mickhansen I'd be more than happy to go through the entire code base and do this if you like?

**Comment by mickhansen** [comment]
@KieronWiltshire We'd certainly welcome

**Pull request merged**
