### PR TITLE
Make Instance.prototype.set safer for Date type. sequelize/sequelize#4843

### PR DESCRIPTION
**Pull request by vhain**
https://github.com/sequelize/sequelize/issues/4843

### CODE REVIEW

**Comment by mickhansen** [comment]
Can you add some tests aswell?

**Comment by Reggino** [comment]
Thanks, this fixed the issue for me

**Comment by yonjah** [comment]
@vhain Thanks for this fix.
There is one thing I'm not sure about. What will happen if `originalValue` is set to some date but the new `value` is  '0000-00-00 00:00:00' ?  it seems like on line 348 the value would be set back to  '0000-00-00 00:00:00' but then on line 351 `value.getTime` will be called (which will cause an error).
I'm not sure if this is actually the case since I haven't had a chance to run the code so this is only what I could deduce from reading the commit. 
If this is actually the case I would suggest changing the next if to 
```javascript
if (originalValue === value || ((originalValue instanceof Date) && (value instanceof Date) && _.isEqual(value.getTime(), originalValue.getTime()))) {
	return;
}
```

This has a few extra changes - 
if both `originalValue` and `value` are  '0000-00-00 00:00:00' (or any identical non object value) the set will be ignored
if both `originalValue.getTime` and `value.getTime` return the same value including NaN the set will be ignored

If the original behavior (ignoring identical '0000-00-00 00:00:00' or NaN values) is needed you can instead just add the check for `value` being instance of Date to the original condition

**Comment by vhain** [comment]
@yonjah thanks for your advice. I just pushed changes.

@mickhansen sorry for late reply. I just pushed test.

**Comment by vhain** [comment]
similar fix was already merged https://github.com/sequelize/sequelize/pull/4945

**Pull request closed without merging**
