### PR TITLE
add optional name arg to .hook function

### PR DESCRIPTION
**Pull request by ns3777k**
issue https://github.com/sequelize/sequelize/issues/3901

### CODE REVIEW

**Comment by janmeier** [comment]
It looks to me like this change makes the name required? That should not be the case. 

Also needs a test

**Comment by ns3777k** [comment]
nope.
```js
Model.prototype[hook] = function(name, callback) {
  return this.addHook(hook, name, callback);
};
```

it goes to addHook

```js
addHook: function(hookType, name, fn) {
  if (typeof name === 'function') {
    fn = name;
    name = null;
}
```

Yup. I'll add a test

**Comment by ns3777k** [comment]
Added several tests.

**Comment by janmeier** [comment]
@ns3777k Looks good.

Wow, this hooks test file is just getting bigger and bigger :D. Perhaps hooks are a good candidate for conversion to unit tests @mickhansen ?
Right now we have integration tests that ensures that every type of hook is being called for the relevant functions. I think this could be written more succinctly as a unit test (taking destroy as an example):

```
Stub model.findAll to return some mock data (so that individualHooks are run)

model.destroy({ hooks: true, individualHooks: true })

expect model.runHooks to have been called with beforeBulkDestroy, options
expect model.runHooks to have been called with beforeDestroy, instance, options

expect model.runHooks to have been called with afterDestroy, instance, options
expect model.runHooks to have been called with afterBulkDestroy, options
```

And then another test which ensures that `runHooks` works with both named and unnamed hooks  - which is basically what all the new tests in this PR do ;)

**Comment by janmeier** [comment]
Thanks for this @ns3777k, and sorry for the long wait!

Since my last post I've rewritten large parts of the hooks test (:fire:) and created unit tests instead. I rewrote your tests to https://github.com/sequelize/sequelize/blob/master/test/unit/hooks.test.js#L209-L233

**Comment by ns3777k** [comment]
wanted to do the same but waited for confirmation :-)
good job anyway)

**Pull request merged**
