### PR TITLE
refactor: remove sequelize.import helper

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change
Closes https://github.com/sequelize/sequelize/issues/11739

### CODE REVIEW

**Comment by MichielDeMey** [comment]
I noticed that `.import` has been deprecated in `beta6`, is there an upgrade path or best practices on how to migrate existing code?

The upgrade guide only mentions that the function has been deprecated, but offers no other directions. 😅

**Comment by papb** [comment]
Hi @MichielDeMey, thanks for the comment, we should improve that part of the docs. Can you tell me more about your situation? Can you give an example of code snippet that you have using `import`?

Does your case stem from [this issue in the CLI](https://github.com/sequelize/cli/issues/895) or is it something else?

**Comment by MichielDeMey** [comment]
Yep, looks like the code was originally generated by the CLI.
We can follow up on that issue regarding the deprecated `import` method. 👍

**Comment by roychri** [comment]
For those coming here and tryign that old issue with CLI which is now gone, here's how you can migrate.

From:

```
sequelize.import(path.join(__dirname, '', filename));
```

To:

```
require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);
```

**Comment by mdodge-ecgrow** [comment]
I switched over to using the `require` line and am now getting this error (using Node 14 and Sequelize 6):
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\.....\models\Permissions.js
require() of ES modules is not supported.
require() of C:\.....\models\Permissions.js from C:\.....\models\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename Permissions.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\.....\package.json.
```

I don't want to rename all my models to .cjs and I don't want to remove `"type":"module"`, so I need to somehow figure out that third option.

**Comment by machine-gurning** [comment]
@mdodge-ecgrow did you find a solution? I have the same problem

**Comment by ephys** [comment]
you need to use `import` instead of `require`

**Pull request merged**
