### PR TITLE
Added failing test for complex filter with N:M 'through' association. 

### PR DESCRIPTION
**Pull request by cbebry**
Covers issue #2150

### CODE REVIEW

**Comment by beeant** [comment]
I need this feature.

**Comment by cbebry** [comment]
@mickhansen I know it has been a little while since, but I was curious if the newer versions of sequelize API at all supported this desired behavior.

**Comment by mickhansen** [comment]
I actually recently introduced condition on `include` called `or`.
If you combine `include.where` and `include.or: true` the where conditions will be appended to the join with `OR` instead of `AND`.

We now also support targeting nested fields via the `{'$table.column': value}` where syntax. You can also match columns against columns with `'{'$table.column$': {$col: 'otherTable.column'}}`

**Comment by cbebry** [comment]
Thank you, that actually helps my situation quite a bit.

**Comment by cbebry** [comment]
Being that the issue is handled via the new API, this pull request is no longer relevant. Thanks again.

**Pull request closed without merging**
