### PR TITLE
refactor: use template strings, unify testing, remove dottie

### PR DESCRIPTION
**Pull request by SimonSchick**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Last big PR for a while.

1) Used eslint to convert all string concat to template strings, see https://stackoverflow.com/questions/29055518/are-es6-template-literals-faster-than-string-concatenation
2) Moved all usage of `suite` and `test` within tests to use the `describe` and `it` functions.
3) Replaced dottie with _.set/get (one less dependency 🎉)

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Some tests for Postgres are failing

**Comment by SimonSchick** [comment]
Re dottie, I did a rudimentary benchmark with 10mil iterations.

```
get
lodash: 2487.456ms
dottie: 1422.263ms
set
lodash: 2952.551ms
dottie: 2644.326ms
```

Reason I removed it is that you use `_.get` `_.set` everywhere else, not sure if the performance impact is relevant at all.

**Comment by sushantdhiman** [comment]
We use `lodash.get` to merely get some deep config path, messages etc stuff, nothing critical. `lodash.set` is not used anywhere.

Dottie still got upper hand (as per your benchmark), I would like to measure impact at-least independently before deciding to remove it

**Comment by SimonSchick** [comment]
I don't think it will have any measureable impact in actual consumer use but I will revert the specific changes.

Here is my benchmark:
```
'use strict';

const { get: lget, set: lset } = require('lodash');
const { get: dget, set: dset } = require('dottie');

console.log('get');
{
  const lookup = 'a.b.c.d.e.f.g';
  const obj = {
    a: {
      b: {
        d: {
          e: {
            f: {
              g: 123,
            },
          },
        },
      },
    },
  };
  console.time('lodash');
  for (let i = 0;i<10000000;++i) {
    lget(obj, lookup);
  }
  console.timeEnd('lodash');
}

{
  const lookup = 'a.b.c.d.e.f.g';
  const obj = {
    a: {
      b: {
        d: {
          e: {
            f: {
              g: 123,
            },
          },
        },
      },
    },
  };
  console.time('dottie');
  for (let i = 0;i<10000000;++i) {
    dget(obj, lookup);
  }
  console.timeEnd('dottie');
}

console.log('set');
{
  const lookup = 'a.b.c.d.e.f.g';
  const obj = {};
  console.time('lodash');
  for (let i = 0;i<10000000;++i) {
    lset(obj, lookup, 123);
  }
  console.timeEnd('lodash');
}

{
  const lookup = 'a.b.c.d.e.f.g';
  const obj = {};
  console.time('dottie');
  for (let i = 0;i<10000000;++i) {
    dset(obj, lookup);
  }
  console.timeEnd('dottie');
}
```

**Comment by sushantdhiman** [comment]
Thanks @SimonSchick

**Pull request merged**
