### PR TITLE
feat!: make generated association names lowerCamelCase by default

### PR DESCRIPTION
**Pull request by ephys**
## Pull Request Checklist

This PR makes association names generated by Sequelize be camelCase instead of PascalCase by default.

Until now, the name of the association was the name (plural or singular, depending) of the target model.

Our documentation uses PascalCase for model names (as they are JS classes) and camelCase for association names & attributes (as they are class fields).

Using the model name as the association name broke that convention, so the new implementation turns it into camelCase.

This is a breaking change, we will need to document that
- generated association names are camelCase by default
- their associated foreign key will therefore be camelCase too

### CODE REVIEW

**Comment by WikiRik** [comment]
Not related to your change, but I had to manually cancel the DB2 tests. Check out the timestamps;
image

and compare that to postgres;
image

Should be an easy fix with how we run db2 tests compared to the others, but wanted to comment it somewhere before I forget

**Review by WikiRik — APPROVED** [review]
Looks good. Also some maintenance on the tests, thanks for that!

**Comment by WikiRik** [comment]
@ephys I'll let you merge this one

**Comment by wguerram** [comment]
Hi, could you please look this issue. Might be related to this pull request.

[https://github.com/sequelize/sequelize/issues/17074](url)

**Pull request merged**
