### PR TITLE
chore: misc cleanup

### PR DESCRIPTION
**Pull request by SimonSchick**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This is a smaller collection of changes:

TS: 
 - Add some missing things such as `on` clause overrides, `getterMethods` etc.
 - Fixed indenting
 - Enforce TS 3.x `unknown` instead of `any` which improves type safety
 
Testing:
 - Updated mocha
 - Removed `--ui tdd` as mocha no longer provides `describe` `it` etc. when using `tdd`.
 - Added symbol `inspect` methods, otherwise node v10+ generate EXCESSIVE (millions of lines) of results, this will also help people debugging.

Core:
 - Updated tedious to v6, there should be no breaking changes, this should be added changelogs in v5 however.
 - Simplied `ModelManager.getModel`
 - Simplified some base class calls in data types that have no arguments.

Summary:
 - Only breaking change is `tedious` update.

### CODE REVIEW

**Comment by sushantdhiman** [comment]
> SequelizeConnectionError: The "config.options.port" property must be of type number.

tedious after v4 added some strict validations, tests config needs to be updated to accommodate this

**Comment by SimonSchick** [comment]
I hadn't run integration tests yet, they don't want to run on my machine, I will fix those :)

**Comment by SimonSchick** [comment]
@sushantdhiman can you give me a pointer where that value comes from? I've tried to add type conversions in a few locations but none worked, I can also not reproduce this issue locally.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/blob/master/scripts/appveyor-setup.ps1#L15 generated in AppVeyor itself, I guess port there is string?

**Comment by sushantdhiman** [comment]
@SimonSchick just revert tedious related changes for now, as there are more breaking changes. Better to target them separately

**Comment by SimonSchick** [comment]
Done, unfortunately coverage dropped a tiny bit 😢

**Pull request merged**
