### PR TITLE
Added validationFailed hook

### PR DESCRIPTION
**Pull request by skleeschulte**
See [ afterValidate hook is not called when validation fails #1626 ](https://github.com/sequelize/sequelize/issues/1626)

I added an async validationFailed hook which is called with modelInstance, options and validationError. If the hook throws an error, it replaces the original validation error.

### CODE REVIEW

**Comment by mickhansen** [comment]
Please remove docs/api/ from the PR, making it easier to review.
We don't generally have hooks for failures, what's your usecase here?

**Comment by skleeschulte** [comment]
My usecase: I need to customize the error message for the internal validator for `allowNull = false`. I need to do this while having a reference to the model instance. Doing it "from the outside" would mean that I have to wrap every create and update request.

By providing a hook for validation failures with the possibility to modify the thrown error one would get all the flexibility in generating errors in the desired format, e.g. custom messages for other inbuilt validators, filtering validation errors for specific fields, ...

As you can see in [afterValidate hook is not called when validation fails #1626](https://github.com/sequelize/sequelize/issues/1626), others have requested this feature too, and your statement about this was:

> But yeah we could definitely add a validation failed hook i suppose, that wouldn't interfere with anything.

**Comment by mickhansen** [comment]
Thanks for linking my previous opinion, i forgot that i wrote that, but i still do agree with myself.
I'm all for this hook, just wanted to make sure we weren't solving a problem with the wrong method :)

**Comment by mickhansen** [comment]
Build failure unrelated, can you remove the docs/api/ changes, it's all autogenerated and just messes up the diff.

Should the name instead be `afterValidationFailure`? I'm not sure, it's not really an event that would have a "before". /cc @janmeier

**Comment by skleeschulte** [comment]
Ok :)
I reverted the changes to `docs/api/hooks.md` (I didn't commit the changes to the other api docs files in the first place).
I'm indifferent about `validationFailed` vs `afterValidationFailure`.

**Comment by janmeier** [comment]
`validationFailed` it is - I agree it doesn't make sense to have after when there is no before

**Pull request merged**
