### PR TITLE
docs(license): change contributors to authors

### PR DESCRIPTION
**Pull request by fncolon**
License notice contributors when it's likely to be authors or "The Team Name"

as this part from MIT LICENSE mentioning too:
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
***AUTHORS*** OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

also optionally we can add AUTHORS.md file to list all the authors (contributors) in Sequelize or change it to Team Name instead (which is Sequelize Organization or Sequelize).

### CODE REVIEW

**Comment by fncolon** [comment]
cc @sdepold as the founder of Sequelize.

Anyone contributing to sequelize is also copyright holder.
I'm just tweaking little part of the license.

**Comment by sdepold** [comment]
legal schmegal :) Since this is open source, I think it boils down to almost the same. 

Some example from other projects:

express:
```
Copyright (c) 2009-2014 TJ Holowaychuk <tj@vision-media.ca>
Copyright (c) 2013-2014 Roman Shtylman <shtylman+expressjs@gmail.com>
Copyright (c) 2014-2015 Douglas Christopher Wilson <doug@somethingdoug.com>
```

marko
```
Copyright 2020 eBay Inc. and contributors
```

vue:

```
Copyright (c) 2013-present, Yuxi (Evan) You
```

morgan:

```
Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>
Copyright (c) 2014-2017 Douglas Christopher Wilson <doug@somethingdoug.com>
```

mocha:
```
Copyright (c) 2011-2022 OpenJS Foundation and contributors, https://openjsf.org
```

chai:
```
Copyright (c) 2017 Chai.js Assertion Library
```

**Comment by sdepold** [comment]
there is also: https://github.com/mochajs/mocha/blob/master/scripts/update-authors.js

**Review by sdepold — APPROVED** [review]

**Comment by sdepold** [comment]
I don't have a strong opinion on this. so it might as well be Authors.

**Comment by sdepold** [comment]
I guess we could add that authors.md file too

**Comment by fncolon** [comment]
I will progress on automate scripts in the weekend, look forward for it, i will merge this instead of drafting ;)

**Pull request merged**
