### PR TITLE
build: allow db2 tests to fail

### PR DESCRIPTION
**Pull request by WikiRik**
I noticed that DB2 tests were failing but CI still let them pass, this should solve that

### CODE REVIEW

**Review by ephys — APPROVED** [review]
That's weird. Is there a reason why db2 was allowed to fail?

**Comment by sdepold** [comment]
I guess we did that because it was considered experimental. It seems semi stable however?

**Comment by WikiRik** [comment]
> I guess we did that because it was considered experimental. It seems semi stable however?

They are two flaky tests for DB2 (especially for Node 12) but in general it seems to be running fine. At least we can see that some tests have failed. Maintainers can still merge even if DB2 tests fail because they are not required so there is no big harm in this change. But I'll leave it up to you @sdepold to merge

**Comment by sdepold** [comment]
Aaaand it is optional for the release step right?

**Review by fncolon — APPROVED** [review]
I thought it's just worked like p-retry when we scrape something and got cloudflare in front of us but it turns out it's not.

LGTM.

**Comment by ephys** [comment]
I think I get why the tests were allowed to fail now 😅

**Comment by sdepold** [comment]
> I think I get why the tests were allowed to fail now 😅

😅

**Pull request merged**
