### PR TITLE
refactor: replace bluebird .each

### PR DESCRIPTION
**Pull request by jedwards1211**
#11859 

Many uses of .each were deep within nasty pyramids of doom, in those cases I went ahead and
modernized the entire function to async/await.

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by papb** [comment]
> nasty pyramids of doom

Yeah :sob: 

> in those cases I went ahead and modernized the entire function to async/await.

This is awesome!!

**Comment by papb** [comment]
Ouch, tests are failing though, hopefully not too hard to fix

**Comment by jedwards1211** [comment]
okay fixed

**Comment by papb** [comment]
Nice! Next time please don't force push though, unless really necessary, makes it harder to review. We squash upon merge so the history will be clean anyway.

**Comment by jedwards1211** [comment]
oh okay

**Pull request merged**
