### PR TITLE
fix(db2): change SSL related keyword and value in connection-manager.ts

### PR DESCRIPTION
**Pull request by vatro**
## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change
Fixes issue #16583
See ['ibm_db' API Documentation](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md). search for `Secure Database Connection using SSL/TSL`:
```bash
connStr = "DATABASE=database;HOSTNAME=hostname;PORT=port;Security=SSL;SSLServerCertificate=<cert.arm_file_path>;PROTOCOL=TCPIP;UID=username;PWD=passwd;";
```

The SSL related keyword should be `Security` (not `SECURITY`) with a value of `SSL` (string, not boolean).

## Todos

- [ ] Clarify if I should do any more of the "Pull Request Checklist" TODOs and if yes, how exactly.

### CODE REVIEW

**Comment by vatro** [comment]
Hi! I've switched the the pull request base branch from "main" to "v7" and then rebased / forced pushed. Not sure this was best practice, that's why I've closed the pull request. I could reopen it if it's ok as it is. Otherwise I'll delete it and make a new one later today.

**Comment by WikiRik** [comment]
We merge to `main` and do a separate merge to v7 when we do a new release. So the base branch of main was correct

**Comment by vatro** [comment]
> We merge to `main` and do a separate merge to v7 when we do a new release. So the base branch of main was correct

ok, what would be the best thing to do now?: 1. delete + make a fresh one or 2. reopen + try to switch base back to main? 🤔

**Comment by WikiRik** [comment]
Feel free to make a fresh one, that's easiest

**Pull request closed without merging**
