### PR TITLE
fix(oracle): clean constraints

### PR DESCRIPTION
**Pull request by cbardasano**
## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

Oracle doesn't support "ON UPDATE" actions in constraints and it throws an error if defined. It also doesn't support "ON DELETE NO ACTION".

The PR modifies `addConstraintQuery` method to avoid errors.

### CODE REVIEW

**Comment by WikiRik** [comment]
@cbardasano can you add an unit test in [this file](https://github.com/sequelize/sequelize/blob/v6/test/unit/sql/add-constraint.test.js) that fails on current v6 but passes now with this change?

@sudarshan12s @hjamil-24 can you review this as well?

**Comment by sudarshan12s** [comment]
Thanks for the changes. look fine to me. I see `on update cascade` functionality tests `(it('can cascade updates') ` are already skipped for oracle dialect. 

It could be a documentation thing,  how do we convey to the application that this functionalities are not supported?

**Comment by sudarshan12s** [comment]
> it('can cascade updates'

I see we already get an error when an update of parent primary key is attempted expecting an `update on cascade ` functionality 
`SequelizeForeignKeyConstraintError: ORA-02292: integrity constraint (SEQUELIZETEST.SYS_C00187879) violated - child record found`

**Comment by cbardasano** [comment]
> > it('can cascade updates'
> 
> I see we already get an error when an update of parent primary key is attempted expecting an `update on cascade ` functionality `SequelizeForeignKeyConstraintError: ORA-02292: integrity constraint (SEQUELIZETEST.SYS_C00187879) violated - child record found`

But that is the expected behavior, isn't it?

I mean, if oracle doesn't support 'on update cascade' and you try to update a key referenced by other tables, it is normal that it throws an error.

**Comment by sudarshan12s** [comment]
> > > it('can cascade updates'
> > 
> > 
> > I see we already get an error when an update of parent primary key is attempted expecting an `update on cascade ` functionality `SequelizeForeignKeyConstraintError: ORA-02292: integrity constraint (SEQUELIZETEST.SYS_C00187879) violated - child record found`
> 
> But that is the expected behavior, isn't it?
> 
> I mean, if oracle doesn't support 'on update cascade' and you try to update a key referenced by other tables, it is normal that it throws an error.

Yes just confirming the error ...

**Review by sudarshan12s — APPROVED** [review]
Changes look fine to me.

**Review by WikiRik — APPROVED** [review]

**Pull request merged**
