### PR TITLE
Add afterIncludeCreate hook

### PR DESCRIPTION
**Pull request by Verdier**
This PR is related to #5517

### CODE REVIEW

**Comment by Verdier** [comment]
Refactored to be only called on create (update does not support include) and some tests added. Could you review @mickhansen?

**Comment by mickhansen** [comment]
I'm considering whether we shouldn't just move the afterCreate hook.

**Comment by Verdier** [comment]
No, sometime we need to modify the included values, for that we need a hook before creating the include.

**Comment by Verdier** [comment]
If you want, we can reverse the hooks: `afterCreateBeforeInclude` and `afterCreate` but that's a breaking change (for us for exemple, because we modify the includes in the `afterCreate` hook).

**Comment by mickhansen** [comment]
You modify the overall values passed to create in an afterCreate hook to modify the included elements created?

I'd say you should do that in beforeCreate to be more pure. It's unintended that changing values in afterCreate has an effect at all.

**Comment by mickhansen** [comment]
I'm not a huge fan of having a lot of hooks with long names denoting specific points in a call path. Obviously i'd love to allow plugging into a method at any point to help plugins, just not sure how we design it best.

**Comment by Verdier** [comment]
Your are true about modifying the included models into the `beforeCreate` hook. Would you like me to remove the new hook and to just move the `afterCreate` hook after the creation of the included models?

**Comment by Verdier** [comment]
After reflexion @mickhansen , I agree with you that it's better to only move the afterCreate hook... Could you confirm?

**Comment by mickhansen** [comment]
I think that's the better solution, however i'm worried about BC if others are depending on it like you have (although that really wasn't intended, but that doesn't change that we'd like to minimize breaks).

**Comment by Verdier** [comment]
Ok @mickhansen, I've locally create the hook by replacing the `save` method at runtime. So I've a solution for our problem and the merge is no more a high priority for us, we can take the time to find the best solution. But I'm certain that we have to add/move a hook to be able to achieve that.

**Pull request closed without merging**
