### PR TITLE
Make relations schema aware when schema is given

### PR DESCRIPTION
**Pull request by vanthome**
When I have a data model using Postgres and I'm using schemas (other than the default schema) and I have relations, one need to set the schema also for `REFERENCES`. This was not the case so far. 
This PR applies the schema when provided as `options` to `sync()`.

### CODE REVIEW

**Comment by SimonSchick** [comment]
Needs tests.

**Comment by SimonSchick** [comment]
Please rebase, your history seems to be kinda messed up.

**Comment by vanthome** [comment]
I will PR it again.

**Comment by hamburml** [comment]
Any news here?

**Comment by papb** [comment]
@vanthome When you do, please link to this PR.

**Comment by vanthome** [comment]
I created a new PR here: https://github.com/sequelize/sequelize/pull/11272
This can be closed.

**Pull request closed without merging**
