### PR TITLE
docs: reorganize files and improve styles

### PR DESCRIPTION
**Pull request by papb**
This PR:

* Reorganizes files in the docs folder
* Refactors plugins to be cleaner and to run after esdoc has made all the work
* Removes the huge list of data types that clutters the main API Reference page
* Adds sections to the manuals menu
* Improves the docs header layout

This PR is mainly a preparation for my next big docs PR

### CODE REVIEW

**Comment by papb** [comment]
Previews:

image

image

**Comment by sushantdhiman** [comment]
This will break existing URLs, right?

**Comment by papb** [comment]
@sushantdhiman You mean URLs like https://sequelize.org/master/manual/scopes.html#merging for example? Those will stay exactly the same. The fact that I moved the `.md` files around don't change this (interestingly!). I just re-tested it to be sure.

Or are you talking about other URLs?

**Pull request merged**
