### PR TITLE
Backport changes to v6

### PR DESCRIPTION
**Pull request by ephys**
This PR backports the following v7 changes to v6:

- #14090
- #14126
- #14149
- #14156
- #14154
- #14159
- #14147
- #14155
- #14151
- #14017

As usual with my backport PRs, don't squash it, for proper changelog generation

### CODE REVIEW

**Comment by WikiRik** [comment]
I wasn't planning on including #14149 and #14159  in v6 to be honest. For #14159 we need to watch how yarn.lock is generated. #14149 would need an update so Node 10 is also included.

**Comment by ephys** [comment]
I can remove them, I went down the commit history and included anything that wasn't a breaking change or a new feature that would be too large to merge

https://github.com/sequelize/sequelize/pull/14159 should be fine, yarn regenerated the lockfile

https://github.com/sequelize/sequelize/pull/14149, I actually tweaked a little bit for v6 but as users are using sequelize 6 with node >= 14, I figured bringing the information in v6 was useful after all (especially with node 12 being EOL in just a couple of months).
I haven't specified which version of pg should be used with node 10 as node 10 has been EOL for a year. Would you like me to amend that commit to change it? I basically just need to change `for Node 12, use pg version 7.0.0` to `for Node 10 & 12, use pg version 7.0.0` (as a rebase to avoid polluting the commit history)

**Comment by WikiRik** [comment]
Yeah, just do that small change and we should be good. Since v6 supports Node 10 we should not update documentation that would remove references to that.

Thanks for your work on this!

**Review by WikiRik — COMMENTED** [review]
Other files look good, so just update the pg docs and then we should be good to go

**Comment by ephys** [comment]
I haven't used rebase to edit a commit in a long time but it looks like everything went well. Docs changes done :)

**Review by WikiRik — APPROVED** [review]
Yup, only the correct file was changed since when I last marked them as viewed so GitHub seems to think no other changes were made. Let's get the release out

**Comment by ephys** [comment]
Great, I'll handle this as soon as tests pass 😊

**Comment by ephys** [comment]
Failing test is the flaky postgres one:

```typescript
  1) [POSTGRES Specific] DAO
       enums
         ARRAY(ENUM)
           should be able to insert a new record even with an array of enums in a schema:
     schema "special_schema" does not exist
```

**Pull request merged**
