### PR TITLE
Add support for scope in has-one association

### PR DESCRIPTION
**Pull request by Verdier**
This PR fix two issues:
- the association's `scope` was not injected in `where` clause when eager loaded. This is **extremely critical** because any *raw* that match without the `where` restriction is eager loaded, that could result in sending private data to the client (that's what append to us...),
- the association's `scope` was not used is the creator helper method (ie. `createInstance`)

### CODE REVIEW

**Comment by mickhansen** [comment]
hasOne never had scope support, soooo ;p
The two bugs you mention are actually just the fact that the implementation does not exist.

**Comment by Verdier** [comment]
Haha @mickhansen that's fun... the implementation is here. Could you merge?

**Comment by mickhansen** [comment]
Needs code and test for associationGetter aswell.

**Comment by Verdier** [comment]
Ok I'll do that tomorrow

**Comment by mickhansen** [comment]
Great, will merge then :)

**Comment by Verdier** [comment]
@mickhansen done. Ready to merge.

**Pull request merged**
