### PR TITLE
Inflection

### PR DESCRIPTION
**Pull request by overlookmotel**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [X] Have you added an entry under `Future` in the changelog?

### Description of change

As discussed in #6023.

This PR:

* Updates [inflection](https://www.npmjs.com/package/inflection) dependency to latest and pins the version
* Exports all used [inflection](https://www.npmjs.com/package/inflection) methods as methods of `Utils`
* Updates codebase to use e.g. `Utils.underscore()` rather than `inflection.underscore()`
* Allows a later version of [inflection](https://www.npmjs.com/package/inflection) to be set by user with `Sequelize.Utils.inflection = require('inflection')` and `Utils.pluralize()` etc will use this overriden version of [inflection](https://www.npmjs.com/package/inflection).

I will add to the [test shims](https://github.com/sequelize/sequelize/blob/master/test/supportShim.js) to check that `inflection` is not accessed directly once PR #5836 is merged.

### CODE REVIEW

**Comment by felixfbecker** [comment]
What is wrong with `Utils.inflection.underscore()`?

**Comment by overlookmotel** [comment]
@felixfbecker The idea was to decouple inflection a bit and make it consistent how `inflection` methods are called.

I mean what's wrong with `Utils.inflection.pluralize()` vs `Utils.pluralize()`? But it's been `Utils.pluralize()` for a long time.

**Comment by felixfbecker** [comment]
Just thought always using `Utils.inflection.pluralize` would make it 100% clear that a user can replace it.

**Comment by felixfbecker** [comment]
You changed it in a couple of places, so if we are gonna make it consistent, we might aswell change it the other way... That `exports.inflection` is a bit ugly and won't work with true ES6 modules (might already land in Node 7)

**Comment by overlookmotel** [comment]
> Just thought always using Utils.inflection.pluralize would make it 100% clear that a user can replace it.

Yes, but that also makes it tempting to do...

```js
var Utils = require('./Utils');
var inflection = Utils.inflection;

...

function xxx() {
    ...
    inflection.pluralize() ...
}
```

Which then breaks the ability to replace `Utils.inflection` externally.

**Comment by overlookmotel** [comment]
Look is this really important enough to argue about?

**Comment by felixfbecker** [comment]
No 😃

**Comment by overlookmotel** [comment]
@felixfbecker Sorry I was grumpy! Of course it's always worth discussing before things get folded into the codebase.

How strongly do you feel about this?

**Comment by overlookmotel** [comment]
@felixfbecker Yes I agree that `exports.inflection.pluralize()` is ugly as hell. But I wasn't sure what else to do.

Usually, I'd make up a utils module with this kind of form:

```js
var Utils = {
    inflection: require('inflection'),

    pluralize: function(str) {
        return Utils.inflection.pluralize(str);
    }
};

module.exports = Utils;
```

That's less ugly to my eyes. But the whole structure of `lib/utils.js` is flat, so `exports.inflection` was best I could come up with. Do you have another suggestion?

**Comment by felixfbecker** [comment]
@overlookmotel nevermind :) I don't feel strongly about this at all. Also I was the one who changed it to `exports.whatever = ` instead of `module.exports` because it is more ES6-ish. Which is also a point that should be considered: How will overriding inflection work in ES6?
```js
import * as Utils from 'sequelize/lib/utils';
import * as inflection from 'inflection';
Utils.inflection = inflection;
```
Will only update the local import AFAIK, not what sequelize is using. One option would be something like this:
```js
let inflection = require('inflection');

function useInflection(replacement) {
  inflection = replacement;
}
exports.useInflection = useInflection;

function pluralize(str) {
  return inflection.pluralize(str);
}
exports.pluralize = pluralize;
```
`useInflection` could be re-exported in the main sequelize module so users don't have to import sequelize internals. Opinions?

**Comment by janmeier** [comment]
Exporting a function to explicitly override inflection might be cleaner, yeah

**Comment by overlookmotel** [comment]
@felixfbecker @janmeier Exporting a function sounds good to me.

**Comment by overlookmotel** [comment]
PR updated accordingly. `inflection` is still exported as `Sequelize.Utils.inflection`. Should we remove that now?

**Comment by felixfbecker** [comment]
Yes, because that instance cannot be replaced. All calls should go through `Utils.pluralize` etc.

**Comment by overlookmotel** [comment]
@felixfbecker Agreed. PR amended accordingly.

**Comment by mickhansen** [comment]
LGTM

**Comment by overlookmotel** [comment]
@mickhansen Rebased on master. Ready to merge...

**Comment by overlookmotel** [comment]
Thanks @mickhansen @janmeier @felixfbecker

**Pull request merged**
