### PR TITLE
feat(mysql): queryInterface.addColumn supports AFTER and FIRST keyword in MySQL (#7359)

### LINKED ISSUE #7359: Migrations queryInterface.addColumn before/after another column?
~~Anyhow can I use queryInterface.addColumn to add a column before or after another specific column?~~
It'd be nice to have this feature.

# Add a column after another column
```js
queryInterface.addColumn('tableA', 'columnC', Sequelize.STRING, {
    after: 'columnB'
});
```

## What do you expect to happen?
The column C should be added after columnB

## What is actually happening?
The column append at the end of table

# Add a column as the first column in the table

```js
queryInterface.addColumn('tableA', 'columnA', Sequelize.STRING, {
    first: true
});
```

## What do you expect to happen?
The columnA should be added as the first column of the table

## What is actually happening?
The column append at the end of table

__Dialect:__ mysql
__Database version:__ MySQL 5.6.20
__Sequelize version:__ Sequelize [Node: 6.7.0, CLI: 2.4.0, ORM: 3.24.3, mysql: ^2.11.1]

### PR DESCRIPTION
**Pull request by micksatana**
Resolve #7359
- queryInterface.addColumn supports MySQL ADD COLUMN query with AFTER
or FIRST keyword by using options.first and options.after

- docs: How to use first or after options in queryInterface.addColumn

### CODE REVIEW

**Comment by micksatana** [comment]
The failed case is not related to #7359

**Comment by micksatana** [comment]
Before merged from the sequelize/master, Travis CI failed but AppVeyor passed.

After merged from the sequelize/master, Travis CI passed but AppVeyor failed.

**Comment by micksatana** [comment]
@felixfbecker can this feature merge to sequelize/master?

**Comment by felixfbecker** [comment]
Please don't ping maintainers for no reason. I look through PRs when I find time.

**Comment by felixfbecker** [comment]
Is this supported by other dialects?

**Comment by micksatana** [comment]
This feature is only for MySQL. Some ppl may want to keep columns in correct order.

I don't usually use PostgreSQL and MSSQL. After searching around, it seems columns ordering in both database dialects are not supported.

**Comment by Alexsey** [comment]
At list in `Sequelize` v4.6 with `mysql` I'm using `after` in `queryInterface.addColumn` third argument and it works. Without code of this PR

**Comment by micksatana** [comment]
Thanks Alexsey for pointing out. I didn't aware of the usage. After check back in the history, it seems "AFTER" keyword already available since PR #3166

**Comment by micksatana** [comment]
- Removed support for AFTER keyword from this PR as it's duplicated with PR #3166
 - Added support for FIRST keyword and its unit test case.
 - Added usage in migrations.md

**Pull request merged**
