### PR TITLE
Closes #3019, Model.count should not return NaN

### LINKED ISSUE #3019: Model.count returning NaN because Mysql returns an empty string
### Problem

`Model.count` is returning `NaN` because Mysql returns an empty string when grouping.

```MySQL
SELECT count(*) AS `count` FROM `Model` AS `Model` WHERE (`Model`.`deleted_at` IS NULL AND `Model`.`a_model`='Post' AND `Model`.`a_foreign_key`=186);
# count: 0
```

```MySQL
SELECT count(*) AS `count` FROM `Model` AS `Model` WHERE (`Model`.`deleted_at` IS NULL AND `Model`.`a_model`='Post' AND `Model`.`a_foreign_key`=186) GROUP BY `Model`.`user_id`;
# count: ''
```

If there are values to group up, everything works as expected, but if not, MySQL returns an empty string instead of a `0` (zero).

### Solution

Return parsed Int, or `0` at [queryInterface](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L734);

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?

### Description of change

Closes #3019, Issue seems to be fixed already. Test case to prevent regression.

### CODE REVIEW

**Comment by janmeier** [comment]
The issue mentions a grouping that returns an empty string - Which we try to parse as an int

**Comment by sushantdhiman** [comment]
Thanks @janmeier

**Comment by sushantdhiman** [comment]
Should it return `Integer` or `String`, keeping in mind large counts ?

**Comment by sushantdhiman** [comment]
**Cases**

1. So when we use group, its not possible to get `null` record like this `[ { count: null }, { count: 3} ]`, group by will not return it. It will result into `[ { count: 3 } ]` ( ignored `null` )
2. But its still possible to have `[ ]` when `group` doesn't return anything.
3. When a empty result condition run ( without `group`) then result is `0` `Integer`

Case **2** should keep using `[]` because user must be expecting `Array` with group.

Your comments @mickhansen @janmeier

**Comment by janmeier** [comment]
Agreed with regards to 2.

**Comment by janmeier** [comment]
Yay, github now sends notification emails on new pushes to PRs :tada: !

**Comment by sushantdhiman** [comment]
Don't worry I'll still link you to all PRs :laughing:

**Pull request merged**
