### PR TITLE
Transactions for SQL Server - V3 backport

### PR DESCRIPTION
**Pull request by harshithkashyap**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Have you added an entry under `Future` in the changelog?

### Description of change

V3 backport for #6972

### CODE REVIEW

**Comment by harshithkashyap** [comment]
@felixfbecker @janmeier Any changes in this backport?

**Comment by felixfbecker** [comment]
_Are_ there any changes in the backport besides from the original PR?

**Comment by harshithkashyap** [comment]
No, they are same except for the ES5 syntax.

**Comment by janmeier** [comment]
:+1:

**Pull request merged**
