### PR TITLE
Fix ON condition in included query

### PR DESCRIPTION
**Pull request by linktohack**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Have you added an entry under `Future` in the changelog?

_NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open._

### Description of change

An attempt to fix https://github.com/sequelize/sequelize/issues/6789

Maybe superseded  by https://github.com/sequelize/sequelize/commit/caa03cd586983f594e53c9d4546d859ed3912b0a but that commit is not merged back to `v3`

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Will need this fix for `master` as well, before merging this.

**Comment by sushantdhiman** [comment]
Also needs some tests too :)

**Comment by linktohack** [comment]
Hello, I want to confirm that the problem persists at `sequelize@4.0.0-2`

Please notice that 
```sql
AND (`projects.user_project`.`deletedAt` >= CURRENT_TIMESTAMP OR `projects.user_project`.`deletedAt` IS NULL) 
```
should be on `projects.user_project`, not `projects`

Following is the code:

```javascript
var Sequelize = require('sequelize');
var sequelize = new Sequelize('sqlite://dev.sqlite');

var User = sequelize.define('user', {
  username: Sequelize.STRING,
  birthday: Sequelize.DATE
}, { paranoid: true });

var Project = sequelize.define('project', {
  name: Sequelize.STRING,
}, { paranoid: true });

var UserProject = sequelize.define('user_project', {}, { paranoid: true });

User.belongsToMany(Project, { through: UserProject });
Project.belongsToMany(User, { through: UserProject });

sequelize.sync({force: true}).then(function() {
  return Promise.all([
    User.bulkCreate([{
      username: 'janedoe',
      birthday: new Date(1980, 6, 20)
    }, {
      username: 'meomeo',
      birthday: new Date(1981, 6, 20)
    }]),
    Project.create({
      name: 'hello'
    })
  ])
}).then(function(bulk) {
  var users = bulk[0];
  var project = bulk[1];

  return project.addUsers(users).then(function() {
    return bulk;
  });
}).then(function(bulk) {
  var users = bulk[0];
  var project = bulk[1];

  return users[0].destroy();
}).then(function() {
  return User.findAll({
    include: [{model: Project}]
  });
}).then(function(users) {
  console.log(JSON.stringify(users, null, 2));
});
```
and the result:

```sql
Executing (default): DROP TABLE IF EXISTS `user_projects`;
Executing (default): DROP TABLE IF EXISTS `projects`;
Executing (default): DROP TABLE IF EXISTS `users`;
Executing (default): DROP TABLE IF EXISTS `users`;
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `username` VARCHAR(255), `birthday` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME);
Executing (default): PRAGMA INDEX_LIST(`users`)
Executing (default): DROP TABLE IF EXISTS `projects`;
Executing (default): CREATE TABLE IF NOT EXISTS `projects` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME);
Executing (default): PRAGMA INDEX_LIST(`projects`)
Executing (default): DROP TABLE IF EXISTS `user_projects`;
Executing (default): CREATE TABLE IF NOT EXISTS `user_projects` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, `userId` INTEGER NOT NULL REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `projectId` INTEGER NOT NULL REFERENCES `projects` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY (`userId`, `projectId`));
Executing (default): PRAGMA INDEX_LIST(`user_projects`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_user_projects_1`)
Executing (default): INSERT INTO `users` (`id`,`username`,`birthday`,`createdAt`,`updatedAt`) VALUES (NULL,'janedoe','1980-07-19 22:00:00.000 +00:00','2016-11-10 20:06:00.781 +00:00','2016-11-10 20:06:00.781 +00:00'),(NULL,'meomeo','1981-07-19 22:00:00.000 +00:00','2016-11-10 20:06:00.781 +00:00','2016-11-10 20:06:00.781 +00:00');
Executing (default): INSERT INTO `projects` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (NULL,'hello','2016-11-10 20:06:00.787 +00:00','2016-11-10 20:06:00.787 +00:00');
Executing (default): SELECT `createdAt`, `updatedAt`, `deletedAt`, `userId`, `projectId` FROM `user_projects` AS `user_project` WHERE ((`user_project`.`deletedAt` >= CURRENT_TIMESTAMP OR `user_project`.`deletedAt` IS NULL) AND (`user_project`.`projectId` = 1 AND `user_project`.`userId` IN (1, 2)));
Executing (default): INSERT INTO `user_projects` (`createdAt`,`updatedAt`,`userId`,`projectId`) VALUES ('2016-11-10 20:06:00.820 +00:00','2016-11-10 20:06:00.820 +00:00',1,1),('2016-11-10 20:06:00.820 +00:00','2016-11-10 20:06:00.820 +00:00',2,1);
Executing (default): UPDATE `users` SET `deletedAt`='2016-11-10 20:06:00.827 +00:00' WHERE `id` = 1 AND `deletedAt` IS NULL
Executing (default): SELECT `user`.`id`, `user`.`username`, `user`.`birthday`, `user`.`createdAt`, `user`.`updatedAt`, `user`.`deletedAt`, `projects`.`id` AS `projects.id`, `projects`.`name` AS `projects.name`, `projects`.`createdAt` AS `projects.createdAt`, `projects`.`updatedAt` AS `projects.updatedAt`, `projects`.`deletedAt` AS `projects.deletedAt`, `projects.user_project`.`createdAt` AS `projects.user_project.createdAt`, `projects.user_project`.`updatedAt` AS `projects.user_project.updatedAt`, `projects.user_project`.`deletedAt` AS `projects.user_project.deletedAt`, `projects.user_project`.`userId` AS `projects.user_project.userId`, `projects.user_project`.`projectId` AS `projects.user_project.projectId` FROM `users` AS `user` LEFT OUTER JOIN `user_projects` AS `projects.user_project` ON `user`.`id` = `projects.user_project`.`userId` LEFT OUTER JOIN `projects` AS `projects` ON `projects`.`id` = `projects.user_project`.`projectId` AND (`projects.user_project`.`deletedAt` >= CURRENT_TIMESTAMP OR `projects.user_project`.`deletedAt` IS NULL) AND (`projects`.`deletedAt` >= CURRENT_TIMESTAMP OR `projects`.`deletedAt` IS NULL) WHERE (`user`.`deletedAt` >= CURRENT_TIMESTAMP OR `user`.`deletedAt` IS NULL);
[
  {
    "id": 1,
    "username": "janedoe",
    "birthday": "1980-07-19T22:00:00.000Z",
    "createdAt": "2016-11-10T20:06:00.781Z",
    "updatedAt": "2016-11-10T20:06:00.781Z",
    "deletedAt": "2016-11-10T20:06:00.827Z",
    "projects": [
      {
        "id": 1,
        "name": "hello",
        "createdAt": "2016-11-10T20:06:00.787Z",
        "updatedAt": "2016-11-10T20:06:00.787Z",
        "deletedAt": null,
        "user_project": {
          "createdAt": "2016-11-10T20:06:00.820Z",
          "updatedAt": "2016-11-10T20:06:00.820Z",
          "deletedAt": null,
          "userId": 1,
          "projectId": 1
        }
      }
    ]
  },
  {
    "id": 2,
    "username": "meomeo",
    "birthday": "1981-07-19T22:00:00.000Z",
    "createdAt": "2016-11-10T20:06:00.781Z",
    "updatedAt": "2016-11-10T20:06:00.781Z",
    "deletedAt": null,
    "projects": [
      {
        "id": 1,
        "name": "hello",
        "createdAt": "2016-11-10T20:06:00.787Z",
        "updatedAt": "2016-11-10T20:06:00.787Z",
        "deletedAt": null,
        "user_project": {
          "createdAt": "2016-11-10T20:06:00.820Z",
          "updatedAt": "2016-11-10T20:06:00.820Z",
          "deletedAt": null,
          "userId": 2,
          "projectId": 1
        }
      }
    ]
  }
]
```

**Comment by felixfbecker** [comment]
Okay, we need the fix in master first.

**Pull request closed without merging**
