### PR TITLE
Added the link to sequelize-yugabytedb repo in README

### PR DESCRIPTION
**Pull request by sanyamsinghal**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

This Pull Request adds a link in the README file to the [sequelize-yugabytedb repo](https://github.com/yugabyte/sequelize-yugabytedb) which is under the yugabyte organization. 
The repo basically contains a few changes made to sequelize so that it can be used with YugabyteDB.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by sdepold** [comment]
@sanyamsinghal Which changes are we talking about? Maybe it would be an option to add support for Yugabyte to Sequelize Core itself?

**Comment by sdepold** [comment]
Pinged you an email :)

**Comment by sdepold** [comment]
@sanyamsinghal Did you already get back to me via email? I don't think I have received a response yet.

**Comment by sanyamsinghal** [comment]
Yes @sdepold i had responded on the same thread, please check your mailbox. Just left a reminder msg on the same email.

**Comment by sdepold** [comment]
Oh man. Sorry for this. Sometimes mails just don't happen to appear for me in my inbox but only in the search :( 

I'll get back to you on the mail soon :)

**Comment by sdepold** [comment]
We are going to have our monthly sequelize sync tomorrow and will discuss the matter of how to deal with dialect support requests there: https://www.meetup.com/eBay-Europe-Technology/events/282125063/

Feel free to drop by and participate in the discussion.

**Pull request merged**
