### PR TITLE
test: forward mocha options to individual scripts

### LINKED ISSUE #9898: passing --grep, --bail and other options to test scripts requires really awful workaround
To grep for a test I have to use the following disgusting syntax.
```
$ npm run test-integration-postgres -- -- --grep ignoreDuplicates
```
You would not have this problem if you use yarn because it is better about passing along arguments:
```
$ yarn test-integration-postgres --grep ignoreDuplicates
```
Would get converted to
```
$ cross-env DIALECT=postgres yarn test-integration --grep ignoreDuplicates
```
Which would get converted to
```
mocha --require scripts/mocha-bootload --globals setImmediate,clearImmediate --ui tdd --exit --check-leaks --colors -t 30000 --reporter spec \"test/integration/**/*.test.js\" --grep ignoreDuplicates
```
Here's why npm sucks in this regard:
```
$ npm run test-integration-postgres -- --grep ignoreDuplicates

> sequelize@5.0.0-beta.11 test-integration-postgres /Users/andy/sequelize
> cross-env DIALECT=postgres npm run test-integration "--grep" "ignoreDuplicates"


> sequelize@5.0.0-beta.11 test-integration /Users/andy/sequelize
> mocha --require scripts/mocha-bootload --globals setImmediate,clearImmediate --ui tdd --exit --check-leaks --colors -t 30000 --reporter spec "test/integration/**/*.test.js" "ignoreDuplicates"

Warning: Could not find any test files matching pattern: ignoreDuplicates
FIXME: I want to be supported in this dialect as well :-(


  [POSTGRES] Alias
    ✓ should uppercase the first letter in alias getter, but not in eager loading (69ms)
    ✓ shouldnt touch the passed alias (39ms)
    ✓ should allow me to pass my own plural and singular forms to hasMany
    ✓ should allow me to define plural and singular forms on the model
    ...

$ npm run test-integration-postgres -- -- --grep ignoreDuplicates

> sequelize@5.0.0-beta.11 test-integration-postgres /Users/andy/sequelize
> cross-env DIALECT=postgres npm run test-integration "--" "--grep" "ignoreDuplicates"


> sequelize@5.0.0-beta.11 test-integration /Users/andy/sequelize
> mocha --require scripts/mocha-bootload --globals setImmediate,clearImmediate --ui tdd --exit --check-leaks --colors -t 30000 --reporter spec "test/integration/**/*.test.js" "--grep" "ignoreDuplicates"

FIXME: I want to be supported in this dialect as well :-(


  [POSTGRES] Model
    bulkCreate
      ✓ should support the ignoreDuplicates option


  1 passing (133ms)
```

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #9898

@sushantdhiman although using `yarn` would be simpler, it might be a nasty surprise if any developers don't have it installed.  This is a slightly bigger change to package.json, but it doesn't require `yarn` and it supports passing mocha options to `npm` like `npm run test-unit-all -- --grep ignoreDuplicates --bail` as well.

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] (NA) Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] (NA) Have you added new tests to prevent regressions?
- [x] (NA) Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

I created a `run-test-scripts.js` script that distributes the arguments to each `npm run test-*` command, and use it in the package scripts.

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Sorry I am not sure this is the way I want to run these tests, plus if this will work on Windows. Let's leave this one for now as `-- --` gets the job done for `npm` case and I have changed travis config to use yarn in CI

**Comment by jedwards1211** [comment]
Should I just make a PR replacing npm run with yarn run?

**Comment by jedwards1211** [comment]
I get the impression you never grep for specific test cases...I don't know why you wouldn't but trust me, it gets annoying real quick

**Comment by jedwards1211** [comment]
Also, -- -- doesn't fully work - for `npm run test-unit && npm run test-integration`, the arguments only get passed to the second npm run.  This PR also fixes that.  Yarn run would have this problem too.

The only other option I can see is to allow a `MOCHA_OPTS` enviro

**Comment by jedwards1211** [comment]
After I did some research I discovered I could just put the options I need in test/mocha.opts temporarily, which I didn't realize.  Sorry for the noise then.

**Pull request closed without merging**
