### PR TITLE
Retry query when SQLITE_BUSY is thrown as error.

### PR DESCRIPTION
**Pull request by EToreo**
This pull request satisfies the situation where Sqlite reports back that a database is busy.  It uses https://github.com/mickhansen/retry-as-promised to ease the rate of retry as well as match the error.  The match option can be easily expanded to catch other errors that should be retried.

Before this will work:
* https://github.com/sequelize/sequelize/pull/4911 must be accepted - for blocking transaction types in Sqlite
* https://github.com/mickhansen/retry-as-promised/pull/1 must be accepted - for retry

### CODE REVIEW

**Comment by mickhansen** [comment]
So this automatically retries queries in the case of SQLITE_BUSY yeah?
I like this idea, i'd also love to introduce it for transactions that fail on `unable to serialize on concurrenct update` for transactions (since the PG spec says you should retry the entire transaction)

**Comment by EToreo** [comment]
@mickhansen It does, yes. I suspect that adding similar behavior to transactions would be easy enough and when I have some more time I would be happy to investigate that in another pull request.

**Comment by mickhansen** [comment]
sqlite build is failing currently, and we'll need a rebase.

**Comment by EToreo** [comment]
@mickhansen The unit tests are passing on my dev checkout of this code.  I have made sure the code is the same and my environment is clean.  Could you check out this branch and see if you are able to get the unit tests to run or if you are met with the same build failure?

**Comment by EToreo** [comment]
@mickhansen I have tried this branch on a fresh checkout and install on a different box and it is passing unit tests when run from the command line.  If you could do the same I would be interested in the result.

**Comment by EToreo** [comment]
Closed in favor of https://github.com/sequelize/sequelize/pull/5157#issuecomment-169914982

**Pull request closed without merging**
