### PR TITLE
Fixed association accessor when it's object.

### PR DESCRIPTION
**Pull request by ziflex**
Hi there.
I've faced with issue, when my model has multiple associations and they have alias as object.
As result, the latest association override previous one and I have only one association.

### CODE REVIEW

**Comment by janmeier** [comment]
If you include a test case, it is a lot easier for us to see which issue you are actually fixing :)

**Comment by ziflex** [comment]
Hmmm, looks like it's fixed in v3.0.

**Comment by janmeier** [comment]
Coolio, going to close this one then - but feel free to open a new PR if you can come up with a test :)

**Comment by ziflex** [comment]
Yep, checked. This bug exists in 2.1.3.

**Pull request closed without merging**
