### PR TITLE
fix(ibmi): close connection after query execution

### PR DESCRIPTION
**Pull request by rcronin**
## Pull Request Checklist

- [x] Have you added new tests to prevent regressions? Not applicable
- [x] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [x] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

While using Sequelize against the IBM i, I noticed connections (jobs) on the system are not being closed until the application closes. Since a connection pool isn't used, this is a problem. Connections need to be disposed of. This pull request simply adds a finally on the try catch around the query and closes the connection. Tested against our IBM i (7.4).

### CODE REVIEW

**Comment by WikiRik** [comment]
Tagging @markdirish in here as well since he worked on the initial implementation of ibmi

**Comment by ephys** [comment]
I don't see anything in our implementation that indicates that ibmi does not use the connection pool, so closing the connection like this would be a bad idea. The pool is responsible for closing it

**Comment by rcronin** [comment]
> I don't see anything in our implementation that indicates that ibmi does not use the connection pool, so closing the connection like this would be a bad idea. The pool is responsible for closing it

If you look at the node-odbc project, opening a connection pool is done via `odbc.pool` (https://github.com/markdirish/node-odbc/#constructor-odbcpoolconnectionstring). 

If you look at the connection-manager logic for the ibmi dialect, it is using just the `odbc.connect` (https://github.com/markdirish/node-odbc/#constructor-odbcconnectconnectionstring). 
https://github.com/sequelize/sequelize/blob/8a98dde54995a482c8e3814d51803783bb3117fd/packages/core/src/dialects/ibmi/connection-manager.ts#L62
That function opens a non-pooled connection against the database. Since nothing in the current codebase closes the connection, these connections just stay open on the database until the actual sequelize instance is destroyed.

**Comment by ephys** [comment]
We don't use obdc's pool, [we use our own pool](https://github.com/sequelize/sequelize/blob/8a98dde54995a482c8e3814d51803783bb3117fd/packages/core/src/dialects/abstract/connection-manager.ts#L67-L84)

It handles disconnecting a connection when the connection has been unused for a few seconds. It does so by calling [this method](https://github.com/sequelize/sequelize/blob/8a98dde54995a482c8e3814d51803783bb3117fd/packages/core/src/dialects/ibmi/connection-manager.ts#L86), which is the same method you added in query.js

**Comment by rcronin** [comment]
Thanks for clarifying how that works. How many connections will stay open by default?

**Comment by ephys** [comment]
This is the default configuration:

```
// maximum & minimum number of concurrent open connection
max: 5,
min: 0,
// How long a connection can be idle/unused before being closed (milliseconds)
idle: 10_000,
// When requesting a connection, how long will the pool wait for a connection to become available before throwing an error (milliseconds)
acquire: 60_000,
// How often does the pool check if there are idle connections to close (milliseconds)
evict: 1000,
// How many times can a connection be requested before being released
maxUses: Infinity,
```

It can be changed by using the `pool` option when instantiating Sequelize: https://sequelize.org/api/v7/interfaces/_sequelize_core.options#pool

**Comment by evanrittenhouse** [comment]
> It handles disconnecting a connection when the connection has been unused for a few seconds. It does so by calling this method, which is the same method you added in query.js

If it's auto-closed after a period of inactivity, I'm not sure that a per-query disconnect is necessary. Is it safe to close this as a no-op?

**Comment by rcronin** [comment]
Yeah good to close. I’ll see how connections close after getting the pool set up.

**Pull request closed without merging**
