### PR TITLE
fix: fix typings for queries with  {plain: true} option

### PR DESCRIPTION
**Pull request by arsonik**
### Description Of Change

Add null to returned Promise when querying with {plain: true}

### CODE REVIEW

**Comment by arsonik** [comment]
I guess it should wait for https://github.com/sequelize/sequelize/pull/13870 to be merged

**Comment by WikiRik** [comment]
> I guess it should wait for #13870 to be merged

Don't worry about that. The tests are re-running, but we can approve this PR without disabling the flaky test

**Comment by arsonik** [comment]
> > I guess it should wait for #13870 to be merged
> 
> Don't worry about that. The tests are re-running, but we can approve this PR without disabling the flaky test

ok its all good then ?

**Review by fncolon — APPROVED** [review]

**Review by ephys — APPROVED** [review]

**Comment by ephys** [comment]
Tested and looks good to me. Now it's just a question of merging :)

**Pull request merged**
