### PR TITLE
feat(hasOne): sourceKey support + key validation

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](../CONTRIBUTING.md)?

### Description of change

Closes #9229

### CODE REVIEW

**Comment by callmez** [comment]
hi, i m confuse that is this change support  call with include method? 
cause it's still not work for me.

```js
const User = this.sequelize.define('User', {
    id: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
    },
    username: {
        type: Sequelize.STRING,
        unique: true,
       field: 'the_user_name_field'
    }
});
const Task = this.sequelize.define('Task', {
    title: Sequelize.STRING,
    username: Sequelize.STRING
});

User.hasOne(Task, { as: 'Task', foreignKey: 'username', sourceKey: 'username' });
User.findOne({ 
    where: { username: 'bob' },
    include: [ 'Task' ],
}); // for mysql still generator sql "ON `user`.`id` = `Task`.`username`"

```

**Comment by sushantdhiman** [comment]
v5 only

**Comment by callmez** [comment]
v5 still not work for me.

**Comment by sushantdhiman** [comment]
report an issue

**Pull request merged**
