### PR TITLE
fix(logger): change logging depth from 3 to 1 (#9456)

### PR DESCRIPTION
**Pull request by dsullivan7**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X ] Have you added new tests to prevent regressions?
- [X ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ X] Did you update the typescript typings accordingly (if applicable)?
- [X ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Closes #[9456]

This reduces the log depth from 3 to 1 when logging objects to prevent accidental password logging if a transaction is accidentally passed to the where options of a query.

### CODE REVIEW

**Comment by dsullivan7** [comment]
@sushantdhiman Let me know if you have any feedback on this issue.

**Comment by dsullivan7** [comment]
@sushantdhiman checking in on this PR.

**Comment by dsullivan7** [comment]
@sdepold Do you have any additional comments?

**Comment by sdepold** [comment]
> @sdepold Do you have any additional comments?

Other than: Sorry for radio silence, nope :)

**Pull request merged**
