### PR TITLE
fix(postgres): minifyAliases with through tables

### PR DESCRIPTION
**Pull request by mjy78**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description of change

Closes https://github.com/sequelize/sequelize/issues/12010 minifyAliases does not minify through tables

### CODE REVIEW

**Comment by mjy78** [comment]
Hi @papb, what is the process to request a review on this PR? Do I just leave it in this state?

**Comment by mjy78** [comment]
Bump :)

**Comment by eiskalteschatten** [comment]
This would solve a major problem that we've had with Sequelize for a long time. Has anyone managed to have a look at this yet? Is there a timeline for when this will be merged?

**Comment by eiskalteschatten** [comment]
Why was this allowed to be closed? It would be wonderful if this could actually be merged and properly fixed....

**Comment by ephys** [comment]
This PR is a bit old now, from a time where the project was in between maintainers, and it was left behind in the process :/

I'm available to review it, but a few changes have occurred since. I'm hoping you're still motivated to update it (or if someone else wants to open a new PR with the updated changes).

**Pull request closed without merging**
