### PR TITLE
fix(dropSchema): missing mssql implementation

### LINKED ISSUE #9080: MSSQL dropSchema doesn't work - Abstract Defaults to dropTableQuery?
https://github.com/sequelize/sequelize/blob/196a381d3a9b9011b92a6a8484f9bcbb2dfa2ff8/lib/dialects/abstract/query-generator.js#L50

The abstract class defaults to dropTableQuery? You could potentially drop a table if it had the same name as the schema you were trying to remove.

### PR DESCRIPTION
**Pull request by jerfowler**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Have you added new tests to prevent regressions?
- [X] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](../CONTRIBUTING.md)?

### Description of change

This implements dropSchema for MSSQL.

Closes #9080

### CODE REVIEW

**Comment by eseliger** [comment]
@jerfowler The test is failing

**Comment by jerfowler** [comment]
Sorry, @sushantdhiman, I'm not sure I follow what you're asking for. Am I not supposed to use arrow functions in test code? Can you give an example of the proper approach test code should follow?

**Comment by sushantdhiman** [comment]
@jerfowler With arrow function we dont need to keep reference of parent scope `this` (like https://github.com/sequelize/sequelize/pull/9081/files#diff-ded6a833f0f1a8a3eb7ccf8042816afbR329)

So keep using arrow functions but get rid of `self`, use `this` directly instead

**Comment by jerfowler** [comment]
Not sure why that sqlite test failed... nothing I did. Can we force a retest and see if it clears?

**Comment by jerfowler** [comment]
Closing the Pull request and Reopening worked, all tests pass! woohoo!

**Pull request merged**
