### PR TITLE
meta(deps): upgrade (dev)deps

### PR DESCRIPTION
**Pull request by WikiRik**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [X] Have you added new tests to prevent regressions? _No_
- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)? _Yes_
- [X] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)? _CONTRIBUTING document has been updated_
- [X] Did you update the typescript typings accordingly (if applicable)? _Not needed_
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving? _Yes_
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)? _Yes_

### Description Of Change

Upgraded (dev)dependencies. See Todos for the ones that still can be fixed. The ones in the table below can be fixed when we can use pure ESM packages. 

| Name | Current | Latest |
| --- | --- | --- |
| [js-combinatorics](https://github.com/dankogai/js-combinatorics#readme) | 0.6.1 | 1.5.4 |
| [mocha](https://mochajs.org/) | 7.2.0* | 9.1.3 |
| [p-map](https://github.com/sindresorhus/p-map#readme) | 4.0.0 | 5.3.0 |
| [p-props](https://github.com/sindresorhus/p-props#readme) | 4.0.0 | 5.0.0 |
| [p-settle](https://github.com/sindresorhus/p-settle#readme) | 4.1.1 | 5.0.0 |
| [p-timeout](https://github.com/sindresorhus/p-timeout#readme) | 4.1.0 | 5.0.2 |
| [tedious](https://github.com/tediousjs/tedious) | 8.3.0* | 14.0.0 |

### Todos

- [ ] Update [expect-type](https://github.com/mmkal/ts/tree/main/packages/expect-type#readme) to 0.13.0
- [ ] Update [mocha](https://mochajs.org/) to 8.4.0
- [ ] Update [tedious](https://github.com/tediousjs/tedious) to 11.8.0

### CODE REVIEW

**Comment by sdepold** [comment]
Strong 💪

**Comment by sdepold** [comment]
Did you try the commit message parsing with the new husky setup? I had lots of issues in the past with this style (files vs package.json).

**Comment by sdepold** [comment]
Res lgtm

**Review by sdepold — APPROVED** [review]

**Comment by sdepold** [comment]
feel free to do the rest In an extra pr

**Comment by WikiRik** [comment]
> Did you try the commit message parsing with the new husky setup? I had lots of issues in the past with this style (files vs package.json).

I will check again, but I think I created the files with the husky-4-to-7-cli so the permissions were correct. It needs the files to be executable and normally that's not the case when you create new files manually.

**Comment by sdepold** [comment]
> > Did you try the commit message parsing with the new husky setup? I had lots of issues in the past with this style (files vs package.json).
> 
> I will check again, but I think I created the files with the husky-4-to-7-cli so the permissions were correct. It needs the files to be executable and normally that's not the case when you create new files manually.

IIRC the prime problem for me was that some variables were not filled or something like this

**Comment by WikiRik** [comment]
I will to the others in separate PR(s)

**Comment by sdepold** [comment]
Feel free to merge once you have verified that the hooks are still working

**Pull request merged**
