### PR TITLE
Vertica Dialect for Sequelize

### PR DESCRIPTION
**Pull request by yudarik**
_Thanks for wanting to fix something on Sequelize - we already love you long time! Please delete this text and fill in the template below. If unsure about something, just do as best as you're able._

_If your PR only contains changes to documentation, you may skip the template below._

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Have you added an entry under `Future` in the changelog?

_NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Comment by janmeier** [comment]
This seems like close to a copy-pasta of the postgres dialect (see https://github.com/startappdev/sequelize/blob/8cd43d5ba2295ef82d8fd1f9ef81bb1a2e85dfdb/lib/dialects/vertica/query-generator.js#L45). Is there actually any difference? It also seems you can connect with the pg library (https://github.com/startappdev/sequelize/blob/8cd43d5ba2295ef82d8fd1f9ef81bb1a2e85dfdb/lib/dialects/vertica/connection-manager.js#L19), or is that just too much copy pasta :)

If it is so close to postgres there is no reason to duplicate the code.

Personally I've never heard of Vertica, and while we generally appreciate contributions, I'd be vary against merging something that only a few people need and even fewer can fix bugs on.

**Comment by yudarik** [comment]
Right. The vertica dialect is very like the postgress, although there are few differences since both Vertica and Postgress where the same codebase somewhere in the history, but HP took it to the next level and created Vertica as a solution for Big Data databases.
I've made all necessary changes to make it work.
There are few unit-test that I still need to fix, but I think it's nice to have for people like me that need to work with Vertica on Node.js projects.

**Comment by janmeier** [comment]
Yes, it would be nice for you, but we have to take into account that the code should also be maintainable for us :)

Is it possible to install a free version of vertica? Does it comes as a docker image?

Also, to get this merged, you would have to re-use as much as possible of the postgres dialect. You can do so by importing from the corresponding postgres files, cloning, and overwriting the methods that are different

**Comment by janmeier** [comment]
We are open to _discussions_ and questions about new dialects (see the open oracle PR, which we will hopefully merge soon), but we need to see demand from a substantial amount of users to merge it

**Comment by mike-seekwell** [comment]
I'm also interested in this. @yudarik Is your PR working for you? Have you been using it regularly? 

Also, has anyone tried just using the Postgres dialect with Vertica (maybe an older version like with Redshift)? I'm going to try this week, just wanted to know if anyone else has already done it and what version of Postgres you used.

**Pull request closed without merging**
