### PR TITLE
fix: correct `package.json` path to get version

### PR DESCRIPTION
**Pull request by snitin315**
### Pull Request Checklist

_Please make sure to review and check all of these items:_

- [ ] Have you added new tests to prevent regressions?
- [ ] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

This regression was introduced in https://github.com/sequelize/sequelize/commit/51bc05ae806ee11d36764bdafb4e4645d00e93be ( https://github.com/sequelize/sequelize/pull/13569 )

I found there was discussion around this too https://github.com/sequelize/sequelize/pull/13569/files#r734959627 

Screenshot 2022-02-09 at 6 06 52 AM

While upgrading to the latest version, tests in our project started failing with the following error.

Screenshot 2022-02-09 at 6 01 37 AM

### CODE REVIEW

**Comment by sdepold** [comment]
@ephys is this fixed in your PR too?

**Comment by ephys** [comment]
It's not, actually I think my PR is the culprit because I didn't reverse this change with the flatter structure

@snitin315 thank you for your PR, and sorry for the breakage. The issue is actually in the v6 branch

I'll open a PR in a minute to resolve it (and look into why this wasn't caught by our unit tests) :)

**Comment by ephys** [comment]
Here is the PR: https://github.com/sequelize/sequelize/pull/14073

**Comment by ephys** [comment]
The fix is being published for v6, and is also included in https://github.com/sequelize/sequelize/pull/14068 for main
I'll close this PR but thank you for letting us know and figuring out what went wrong, we appreciate it :)

**Pull request closed without merging**
