### PR TITLE
Use new SQL Server for tests

### PR DESCRIPTION
**Pull request by sdepold**
I need to shut down the current SQL Server instance and created a new one on the same EC2 region. Since I always forget which steps are needed to set up such a machine, I also added some instructions about that.

### CODE REVIEW

**Comment by sdepold** [comment]
If the tests for MSSQL pass and you are +1 on it, I will just change the mssql.sequelizejs.com domain to pinpoint the new URI and change the PR one more time to only contain the instructions.

**Comment by sushantdhiman** [comment]
@sdepold We should keep these steps in Wiki, away from the regular docs stuff. I can move these to a Wiki article if thats ok ?

**Comment by sdepold** [comment]
Good idea!

**Comment by sdepold** [comment]
Can anyone tell why the tests are failing?

**Comment by janmeier** [comment]
A bug in the latest node 6 release affecting tedious

**Comment by sdepold** [comment]
So it's not because of my changes, correct? Will change the dns settings then! :)

**Pull request closed without merging**
