### PR TITLE
docs: describe `findByPk`'s option bag

### PR DESCRIPTION
**Pull request by evanrittenhouse**
## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Todos
Closes https://github.com/sequelize/website/issues/202. Not sure if we want to add more documentation, but I didn't want to duplicate work when `FindOptions` already exists.

Duplicate of https://github.com/sequelize/sequelize/pull/15111

### CODE REVIEW

**Comment by ephys** [comment]
Did you mean to target the `v6` branch? This will unfortunately not resolve https://github.com/sequelize/website/issues/202 since it's a v6 only issue 😅

**Comment by evanrittenhouse** [comment]
Yeah I did 😬 I had some issues with the git remote on my local. Should I just do a new PR?

**Comment by fzn0x** [comment]
This is a lot of conflicts when we target it directly in the same PR, can you replicate this PR to a new PR that targetting v6 branch?

**Comment by fzn0x** [comment]
Since v6 branch is different source of truth

**Comment by ephys** [comment]
You can open a new PR if you want but you can also repurpose this one :)

Here is how:
- copy your changes in a temporary file somewhere (or you will lose them)
- `git checkout v6`
- delete this branch `git branch -D findbypk_jsdoc`
- recreate it from v6 `git checkout -B findbypk_jsdoc`
- paste the changes you copied
- push & replace the branch on the remote `git push origin findbypk_jsdoc --force`

**Comment by evanrittenhouse** [comment]
@ephys  just getting to this, did we remove the commit linting on v6 commits? Seems like I'm getting 107 (!) errors when trying to commit on the new branch as you mentioned.

**Comment by WikiRik** [comment]
> @ephys just getting to this, did we remove the commit linting on v6 commits? Seems like I'm getting 107 (!) errors when trying to commit on the new branch as you mentioned. Though these are actually in the code (i.e. unexpected trailing comma, etc.), so I'm not sure if v6 follows a different linting strategy...?

v6 does indeed follow a different config for the linter

**Comment by ephys** [comment]
This PR has been inactive for a while. Is there still interest in pursuing it, is it blocked, or should we close it?

**Comment by WikiRik** [comment]
I'm closing this, we can always review a recreation on this PR that works for v6

**Pull request closed without merging**
