### PR TITLE
meta: add experimentalDecorators support for sscce

### PR DESCRIPTION
**Pull request by lohart13**
## Pull Request Checklist

- [] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description of Changes

Add `"experimentalDecorators": true` to the root tsconfig so that the `sscce.ts` file can be run.

### CODE REVIEW

**Review by WikiRik — APPROVED** [review]
I don't see other usages of this tsconfig that could break when adding experimentalDecorators so I think we're good. Will wait for Zoé to make sure, maybe I missed something.

Shall we add `yarn sscce-sqlite` (since we can run that in-memory) to the CI to make sure the SSCCE works?

**Comment by WikiRik** [comment]
Similar to SQLite tests, I think if it runs on one dialect it also works on the others. But we need to run it as an integration test so sqlite is the easiest

**Comment by lohart13** [comment]
OK, I've added this now.

**Review by ephys — APPROVED** [review]

**Comment by WikiRik** [comment]
> Edit: should the test-sscce run after all the unit and typings test but before the integration?

It doesn't really matter in my opinion, this is fine

**Comment by ephys** [comment]
Note if we're just running it on sscce, it could be part of the unit suite? It's not a unit test because it requires an actual database but it removes the checkout, node, download etc steps for what is a 1 second test

**Comment by lohart13** [comment]
> Note if we're just running it on sscce, it could be part of the unit suite? It's not a unit test because it requires an actual database but it removes the checkout, node, download etc steps for what is a 1 second test

I agree, this makes sense and should same sometime on the CI.

**Comment by lohart13** [comment]
> > Note if we're just running it on sscce, it could be part of the unit suite? It's not a unit test because it requires an actual database but it removes the checkout, node, download etc steps for what is a 1 second test
> 
> I agree, this makes sense and should same sometime on the CI.

Updated now.
I also added test to the `test-windows`

**Review by WikiRik — APPROVED** [review]

**Pull request merged**
