### PR TITLE
refactor: remove import helper

### PR DESCRIPTION
**Pull request by eseliger**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This isn't needed for an ORM to work and as we try to make the codebase cleaner, this should be part of external tools like the cli.

### CODE REVIEW

**Comment by SimonSchick** [comment]
We will have to release a new version of sequelize-cli in tandem with this change.

**Comment by eseliger** [comment]
As it doesn't even support v5 yet I think some tracking issue would be sufficient if it's too hard to do now 
I'm really not into the cli so idk if it's gonna be hard

**Comment by papb** [comment]
Hi, I will probably be working on the CLI soon to stop using sequelize.import there. In the meantime, I have a question: why is this PR showing '128 changed files'? Perhaps some rebasing needs to be done?

@eseliger

**Comment by eseliger** [comment]
jupp, this must be rebased 🙈

**Comment by sushantdhiman** [comment]
This branch contains lots of un-related code and need rebase. I am closing this for now as it will be better to open a new pr just for removing import helper

**Comment by SimonSchick** [comment]
@sushantdhiman that's why it was targeting the v6 branch which was we planned to release eventually.
Unfortunately things got tricky and we lost momentum to get it out.

**Pull request closed without merging**
