### PR TITLE
Link directly to API docs

### PR DESCRIPTION
**Pull request by danawoodman**
Make it clearer there is both a "Guides" and "API docs". The small "Reference" link isn't super obvious to a newcomer (like myself). I find I always scan a readme for "API docs" and this PR will make that clearer and quicker for new users.

### CODE REVIEW

**Comment by sushantdhiman** [comment]
Rather than this we should improve docs layout so "Reference" is more visible somehow

**Comment by danawoodman** [comment]
Personally I don't see the two as mutually exclusive. Is there harm in adding it?

**Comment by sushantdhiman** [comment]
@danawoodman https://github.com/sequelize/sequelize/pull/7724 this pr covers your ideas :)

**Comment by danawoodman** [comment]
It doesn't actually but I don't care strongly enough to push any more

**Pull request closed without merging**
