### PR TITLE
docs(manual/other-topics/hooks): Fix broken link to `hooks.js`

### PR DESCRIPTION
**Pull request by oprearocks**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

The current manual link points to `sequelize/lib/hooks.js` which was probably changed during a project file structure update.
For more inexperienced people who are looking to learn more about the available hooks, looking through the source code is the only option. When their main entryopint is the manual, they're greeted with a broken link.

### CODE REVIEW

**Comment by oprearocks** [comment]
Ah! Seems like my Markdown auto-formatter kicked in and reshuffled some symbols. Let me know if that's an issue and I can disable it and push the change again. The only real change is related to the `hooks.js` link.

**Comment by karpikpl** [comment]
you have more changes in your PR but I think it's the same thing I did in #12669

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future! Nice catch!

> Ah! Seems like my Markdown auto-formatter kicked in and reshuffled some symbols. Let me know if that's an issue and I can disable it and push the change again. The only real change is related to the `hooks.js` link.

Normally I'd ask you to do that, but as @karpikpl said, it turns out your pull request is a duplicate of his own :sweat_smile: thanks to both of you for catching this mistake. Let's continue on #12669

**Comment by oprearocks** [comment]
Yes, definitely looks like a duplicate of what he did. I just came here to close the PR and remove the branch. Thanks for the great software!

**Pull request closed without merging**
