### PR TITLE
fix(model): V6 unique composite index upsert

### PR DESCRIPTION
**Pull request by brianschardt**
Currently updateOnDuplicate for unique index and indexes do not work. This PR solves this issue.

This is following the conversation in this PR: #12516

### CODE REVIEW

**Comment by brianschardt** [comment]
@aecorredor @eseliger can we get this merged in. I am shocked at how such a small change takes has a long and arduous process. If I can help make things better please let me know.

**Comment by aecorredor** [comment]
I'm not a maintainer so I really don't have much of a say in respect to that.

**Comment by aecorredor** [comment]
@eseliger hey! who would be responsible for getting this approved and merged? Thanks!

**Comment by aecorredor** [comment]
any update on this from maintainers? This should be a pretty important issue as bulk updates are pretty common right?

**Comment by aecorredor** [comment]
@papb sorry to bring you into this out of the blue. Just wondering what would the process be for us to get this in. Thanks!

CC: @brianschardt

**Comment by brianschardt** [comment]
@aecorredor @eseliger can we get this merged in? also is this already fixed? This is such a huge update for the sequelize community...

**Comment by Jplus2** [comment]
Any update on this?

**Comment by papb** [comment]
Continuing on #13345

**Pull request closed without merging**
