### PR TITLE
docs: change jsdoc for findbypk

### PR DESCRIPTION
**Pull request by evanrittenhouse**
## Pull Request Checklist

- [ ] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Todos
Closes https://github.com/sequelize/website/issues/202. Not sure if we want to add more documentation, but I didn't want to duplicate work when `FindOptions` already exists.

### CODE REVIEW

**Comment by fzn0x** [comment]
This is a good approach to always sync findAll options with findAndCountAll, so we can avoid some missing options in the future.

**Review by fzn0x — DISMISSED** [review]
LGTM

**Review by ephys — CHANGES_REQUESTED** [review]
placeholder because I want to review before merging

**Comment by evanrittenhouse** [comment]
@ephys Is there somewhere that we have the equivalent of `FindOptions` for v6? If not, would we need to rewrite all `<X>Options` interfaces for v6?

**Comment by fzn0x** [comment]
AFAIK you can only use link https://jsdoc.app/tags-inline-link.html to reference something

**Comment by fzn0x** [comment]
> @fzn0x You can't use link because the type does not exist in JSDoc, it only exists in TypeScript. This is why TypeDoc in v7 can use it but esdoc in v6 cannot
> 
> > Is there somewhere that we have the equivalent of FindOptions for v6
> 
> There isn't unfortunately. If you want to do this you'd have to copy each option here. This is what methods like `Sequelize#query` do: https://sequelize.org/api/v6/class/src/sequelize.js~sequelize#instance-method-query

I thought the same jsdoc could do 😞

**Comment by evanrittenhouse** [comment]
See https://github.com/sequelize/sequelize/pull/15115

**Comment by evanrittenhouse** [comment]
See https://github.com/sequelize/sequelize/pull/15115

**Pull request closed without merging**
