### PR TITLE
Implement node-style callbacks

### PR DESCRIPTION
**Pull request by tellnes**
I do not know if this has been brought up before, so I'm hoping for the best now.
The only issue I could find was #242.

It would be nice if the node-style callbacks was supported. To me, it looks like it is not that complicated to achieve.

I've probably forgotten some of the public APIs, but this is a start. I'll update the pull request if there is positive response to this.

Maybe it needed some tests too?

### CODE REVIEW

**Comment by erkstruwe** [comment]
Since Sequelize uses Bluebird 3.x, every promise is automatically equipped with the equivalent `asCallback` and `nodeify` functions, which provide the desired functionality. Use like this:
```javascript
return async.auto({
  article: function(cb) {
    return Article.findById(1).nodeify(cb);
  },
  user: ['article', function(cb, results) {
    return results.article ? User.findById(results.article.user).nodeify(cb) : cb();
  }]
}, function(e, r) {
  if (e)
    return res.error(e);

  return res.send(r);
});
```

**Comment by contra** [comment]
It would be nice if this was documented somewhere - there are tickets with a wide variety of answers. It isn't clear which promises implementation sequelize uses from the docs either, so not obvious you can use bluebird methods.

For anyone reading: To use sequelize with callbacks, it isn't `.done()` or `.complete()` or `.success()` or any of the other methods discussed: it's `.asCallback(cb)`.

**Comment by mickhansen** [comment]
@contra http://docs.sequelizejs.com/en/latest/docs/getting-started/

**Comment by aledalgrande** [comment]
@mickhansen there isn't any reference to callbacks in that page?

**Pull request closed without merging**
