### PR TITLE
feat(query): Added support of literals in `returning` statements

### PR DESCRIPTION
**Pull request by TheOptimisticFactory**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Added the ability to pass literals into `returning: [ <elements> ]` option for **postgres**. This allows the following:

```javascript
const [ user ] = await db.users.bulkCreate([{
    enabled: true,
    username: database.sequelize.literal(`PGP_SYM_ENCRYPT('demo', '${JWT.KEY}')`),
  }], {
    returning: [
      'id_user',
      [ database.sequelize.literal(`PGP_SYM_DECRYPT(CAST(username AS BYTEA), '${JWT.KEY}'`), 'username' ],
    ],
  });
```

I haven't looked into where to add some tests, nor if a documentation update/typescript typings are necessary

### CODE REVIEW

**Comment by TheOptimisticFactory** [comment]
Tests are passing :heart:

**Comment by TheOptimisticFactory** [comment]
@papb Not sure how to improve the coverage though. It seems odd to me it is allegedly dropping this much

**Comment by papb** [comment]
Hello, thanks for the work! Can you please remind me of what is currently supported for the `returning` option (before your PR is merged)? Is it just an array of strings?

**Comment by TheOptimisticFactory** [comment]
Currently `returning` supports either (depending on which method )
- an **array of strings** (like `[ 'id', 'email' ]`)
- a **boolean** (`true` being equivalent to return all)

---

For example:
```javascript
// Assuming the following "users" model exists
const Users= sequelize.define('users', {
    id_user: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  });

// Query with "RETURNING" fragment using an array containing a literal
const [ user ] = await db.users.bulkCreate([{
    enabled: true,
    username: database.sequelize.literal(`PGP_SYM_ENCRYPT('demo', '${JWT.KEY}')`),
  }], {
    returning: [
      'id_user',
      [ database.sequelize.literal(`PGP_SYM_DECRYPT(CAST(username AS BYTEA), '${JWT.KEY}'`), 'username' ],
    ],
  });
```

### _Without_ this PR ###

- Any literal in the array will fail to be mapped against the model as it isn't the name of a model column 
- In the example, it will lookup for a column named `PGP_SYM_DECRYPT(CAST(username AS BYTEA), '${JWT.KEY}'`, which does not exist

=> Sequelize would throw an error at `options.returning.map(attr => model.rawAttributes[attr].field || attr);` because `model.rawAttributes[attr]` is undefined, and as a result does not have a property named `field`

=> And even if it did not throw, the resulting SQL fragment (in Postgresql) 
would look like `[...] RETURNING "id_user", "PGP_SYM_DECRYPT(CAST(email AS BYTEA), 'SECRET_KEY')"`, which won't work

### _With_ this PR ###

With this PR, it extends the array support with the ability to have literal attributes, which won't be quoted like other attributes would, resulting in a properly formed SQL query

=> The resulting SQL fragment (in Postgresql) would look like `[...] RETURNING "id_user", PGP_SYM_DECRYPT(CAST(email AS BYTEA), 'SECRET_KEY') AS "email"`

**Comment by papb** [comment]
@TheOptimisticFactory Cool, thanks! Also, if I'm not mistaken, no escaping/sanitizing is performed in the `.literal` call, right?

**Comment by papb** [comment]
> @papb Not sure how to improve the coverage though. It seems odd to me it is allegedly dropping this much

Don't worry for now, let's get everything else sorted out first, this is probably a glitch with codecov

**Comment by TheOptimisticFactory** [comment]
> @TheOptimisticFactory Cool, thanks! Also, if I'm not mistaken, no escaping/sanitizing is performed in the `.literal` call, right?

That is correct. The input from the literal is taken as is.

**Comment by papb** [comment]
> That is correct. The input from the literal is taken as is.

:+1:

> This PR applies to all dialects, not just PostgreSQL (my original intent was for PostgreSQL only, but I assumed other dialects might have a similar use-case)

Isn't `returning` a postgres-only thing?

**Comment by TheOptimisticFactory** [comment]
> Isn't `returning` a postgres-only thing?

To my knowledge it pretty well might.

Yet, the quoting changes has been applied to `lib/dialects/abstract/query-generator/helpers/quote.js`, for all dialects to use, if need be (https://github.com/sequelize/sequelize/pull/11547/files#diff-17fc71da498288ed969157ce5bcabf15R51)

**Comment by papb** [comment]
I will review this more carefully later, I will probably ask for some refactor

**Comment by TheOptimisticFactory** [comment]
@papb In which release cycle is this PR gonna land? `5.X` or `6.X` ?

**Comment by papb** [comment]
Hello, since this PR is targeting the master branch it will land into 6.x, however once it gets accepted you could just open a "clone PR" targeting v5 and we shall merge that as well, this way the change is applied to both 5.x and 6.x :)

And sorry for taking long to look into it... Hopefully will do in the near future :)

**Comment by TheOptimisticFactory** [comment]
Any updates?

**Comment by papb** [comment]
Hi @TheOptimisticFactory sorry for taking so long. I am still super busy, hopefully I will have more time later

**Comment by TheOptimisticFactory** [comment]
Bumping this PR, I would like to stop using a forked-version of Sequelize..

**Comment by TheOptimisticFactory** [comment]
As of today this is still an issue that persists on both v5 and v6.

**Comment by TheOptimisticFactory** [comment]
ping @papb, what should I do?

**Comment by TheOptimisticFactory** [comment]
This is STILL an usse in Sequelize v6.6.5
image

**Comment by TheOptimisticFactory** [comment]
Is there any maintainer who could take a look at this?

**Comment by WikiRik** [comment]
Closing this since it is still against `master`. Can be reopened if that changes.

**Pull request closed without merging**
