### PR TITLE
Fix duplicate columns in ORDER BY statement bug

### PR DESCRIPTION
**Pull request by rdiaztushman**
For the v3 branch and only for MSSQL queries. Fixes bug causing duplicate columns in ORDER BY statement when order is already specified.  Error from SQL: "A column has been specified more than once in the order by list. Columns in the order by list must be unique."

### CODE REVIEW

**Comment by felixfbecker** [comment]
What about master?

**Comment by jacinto123** [comment]
Is there any chance of getting this merged in? I am having this issue?

**Comment by felixfbecker** [comment]
@jacinto123 if you wanna port this to master

**Comment by jacinto123** [comment]
@felixfbecker If I am understanding this correctly all that needs to do is the tests? Or is there something else?

**Pull request closed without merging**
